// src/views/FantasyLeaderboardView.vue
<template>
  <v-overlay v-model="isLoading" persistent absolute class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <v-row class="mb-4">
      <v-col>
        <h1><v-icon class="mr-2">mdi-trophy</v-icon> Fantasy teams leaderboard</h1>
      </v-col>
    </v-row>

    <v-alert v-if="errorMessage" type="error" variant="tonal" border="start" border-color="error" class="mb-4" closable>
      {{ errorMessage }}
    </v-alert>

    <v-row>
      <v-col cols="12">
        <v-card elevation="2">
          <v-card-text class="pa-0">
            <v-toolbar flat height="auto">
              <v-row align="center" class="flex-wrap ma-0 pa-2">
                <v-col cols="12" sm="auto">
                  <SeasonSelect />
                </v-col>
                <v-spacer />
                <v-col cols="12" sm="auto">
                  <v-btn v-if="auth.isAdmin" variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openCreateDialog" block>
                    Create team
                  </v-btn>
                </v-col>
              </v-row>
            </v-toolbar>
            <v-data-table
              v-model:expanded="expanded"
              :headers="headers"
              :items="sortedTeams"
              :items-per-page="25"
              :no-data-text="auth.isAdmin ? 'No fantasy teams in this season yet. Create the first one.' : 'No fantasy teams in this season yet.'"
              item-value="id"
              show-expand
              expand-on-click
              class="elevation-1"
              density="comfortable"
            >
              <template v-slot:[`item.rank`]="{ index }">
                <v-chip :color="getRankColor(index + 1)" size="small">
                  {{ index + 1 }}
                </v-chip>
              </template>

              <template v-slot:[`item.name`]="{ item }">
                {{ item.name || 'N/A' }}
              </template>

              <template v-slot:[`item.captain`]="{ item }">
                <!-- no race: the captain bets, they don't play -->
                <PlayerName v-if="item.captain" :player="item.captain" />
                <template v-else>N/A</template>
              </template>

              <template v-slot:[`item.player_points`]="{ item }">
                {{ item.player_points || 0 }}
              </template>

              <template v-slot:[`item.bench_points`]="{ item }">
                {{ item.bench_points || 0 }}
              </template>

              <template v-slot:[`item.team_points`]="{ item }">
                {{ item.team_points || 0 }}
              </template>

              <template v-slot:[`item.grind_points`]="{ item }">
                {{ item.grind_points || 0 }}
              </template>

              <template v-slot:[`item.race_points`]="{ item }">
                {{ item.race_points || 0 }}
              </template>

              <template v-slot:[`item.bet_points`]="{ item }">
                {{ item.bet_points || 0 }}
              </template>

              <template v-slot:[`item.total_points`]="{ item }">
                <strong>{{ item.total_points || 0 }}</strong>
              </template>

              <template v-slot:[`item.actions`]="{ item }">
                <RowActions :actions="[
                  { icon: 'mdi-pencil', label: 'Edit', public: canEditOwn(item), onClick: () => openEditDialog(item) },
                  { icon: 'mdi-delete', label: 'Delete', color: 'error', onClick: () => openDeleteDialog(item) },
                ]" />
              </template>

              <template v-slot:expanded-row="{ columns, item }">
                <tr>
                  <td :colspan="columns.length" class="pa-0">
                    <!-- sticky: stays in view when the summary row scrolls sideways on a narrow window -->
                    <div class="pa-4 expanded-breakdown">
                      <div class="text-h6 mb-2">Score breakdown</div>
                      <div v-if="!breakdowns[item.id]" class="text-center pa-4">
                        <v-progress-circular indeterminate color="primary" />
                      </div>
                      <FantasyScoreBreakdown
                        v-else
                        :breakdown="breakdowns[item.id]"
                        :players="seasonSignups"
                        :drafted-players="item.drafted_players || []"
                        :season-id="selectedSeasonId"
                        :w3c-season="currentW3CSeason"
                      />
                    </div>
                  </td>
                </tr>
              </template>
            </v-data-table>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>

  <!-- Create/Edit Team Dialog -->
  <v-dialog v-model="editDialog" max-width="900px" persistent>
    <v-card>
      <v-card-title class="text-h5 bg-primary">
        <v-icon class="mr-2">{{ isEditing ? 'mdi-pencil' : 'mdi-plus' }}</v-icon>
        {{ isEditing ? 'Edit fantasy team' : 'Create fantasy team' }}
      </v-card-title>
      <v-card-text class="pt-4">
        <StatusAlert v-model="dialogErrorMessage" />
        <v-form ref="teamForm">
          <v-row>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="editedTeam.name"
                label="Team name *"
                variant="outlined"
                prepend-inner-icon="mdi-account-group"
                density="comfortable"
                :rules="[v => !!v || 'Team name is required']"
              ></v-text-field>
            </v-col>
            <v-col cols="12" md="6">
              <v-select
                v-model="editedTeam.season_id"
                :items="seasonStore.seasons"
                item-title="name"
                item-value="id"
                label="Season *"
                variant="outlined"
                prepend-inner-icon="mdi-calendar"
                density="comfortable"
                :disabled="!auth.isAdmin"
                :rules="[v => !!v || 'Season is required']"
              ></v-select>
            </v-col>
            <v-col cols="12" md="6">
              <v-autocomplete
                v-model="editedTeam.captain_id"
                :items="players"
                item-title="name"
                item-value="id"
                label="Bettor *"
                variant="outlined"
                prepend-inner-icon="mdi-account-star"
                density="comfortable"
                :disabled="!auth.isAdmin"
                :rules="[v => !!v || 'Bettor is required']"
              ></v-autocomplete>
            </v-col>
            <v-col cols="12" md="6">
              <v-autocomplete
                v-model="editedTeam.drafted_team_id"
                :items="gnlTeams"
                item-title="name"
                item-value="id"
                label="Drafted team *"
                variant="outlined"
                prepend-inner-icon="mdi-shield"
                density="comfortable"
                :rules="[v => !!v || 'Drafted team is required']"
              ></v-autocomplete>
            </v-col>
            <v-col v-if="fantasyGrind" cols="12" md="6">
              <v-autocomplete
                v-model="editedTeam.grind_team_id"
                :items="gnlTeams"
                item-title="name"
                item-value="id"
                label="Grind team"
                variant="outlined"
                prepend-inner-icon="mdi-shield-star"
                density="comfortable"
                clearable
              ></v-autocomplete>
            </v-col>
            <v-col cols="12" md="6">
              <v-select
                v-model="editedTeam.drafted_race"
                :items="races"
                label="Drafted race *"
                variant="outlined"
                prepend-inner-icon="mdi-sword"
                density="comfortable"
                :rules="[v => !!v || 'Drafted race is required']"
              ></v-select>
            </v-col>
          </v-row>

          <v-row>
            <v-col cols="12">
              <v-divider class="my-2"></v-divider>
              <h3 class="text-h6 mb-3">Drafted players (select 1 per tier) *</h3>
              <v-alert type="info" variant="tonal" density="compact" class="mb-3">
                You must select exactly one player from each tier (1-{{ tierCount }})
              </v-alert>
            </v-col>
            <v-col cols="12" md="6" v-for="tier in tiers" :key="tier">
              <v-autocomplete
                v-model="selectedTierPlayers[tier]"
                :items="tierPlayers[tier]"
                item-title="name"
                item-value="id"
                :label="`Tier ${tier} player *`"
                variant="outlined"
                density="comfortable"
                :rules="[v => !!v || `Tier ${tier} player is required`]"
                clearable
              >
                <template v-slot:prepend-inner>
                  <v-chip size="small" :color="tierColors[tier - 1]">T{{ tier }}</v-chip>
                </template>
              </v-autocomplete>
            </v-col>
          </v-row>
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="closeEditDialog" :disabled="isSaving">Cancel</v-btn>
        <v-btn v-if="auth.isAdmin || (isEditing && canEditOwn(editedTeam))" color="primary" variant="elevated" @click="saveTeam" :loading="isSaving">{{ isEditing ? 'Update' : 'Create' }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <!-- Delete Confirmation Dialog -->
  <v-dialog v-model="deleteDialog" max-width="500px">
    <v-card>
      <v-card-title class="bg-error text-on-error">
        <v-icon class="mr-2" color="on-error">mdi-alert</v-icon>
        Confirm delete
      </v-card-title>
      <v-card-text class="pt-4">
        <p>Are you sure you want to delete the fantasy team "{{ teamToDelete?.name }}"?</p>
        <p class="text-error font-weight-bold mt-2">This action cannot be undone.</p>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="closeDeleteDialog" :disabled="isDeleting">Cancel</v-btn>
        <v-btn v-if="auth.isAdmin" color="error" variant="elevated" prepend-icon="mdi-delete" @click="confirmDelete" :loading="isDeleting">Delete</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import RowActions from '@/components/RowActions.vue';
import FantasyScoreBreakdown from '@/components/FantasyScoreBreakdown.vue';
import { ref, computed, onMounted, watch } from 'vue';
import { useAuthStore, useFantasyStore, useSeasonStore, useTeamStore } from '@/stores';
import { storeToRefs } from 'pinia';
import { resolveCurrentW3CSeason } from '@/helpers/current-season';
import SeasonSelect from '@/components/SeasonSelect.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import { useColumns } from '@/helpers/columns';
import { ALL_COLORS, tierSelectionError } from '@/helpers/tiers.mjs';


const fantasyStore = useFantasyStore();
const seasonStore = useSeasonStore();
const teamStore = useTeamStore();
const auth = useAuthStore();

const { teams } = storeToRefs(fantasyStore);
const { selectedSeasonId } = storeToRefs(seasonStore);

const isLoading = ref(false);
const isSaving = ref(false);
const isDeleting = ref(false);
const errorMessage = ref(null);
const pickedSeason = computed(() => seasonStore.seasons.find((season) => season.id === selectedSeasonId.value));
// The season the picker is on says how many tiers it cuts; tier 1 is always Diamond
const tierCount = computed(() => pickedSeason.value?.fantasy_tiers);
// The season also says whether a bettor picks a second team to grind
const fantasyGrind = computed(() => !!pickedSeason.value?.fantasy_grind);
const tiers = computed(() => Array.from({ length: tierCount.value || 0 }, (_, i) => i + 1));
const tierColors = [...ALL_COLORS].reverse();
const currentW3CSeason = ref(null);
const editDialog = ref(false);
const deleteDialog = ref(false);
const teamToDelete = ref(null);
const isEditing = ref(false);
const expanded = ref([]);
const breakdowns = ref({});  // by team id, filled when a row expands
const players = computed(() => seasonSignups.value);
// The breakdown's opponent/bet resolve() pool: season signups, carrying signup_race
const seasonSignups = ref([]);
const gnlTeams = ref([]);
const races = ref([
  { title: 'Human', value: 'HU' },
  { title: 'Orc', value: 'OC' },
  { title: 'Night Elf', value: 'NE' },
  { title: 'Undead', value: 'UD' },
  { title: 'Random', value: 'RANDOM' }
]);
// A drafted player is UserPublic, which carries its id under one of these names
const draftedId = (player) => player.user_id || player.id || player.player_id;
const emptyTeam = (seasonId = null) => ({
  id: null,
  name: '',
  season_id: seasonId,
  captain_id: null,
  drafted_team_id: null,
  grind_team_id: null,
  drafted_race: null,
  player_ids: []
});
const emptyTierSelection = () => Object.fromEntries(tiers.value.map((tier) => [tier, null]));

const editedTeam = ref(emptyTeam());
const teamForm = ref(null);
const dialogErrorMessage = ref(null);
// The tier is a season fact now, so the buckets follow the season's signups
const tierPlayers = computed(() => {
  const byTier = Object.fromEntries(tiers.value.map((tier) => [tier, []]));
  for (const player of players.value) {
    if (player.fantasy_tier >= 1 && player.fantasy_tier <= tierCount.value) {
      byTier[player.fantasy_tier].push(player);
    }
  }
  return byTier;
});
const selectedTierPlayers = ref(emptyTierSelection());

const allHeaders = computed(() => [
  { title: '', key: 'data-table-expand', sortable: false, width: '48px' },
  { title: 'Rank', value: 'rank', sortable: false, width: '80px' },
  { title: 'Fantasy team', value: 'name', sortable: false },
  { mobile: false, title: 'Bettor', value: 'captain', sortable: false },
  // the order the breakdown panels open in, so a column and its panel line up
  { mobile: false, title: 'Team points', value: 'team_points', align: 'end' },
  ...(fantasyGrind.value ? [{ mobile: false, title: 'Grind points', value: 'grind_points', align: 'end' }] : []),
  { mobile: false, title: 'Race points', value: 'race_points', align: 'end' },
  { mobile: false, title: 'Player points', value: 'player_points', align: 'end' },
  { mobile: false, title: 'Bench points', value: 'bench_points', align: 'end' },
  { mobile: false, title: 'Bet points', value: 'bet_points', align: 'end' },
  { title: 'Total', value: 'total_points', align: 'end' },
  // the column exists only for viewers with at least one visible row action: admin, or captain of a listed team
  ...(auth.isAdmin || teams.value.some(canEditOwn)
    ? [{ title: '', value: 'actions', sortable: false, align: 'center' }] : []),
]);
const headers = useColumns(allHeaders);

const myUserId = computed(() => auth.me?.user?.id ?? null);
// A bettor edits their own team only while the season is open; the draft freezes when it commences
const canEditOwn = (team) => !!myUserId.value && team.captain_id === myUserId.value && pickedSeason.value?.phase === 'open';

// An expanded row shows the breakdown, fetched once per team and season
watch(expanded, async (ids) => {
  for (const id of ids) {
    if (breakdowns.value[id] || !selectedSeasonId.value) continue;
    try {
      breakdowns.value[id] = await fantasyStore.getTeamScoreBreakdown(id, selectedSeasonId.value);
    } catch (error) {
      console.error('Failed to fetch score breakdown:', error);
      errorMessage.value = `Failed to fetch score breakdown: ${error.message || 'Unknown error'}`;
    }
  }
});

const sortedTeams = computed(() => {
  return [...teams.value].sort((a, b) => {
    const aTotal = a.total_points || 0;
    const bTotal = b.total_points || 0;
    return bTotal - aTotal;
  });
});

const getRankColor = (rank) => {
  if (rank === 1) return 'primary';
  if (rank <= 3) return 'secondary';
  return undefined;
};

const fetchData = async () => {
  if (!selectedSeasonId.value) return;  // the picker resolves one
  isLoading.value = true;
  errorMessage.value = null;
  try {
    // Fetch teams for selected season
    expanded.value = [];
    breakdowns.value = {};
    const teamsQuery = `season_id == ${selectedSeasonId.value}`;
    await fantasyStore.searchTeams(teamsQuery);
    seasonSignups.value = await seasonStore.fetchSeasonSignups(selectedSeasonId.value) || [];
  } catch (error) {
    console.error('Failed to fetch fantasy teams:', error);
    errorMessage.value = 'Failed to load fantasy teams. Please try again later.';
  } finally {
    isLoading.value = false;
  }
};

const openCreateDialog = async () => {
  isEditing.value = false;
  dialogErrorMessage.value = null;
  editedTeam.value = emptyTeam(selectedSeasonId.value);
  selectedTierPlayers.value = emptyTierSelection();
  await loadTeams();
  editDialog.value = true;
};

const openEditDialog = async (team) => {
  isEditing.value = true;
  dialogErrorMessage.value = null;
  
  editedTeam.value = {
    id: team.id,
    name: team.name,
    season_id: team.season_id,
    captain_id: team.captain_id,
    drafted_team_id: team.drafted_team_id,
    grind_team_id: team.grind_team_id ?? null,
    drafted_race: team.drafted_race,
    player_ids: team.drafted_players?.map(draftedId).filter(Boolean) || []
  };
  
  // Load the teams first so the drafted-team picker is populated
  await loadTeams();
  
  // Reset tier selections
  selectedTierPlayers.value = emptyTierSelection();
  
  // Populate tier selections from existing players AFTER players are loaded
  if (team.drafted_players && team.drafted_players.length > 0) {
    team.drafted_players.forEach(dp => {
      const playerId = draftedId(dp);
      const player = players.value.find(p => p.id === playerId);
      // A tier above the season's count has no picker, so it lands in no slot
      if (player && player.fantasy_tier >= 1 && player.fantasy_tier <= tierCount.value) {
        selectedTierPlayers.value[player.fantasy_tier] = player.id;
      }
    });
  }
  
  editDialog.value = true;
};

const closeEditDialog = () => {
  editDialog.value = false;
  dialogErrorMessage.value = null;
  editedTeam.value = emptyTeam();
  selectedTierPlayers.value = emptyTierSelection();
};

const saveTeam = async () => {
  // Validate form
  const { valid } = await teamForm.value.validate();
  if (!valid) return;

  // One player per tier the season cuts, and a season with no cut tiers takes no team
  const selectionError = tierSelectionError(tierCount.value, selectedTierPlayers.value);
  if (selectionError) {
    dialogErrorMessage.value = selectionError;
    return;
  }

  // Build player_ids array from tier selections
  const playerIds = Object.values(selectedTierPlayers.value).filter(id => id !== null);

  isSaving.value = true;
  dialogErrorMessage.value = null;
  try {
    const teamData = {
      name: editedTeam.value.name,
      season_id: editedTeam.value.season_id,
      captain_id: editedTeam.value.captain_id,
      drafted_team_id: editedTeam.value.drafted_team_id,
      grind_team_id: editedTeam.value.grind_team_id ?? null,
      drafted_race: editedTeam.value.drafted_race
    };

    if (isEditing.value) {
      // Update existing team
      await fantasyStore.updateTeam(editedTeam.value.id, teamData);
      
      // Update players if changed
      const team = teams.value.find(t => t.id === editedTeam.value.id);
      // Get current player IDs - use the same property lookup as in openEditDialog
      const currentPlayerIds = team.drafted_players?.map(draftedId).filter(Boolean) || [];
      
      const playersToAdd = playerIds.filter(id => !currentPlayerIds.includes(id));
      const playersToRemove = currentPlayerIds.filter(id => !playerIds.includes(id));
      
      if (playersToRemove.length > 0) {
        await fantasyStore.removePlayers(editedTeam.value.id, playersToRemove);
      }
      if (playersToAdd.length > 0) {
        await fantasyStore.addPlayers(editedTeam.value.id, playersToAdd);
      }
    } else {
      // Create new team
      const newTeam = await fantasyStore.createTeam(teamData);
      
      // Add players
      if (playerIds.length > 0) {
        await fantasyStore.addPlayers(newTeam.id, playerIds);
      }
    }

    closeEditDialog();
    await fetchData(); // Refresh the list
  } catch (error) {
    console.error('Failed to save team:', error);
    dialogErrorMessage.value = `Failed to ${isEditing.value ? 'update' : 'create'} team: ${error.message || 'Unknown error'}`;
  } finally {
    isSaving.value = false;
  }
};

const loadTeams = async () => {
  try {
    if (selectedSeasonId.value) {
      await teamStore.fetchTeamsBySeasonBasic(selectedSeasonId.value);
      gnlTeams.value = teamStore.teams || [];
    }
  } catch (error) {
    console.error('Failed to load teams:', error);
  }
};

const openDeleteDialog = (team) => {
  teamToDelete.value = team;
  deleteDialog.value = true;
};

const closeDeleteDialog = () => {
  deleteDialog.value = false;
  teamToDelete.value = null;
};

const confirmDelete = async () => {
  if (!teamToDelete.value) return;
  
  isDeleting.value = true;
  errorMessage.value = null;
  try {
    await fantasyStore.deleteTeam(teamToDelete.value.id);
    closeDeleteDialog();
    await fetchData(); // Refresh the list
  } catch (error) {
    console.error('Failed to delete team:', error);
    errorMessage.value = `Failed to delete team: ${error.message || 'Unknown error'}`;
    closeDeleteDialog();
  } finally {
    isDeleting.value = false;
  }
};

watch(selectedSeasonId, fetchData, { immediate: true });

onMounted(async () => {
  loadTeams();
  currentW3CSeason.value = await resolveCurrentW3CSeason();
});
</script>

<style scoped>
.expanded-breakdown {
  position: sticky;
  left: 0;
  max-width: calc(100vw - 48px);
}
</style>

// next/src/app/(app)/fantasy/FantasyLeaderboardView.tsx
"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useRef, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Combobox } from "@/components/ui/Combobox";
import { DataTable } from "@/components/ui/DataTable";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Pick } from "@/components/ui/Pick";
import { Separator } from "@/components/ui/separator";
import { FantasyScoreBreakdown } from "@/components/fantasy/FantasyScoreBreakdown";
import { PageHeader } from "@/components/PageHeader";
import { PlayerName } from "@/components/PlayerName";
import { RowActions } from "@/components/RowActions";
import { SeasonSelect } from "@/components/SeasonSelect";
import { StatusAlert } from "@/components/StatusAlert";
import { MD_AND_UP, useBreakpoint } from "@/hooks/breakpoint";
import { useAuth, useFantasyStore, useSeason, useSeasonStore, useTeamStore } from "@/stores";
import { resolveCurrentW3CSeason } from "@/helpers/current-season.js";
import { ALL_COLORS, tierSelectionError } from "@/helpers/tiers.mjs";

const races = [
  { title: "Human", value: "HU" },
  { title: "Orc", value: "OC" },
  { title: "Night Elf", value: "NE" },
  { title: "Undead", value: "UD" },
  { title: "Random", value: "RANDOM" },
];

// Tailwind builds no class from a name held in data, so each tier chip is written out.
const TIER_CHIP: Record<string, string> = {
  "tier-1": "bg-tier-1 text-on-tier-1",
  "tier-2": "bg-tier-2 text-on-tier-2",
  "tier-3": "bg-tier-3 text-on-tier-3",
  "tier-4": "bg-tier-4 text-on-tier-4",
  "tier-5": "bg-tier-5 text-on-tier-5",
  "tier-6": "bg-tier-6 text-on-tier-6",
};
const tierColors = [...(ALL_COLORS as string[])].reverse();

// A drafted player is UserPublic, which carries its id under one of these names
const draftedId = (player: any) => player.user_id || player.id || player.player_id;

const emptyTeam = (seasonId: number | null = null) => ({
  id: null as number | null,
  name: "",
  season_id: seasonId,
  captain_id: null as number | null,
  drafted_team_id: null as number | null,
  grind_team_id: null as number | null,
  drafted_race: null as string | null,
  player_ids: [] as number[],
});

/** Every fantasy team of one season by total points, each row opening its score breakdown. */
export function FantasyLeaderboardView() {
  const fantasyStore = useFantasyStore();
  const seasonStore = useSeasonStore();
  const teamStore = useTeamStore();
  const auth = useAuth();
  const { seasons, selectedSeasonId } = useSeason();

  const [teams, setTeams] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [currentW3CSeason, setCurrentW3CSeason] = useState<any>(null);
  const [editDialog, setEditDialog] = useState(false);
  const [deleteDialog, setDeleteDialog] = useState(false);
  const [teamToDelete, setTeamToDelete] = useState<any>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [breakdowns, setBreakdowns] = useState<Record<number, any>>({}); // by team id, filled when a row expands
  // The breakdown's opponent/bet resolve() pool: season signups, carrying signup_race
  const [seasonSignups, setSeasonSignups] = useState<any[]>([]);
  const [gnlTeams, setGnlTeams] = useState<any[]>([]);
  const [editedTeam, setEditedTeam] = useState(emptyTeam());
  const [selectedTierPlayers, setSelectedTierPlayers] = useState<Record<number, number | null>>({});
  const [dialogErrorMessage, setDialogErrorMessage] = useState<string | null>(null);

  const mdAndUp = useBreakpoint(MD_AND_UP);

  const pickedSeason = seasons.find((season: any) => season.id === selectedSeasonId);
  // The season the picker is on says how many tiers it cuts; tier 1 is always Diamond
  const tierCount: number | undefined = pickedSeason?.fantasy_tiers;
  // The season also says whether a fantasy captain picks a second team to grind
  const fantasyGrind = !!pickedSeason?.fantasy_grind;
  const tiers = useMemo(() => Array.from({ length: tierCount || 0 }, (_, i) => i + 1), [tierCount]);
  const players = seasonSignups;

  const myUserId = auth.me?.user?.id ?? null;
  // A fantasy captain edits their own team only while the season is open; the draft freezes when it commences
  const canEditOwn = (team: any) => !!myUserId && team.captain_id === myUserId && pickedSeason?.phase === "open";

  // The tier is a season fact now, so the buckets follow the season's signups
  const tierPlayers = useMemo(() => {
    const byTier: Record<number, any[]> = Object.fromEntries(tiers.map((tier) => [tier, []]));
    for (const player of players) {
      if (player.fantasy_tier >= 1 && player.fantasy_tier <= (tierCount || 0)) byTier[player.fantasy_tier].push(player);
    }
    return byTier;
  }, [tiers, players, tierCount]);

  const emptyTierSelection = () => Object.fromEntries(tiers.map((tier) => [tier, null]));

  const sortedTeams = useMemo(() => [...teams].sort((a, b) => (b.total_points || 0) - (a.total_points || 0)), [teams]);

  const rankVariant = (rank: number) => (rank === 1 ? "default" : rank <= 3 ? "secondary" : "outline");

  const fetchData = async () => {
    if (!selectedSeasonId) return; // the picker resolves one
    setIsLoading(true);
    setErrorMessage(null);
    try {
      setBreakdowns({});
      setTeams(await fantasyStore.searchTeams(`season_id == ${selectedSeasonId}`));
      setSeasonSignups((await seasonStore.fetchSeasonSignups(selectedSeasonId)) || []);
    } catch (error: any) {
      console.error("Failed to fetch fantasy teams:", error);
      setErrorMessage("Failed to load fantasy teams. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  const loadTeams = async () => {
    try {
      if (selectedSeasonId) setGnlTeams((await teamStore.fetchTeamsBySeasonBasic(selectedSeasonId)) || []);
    } catch (error: any) {
      console.error("Failed to load teams:", error);
    }
  };

  // The season the picker resolves drives the page; both reads run again when it changes.
  const fetched = useRef<number | null>(null);
  useEffect(() => {
    if (!selectedSeasonId || fetched.current === selectedSeasonId) return;
    fetched.current = selectedSeasonId;
    fetchData();
    loadTeams();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedSeasonId]);

  useEffect(() => {
    resolveCurrentW3CSeason().then(setCurrentW3CSeason);
  }, []);

  // An expanded row shows the breakdown, fetched once per team and season
  const loadBreakdown = async (team: any) => {
    if (breakdowns[team.id] || !selectedSeasonId) return;
    try {
      const breakdown = await fantasyStore.getTeamScoreBreakdown(team.id, selectedSeasonId);
      setBreakdowns((was) => ({ ...was, [team.id]: breakdown }));
    } catch (error: any) {
      console.error("Failed to fetch score breakdown:", error);
      setErrorMessage(`Failed to fetch score breakdown: ${error.message || "Unknown error"}`);
    }
  };

  const openCreateDialog = async () => {
    setIsEditing(false);
    setDialogErrorMessage(null);
    setEditedTeam(emptyTeam(selectedSeasonId));
    setSelectedTierPlayers(emptyTierSelection());
    await loadTeams();
    setEditDialog(true);
  };

  const openEditDialog = async (team: any) => {
    setIsEditing(true);
    setDialogErrorMessage(null);
    setEditedTeam({
      id: team.id,
      name: team.name,
      season_id: team.season_id,
      captain_id: team.captain_id,
      drafted_team_id: team.drafted_team_id,
      grind_team_id: team.grind_team_id ?? null,
      drafted_race: team.drafted_race,
      player_ids: team.drafted_players?.map(draftedId).filter(Boolean) || [],
    });

    // Load the teams first so the drafted-team picker is populated
    await loadTeams();

    const selection: Record<number, number | null> = emptyTierSelection();
    // A tier above the season's count has no picker, so it lands in no slot
    for (const dp of team.drafted_players || []) {
      const player = players.find((p) => p.id === draftedId(dp));
      if (player && player.fantasy_tier >= 1 && player.fantasy_tier <= (tierCount || 0)) selection[player.fantasy_tier] = player.id;
    }
    setSelectedTierPlayers(selection);
    setEditDialog(true);
  };

  const closeEditDialog = () => {
    setEditDialog(false);
    setDialogErrorMessage(null);
    setEditedTeam(emptyTeam());
    setSelectedTierPlayers(emptyTierSelection());
  };

  // The required fields the Vue form's rules named, in the order they are asked for
  const missingField = () =>
    !editedTeam.name
      ? "Team name is required"
      : !editedTeam.season_id
        ? "Season is required"
        : !editedTeam.captain_id
          ? "Fantasy Captain is required"
          : !editedTeam.drafted_team_id
            ? "Drafted team is required"
            : !editedTeam.drafted_race
              ? "Drafted race is required"
              : null;

  const saveTeam = async () => {
    // One player per tier the season cuts, and a season with no cut tiers takes no team
    const error = missingField() || tierSelectionError(tierCount, selectedTierPlayers);
    if (error) {
      setDialogErrorMessage(error);
      return;
    }

    const playerIds = Object.values(selectedTierPlayers).filter((id): id is number => id !== null);

    setIsSaving(true);
    setDialogErrorMessage(null);
    try {
      const teamData = {
        name: editedTeam.name,
        season_id: editedTeam.season_id,
        captain_id: editedTeam.captain_id,
        drafted_team_id: editedTeam.drafted_team_id,
        grind_team_id: editedTeam.grind_team_id ?? null,
        drafted_race: editedTeam.drafted_race,
      };

      if (isEditing) {
        await fantasyStore.updateTeam(editedTeam.id!, teamData);

        // Update players if changed
        const team = teams.find((t) => t.id === editedTeam.id);
        const currentPlayerIds: number[] = team.drafted_players?.map(draftedId).filter(Boolean) || [];
        const playersToAdd = playerIds.filter((id) => !currentPlayerIds.includes(id));
        const playersToRemove = currentPlayerIds.filter((id) => !playerIds.includes(id));

        if (playersToRemove.length > 0) await fantasyStore.removePlayers(editedTeam.id!, playersToRemove);
        if (playersToAdd.length > 0) await fantasyStore.addPlayers(editedTeam.id!, playersToAdd);
      } else {
        const newTeam = await fantasyStore.createTeam(teamData);
        if (playerIds.length > 0) await fantasyStore.addPlayers(newTeam.id, playerIds);
      }

      closeEditDialog();
      await fetchData();
    } catch (error: any) {
      console.error("Failed to save team:", error);
      setDialogErrorMessage(`Failed to ${isEditing ? "update" : "create"} team: ${error.message || "Unknown error"}`);
    } finally {
      setIsSaving(false);
    }
  };

  const closeDeleteDialog = () => {
    setDeleteDialog(false);
    setTeamToDelete(null);
  };

  const confirmDelete = async () => {
    if (!teamToDelete) return;
    setIsDeleting(true);
    setErrorMessage(null);
    try {
      await fantasyStore.deleteTeam(teamToDelete.id);
      // The module keeps no list, so the page drops the row itself
      setTeams((was) => was.filter((team) => team.id !== teamToDelete.id));
      closeDeleteDialog();
      await fetchData();
    } catch (error: any) {
      console.error("Failed to delete team:", error);
      setErrorMessage(`Failed to delete team: ${error.message || "Unknown error"}`);
      closeDeleteDialog();
    } finally {
      setIsDeleting(false);
    }
  };

  const pointsColumn = (key: string, header: string) => ({
    id: key,
    accessorKey: key,
    header,
    cell: ({ row }: any) => row.original[key] || 0,
  });

  const columns: any[] = [
    { id: "rank", header: "Rank", enableSorting: false, cell: ({ row }: any) => <Badge variant={rankVariant(row.index + 1)}>{row.index + 1}</Badge> },
    { id: "name", accessorKey: "name", header: "Fantasy team", enableSorting: false, cell: ({ row }: any) => row.original.name || "N/A" },
    {
      id: "captain",
      header: "Fantasy Captain",
      enableSorting: false,
      // no race: the captain bets, they don't play
      cell: ({ row }: any) => (row.original.captain ? <PlayerName player={row.original.captain} /> : "N/A"),
    },
    // the order the breakdown panels open in, so a column and its panel line up
    pointsColumn("team_points", "Team points"),
    ...(fantasyGrind ? [pointsColumn("grind_points", "Grind points")] : []),
    pointsColumn("race_points", "Race points"),
    pointsColumn("player_points", "Player points"),
    pointsColumn("bench_points", "Bench points"),
    pointsColumn("bet_points", "Bet points"),
    { id: "total_points", accessorKey: "total_points", header: "Total", cell: ({ row }: any) => <strong>{row.original.total_points || 0}</strong> },
    // the column exists only for viewers with at least one visible row action: admin, or captain of a listed team
    ...(auth.isAdmin || teams.some(canEditOwn)
      ? [
          {
            id: "actions",
            header: "",
            enableSorting: false,
            cell: ({ row }: any) => (
              <RowActions
                actions={[
                  { icon: "mdi-pencil", label: "Edit", public: canEditOwn(row.original), onClick: () => openEditDialog(row.original) },
                  { icon: "mdi-delete", label: "Delete", color: "error", onClick: () => { setTeamToDelete(row.original); setDeleteDialog(true); } },
                ]}
              />
            ),
          },
        ]
      : []),
  ];

  const hiddenOnPhone = ["captain", "team_points", "grind_points", "race_points", "player_points", "bench_points", "bet_points"];
  const columnVisibility = Object.fromEntries(hiddenOnPhone.map((key) => [key, mdAndUp]));

  const playerItems = (list: any[]) => list.map((player) => ({ value: String(player.id), title: player.name }));
  const teamItems = gnlTeams.map((team) => ({ value: String(team.id), title: team.name }));

  return (
    <div className="p-4">
      {/* The page dims while the teams load. */}
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <span className="size-16 animate-spin rounded-full border-8 border-primary border-t-transparent" />
        </div>
      ) : null}

      <PageHeader title={<><Icon name="mdi-trophy" className="mr-2" />Fantasy Teams Leaderboard</>} />

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      <Card className="card gap-0 py-0">
        <CardContent className="p-0">
          <div className="flex flex-wrap items-center gap-2 p-2">
            <div className="w-full sm:w-auto">
              <SeasonSelect />
            </div>
            {auth.isAdmin ? (
              <Button className="w-full sm:ml-auto sm:w-auto" onClick={openCreateDialog}>
                <Icon name="mdi-plus" />
                Create team
              </Button>
            ) : null}
          </div>

          <DataTable
            data={sortedTeams}
            columns={columns}
            pageSize={25}
            rowId={(team: any) => String(team.id)}
            columnVisibility={columnVisibility}
            empty={auth.isAdmin ? "No fantasy teams in this season yet. Create the first one." : "No fantasy teams in this season yet."}
            onExpand={loadBreakdown}
            expand={(team: any) => (
              // sticky: stays in view when the summary row scrolls sideways on a narrow window
              <div className="sticky left-0 max-w-[calc(100vw-48px)] p-4">
                <div className="mb-2 text-xl">Score breakdown</div>
                {!breakdowns[team.id] ? (
                  <div className="p-4 text-center">
                    <span className="inline-block size-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
                  </div>
                ) : (
                  <FantasyScoreBreakdown
                    breakdown={breakdowns[team.id]}
                    players={seasonSignups}
                    draftedPlayers={team.drafted_players || []}
                    seasonId={selectedSeasonId}
                    w3cSeason={currentW3CSeason}
                  />
                )}
              </div>
            )}
          />
        </CardContent>
      </Card>

      {/* Create/Edit Team Dialog */}
      <Dialog open={editDialog} onOpenChange={(open) => (open ? setEditDialog(true) : closeEditDialog())} disablePointerDismissal>
        <DialogContent showCloseButton={false} className="gap-0 p-0 sm:max-w-[900px]">
          <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name={isEditing ? "mdi-pencil" : "mdi-plus"} />
            {isEditing ? "Edit fantasy team" : "Create fantasy team"}
          </DialogTitle>

          <div className="max-h-[70vh] overflow-y-auto p-4">
            <StatusAlert modelValue={dialogErrorMessage} onClose={() => setDialogErrorMessage(null)} />

            <div className="grid gap-4 md:grid-cols-2">
              <Field label="Team name *" htmlFor="team-name">
                <Input id="team-name" value={editedTeam.name} onChange={(event) => setEditedTeam({ ...editedTeam, name: event.target.value })} />
              </Field>
              <Pick
                label="Season *"
                items={seasons.map((season: any) => ({ value: season.id, title: season.name }))}
                value={editedTeam.season_id}
                onChange={(value) => setEditedTeam({ ...editedTeam, season_id: value })}
                disabled={!auth.isAdmin}
              />
              <Field label="Fantasy Captain *" htmlFor="team-captain">
                <Combobox
                  id="team-captain"
                  items={playerItems(players)}
                  value={editedTeam.captain_id == null ? null : String(editedTeam.captain_id)}
                  onChange={(value) => setEditedTeam({ ...editedTeam, captain_id: value == null ? null : Number(value) })}
                  label="Fantasy Captain"
                  disabled={!auth.isAdmin}
                />
              </Field>
              <Field label="Drafted team *" htmlFor="team-drafted">
                <Combobox
                  id="team-drafted"
                  items={teamItems}
                  value={editedTeam.drafted_team_id == null ? null : String(editedTeam.drafted_team_id)}
                  onChange={(value) => setEditedTeam({ ...editedTeam, drafted_team_id: value == null ? null : Number(value) })}
                  label="Drafted team"
                />
              </Field>
              {fantasyGrind ? (
                <Field label="Grind team" htmlFor="team-grind">
                  <div className="flex items-center gap-1">
                    <Combobox
                      id="team-grind"
                      items={teamItems}
                      value={editedTeam.grind_team_id == null ? null : String(editedTeam.grind_team_id)}
                      onChange={(value) => setEditedTeam({ ...editedTeam, grind_team_id: value == null ? null : Number(value) })}
                      label="Grind team"
                    />
                    {editedTeam.grind_team_id != null ? (
                      <Button variant="ghost" size="icon-sm" aria-label="Clear Grind team" onClick={() => setEditedTeam({ ...editedTeam, grind_team_id: null })}>
                        <Icon name="mdi-close" />
                      </Button>
                    ) : null}
                  </div>
                </Field>
              ) : null}
              <Pick
                label="Drafted race *"
                items={races}
                value={editedTeam.drafted_race}
                onChange={(value) => setEditedTeam({ ...editedTeam, drafted_race: value })}
              />
            </div>

            <Separator className="my-4" />
            <h3 className="mb-3 text-xl">Drafted players (select 1 per tier) *</h3>
            <StatusAlert modelValue={`You must select exactly one player from each tier (1-${tierCount ?? ""})`} type="info" />

            <div className="grid gap-4 md:grid-cols-2">
              {tiers.map((tier) => (
                <Field key={tier} label={`Tier ${tier} player *`} htmlFor={`tier-${tier}`}>
                  <div className="flex items-center gap-1">
                    <Badge className={TIER_CHIP[tierColors[tier - 1]]}>T{tier}</Badge>
                    <Combobox
                      id={`tier-${tier}`}
                      items={playerItems(tierPlayers[tier] || [])}
                      value={selectedTierPlayers[tier] == null ? null : String(selectedTierPlayers[tier])}
                      onChange={(value) => setSelectedTierPlayers({ ...selectedTierPlayers, [tier]: value == null ? null : Number(value) })}
                      label={`Tier ${tier} player`}
                    />
                    {selectedTierPlayers[tier] != null ? (
                      <Button variant="ghost" size="icon-sm" aria-label={`Clear tier ${tier} player`} onClick={() => setSelectedTierPlayers({ ...selectedTierPlayers, [tier]: null })}>
                        <Icon name="mdi-close" />
                      </Button>
                    ) : null}
                  </div>
                </Field>
              ))}
            </div>
          </div>

          <div className="flex justify-end gap-2 px-4 py-3">
            <Button variant="ghost" onClick={closeEditDialog} disabled={isSaving}>
              Cancel
            </Button>
            {auth.isAdmin || (isEditing && canEditOwn(editedTeam)) ? (
              <Button onClick={saveTeam} disabled={isSaving}>
                <Icon name={isSaving ? "mdi-loading mdi-spin" : "mdi-check"} />
                {isEditing ? "Update" : "Create"}
              </Button>
            ) : null}
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialog} onOpenChange={(open) => (open ? setDeleteDialog(true) : closeDeleteDialog())}>
        <DialogContent showCloseButton={false} className="gap-0 p-0 sm:max-w-[500px]">
          {/* DESIGN.md: a dialog that deletes something wears bg-error */}
          <DialogTitle className="flex items-center gap-2 bg-error px-4 py-3 text-on-error">
            <Icon name="mdi-alert" />
            Confirm delete
          </DialogTitle>
          <div className="p-4">
            <p>Are you sure you want to delete the fantasy team &quot;{teamToDelete?.name}&quot;?</p>
            <p className="mt-2 font-bold text-error">This action cannot be undone.</p>
          </div>
          <div className="flex justify-end gap-2 px-4 py-3">
            <Button variant="ghost" onClick={closeDeleteDialog} disabled={isDeleting}>
              Cancel
            </Button>
            {auth.isAdmin ? (
              <Button variant="destructive" onClick={confirmDelete} disabled={isDeleting}>
                <Icon name={isDeleting ? "mdi-loading mdi-spin" : "mdi-delete"} />
                Delete
              </Button>
            ) : null}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default FantasyLeaderboardView;
