// src/views/KothView.vue
<!-- Every KOTH night, newest first. A night is one event of the KOTH league, so this page
     only opens tonight's and hands the run over to the event run page. -->
<template>
  <v-container fluid class="pa-4">
    <div class="d-flex flex-wrap align-center ga-3">
      <h1 class="text-h5 text-md-h3 font-weight-bold">
        <v-icon class="mr-2" size="large">mdi-crown</v-icon>
        KOTH Nights
      </h1>
      <v-spacer />
      <v-btn variant="outlined" color="primary" prepend-icon="mdi-eye-outline" to="/koth/dashboard">Public page</v-btn>
      <v-btn color="primary" prepend-icon="mdi-plus" :disabled="loading" @click="openDialog">Open tonight</v-btn>
    </div>

    <StatusAlert v-model="error" class="mt-4" />

    <v-card elevation="2" class="mt-4">
      <v-progress-linear v-if="loading" indeterminate />
      <v-table density="comfortable" hover>
        <thead>
          <tr>
            <th>Night</th>
            <th class="d-none d-md-table-cell">Date</th>
            <th>State</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="night in nights" :key="night.id">
            <td class="py-3">
              <RouterLink :to="`/events/${night.id}/admin`"><strong>{{ night.name }}</strong></RouterLink>
              <!-- a phone drops the date column, so the date rides under the name -->
              <div class="d-md-none text-caption text-medium-emphasis">{{ dateRange(night) }}</div>
            </td>
            <td class="d-none d-md-table-cell text-no-wrap">{{ dateRange(night) || '—' }}</td>
            <td>
              <v-chip size="small" variant="tonal" :color="STATE_COLOR[stateOf(night)]">
                {{ STATE_LABEL[stateOf(night)] || '—' }}
              </v-chip>
            </td>
          </tr>
          <tr v-if="!nights.length && !loading">
            <td colspan="3" class="text-medium-emphasis py-6 text-center">No night has run yet.</td>
          </tr>
        </tbody>
      </v-table>
    </v-card>

    <!-- Tonight's night: when it starts, and where its three brackets cut -->
    <v-dialog v-model="dialogOpen" max-width="520">
      <v-card>
        <v-card-title class="bg-primary">Open tonight</v-card-title>
        <v-card-text class="pt-4">
          <StatusAlert v-model="dialogError" />
          <v-text-field v-model="form.starts_at" type="datetime-local" label="Starts at"
            variant="outlined" density="comfortable" class="mb-2" />
          <div class="text-subtitle-2 mb-2">The MMR each bracket opens at</div>
          <v-row dense>
            <v-col v-for="(bound, index) in form.lower_bounds" :key="index" cols="12" sm="4">
              <v-text-field :model-value="bound" type="number" :label="`Bracket ${index + 1}`"
                variant="outlined" density="comfortable" hide-details
                @update:model-value="form.lower_bounds[index] = Number($event)" />
            </v-col>
          </v-row>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="dialogOpen = false">Cancel</v-btn>
          <v-btn color="primary" variant="elevated" :disabled="!form.starts_at || saving"
            :loading="saving" @click="openNight">Open tonight</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { DateTime } from 'luxon';
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';

import StatusAlert from '@/components/StatusAlert.vue';
import { dateRange, STATE_COLOR, STATE_LABEL, stateOf } from '@/helpers/event-labels.mjs';
import { useEventStore } from '@/stores';

// The bracket cuts a first night takes, weakest first, the way the module names them
const DEFAULT_BOUNDS = [0, 1450, 1600];

const router = useRouter();
const store = useEventStore();

const nights = ref([]);
const loading = ref(true);
const saving = ref(false);
const error = ref(null);
const dialogError = ref(null);
const dialogOpen = ref(false);
const form = ref({ starts_at: '', lower_bounds: [...DEFAULT_BOUNDS] });

const load = async () => {
  loading.value = true;
  try {
    nights.value = await store.fetchEvents(null, 'koth');
  } catch (e) {
    error.value = `The nights did not load: ${e.message}`;
  } finally {
    loading.value = false;
  }
};

onMounted(load);

// Tonight at the hour the last night started, and its bracket cuts, weakest first.
// The list read carries no divisions, so the last night is read in full for them.
const openDialog = async () => {
  dialogError.value = null;
  const last = nights.value[0]
    ? await store.fetchEvent(nights.value[0].id).catch(() => null)
    : null;
  const started = last?.starts_at ? DateTime.fromISO(last.starts_at, { zone: 'utc' }).toLocal() : null;
  const start = DateTime.now().set({
    hour: started?.hour ?? 20, minute: started?.minute ?? 0, second: 0, millisecond: 0,
  });
  const bounds = [...(last?.divisions || [])]
    .sort((a, b) => b.position - a.position)
    .map((band) => band.lower_bound ?? 0);
  form.value = {
    starts_at: start.toFormat("yyyy-LL-dd'T'HH:mm"),
    lower_bounds: bounds.length === 3 ? bounds : [...DEFAULT_BOUNDS],
  };
  dialogOpen.value = true;
};

const openNight = async () => {
  saving.value = true;
  dialogError.value = null;
  try {
    const night = await store.openNight({
      starts_at: DateTime.fromISO(form.value.starts_at).toUTC().toISO(),
      lower_bounds: form.value.lower_bounds,
    });
    dialogOpen.value = false;
    router.push(`/events/${night.id}/admin`);
  } catch (e) {
    dialogError.value = e.message;
  } finally {
    saving.value = false;
  }
};
</script>

// next/src/app/(app)/koth/KothView.tsx
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { DateTime } from "luxon";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toneClass } from "@/components/ui/tone";
import { PageHeader } from "@/components/PageHeader";
import { StatusAlert } from "@/components/StatusAlert";
import { dateRange, STATE_COLOR, STATE_LABEL, stateOf } from "@/helpers/event-labels.mjs";
import { useEventStore } from "@/stores";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const phoneCell = "hidden min-[960px]:table-cell";
// event-labels.mjs is plain JS, so its records index by a known key; the seam widens them
const stateColor = STATE_COLOR as Record<string, string>;
const stateLabel = STATE_LABEL as Record<string, string>;

// The bracket cuts a first night takes, weakest first, the way the module names them
const DEFAULT_BOUNDS = [0, 1450, 1600];

/** Every KOTH night, newest first. A night is one event of the KOTH league, so this page
 *  only opens tonight's and hands the run over to the event run page. */
export function KothView() {
  const router = useRouter();
  const store = useEventStore();

  const [nights, setNights] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [dialogError, setDialogError] = useState<string | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [form, setForm] = useState({ starts_at: "", lower_bounds: [...DEFAULT_BOUNDS] });

  useEffect(() => {
    const load = async () => {
      try {
        setNights(await store.fetchEvents(null, "koth"));
      } catch (e) {
        setError(`The nights did not load: ${(e as Error).message}`);
      } finally {
        setLoading(false);
      }
    };
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Tonight at the hour the last night started, and its bracket cuts, weakest first.
  // The list read carries no divisions, so the last night is read in full for them.
  const openDialog = async () => {
    setDialogError(null);
    const last: Row | null = nights[0] ? await store.fetchEvent(nights[0].id).catch(() => null) : null;
    const started = last?.starts_at ? DateTime.fromISO(last.starts_at, { zone: "utc" }).toLocal() : null;
    const start = DateTime.now().set({ hour: started?.hour ?? 20, minute: started?.minute ?? 0, second: 0, millisecond: 0 });
    const bounds: number[] = [...(last?.divisions || [])].sort((a: Row, b: Row) => b.position - a.position).map((band: Row) => band.lower_bound ?? 0);
    setForm({
      starts_at: start.toFormat("yyyy-LL-dd'T'HH:mm"),
      lower_bounds: bounds.length === 3 ? bounds : [...DEFAULT_BOUNDS],
    });
    setDialogOpen(true);
  };

  const openNight = async () => {
    setSaving(true);
    setDialogError(null);
    try {
      const night = await store.openNight({
        starts_at: DateTime.fromISO(form.starts_at).toUTC().toISO(),
        lower_bounds: form.lower_bounds,
      });
      setDialogOpen(false);
      router.push(`/events/${night.id}/admin`);
    } catch (e) {
      setDialogError((e as Error).message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <PageHeader
        title={
          <span className="inline-flex items-center gap-2">
            <Icon name="mdi-crown" />
            KOTH Nights
          </span>
        }
      >
        <Button nativeButton={false} variant="outline" className="text-primary-text" render={<Link href="/koth/dashboard" />}>
          <Icon name="mdi-eye-outline" />
          Public page
        </Button>
        <Button disabled={loading} onClick={openDialog}>
          <Icon name="mdi-plus" />
          Open tonight
        </Button>
      </PageHeader>

      <StatusAlert modelValue={error} onClose={() => setError(null)} />

      <Card className="card">
        {loading ? <Progress value={null} /> : null}
        <div className="table-scroll overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Night</TableHead>
                <TableHead className={phoneCell}>Date</TableHead>
                <TableHead>State</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {nights.map((night) => (
                <TableRow key={night.id}>
                  <TableCell className="py-3">
                    <Link href={`/events/${night.id}/admin`}>
                      <strong>{night.name}</strong>
                    </Link>
                    {/* a phone drops the date column, so the date rides under the name */}
                    <div className="text-xs text-muted-foreground min-[960px]:hidden">{dateRange(night)}</div>
                  </TableCell>
                  <TableCell className={cn(phoneCell, "whitespace-nowrap")}>{dateRange(night) || "—"}</TableCell>
                  <TableCell>
                    <Badge className={toneClass(stateColor[stateOf(night)])}>{stateLabel[stateOf(night)] || "—"}</Badge>
                  </TableCell>
                </TableRow>
              ))}
              {!nights.length && !loading ? (
                <TableRow>
                  <TableCell colSpan={3} className="py-6 text-center text-muted-foreground">
                    No night has run yet.
                  </TableCell>
                </TableRow>
              ) : null}
            </TableBody>
          </Table>
        </div>
      </Card>

      {/* Tonight's night: when it starts, and where its three brackets cut */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent showCloseButton={false} className="max-w-[520px] gap-0 p-0 sm:max-w-[520px]">
          <DialogTitle className="bg-primary px-4 py-3 text-on-primary">Open tonight</DialogTitle>
          <div className="flex flex-col gap-3 p-4">
            <StatusAlert modelValue={dialogError} onClose={() => setDialogError(null)} />
            <Field label="Starts at" htmlFor="night-starts-at">
              <Input id="night-starts-at" type="datetime-local" value={form.starts_at} onChange={(e) => setForm({ ...form, starts_at: e.target.value })} />
            </Field>
            <div className="text-sm font-medium">The MMR each bracket opens at</div>
            <div className="grid gap-2 sm:grid-cols-3">
              {form.lower_bounds.map((bound, index) => (
                <Field key={index} label={`Bracket ${index + 1}`} htmlFor={`night-bound-${index}`}>
                  <Input
                    id={`night-bound-${index}`}
                    type="number"
                    value={bound}
                    onChange={(e) => setForm({ ...form, lower_bounds: form.lower_bounds.map((one, at) => (at === index ? Number(e.target.value) : one)) })}
                  />
                </Field>
              ))}
            </div>
          </div>
          <div className="flex justify-end gap-2 p-4 pt-0">
            <Button variant="ghost" onClick={() => setDialogOpen(false)}>
              Cancel
            </Button>
            <Button disabled={!form.starts_at || saving} onClick={openNight}>
              {saving ? <Icon name="mdi-loading mdi-spin" /> : null}
              Open tonight
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

export default KothView;
