// src/views/LeaguesView.vue
<!-- Every league the app runs. A league is what repeats; its events are the runs
     players sign up for, and they live on the league's own page. -->
<template>
  <v-container fluid class="pa-4">
    <v-row class="mb-4">
      <v-col>
        <h1 class="text-h5 text-md-h3 font-weight-bold">
          <v-icon class="mr-2" size="large">mdi-shield-star</v-icon>
          Leagues
        </h1>
      </v-col>
    </v-row>

    <StatusAlert v-model="error" />

    <div v-if="auth.isAdmin" class="d-flex justify-end mb-4">
      <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openDialog">New league</v-btn>
    </div>

    <v-card elevation="2">
      <v-progress-linear v-if="loading" indeterminate />
      <v-table density="comfortable" hover>
        <thead>
          <tr>
            <th>League</th>
            <th class="d-none d-md-table-cell">Kind</th>
            <th class="d-none d-md-table-cell">Entrants</th>
            <th class="text-right">Events</th>
            <th class="d-none d-md-table-cell">Next event</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rows" :key="row.league.id">
            <td class="py-3">
              <RouterLink :to="`/leagues/${row.league.id}`"><strong>{{ row.league.name }}</strong></RouterLink>
              <!-- a phone drops three columns, so their words ride under the name -->
              <div class="d-md-none text-caption text-medium-emphasis">
                {{ [titleOf(LEAGUE_KINDS, row.league.kind), titleOf(ENTRANT_KINDS, row.league.entrant_kind), row.next && `Next: ${row.next.name}`].filter(Boolean).join(' · ') }}
              </div>
            </td>
            <td class="d-none d-md-table-cell">{{ titleOf(LEAGUE_KINDS, row.league.kind) }}</td>
            <td class="d-none d-md-table-cell">{{ titleOf(ENTRANT_KINDS, row.league.entrant_kind) }}</td>
            <td class="text-right">{{ row.count }}</td>
            <td class="d-none d-md-table-cell">
              <RouterLink v-if="row.next" :to="`/events/${row.next.id}`">{{ row.next.name }}</RouterLink>
              <span v-else class="text-medium-emphasis">—</span>
            </td>
          </tr>
          <tr v-if="!rows.length && !loading">
            <td colspan="5" class="text-medium-emphasis py-6 text-center">
              No leagues yet. A league holds the events that repeat, like the GNL or KOTH.
            </td>
          </tr>
        </tbody>
      </v-table>
    </v-card>

    <v-dialog v-model="dialog" max-width="600">
      <v-card title="New league">
        <v-card-text>
          <StatusAlert v-model="formError" />
          <v-row dense>
            <v-col cols="12" md="8">
              <v-text-field v-model="form.name" label="Name" autofocus />
            </v-col>
            <v-col cols="12" md="4">
              <v-text-field v-model="form.short_name" label="Short name" />
            </v-col>
            <v-col cols="12" md="6">
              <v-select v-model="form.kind" :items="LEAGUE_KINDS" label="Kind" />
            </v-col>
            <v-col cols="12" md="6">
              <v-select v-model="form.entrant_kind" :items="ENTRANT_KINDS" label="Entrants" />
            </v-col>
            <v-col cols="12">
              <v-text-field v-model="form.page_url" label="Page link" placeholder="https://" />
            </v-col>
          </v-row>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="dialog = false">Cancel</v-btn>
          <v-btn color="primary" variant="elevated" :loading="saving" :disabled="!form.name.trim()" @click="save">Create league</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';

import StatusAlert from '@/components/StatusAlert.vue';
import { ENTRANT_KINDS, LEAGUE_KINDS, leaguePayload, stateOf, titleOf } from '@/helpers/event-labels.mjs';
import { useAuthStore, useEventStore } from '@/stores';

const auth = useAuthStore();
const store = useEventStore();
const leagues = ref([]);
const events = ref([]);
const loading = ref(true);
const error = ref(null);
const dialog = ref(false);
const saving = ref(false);
const formError = ref(null);
const blank = () => ({ name: '', short_name: '', kind: 'custom', entrant_kind: 'solo', page_url: '' });
const form = ref(blank());

// The list read leaves a league's events empty, so the count and the next run come
// off the events list. The soonest run that has not finished is the next one.
const rows = computed(() => leagues.value.map((league) => {
  const mine = events.value.filter((event) => event.league_id === league.id);
  const next = [...mine]
    .filter((event) => stateOf(event) !== 'finished')
    .sort((a, b) => (a.start_date || '9999').localeCompare(b.start_date || '9999'))[0] || null;
  return { league, count: mine.length, next };
}));

const load = async () => {
  loading.value = true;
  try {
    [leagues.value, events.value] = await Promise.all([store.fetchLeagues(), store.fetchEvents()]);
  } catch (e) {
    error.value = `The leagues did not load: ${e.message}`;
  } finally {
    loading.value = false;
  }
};

const openDialog = () => {
  form.value = blank();
  formError.value = null;
  dialog.value = true;
};

const save = async () => {
  saving.value = true;
  formError.value = null;
  try {
    await store.createLeague(leaguePayload(form.value));
    dialog.value = false;
    await load();
  } catch (e) {
    formError.value = `The league was not created: ${e.message}`;
  } finally {
    saving.value = false;
  }
};

onMounted(load);
</script>

// next/src/app/(app)/leagues/LeaguesView.tsx
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageHeader } from "@/components/PageHeader";
import { StatusAlert } from "@/components/StatusAlert";
import { ENTRANT_KINDS, LEAGUE_KINDS, leaguePayload, stateOf, titleOf } from "@/helpers/event-labels.mjs";
import { useAuth, useEventStore } from "@/stores";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;
type Item = { value: string; title: string };

const phoneCell = "hidden min-[960px]:table-cell";
const blank = () => ({ name: "", short_name: "", kind: "custom", entrant_kind: "solo", page_url: "" });

/** One pick of the new league form: the v-select port, which shows the item's title. */
function KindSelect({ id, items, value, onChange }: { id: string; items: Item[]; value: string; onChange: (value: string) => void }) {
  return (
    <Select value={value} onValueChange={(picked) => onChange(picked as string)}>
      <SelectTrigger id={id} className="w-full">
        <SelectValue>{(picked: string) => titleOf(items, picked)}</SelectValue>
      </SelectTrigger>
      <SelectContent>
        {items.map((item) => (
          <SelectItem key={item.value} value={item.value}>
            {item.title}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

/** Every league the app runs. A league is what repeats; its events are the runs
 *  players sign up for, and they live on the league's own page. */
export function LeaguesView() {
  const auth = useAuth();
  const store = useEventStore();
  const [leagues, setLeagues] = useState<Row[]>([]);
  const [events, setEvents] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dialog, setDialog] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [form, setForm] = useState(blank());

  // The list read leaves a league's events empty, so the count and the next run come
  // off the events list. The soonest run that has not finished is the next one.
  const rows = leagues.map((league) => {
    const mine = events.filter((event) => event.league_id === league.id);
    const next = mine.filter((event) => stateOf(event) !== "finished").sort((a, b) => (a.start_date || "9999").localeCompare(b.start_date || "9999"))[0] || null;
    return { league, count: mine.length, next };
  });

  const load = async () => {
    try {
      const [leagueRows, eventRows] = await Promise.all([store.fetchLeagues(), store.fetchEvents()]);
      setLeagues(leagueRows);
      setEvents(eventRows);
    } catch (e) {
      setError(`The leagues did not load: ${(e as Error).message}`);
    } finally {
      setLoading(false);
    }
  };

  const openDialog = () => {
    setForm(blank());
    setFormError(null);
    setDialog(true);
  };

  const save = async () => {
    setSaving(true);
    setFormError(null);
    try {
      await store.createLeague(leaguePayload(form));
      setDialog(false);
      setLoading(true);
      await load();
    } catch (e) {
      setFormError(`The league was not created: ${(e as Error).message}`);
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    // the loader sets state, so it runs just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(load);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <PageHeader
        title={
          <span className="inline-flex items-center gap-2">
            <Icon name="mdi-shield-star" />
            Leagues
          </span>
        }
      />

      <StatusAlert modelValue={error} onClose={() => setError(null)} />

      {auth.isAdmin ? (
        <div className="mb-4 flex justify-end">
          <Button onClick={openDialog}>
            <Icon name="mdi-plus" />
            New league
          </Button>
        </div>
      ) : null}

      <Card className="card">
        {loading ? <Progress value={null} /> : null}
        <div className="table-scroll overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>League</TableHead>
                <TableHead className={phoneCell}>Kind</TableHead>
                <TableHead className={phoneCell}>Entrants</TableHead>
                <TableHead className="text-right">Events</TableHead>
                <TableHead className={phoneCell}>Next event</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.map((row) => (
                <TableRow key={row.league.id}>
                  <TableCell className="py-3">
                    <Link href={`/leagues/${row.league.id}`}>
                      <strong>{row.league.name}</strong>
                    </Link>
                    {/* a phone drops three columns, so their words ride under the name */}
                    <div className="text-xs text-muted-foreground min-[960px]:hidden">
                      {[titleOf(LEAGUE_KINDS, row.league.kind), titleOf(ENTRANT_KINDS, row.league.entrant_kind), row.next && `Next: ${row.next.name}`].filter(Boolean).join(" · ")}
                    </div>
                  </TableCell>
                  <TableCell className={phoneCell}>{titleOf(LEAGUE_KINDS, row.league.kind)}</TableCell>
                  <TableCell className={phoneCell}>{titleOf(ENTRANT_KINDS, row.league.entrant_kind)}</TableCell>
                  <TableCell className="tnum text-right">{row.count}</TableCell>
                  <TableCell className={phoneCell}>{row.next ? <Link href={`/events/${row.next.id}`}>{row.next.name}</Link> : <span className="text-muted-foreground">—</span>}</TableCell>
                </TableRow>
              ))}
              {!rows.length && !loading ? (
                <TableRow>
                  <TableCell colSpan={5} className="py-6 text-center text-muted-foreground">
                    No leagues yet. A league holds the events that repeat, like the GNL or KOTH.
                  </TableCell>
                </TableRow>
              ) : null}
            </TableBody>
          </Table>
        </div>
      </Card>

      <Dialog open={dialog} onOpenChange={setDialog}>
        <DialogContent showCloseButton={false} className="max-w-[600px] gap-0 p-0 sm:max-w-[600px]">
          <DialogTitle className="px-4 pt-4 text-xl">New league</DialogTitle>
          <div className="p-4">
            <StatusAlert modelValue={formError} onClose={() => setFormError(null)} />
            <div className="grid gap-3 min-[960px]:grid-cols-12">
              <Field className="min-[960px]:col-span-8" label="Name" htmlFor="league-name">
                <Input id="league-name" autoFocus value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />
              </Field>
              <Field className="min-[960px]:col-span-4" label="Short name" htmlFor="league-short-name">
                <Input id="league-short-name" value={form.short_name} onChange={(e) => setForm({ ...form, short_name: e.target.value })} />
              </Field>
              <Field className="min-[960px]:col-span-6" label="Kind" htmlFor="league-kind">
                <KindSelect id="league-kind" items={LEAGUE_KINDS} value={form.kind} onChange={(kind) => setForm({ ...form, kind })} />
              </Field>
              <Field className="min-[960px]:col-span-6" label="Entrants" htmlFor="league-entrant-kind">
                <KindSelect id="league-entrant-kind" items={ENTRANT_KINDS} value={form.entrant_kind} onChange={(entrant_kind) => setForm({ ...form, entrant_kind })} />
              </Field>
              <Field className="min-[960px]:col-span-12" label="Page link" htmlFor="league-page-url">
                <Input id="league-page-url" placeholder="https://" value={form.page_url} onChange={(e) => setForm({ ...form, page_url: e.target.value })} />
              </Field>
            </div>
          </div>
          <div className="flex justify-end gap-2 p-4 pt-0">
            <Button variant="ghost" onClick={() => setDialog(false)}>
              Cancel
            </Button>
            <Button disabled={saving || !form.name.trim()} onClick={save}>
              {saving ? <Icon name="mdi-loading mdi-spin" /> : null}
              Create league
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

export default LeaguesView;
