// src/views/SeasonTeamDetailsView.vue
<template>
  <v-overlay v-model="isLoading" persistent contained class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <!-- Page Header: the team, and the season it is read in -->
    <v-row class="mb-4">
      <v-col>
        <h1>
          <v-icon class="mr-2">mdi-shield-account</v-icon>
          {{ team?.name || 'Team' }}
        </h1>
        <div v-if="seasonLabel" class="text-medium-emphasis mt-1">{{ seasonLabel }}</div>
      </v-col>
    </v-row>

    <StatusAlert v-model="errorMessage" />

    <!-- Team Overview -->
    <v-card v-if="team" elevation="2" class="mb-4">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-shield-account</v-icon>
        <span>Season points</span>
      </v-card-title>
      <v-card-text v-if="currentSeasonInfo">
        <p><strong><ColumnNote title="Points:" :note="POINTS_NOTES['Points']" /></strong> {{ currentSeasonInfo.final_score }}</p>
        <p><strong><ColumnNote title="Points against:" :note="POINTS_NOTES['Points against']" /></strong> {{ currentSeasonInfo.points_against }}</p>
        <p><strong><ColumnNote title="Points available:" :note="POINTS_NOTES['Points available']" /></strong> {{ currentSeasonInfo.points_available }}</p>
      </v-card-text>
    </v-card>

    <!-- Ladder -->
    <v-card v-if="ladderTeam" elevation="2" class="mb-4">
      <v-card-title class="bg-primary d-flex align-center">
        <W3CIcon :size="22" class="mr-2" />
        <span>W3C ladder</span>
      </v-card-title>
      <v-toolbar flat height="auto">
        <v-row align="center" class="flex-wrap ma-0 pa-2" style="gap: 8px">
          <v-chip variant="outlined" size="small">{{ ladderTeam.points }} points</v-chip>
          <v-chip variant="outlined" size="small">Rank {{ ladderRank }}</v-chip>
          <v-chip variant="outlined" size="small">{{ ladderTeam.games }} games</v-chip>
          <v-spacer />
          <span class="text-caption text-medium-emphasis">
            {{ ladderSyncCaption }}
            <v-tooltip activator="parent" location="top">{{ localFromIso(ladderSyncedAt) }}</v-tooltip>
          </span>
        </v-row>
      </v-toolbar>
      <v-table density="compact">
        <thead>
          <tr>
            <th>Name</th>
            <th style="width: 64px">Race</th>
            <th class="text-right d-none d-md-table-cell">
              <ColumnNote title="Ladder points" :note="LADDER_NOTE" />
            </th>
            <th class="d-none d-md-table-cell">
              <ColumnNote title="Achievements" :note="ACHIEVEMENTS_NOTE" />
            </th>
            <th class="text-right">
              <ColumnNote title="Total points" :note="SCORED_NOTE" />
            </th>
            <th class="text-right">W</th>
            <th class="text-right">L</th>
            <th class="text-right"><W3CMmr /></th>
            <th class="text-right d-none d-md-table-cell">
              <W3CMmr suffix=" +/-" />
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in ladderTeam.players" :key="row.id">
            <td><PlayerName :player="row" /></td>
            <td><RaceIcon v-if="row.race" :raceIdentifier="row.race" /></td>
            <td class="text-right d-none d-md-table-cell">{{ row.ladder_points }}</td>
            <td class="d-none d-md-table-cell">
              <AchievementChip :badges="row.achievements" />
            </td>
            <td class="text-right font-weight-bold">{{ row.points }}</td>
            <td class="text-right text-win">{{ row.wins }}</td>
            <td class="text-right text-loss">{{ row.losses }}</td>
            <td class="text-right">{{ row.mmr?.current ?? '\u2014' }}</td>
            <td class="text-right d-none d-md-table-cell" :class="ladderMmrDiff(row) > 0 ? 'text-win' : ladderMmrDiff(row) < 0 ? 'text-loss' : ''">
              <span v-if="ladderMmrDiff(row) == null">&mdash;</span>
              <span v-else>{{ ladderMmrDiff(row) > 0 ? `+${ladderMmrDiff(row)}` : ladderMmrDiff(row) }}</span>
            </td>
          </tr>
        </tbody>
      </v-table>
    </v-card>

    <!-- The roster of this season: the captains an admin sets, then the players -->
    <TeamRoster :captains="seasonCaptains" :members="players"
      no-captains="No captains recorded for this season." no-members="No members recorded for this season.">
      <template #captains-actions>
        <v-card-text v-if="auth.isAdmin" class="pa-0">
          <v-toolbar flat height="auto">
            <v-row align="center" class="flex-wrap ma-0 pa-2">
              <v-spacer />
              <v-col cols="12" sm="auto">
                <v-btn variant="elevated" color="success" prepend-icon="mdi-content-save" @click="saveCaptains" :loading="isSavingCaptains" :disabled="isSavingCaptains" block>
                  Save captains
                </v-btn>
              </v-col>
            </v-row>
          </v-toolbar>
        </v-card-text>
      </template>

      <template #captains="{ captains }">
        <div v-if="!auth.isAdmin" class="d-flex flex-wrap ga-3">
          <PlayerName v-for="captain in captains" :key="captain.id" :player="captain" />
          <span v-if="!captains.length" class="text-medium-emphasis">No captains recorded for this season.</span>
        </div>

        <template v-else>
          <p class="text-subtitle-2 mb-3">Assign the captains of this season:</p>

          <v-autocomplete
            v-model="captainIds"
            :items="allAvailableUsers"
            item-title="name"
            item-value="id"
            label="Captains"
            placeholder="Start typing to search..."
            multiple
            chips
            closable-chips
            clearable
            auto-select-first
            hint="Any number of captains"
            persistent-hint
          >
            <template v-slot:prepend-inner>
              <v-icon color="primary">mdi-shield-star</v-icon>
            </template>
          </v-autocomplete>
        </template>

        <!-- Save captains answers the accounts the guild has not granted the role yet -->
        <v-chip
          v-for="captain in missingRoleCaptains"
          :key="captain.id"
          color="warning"
          variant="tonal"
          size="small"
          prepend-icon="mdi-alert"
          class="mr-2 mt-4"
        >
          {{ captain.name }} — role missing in Discord
        </v-chip>
      </template>

      <template #members="{ members }">
        <v-card-text class="pa-0">
          <v-data-table
            :headers="tableHeader"
            :loading="isLoading"
            :items="members"
            :hide-default-footer="members.length <= 10"
            :row-props="playerRowProps"
            fixed-header
            hover
          >
            <template v-slot:[`header.mmr`]><W3CMmr /></template>
            <template v-slot:loading>
              <v-skeleton-loader type="table-row@10"></v-skeleton-loader>
            </template>

            <template #top>
              <v-toolbar v-if="auth.isAdmin || canSetRounds" flat height="auto">
                <v-row align="center" class="flex-wrap ma-0 pa-2">
                  <v-spacer />
                  <v-col cols="12" sm="auto">
                    <v-btn v-if="auth.isAdmin" variant="elevated" color="primary" @click="syncW3CTeam" :loading="isLoading" :disabled="isLoading" block>
                      <template #prepend><W3CIcon :size="18" /></template>
                      Sync W3C
                      <v-tooltip activator="parent" location="top">MMR and ladder matches</v-tooltip>
                    </v-btn>
                  </v-col>
                  <v-col cols="12" sm="auto">
                    <v-btn v-if="canSetRounds" variant="elevated" color="primary" prepend-icon="mdi-calendar-account" :to="`/team/${teamId}/season/${$route.params.season_id}/rounds`" block>
                      Team rounds
                    </v-btn>
                  </v-col>
                  <v-col cols="12" sm="auto">
                    <v-btn v-if="auth.isAdmin" variant="elevated" color="success" prepend-icon="mdi-plus" @click="showNewPlayerModal = true" block>
                      Add player
                    </v-btn>
                  </v-col>
                </v-row>
              </v-toolbar>
            </template>

              <template v-slot:item="{ item }">
                <tr class="text-no-wrap">
                  <td><PlayerName :player="item" /></td>
                  <td class="d-none d-md-table-cell">{{ item.battleTag }}</td>
                  <td class="d-none d-md-table-cell">{{ item.discordTag }}</td>
                  <td>{{ getW3CMMR(item, currentW3CSeason, item.signup_race) ?? 'N/A' }}
                    <div class="text-caption text-medium-emphasis">{{ syncedAgo(item) }}<v-tooltip activator="parent" location="top">{{ syncedAt(item) }}</v-tooltip></div>
                  </td>
                  <td>
                    <div v-if="item.signup_race">
                      <RaceIcon :raceIdentifier="item.signup_race" />
                    </div>
                  </td>     
                  <td>
                    <RowActions :actions="[
                      { icon: 'mdi-chart-box', label: 'View player stats', public: true, onClick: () => router.push(playerPath(item)) },
                      { icon: 'mdi-account-minus', label: 'Remove from team', color: 'error', onClick: () => removePlayerFromTeam(item.id) },
                    ]" />
                  </td>
                </tr>
              </template>
            <template #no-data>
              <div v-if="!errorMessage" class="text-center pa-8">
                <v-icon size="64" class="text-disabled">mdi-account-off</v-icon>
                <div class="text-h6 text-medium-emphasis mt-4 mb-2">No players found</div>
                <p class="text-medium-emphasis mb-4">Add players to this team to get started</p>
                <v-btn v-if="auth.isAdmin" variant="elevated" color="primary" prepend-icon="mdi-plus" @click="showNewPlayerModal = true">
                  Add first player
                </v-btn>
              </div>
            </template>
          </v-data-table>
        </v-card-text>
      </template>
    </TeamRoster>

  <!-- Add New Player Modal -->
  <v-dialog v-model="showNewPlayerModal" persistent max-width="900">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-account-multiple-plus</v-icon>
        Select players to add
      </v-card-title>

      <v-card-text class="pt-4">
        <!-- Filters (reusable) -->
        <FilterPanel
          v-model:searchName="searchName"
          v-model:searchRace="searchRace"
          v-model:rangeValues="rangeValues"
          :showName="true"
          :showRace="true"
          :showSeason="false"
          :showMMR="true"
          :showReset="true"
          @reset="fetchAllPlayers"
        />
        <v-data-table
          :headers="playerTableHeaders"
          :items="filteredAllPlayers"
          item-value="id"
          v-model="selectedPlayers"
          show-select
          :item-disabled="isRowDisabled"
          density="comfortable"
        >
          <template v-slot:[`header.mmr`]><W3CMmr /></template>
          <template v-slot:[`item.name`]="{ item }">
            <PlayerName :player="item" plain />
          </template>
        </v-data-table>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn @click="showNewPlayerModal = false">Cancel</v-btn>
        <v-btn color="primary" variant="elevated" prepend-icon="mdi-content-save" v-if="auth.isAdmin" @click="saveSelectedPlayers">
          Add selected players
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <W3CSyncResultDialog v-model="syncDialog" :entries="syncEntries" />
  </v-container>
</template>

<script setup>
import RowActions from '@/components/RowActions.vue';
import { useRouter } from 'vue-router';
import { useAuthStore, useTeamStore, usePlayerStore, useSeasonStore, useLadderStore } from '@/stores';
import { resolveCurrentW3CSeason } from '@/helpers/current-season';
import { SCORED_NOTE, ACHIEVEMENTS_NOTE, LADDER_NOTE, POINTS_NOTES } from '@/helpers/achievements';
import ColumnNote from '@/components/ColumnNote.vue';
import W3CMmr from '@/components/W3CMmr.vue';
import { computed, onMounted, ref, watch } from 'vue';
import { storeToRefs } from 'pinia';
import AchievementChip from '@/components/AchievementChip.vue';
import FilterPanel from '@/components/FilterPanel.vue';
import { getW3CMMR, syncedAgo, syncedAt, agoFromIso, localFromIso } from '@/helpers/w3c-stats';
import { matchesPlayerSearch, filterByMmrRange, playerPath, playerRowProps } from '@/helpers/players';
import W3CIcon from '@/components/W3CIcon.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import W3CSyncResultDialog from '@/components/W3CSyncResultDialog.vue';
import { useColumns } from '@/helpers/columns';
import { eventLabel } from '@/helpers/event-labels.mjs';
import { rosterOf } from '@/helpers/team-roster.mjs';
import TeamRoster from '@/components/TeamRoster.vue';


// Router and store setup
const router = useRouter();
const teamStore = useTeamStore();
const playerStore = usePlayerStore();
const seasonStore = useSeasonStore();
const ladderStore = useLadderStore();
const auth = useAuthStore();

// Route params
const teamId = computed(() => router.currentRoute.value.params.id);
const seasonId = computed(() => {
  const id = router.currentRoute.value.params.season_id;
  return id ? useSeasonStore().seasonIdOf(id) : null;
});

// The rounds grid takes a captain of this team, or any admin
const canSetRounds = computed(() => auth.isCaptainOf(teamId.value, seasonId.value));

// The season under the team name, named the way every other page names an event
const seasonLabel = computed(() => {
  const season = seasonStore.seasons.find((row) => row.id === seasonId.value);
  return season ? eventLabel(season) : '';
});

// Current W3C season for stats fallback
const currentW3CSeason = ref(null);

// Store refs
const { team } = storeToRefs(teamStore);

// Season info for the currently viewed season
const currentSeasonInfo = computed(() => {
  if (!team.value?.seasons_info) return null;
  return team.value.seasons_info.find(s => s.season_id === seasonId.value)
    ?? team.value.seasons_info[0];
});

// State management
const isLoading = ref(false);
const errorMessage = ref(null);
const players = ref([]);
// The Add Player dialog pool: season signups, carrying signup_race and MMR stats
const seasonSignups = ref([]);
const showNewPlayerModal = ref(false);
const selectedPlayers = ref([]);

// Captain management state
const captainIds = ref([]);
const discordRoleMissing = ref([]);
const isSavingCaptains = ref(false);
const allAvailableUsers = ref([]);

const seasonCaptains = computed(() => rosterOf(team.value, seasonId.value).captains);

const missingRoleCaptains = computed(() =>
  seasonCaptains.value.filter(captain => discordRoleMissing.value.includes(captain.discordId))
);

// Ladder card state
const seasonLadder = ref(null);

const ladderTeam = computed(() =>
  (seasonLadder.value?.teams ?? []).find(t => String(t.id) === String(teamId.value)) ?? null
);

// The card is as synced as its least synced player, and says so when one is behind
const ladderSyncedAt = computed(() => {
  const stamps = (ladderTeam.value?.players ?? []).map(player => player.synced_at).filter(Boolean);
  return seasonLadder.value?.season?.synced_at ?? stamps.sort()[0] ?? null;
});

const ladderSyncCaption = computed(() => {
  const players = ladderTeam.value?.players ?? [];
  const synced = players.filter(player => player.synced_at).length;
  if (!synced) return 'never synced';
  if (synced < players.length) return `partly synced · ${synced} of ${players.length} players`;
  const ago = agoFromIso(ladderSyncedAt.value);
  return ago === 'never synced' ? ago : `synced ${ago}`;
});

// The teams of the answer are ordered by ladder points
const ladderRank = computed(() =>
  (seasonLadder.value?.teams ?? []).findIndex(t => String(t.id) === String(teamId.value)) + 1
);

// A player still in his placement games has no MMR, so there is no span to subtract
const ladderMmrDiff = (row) =>
  row.mmr?.current != null && row.mmr?.start != null ? row.mmr.current - row.mmr.start : null;

const fetchLadder = async () => {
  if (!seasonId.value) return;
  try {
    seasonLadder.value = await ladderStore.seasonLadder(seasonId.value);
  } catch (error) {
    console.error('Failed to load the ladder of the season:', error);
    seasonLadder.value = null;
  }
};

// Search state
const searchRace = ref(null);
const searchName = ref(null);
const rangeValues = ref([0, 3000]);

// Table configuration
const allTableHeader = [
  { title: 'Name', value: 'name', sortable: true },  
  { mobile: false, title: 'Battletag', value: 'battleTag', sortable: true },    
  { mobile: false, title: 'Discord name', value: 'discordTag', sortable: true }, 
  { title: 'W3C MMR', value: 'mmr', sortable: false }, 
  { title: 'Main race', value: 'race', sortable: true },  
  { title: '', key: 'actions', align: 'end', sortable: false }, 
];
const tableHeader = useColumns(allTableHeader);

const playerTableHeaders = [
  { title: 'Name', value: 'name' },
  { title: 'Battletag', value: 'battleTag' },
  { title: 'MMR', value: 'mmr' },
];

// Methods

const fetchAllPlayers = async () => {
  try {
    seasonSignups.value = await seasonStore.fetchSeasonSignups(seasonId.value) || [];
  } catch (error) {
    console.error('Failed to fetch players:', error);
  } finally {
    isLoading.value = false;
    searchName.value = '';
    searchRace.value = '';
    rangeValues.value = [0, 3000];
  }
};

const fetchTeam = async () => {
  isLoading.value = true;
  errorMessage.value = null;
  try {
    await teamStore.fetchTeamBySeason(teamId.value, seasonId.value);
    if (!team.value) {
      errorMessage.value = 'No team information found.';
    }
    players.value = rosterOf(team.value, seasonId.value).members;
    
    // Load ALL users for captain selection (captains can be anyone, not just season players)
    await playerStore.fetchPlayers();
    // For captains, use ALL users directly from store (not filtered by season)
    allAvailableUsers.value = playerStore.players || [];
    
    // Initialize captain selections based on current captains (order is preserved)
    captainIds.value = seasonCaptains.value.map(captain => captain.id);
  } catch (error) {
    console.error(error);
    errorMessage.value = 'Failed to load team. Please try again later.';
  } finally {
    isLoading.value = false;
  }
};

const saveCaptains = async () => {
  isSavingCaptains.value = true;
  try {
    const saved = await teamStore.setCaptains(teamId.value, seasonId.value, captainIds.value);
    // Refresh team data to show updated captain status
    await fetchTeam();
    discordRoleMissing.value = saved?.discord_role_missing || [];
  } catch (error) {
    console.error('Failed to save captains:', error);
    errorMessage.value = 'Failed to save captains. Please try again.';
  } finally {
    isSavingCaptains.value = false;
  }
};

const saveSelectedPlayers = async () => {
  try {
    await teamStore.addPlayersToTeamForSeason(
      teamId.value,
      seasonId.value,
      selectedPlayers.value
    );
    selectedPlayers.value = [];
    fetchTeam();
    showNewPlayerModal.value = false;
  } catch (error) {
    console.error('Failed to save selected players:', error);
  }
};

watch(showNewPlayerModal, (newValue) => {
  if (newValue === true) {
    fetchAllPlayers();
  }
});

onMounted(async () => {
  currentW3CSeason.value = await resolveCurrentW3CSeason();
  fetchTeam();
  fetchLadder();
});

const removePlayerFromTeam = async (playerId) => {
  if (!confirm('Remove this player from the team?')) return;
  try {
    await teamStore.removePlayersFromTeamForSeason(
      teamId.value,
      seasonId.value,
      [playerId]
    );
    fetchTeam();
  } catch (error) {
    console.error('Error removing player:', error);
  }
};

const syncDialog = ref(false);
const syncEntries = ref([]);

const syncW3CTeam = async () => {
  isLoading.value = true;
  syncEntries.value = [];
  syncDialog.value = true;
  try {
    syncEntries.value = [{ title: team.value?.name ?? 'Team', result: await teamStore.syncPlayersW3C(teamId.value, seasonId.value) }];
    await fetchTeam();
  } catch (error) {
    console.error('Error syncing W3C data:', error);
    syncEntries.value = [{ title: team.value?.name ?? 'Team', error }];
  } finally {
    isLoading.value = false;
  }
};

const isRowDisabled = (item) => {
  let playerAlreadyInTeam = false;
  for (const player in players.value) {
    if (player == item.id) {
      playerAlreadyInTeam = true;
      break;
    }
  }
  return playerAlreadyInTeam;
};





const filteredAllPlayers = computed(() => {
  let list = seasonSignups.value || [];

  if (searchName.value && searchName.value.trim().length > 0) {
    list = list.filter(p => matchesPlayerSearch(p, searchName.value));
  }

  if (searchRace.value) {
    list = list.filter(p => p.signup_race === searchRace.value);
  }

  // filter by mmr range — only apply if user changed from defaults
  list = filterByMmrRange(list, rangeValues.value, p => Number(getW3CMMR(p, currentW3CSeason.value, p.signup_race) ?? 0));

  return list;
});

</script>

<style scoped>
.player-row {
  cursor: pointer;
  transition: all 0.2s ease;
}

.player-row:hover {
  background-color: rgba(var(--v-theme-primary), 0.05) !important;
}

</style>

// next/src/app/(app)/team/[id]/season/[season_id]/SeasonTeamDetailsView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Combobox } from "@/components/ui/Combobox";
import { DataTable } from "@/components/ui/DataTable";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Icon } from "@/components/ui/Icon";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { TapTooltip } from "@/components/ui/TapTooltip";
import { toneClass } from "@/components/ui/tone";
import { AchievementChip } from "@/components/AchievementChip";
import { ColumnNote } from "@/components/ColumnNote";
import { FilterPanel } from "@/components/FilterPanel";
import { PlayerName } from "@/components/PlayerName";
import { RaceIcon } from "@/components/RaceIcon";
import { RowActions } from "@/components/RowActions";
import { StatusAlert } from "@/components/StatusAlert";
import { TeamRoster } from "@/components/TeamRoster";
import { W3CIcon } from "@/components/W3CIcon";
import { W3CMmr } from "@/components/W3CMmr";
import { W3CSyncResultDialog, type SyncEntry } from "@/components/W3CSyncResultDialog";
import { MD_AND_UP, useBreakpoint } from "@/hooks/breakpoint";
import { ACHIEVEMENTS_NOTE, LADDER_NOTE, POINTS_NOTES, SCORED_NOTE } from "@/helpers/achievements";
import { resolveCurrentW3CSeason } from "@/helpers/current-season";
import { eventLabel } from "@/helpers/event-labels.mjs";
import { filterByMmrRange, matchesPlayerSearch, playerPath } from "@/helpers/players.mjs";
import { rosterOf } from "@/helpers/team-roster.mjs";
import { agoFromIso, getW3CMMR, localFromIso, syncedAgo, syncedAt } from "@/helpers/w3c-stats";
import { useAuth, useLadderStore, usePlayerStore, useSeason, useTeamStore } from "@/stores";

type Row = Record<string, any>;
const pointsNotes = POINTS_NOTES as Record<string, string>;

// A player still in his placement games has no MMR, so there is no span to subtract
const ladderMmrDiff = (row: Row) => (row.mmr?.current != null && row.mmr?.start != null ? row.mmr.current - row.mmr.start : null);

const diffClass = (diff: number | null) => (diff == null ? "" : diff > 0 ? "text-win" : diff < 0 ? "text-loss" : "");

export function SeasonTeamDetailsView({ id, seasonKey }: { id: string; seasonKey: string }) {
  const auth = useAuth();
  const teamStore = useTeamStore();
  const playerStore = usePlayerStore();
  const ladderStore = useLadderStore();
  const { seasons, seasonIdOf, fetchSeasonSignups } = useSeason();

  const teamId = Number(id);
  const seasonId = seasonIdOf(seasonKey);
  const mdAndUp = useBreakpoint(MD_AND_UP);

  const [team, setTeam] = useState<Row | null>(null);
  const [players, setPlayers] = useState<Row[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [currentW3CSeason, setCurrentW3CSeason] = useState<number | undefined>(undefined);

  // The Add Player dialog pool: season signups, carrying signup_race and MMR stats
  const [seasonSignups, setSeasonSignups] = useState<Row[]>([]);
  const [showNewPlayerModal, setShowNewPlayerModal] = useState(false);
  const [selectedPlayers, setSelectedPlayers] = useState<number[]>([]);

  const [captainIds, setCaptainIds] = useState<number[]>([]);
  const [discordRoleMissing, setDiscordRoleMissing] = useState<string[]>([]);
  const [isSavingCaptains, setIsSavingCaptains] = useState(false);
  const [allAvailableUsers, setAllAvailableUsers] = useState<Row[]>([]);

  const [seasonLadder, setSeasonLadder] = useState<Row | null>(null);
  const [syncDialog, setSyncDialog] = useState(false);
  const [syncEntries, setSyncEntries] = useState<SyncEntry[]>([]);

  const [searchName, setSearchName] = useState("");
  const [searchRace, setSearchRace] = useState<string | null>(null);
  const [rangeValues, setRangeValues] = useState([0, 3000]);

  // The rounds grid takes a captain of this team, or any admin
  const canSetRounds = auth.isCaptainOf(teamId, seasonId as number);

  // The season under the team name, named the way every other page names an event
  const seasonRow = seasons.find((row: Row) => row.id === seasonId);
  const seasonLabel = seasonRow ? eventLabel(seasonRow) : "";

  // Season info for the currently viewed season
  const currentSeasonInfo = team?.seasons_info ? team.seasons_info.find((s: Row) => s.season_id === seasonId) ?? team.seasons_info[0] : null;

  const seasonCaptains: Row[] = rosterOf(team, seasonId).captains;
  const missingRoleCaptains = seasonCaptains.filter((captain) => discordRoleMissing.includes(captain.discordId));
  const chosenCaptains = captainIds.map((captainId) => allAvailableUsers.find((user) => user.id === captainId) ?? { id: captainId, name: String(captainId) });

  const ladderTeam: Row | null = (seasonLadder?.teams ?? []).find((t: Row) => String(t.id) === String(teamId)) ?? null;

  // The card is as synced as its least synced player, and says so when one is behind
  const ladderSyncedAt = (() => {
    const stamps = (ladderTeam?.players ?? []).map((player: Row) => player.synced_at).filter(Boolean);
    return seasonLadder?.season?.synced_at ?? stamps.sort()[0] ?? null;
  })();

  const ladderSyncCaption = (() => {
    const ladderPlayers: Row[] = ladderTeam?.players ?? [];
    const synced = ladderPlayers.filter((player) => player.synced_at).length;
    if (!synced) return "never synced";
    if (synced < ladderPlayers.length) return `partly synced · ${synced} of ${ladderPlayers.length} players`;
    const ago = agoFromIso(ladderSyncedAt);
    return ago === "never synced" ? ago : `synced ${ago}`;
  })();

  // The teams of the answer are ordered by ladder points
  const ladderRank = (seasonLadder?.teams ?? []).findIndex((t: Row) => String(t.id) === String(teamId)) + 1;

  const fetchTeam = async () => {
    setIsLoading(true);
    setErrorMessage(null);
    try {
      const loaded = await teamStore.fetchTeamBySeason(teamId, seasonId as number);
      setTeam(loaded);
      if (!loaded) setErrorMessage("No team information found.");
      setPlayers(rosterOf(loaded, seasonId).members);
      // Load ALL users for captain selection (captains can be anyone, not just season players)
      const users = (await playerStore.fetchPlayers()) || [];
      setAllAvailableUsers(users);
      // Initialize captain selections based on current captains (order is preserved)
      setCaptainIds(rosterOf(loaded, seasonId).captains.map((captain: Row) => captain.id));
      return loaded;
    } catch (error) {
      console.error(error);
      setErrorMessage("Failed to load team. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (!seasonId) return;
    // the loaders set state, so they run just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(async () => {
      setCurrentW3CSeason((await resolveCurrentW3CSeason()) ?? undefined);
      await fetchTeam();
      try {
        setSeasonLadder(await ladderStore.seasonLadder(seasonId));
      } catch (error) {
        console.error("Failed to load the ladder of the season:", error);
        setSeasonLadder(null);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId, teamId]);

  const fetchAllPlayers = async () => {
    try {
      setSeasonSignups((await fetchSeasonSignups(seasonId as number)) || []);
    } catch (error) {
      console.error("Failed to fetch players:", error);
    } finally {
      setIsLoading(false);
      setSearchName("");
      setSearchRace(null);
      setRangeValues([0, 3000]);
    }
  };

  const openNewPlayerModal = () => {
    setShowNewPlayerModal(true);
    fetchAllPlayers();
  };

  const saveCaptains = async () => {
    setIsSavingCaptains(true);
    try {
      const saved = await teamStore.setCaptains(teamId, seasonId as number, captainIds);
      // Refresh team data to show updated captain status
      await fetchTeam();
      setDiscordRoleMissing(saved?.discord_role_missing || []);
    } catch (error) {
      console.error("Failed to save captains:", error);
      setErrorMessage("Failed to save captains. Please try again.");
    } finally {
      setIsSavingCaptains(false);
    }
  };

  const saveSelectedPlayers = async () => {
    try {
      await teamStore.addPlayersToTeamForSeason(teamId, seasonId as number, selectedPlayers);
      setSelectedPlayers([]);
      await fetchTeam();
      setShowNewPlayerModal(false);
    } catch (error) {
      console.error("Failed to save selected players:", error);
    }
  };

  const removePlayerFromTeam = async (playerId: number) => {
    if (!confirm("Remove this player from the team?")) return;
    try {
      await teamStore.removePlayersFromTeamForSeason(teamId, seasonId as number, [playerId]);
      await fetchTeam();
    } catch (error) {
      console.error("Error removing player:", error);
    }
  };

  const syncW3CTeam = async () => {
    setIsLoading(true);
    setSyncEntries([]);
    setSyncDialog(true);
    try {
      setSyncEntries([{ title: team?.name ?? "Team", result: await teamStore.syncPlayersW3C(teamId, seasonId as number) }]);
      await fetchTeam();
    } catch (error) {
      console.error("Error syncing W3C data:", error);
      setSyncEntries([{ title: team?.name ?? "Team", error: error as Error }]);
    } finally {
      setIsLoading(false);
    }
  };

  // The dialog table holds its page while this array holds its identity, so a tick keeps the page
  const filteredAllPlayers: Row[] = useMemo(() => {
    let list = seasonSignups;
    if (searchName.trim().length > 0) list = list.filter((p) => matchesPlayerSearch(p, searchName));
    if (searchRace) list = list.filter((p) => p.signup_race === searchRace);
    // filter by mmr range — only apply if user changed from defaults
    return filterByMmrRange(list, rangeValues, (p: Row) => Number(getW3CMMR(p, currentW3CSeason, p.signup_race) ?? 0));
  }, [seasonSignups, searchName, searchRace, rangeValues, currentW3CSeason]);

  const syncCell = (row: Row) => (
    <TapTooltip className="text-xs text-muted-foreground" content={syncedAt(row)}>
      {syncedAgo(row)}
    </TapTooltip>
  );

  return (
    <div className="p-4">
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <Icon name="mdi-loading" size={64} className="animate-spin text-primary" />
        </div>
      ) : null}

      {/* Page Header: the team, and the season it is read in */}
      <div className="mb-4">
        <h1 className="flex items-center gap-2">
          <Icon name="mdi-shield-account" />
          {team?.name || "Team"}
        </h1>
        {seasonLabel ? <div className="mt-1 text-muted-foreground">{seasonLabel}</div> : null}
      </div>

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      {/* Team Overview */}
      {team ? (
        <Card className="card mb-4 gap-0 py-0">
          <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-shield-account" />
            <span>Season points</span>
          </CardTitle>
          {currentSeasonInfo ? (
            <CardContent className="py-4">
              <p>
                <strong>
                  <ColumnNote title="Points:" note={pointsNotes["Points"]} />
                </strong>{" "}
                <span className="tnum">{currentSeasonInfo.final_score}</span>
              </p>
              <p>
                <strong>
                  <ColumnNote title="Points against:" note={pointsNotes["Points against"]} />
                </strong>{" "}
                <span className="tnum">{currentSeasonInfo.points_against}</span>
              </p>
              <p>
                <strong>
                  <ColumnNote title="Points available:" note={pointsNotes["Points available"]} />
                </strong>{" "}
                <span className="tnum">{currentSeasonInfo.points_available}</span>
              </p>
            </CardContent>
          ) : null}
        </Card>
      ) : null}

      {/* Ladder */}
      {ladderTeam ? (
        <Card className="card mb-4 gap-0 py-0">
          <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <W3CIcon size={22} />
            <span>W3C ladder</span>
          </CardTitle>
          <div className="flex flex-wrap items-center gap-2 p-2">
            <Badge variant="outline">{ladderTeam.points} points</Badge>
            <Badge variant="outline">Rank {ladderRank}</Badge>
            <Badge variant="outline">{ladderTeam.games} games</Badge>
            <TapTooltip className="ms-auto text-xs text-muted-foreground" content={localFromIso(ladderSyncedAt)}>
              {ladderSyncCaption}
            </TapTooltip>
          </div>
          <div className="table-scroll overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead style={{ width: "64px" }}>Race</TableHead>
                  <TableHead className="hidden text-right min-[960px]:table-cell">
                    <ColumnNote title="Ladder points" note={LADDER_NOTE} />
                  </TableHead>
                  <TableHead className="hidden min-[960px]:table-cell">
                    <ColumnNote title="Achievements" note={ACHIEVEMENTS_NOTE} />
                  </TableHead>
                  <TableHead className="text-right">
                    <ColumnNote title="Total points" note={SCORED_NOTE} />
                  </TableHead>
                  <TableHead className="text-right">W</TableHead>
                  <TableHead className="text-right">L</TableHead>
                  <TableHead className="text-right">
                    <W3CMmr />
                  </TableHead>
                  <TableHead className="hidden text-right min-[960px]:table-cell">
                    <W3CMmr suffix=" +/-" />
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {(ladderTeam.players ?? []).map((row: Row) => (
                  <TableRow key={row.id}>
                    <TableCell>
                      <PlayerName player={row} />
                    </TableCell>
                    <TableCell>{row.race ? <RaceIcon raceIdentifier={row.race} /> : null}</TableCell>
                    <TableCell className="tnum hidden text-right min-[960px]:table-cell">{row.ladder_points}</TableCell>
                    <TableCell className="hidden min-[960px]:table-cell">
                      <AchievementChip badges={row.achievements} />
                    </TableCell>
                    <TableCell className="tnum text-right font-bold">{row.points}</TableCell>
                    <TableCell className="tnum text-right text-win">{row.wins}</TableCell>
                    <TableCell className="tnum text-right text-loss">{row.losses}</TableCell>
                    <TableCell className="tnum text-right">{row.mmr?.current ?? "—"}</TableCell>
                    <TableCell className={`tnum hidden text-right min-[960px]:table-cell ${diffClass(ladderMmrDiff(row))}`}>
                      {ladderMmrDiff(row) == null ? "—" : ladderMmrDiff(row)! > 0 ? `+${ladderMmrDiff(row)}` : ladderMmrDiff(row)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </Card>
      ) : null}

      {/* The roster of this season: the captains an admin sets, then the players */}
      <TeamRoster
        captains={seasonCaptains}
        members={players}
        noCaptains="No captains recorded for this season."
        noMembers="No members recorded for this season."
        captainsActions={
          auth.isAdmin ? (
            <div className="flex justify-end p-2">
              <Button className="bg-success text-on-success" onClick={saveCaptains} disabled={isSavingCaptains}>
                <Icon name={isSavingCaptains ? "mdi-loading mdi-spin" : "mdi-content-save"} />
                Save captains
              </Button>
            </div>
          ) : null
        }
        renderCaptains={({ captains }) => (
          <>
            {!auth.isAdmin ? (
              <div className="flex flex-wrap gap-3">
                {captains.map((captain) => (
                  <PlayerName key={captain.id} player={captain} />
                ))}
                {!captains.length ? <span className="text-muted-foreground">No captains recorded for this season.</span> : null}
              </div>
            ) : (
              <>
                <p className="mb-3 text-sm font-medium">Assign the captains of this season:</p>
                {/* Any number of captains: the picker adds one, and each chip takes one back out */}
                <Combobox
                  label="Captains"
                  placeholder="Start typing to search..."
                  items={allAvailableUsers.filter((user) => !captainIds.includes(user.id)).map((user) => ({ value: String(user.id), title: user.name ?? "" }))}
                  value={null}
                  onChange={(value) => (value == null ? undefined : setCaptainIds((was) => [...was, Number(value)]))}
                />
                <p className="mt-1 text-xs text-muted-foreground">Any number of captains</p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {chosenCaptains.map((captain) => (
                    <Badge key={captain.id} variant="secondary">
                      {captain.name}
                      <button
                        type="button"
                        aria-label={`Remove ${captain.name}`}
                        onClick={() => setCaptainIds((was) => was.filter((captainId) => captainId !== captain.id))}
                      >
                        <Icon name="mdi-close" />
                      </button>
                    </Badge>
                  ))}
                </div>
              </>
            )}

            {/* Save captains answers the accounts the guild has not granted the role yet */}
            <div className="mt-4 flex flex-wrap gap-2">
              {missingRoleCaptains.map((captain) => (
                <Badge key={captain.id} className={toneClass("warning")}>
                  <Icon name="mdi-alert" />
                  {captain.name} — role missing in Discord
                </Badge>
              ))}
            </div>
          </>
        )}
        renderMembers={({ members }) => (
          <>
            {auth.isAdmin || canSetRounds ? (
              <div className="flex flex-wrap justify-end gap-2 p-2">
                {auth.isAdmin ? (
                  <TapTooltip content="MMR and ladder matches">
                    <Button onClick={syncW3CTeam} disabled={isLoading}>
                      <W3CIcon size={18} />
                      Sync W3C
                    </Button>
                  </TapTooltip>
                ) : null}
                {canSetRounds ? (
                  <Button nativeButton={false} render={<Link href={`/team/${teamId}/season/${seasonKey}/rounds`} />}>
                    <Icon name="mdi-calendar-account" />
                    Team rounds
                  </Button>
                ) : null}
                {auth.isAdmin ? (
                  <Button className="bg-success text-on-success" onClick={openNewPlayerModal}>
                    <Icon name="mdi-plus" />
                    Add player
                  </Button>
                ) : null}
              </div>
            ) : null}
            {/* The roster arrives after the mount, so the table starts over when the paging mode changes */}
            <DataTable
              key={members.length > 10 ? "paged" : "all"}
              data={members as Row[]}
              pageSize={members.length > 10 ? 10 : undefined}
              columnVisibility={{ battleTag: mdAndUp, discordTag: mdAndUp }}
              empty={
                errorMessage ? null : (
                  <div className="p-8 text-center">
                    <Icon name="mdi-account-off" size={64} className="text-muted-foreground" />
                    <div className="mt-4 mb-2 text-xl text-muted-foreground">No players found</div>
                    <p className="mb-4 text-muted-foreground">Add players to this team to get started</p>
                    {auth.isAdmin ? (
                      <Button onClick={openNewPlayerModal}>
                        <Icon name="mdi-plus" />
                        Add first player
                      </Button>
                    ) : null}
                  </div>
                )
              }
              columns={[
                { id: "name", accessorKey: "name", header: "Name", cell: ({ row }) => <PlayerName player={row.original} /> },
                { id: "battleTag", accessorKey: "battleTag", header: "Battletag" },
                { id: "discordTag", accessorKey: "discordTag", header: "Discord name" },
                {
                  id: "mmr",
                  header: () => <W3CMmr />,
                  enableSorting: false,
                  cell: ({ row }) => (
                    <>
                      <div className="tnum">{getW3CMMR(row.original, currentW3CSeason, row.original.signup_race) ?? "N/A"}</div>
                      {syncCell(row.original)}
                    </>
                  ),
                },
                {
                  id: "race",
                  accessorKey: "signup_race",
                  header: "Main race",
                  cell: ({ row }) => (row.original.signup_race ? <RaceIcon raceIdentifier={row.original.signup_race} /> : null),
                },
                {
                  id: "actions",
                  header: "",
                  enableSorting: false,
                  cell: ({ row }) => (
                    <RowActions
                      actions={[
                        { icon: "mdi-chart-box", label: "View player stats", public: true, href: playerPath(row.original) },
                        { icon: "mdi-account-minus", label: "Remove from team", color: "error", onClick: () => removePlayerFromTeam(Number(row.original.id)) },
                      ]}
                    />
                  ),
                },
              ]}
            />
          </>
        )}
      />

      {/* Add New Player Modal */}
      <Dialog open={showNewPlayerModal} onOpenChange={setShowNewPlayerModal} disablePointerDismissal>
        <DialogContent showCloseButton={false} className="max-h-[90vh] max-w-[900px] overflow-y-auto gap-0 p-0 sm:max-w-[900px]">
          <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-account-multiple-plus" />
            Select players to add
          </DialogTitle>

          <div className="p-4">
            {/* Filters (reusable) */}
            <FilterPanel
              searchName={searchName}
              onSearchNameChange={setSearchName}
              searchRace={searchRace}
              onSearchRaceChange={setSearchRace}
              rangeValues={rangeValues}
              onRangeValuesChange={setRangeValues}
              showName
              showRace
              showSeason={false}
              showMMR
              showReset
              onReset={fetchAllPlayers}
            />
            <DataTable
              data={filteredAllPlayers}
              pageSize={10}
              empty="No signed-up players match the filters."
              columns={[
                {
                  id: "select",
                  header: "",
                  enableSorting: false,
                  cell: ({ row }) => (
                    <Checkbox
                      checked={selectedPlayers.includes(row.original.id)}
                      disabled={players.some((player) => player.id === row.original.id)}
                      onCheckedChange={(checked) =>
                        setSelectedPlayers((was) => (checked ? [...was, row.original.id] : was.filter((playerId) => playerId !== row.original.id)))
                      }
                      aria-label={row.original.name}
                    />
                  ),
                },
                { id: "name", accessorKey: "name", header: "Name", cell: ({ row }) => <PlayerName player={row.original} plain /> },
                { id: "battleTag", accessorKey: "battleTag", header: "Battletag" },
                {
                  id: "mmr",
                  header: () => <W3CMmr />,
                  enableSorting: false,
                  cell: ({ row }) => <span className="tnum">{getW3CMMR(row.original, currentW3CSeason, row.original.signup_race) ?? "N/A"}</span>,
                },
              ]}
            />
          </div>
          <div className="flex justify-end gap-2 p-4 pt-0">
            <Button variant="ghost" onClick={() => setShowNewPlayerModal(false)}>
              Cancel
            </Button>
            {auth.isAdmin ? (
              <Button onClick={saveSelectedPlayers}>
                <Icon name="mdi-content-save" />
                Add selected players
              </Button>
            ) : null}
          </div>
        </DialogContent>
      </Dialog>

      <W3CSyncResultDialog modelValue={syncDialog} entries={syncEntries} onUpdateModelValue={setSyncDialog} />
    </div>
  );
}

export default SeasonTeamDetailsView;
