// src/views/SeasonAchievementsView.vue
<template>
  <v-overlay v-model="isLoading" persistent contained class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <!-- Page Header -->
    <v-row class="mb-2" align="center">
      <v-col>
        <h1>
          <v-icon class="mr-2">mdi-trophy-variant-outline</v-icon>
          Season Achievements
        </h1>
        <div class="text-subtitle-1 text-medium-emphasis">{{ season?.name }}</div>
      </v-col>
      <v-col cols="auto" class="d-flex align-center ga-2">
        <v-btn variant="text" prepend-icon="mdi-arrow-left" :to="`/seasons/${route.params.id}`">Back to season</v-btn>
        <v-btn color="primary" variant="elevated" prepend-icon="mdi-content-save" :disabled="!isDirty" @click="save">
          Save
        </v-btn>
      </v-col>
    </v-row>

    <StatusAlert v-model="errorMessage" />

    <v-row align="center" class="mb-1">
      <v-col cols="12" sm="4" md="3">
        <v-select
          v-model="importSource"
          :items="importItems"
          label="Import from"
          variant="outlined"
          density="compact"
          hide-details
          @update:modelValue="runImport"
        />
      </v-col>
      <v-col class="text-caption text-medium-emphasis">Imported points come from the source season. Edit them before you save.</v-col>
    </v-row>

    <v-row>
      <v-col v-for="card in CARDS" :key="card.key" cols="12" md="6">
        <v-card elevation="2">
          <v-card-title class="bg-primary d-flex align-center">
            <v-icon class="mr-2">{{ card.icon }}</v-icon>
            <span class="card-title-text text-truncate" :title="card.title">{{ card.title }}</span>
            <v-spacer />
            <v-chip size="small" variant="outlined" class="mr-2 flex-shrink-0">{{ rowsOf(card.team).length }} rules</v-chip>
            <v-btn size="small" variant="outlined" @click="addOpen[card.key] = !addOpen[card.key]">Add</v-btn>
          </v-card-title>

          <v-expand-transition>
            <div v-if="addOpen[card.key]" class="add-panel">
              <div class="d-flex align-center px-4 pt-2 text-caption text-medium-emphasis">
                <span>Rules not in this season</span>
                <v-spacer />
                <span>{{ notAdded(card.team).length }} available</span>
              </div>
              <v-list density="compact" bg-color="transparent" max-height="220" class="overflow-y-auto">
                <v-list-item v-for="rule in notAdded(card.team)" :key="rule.rule_id" @click="addRule(rule)">
                  <template #prepend>
                    <AchievementIcon :id="rule.rule_id" :size="22" class="mr-3" />
                  </template>
                  <v-list-item-title class="text-body-2">{{ rule.name }}</v-list-item-title>
                  <template #append>
                    <v-chip size="x-small" label>{{ rule.points }}</v-chip>
                  </template>
                </v-list-item>
                <v-list-item v-if="!notAdded(card.team).length" class="text-caption text-medium-emphasis">Every rule is already in this season</v-list-item>
              </v-list>
            </div>
          </v-expand-transition>

          <v-list max-height="560" class="overflow-y-auto rule-list">
            <v-list-item v-for="row in rowsOf(card.team)" :key="row.rule_id" class="py-2">
              <template #prepend>
                <AchievementIcon :id="row.rule_id" :size="28" class="mr-4" />
              </template>
              <v-list-item-title class="font-weight-medium">{{ row.name }}</v-list-item-title>
              <v-list-item-subtitle class="text-wrap">{{ fill(row.description, row.params) }}</v-list-item-subtitle>
              <template #append>
                <v-text-field
                  v-model.number="row.points"
                  type="number"
                  min="0"
                  label="Points"
                  variant="outlined"
                  density="compact"
                  hide-details
                  class="num-field ml-2"
                />
                <v-text-field
                  v-for="key in Object.keys(row.params)"
                  :key="key"
                  v-model.number="row.params[key]"
                  type="number"
                  min="1"
                  :label="key"
                  variant="outlined"
                  density="compact"
                  hide-details
                  class="num-field ml-2"
                />
                <v-btn icon="mdi-close" variant="text" size="small" color="error" @click="removeRow(row)" />
              </template>
            </v-list-item>
            <v-list-item v-if="!rowsOf(card.team).length" class="text-medium-emphasis">No rules yet. Add one or import a season.</v-list-item>
          </v-list>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import { storeToRefs } from 'pinia';
import { useRoute } from 'vue-router';

import { useSeasonStore } from '@/stores';
import StatusAlert from '@/components/StatusAlert.vue';
import AchievementIcon from '@/components/AchievementIcon.vue';

const CARDS = [
  { key: 'player', title: 'Player achievements', icon: 'mdi-account-outline', team: false },
  { key: 'team', title: 'Team achievements', icon: 'mdi-account-group-outline', team: true },
];

// Put each rule's current numbers into its description template
const fill = (template, params) => (template || '').replace(/\{(\w+)\}/g, (whole, key) => params?.[key] ?? whole);

const route = useRoute();
const seasonStore = useSeasonStore();
const { seasons } = storeToRefs(seasonStore);

const seasonId = computed(() => seasonStore.seasonIdOf(route.params.id));
const season = computed(() => seasons.value.find((s) => s.id === seasonId.value));
const isLoading = ref(false);
const errorMessage = ref(null);
const addOpen = ref({});
const importSource = ref(null);

const catalogue = ref([]);
const rows = ref([]);  // the working list, saved as a whole
const baseline = ref('');

// What the PUT sends, and what dirty compares
const payload = (list) => list.map((row) => ({ rule_id: row.rule_id, points: Number(row.points) || 0, params: row.params }));
const toRow = (rule) => ({ ...rule, params: { ...(rule.params || {}) } });
const isDirty = computed(() => JSON.stringify(payload(rows.value)) !== baseline.value);

const rowsOf = (team) => rows.value.filter((row) => !!row.team === team);
const notAdded = (team) => catalogue.value.filter((rule) => !!rule.team === team && !rows.value.some((row) => row.rule_id === rule.rule_id));

const importItems = computed(() => [
  { title: 'Catalogue defaults', value: 'catalogue' },
  ...seasons.value
    .filter((s) => s.id !== seasonId.value)
    .sort((a, b) => b.id - a.id)
    .map((s) => ({ title: s.name, value: s.id })),
]);

const run = async (action) => {
  errorMessage.value = null;
  isLoading.value = true;
  try {
    await action();
  } catch (err) {
    console.error('Season achievements action failed', err);
    errorMessage.value = err.error?.message || err.message;
  } finally {
    isLoading.value = false;
  }
};

const addRule = (rule) => rows.value.push(toRow(rule));
const removeRow = (row) => rows.value.splice(rows.value.indexOf(row), 1);

// The select is an action, not a setting: it reads a source and drops back to empty
const runImport = (source) => {
  importSource.value = null;
  if (!source) return;
  if (isDirty.value && !window.confirm('Replace the unsaved list?')) return;
  return run(async () => {
    const list = source === 'catalogue' ? catalogue.value : await seasonStore.fetchSeasonAchievements(source);
    rows.value = list.map(toRow);
  });
};

const save = () => run(async () => {
  rows.value = (await seasonStore.saveSeasonAchievements(seasonId.value, payload(rows.value))).map(toRow);
  baseline.value = JSON.stringify(payload(rows.value));
});

onMounted(() => run(async () => {
  await seasonStore.ensureSeasons();
  const [rules, current] = await Promise.all([
    seasonStore.fetchAchievementCatalogue(),
    seasonStore.fetchSeasonAchievements(seasonId.value),
  ]);
  catalogue.value = rules;
  rows.value = current.map(toRow);
  baseline.value = JSON.stringify(payload(rows.value));
}));
</script>

<style scoped>
.add-panel {
  background: rgba(var(--v-theme-primary), 0.04);
  border-bottom: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
}

.num-field {
  width: 104px;
  flex: none;
}

/* On a phone the number fields sit under the text instead of squeezing it to one character */
@media (max-width: 599px) {
  .rule-list :deep(.v-list-item) {
    grid-template-areas: 'prepend content' 'append append';
    grid-template-columns: max-content 1fr;
  }

  .rule-list :deep(.v-list-item__append) {
    flex-wrap: wrap;
    justify-content: flex-start;
    margin-top: 8px;
  }
}

/* The rule name and its description wrap beside the number fields instead of ending in an ellipsis */
:deep(.v-list-item-title),
:deep(.v-list-item-subtitle) {
  display: block;
  -webkit-line-clamp: unset;
  white-space: normal;
}

/* The card title gives way so the rule count chip keeps its width on a phone */
.card-title-text {
  min-width: 0;
}
</style>

// next/src/app/(app)/seasons/[id]/achievements/SeasonAchievementsView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AchievementIcon } from "@/components/AchievementIcon";
import { StatusAlert } from "@/components/StatusAlert";
import { useSeason } from "@/stores";

const CARDS = [
  { key: "player", title: "Player achievements", icon: "mdi-account-outline", team: false },
  { key: "team", title: "Team achievements", icon: "mdi-account-group-outline", team: true },
];

// Put each rule's current numbers into its description template
const fill = (template: string, params: Record<string, number>) => (template || "").replace(/\{(\w+)\}/g, (whole, key) => String(params?.[key] ?? whole));

type Rule = Record<string, any>;

// What the PUT sends, and what dirty compares
const payload = (list: Rule[]) => list.map((row) => ({ rule_id: row.rule_id, points: Number(row.points) || 0, params: row.params }));
const toRow = (rule: Rule): Rule => ({ ...rule, params: { ...(rule.params || {}) } });

export function SeasonAchievementsView({ id }: { id: string }) {
  const { seasons, seasonIdOf, ensureSeasons, fetchAchievementCatalogue, fetchSeasonAchievements, saveSeasonAchievements } = useSeason();

  const seasonId = seasonIdOf(id);
  const season = seasons.find((s: Rule) => s.id === seasonId);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [addOpen, setAddOpen] = useState<Record<string, boolean>>({});

  const [catalogue, setCatalogue] = useState<Rule[]>([]);
  const [rows, setRows] = useState<Rule[]>([]); // the working list, saved as a whole
  const [baseline, setBaseline] = useState("");

  const isDirty = JSON.stringify(payload(rows)) !== baseline;

  const rowsOf = (team: boolean) => rows.filter((row) => !!row.team === team);
  const notAdded = (team: boolean) => catalogue.filter((rule) => !!rule.team === team && !rows.some((row) => row.rule_id === rule.rule_id));

  const importItems = [
    { title: "Catalogue defaults", value: "catalogue" as string | number },
    ...seasons
      .filter((s: Rule) => s.id !== seasonId)
      .sort((a: Rule, b: Rule) => b.id - a.id)
      .map((s: Rule) => ({ title: s.name, value: s.id as string | number })),
  ];

  const run = async (action: () => Promise<unknown>) => {
    setErrorMessage(null);
    setIsLoading(true);
    try {
      await action();
    } catch (err) {
      console.error("Season achievements action failed", err);
      setErrorMessage((err as any).error?.message || (err as Error).message);
    } finally {
      setIsLoading(false);
    }
  };

  const addRule = (rule: Rule) => setRows((list) => [...list, toRow(rule)]);
  const removeRow = (row: Rule) => setRows((list) => list.filter((one) => one !== row));
  const setRow = (row: Rule, part: Rule) => setRows((list) => list.map((one) => (one === row ? { ...one, ...part } : one)));

  // The select is an action, not a setting: it reads a source and drops back to empty
  const runImport = (source: string | number | null) => {
    if (!source) return;
    if (isDirty && !window.confirm("Replace the unsaved list?")) return;
    return run(async () => {
      const list = source === "catalogue" ? catalogue : await fetchSeasonAchievements(source as number);
      setRows(list.map(toRow));
    });
  };

  const save = () =>
    run(async () => {
      const saved = (await saveSeasonAchievements(seasonId!, payload(rows))).map(toRow);
      setRows(saved);
      setBaseline(JSON.stringify(payload(saved)));
    });

  useEffect(() => {
    // The reads run after the effect body, so the first paint is one render, not a cascade
    queueMicrotask(() => run(async () => {
      await ensureSeasons();
      const [rules, current] = await Promise.all([fetchAchievementCatalogue(), fetchSeasonAchievements(seasonId!)]);
      setCatalogue(rules);
      setRows(current.map(toRow));
      setBaseline(JSON.stringify(payload(current)));
    }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId]);

  return (
    <div className="p-4">
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <Icon name="mdi-loading" size={64} className="animate-spin text-primary" />
        </div>
      ) : null}

      {/* Page Header */}
      <div className="mb-2 flex flex-wrap items-center gap-2">
        <div className="flex-1">
          <h1>
            <Icon name="mdi-trophy-variant-outline" className="mr-2" />
            Season Achievements
          </h1>
          <div className="text-muted-foreground">{season?.name}</div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" nativeButton={false} render={<Link href={`/seasons/${id}`} />}>
            <Icon name="mdi-arrow-left" />
            Back to season
          </Button>
          <Button disabled={!isDirty} onClick={save}>
            <Icon name="mdi-content-save" />
            Save
          </Button>
        </div>
      </div>

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      <div className="mb-1 flex flex-wrap items-center gap-4">
        <Field className="w-full sm:w-64" label="Import from" htmlFor="import-source">
          <Select value={null} onValueChange={runImport}>
            <SelectTrigger id="import-source" className="w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {importItems.map((item) => (
                <SelectItem key={item.value} value={item.value}>
                  {item.title}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </Field>
        <div className="flex-1 text-xs text-muted-foreground">Imported points come from the source season. Edit them before you save.</div>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {CARDS.map((card) => (
          <Card key={card.key} className="card gap-0 py-0">
            <CardHeader className="bg-primary p-4">
              <CardTitle className="flex items-center gap-2 text-on-primary">
                <Icon name={card.icon} />
                <span className="min-w-0 truncate" title={card.title}>
                  {card.title}
                </span>
                <Badge variant="outline" className="ml-auto shrink-0 border-current text-on-primary">
                  {rowsOf(card.team).length} rules
                </Badge>
                <Button size="sm" variant="outline" onClick={() => setAddOpen({ ...addOpen, [card.key]: !addOpen[card.key] })}>
                  Add
                </Button>
              </CardTitle>
            </CardHeader>

            {addOpen[card.key] ? (
              <div className="border-b bg-primary/5">
                <div className="flex items-center px-4 pt-2 text-xs text-muted-foreground">
                  <span>Rules not in this season</span>
                  <span className="ml-auto">{notAdded(card.team).length} available</span>
                </div>
                <ul className="max-h-[220px] overflow-y-auto">
                  {notAdded(card.team).map((rule) => (
                    <li key={rule.rule_id}>
                      <button type="button" className="flex w-full items-center gap-3 px-4 py-1.5 text-left hover:bg-muted" onClick={() => addRule(rule)}>
                        <AchievementIcon id={rule.rule_id} size={22} />
                        <span className="flex-1 text-sm">{rule.name}</span>
                        <Badge variant="outline" className="rounded-[4px] tnum">
                          {rule.points}
                        </Badge>
                      </button>
                    </li>
                  ))}
                  {!notAdded(card.team).length ? <li className="px-4 py-2 text-xs text-muted-foreground">Every rule is already in this season</li> : null}
                </ul>
              </div>
            ) : null}

            <CardContent className="max-h-[560px] overflow-y-auto p-0 py-2">
              <ul>
                {rowsOf(card.team).map((row) => (
                  // On a phone the number fields sit under the text instead of squeezing it to one character
                  <li key={row.rule_id} className="flex flex-wrap items-start gap-4 px-4 py-2 sm:flex-nowrap">
                    <AchievementIcon id={row.rule_id} size={28} className="mt-1" />
                    <div className="min-w-[8rem] flex-1">
                      <div className="font-medium">{row.name}</div>
                      <div className="text-sm text-muted-foreground">{fill(row.description, row.params)}</div>
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                      <Field className="w-[104px]" label="Points" htmlFor={`points-${row.rule_id}`}>
                        <Input
                          id={`points-${row.rule_id}`}
                          type="number"
                          min={0}
                          className="tnum"
                          value={row.points ?? ""}
                          onChange={(e) => setRow(row, { points: e.target.value === "" ? "" : Number(e.target.value) })}
                        />
                      </Field>
                      {Object.keys(row.params).map((key) => (
                        <Field key={key} className="w-[104px]" label={key} htmlFor={`${row.rule_id}-${key}`}>
                          <Input
                            id={`${row.rule_id}-${key}`}
                            type="number"
                            min={1}
                            className="tnum"
                            value={row.params[key] ?? ""}
                            onChange={(e) => setRow(row, { params: { ...row.params, [key]: e.target.value === "" ? "" : Number(e.target.value) } })}
                          />
                        </Field>
                      ))}
                      <Button variant="ghost" size="icon-sm" aria-label="Remove" className="mt-6 text-error" onClick={() => removeRow(row)}>
                        <Icon name="mdi-close" />
                      </Button>
                    </div>
                  </li>
                ))}
                {!rowsOf(card.team).length ? <li className="px-4 py-2 text-muted-foreground">No rules yet. Add one or import a season.</li> : null}
              </ul>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

export default SeasonAchievementsView;
