// src/views/AccessView.vue
<template>
  <v-overlay v-model="isLoading" persistent contained class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <v-row class="mb-4">
      <v-col>
        <h1>
          <v-icon class="mr-2">mdi-shield-account</v-icon>
          Access
        </h1>
      </v-col>
    </v-row>

    <StatusAlert v-model="errorMessage" />

    <StatusAlert v-model="successMessage" type="success" />

    <v-card elevation="2">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-account-key</v-icon>
        <span>Gym admins</span>
      </v-card-title>

      <v-card-text class="pa-0">
        <v-data-table :headers="headers" :items="admins" :loading="isLoading" fixed-header hover>
          <template #top>
            <v-toolbar flat height="auto">
              <v-row align="center" class="flex-wrap ma-0 pa-2">
                <v-spacer />
                <v-col cols="12" sm="auto">
                  <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openAdd" block>
                    Add admin
                  </v-btn>
                </v-col>
              </v-row>
            </v-toolbar>
          </template>

          <template #[`item.name`]="{ item }">
            <PlayerName v-if="playerOf(item)" :player="playerOf(item)" />
            <template v-else>{{ item.name }}</template>
          </template>

          <template #[`item.granted_at`]="{ item }">
            {{ formatDateTime(item.granted_at) }}
          </template>

          <template #[`item.source`]="{ item }">
            <v-chip :color="item.source === 'env' ? undefined : 'primary'" variant="tonal" size="small">
              {{ item.source === 'env' ? 'Environment' : 'App' }}
            </v-chip>
          </template>

          <template #[`item.actions`]="{ item }">
            <RowActions v-if="canRemove(item)" :actions="[
              { icon: 'mdi-delete', label: 'Remove admin', color: 'error', onClick: () => openDeleteDialog(item) },
            ]" />
          </template>

          <template #no-data>
            <div class="text-center pa-8">
              <v-icon size="64" class="text-disabled">{{ loadFailed ? 'mdi-alert-circle-outline' : 'mdi-account-off-outline' }}</v-icon>
              <div class="text-h6 mt-4 text-medium-emphasis">{{ loadFailed ? 'Could not load the admins' : 'No admins granted yet' }}</div>
            </div>
          </template>
        </v-data-table>
      </v-card-text>
    </v-card>

    <v-dialog v-model="addDialog" max-width="600" persistent>
      <v-card>
        <v-card-title class="bg-primary">
          <v-icon class="mr-2">mdi-plus-circle</v-icon>
          Add admin
        </v-card-title>

        <v-alert v-if="dialogError" type="error" variant="tonal" border="start" border-color="error" class="mx-4 my-2" closable @click:close="dialogError = null">
          {{ dialogError }}
        </v-alert>

        <v-card-text class="pt-4">
          <v-combobox
            v-model="picked"
            :items="players"
            item-title="name"
            item-value="discordId"
            :return-object="false"
            label="User"
            hint="Pick a user or type a Discord ID"
            persistent-hint
            variant="outlined"
            density="comfortable"
            prepend-inner-icon="mdi-account-search"
          >
            <template #item="{ props: itemProps, item }">
              <v-list-item v-bind="itemProps" :subtitle="item.raw.discordTag || item.raw.discordId" />
            </template>
          </v-combobox>
        </v-card-text>

        <v-card-actions class="px-4 py-3">
          <v-spacer />
          <v-btn variant="text" @click="addDialog = false">Cancel</v-btn>
          <v-btn color="primary" variant="elevated" prepend-icon="mdi-check" @click="saveAdmin" :loading="isSaving" :disabled="!picked">
            Add admin
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <ConfirmDeleteDialog
      v-model="showDeleteDialog"
      message="Remove this admin?"
      @confirm="confirmDelete"
      @cancel="showDeleteDialog = false"
    />
  </v-container>
</template>

<script setup>
import RowActions from '@/components/RowActions.vue';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';
import { useAuthStore, useConfigStore, usePlayerStore } from '@/stores';
import { onMounted, ref } from 'vue';
import { storeToRefs } from 'pinia';
import StatusAlert from '@/components/StatusAlert.vue';
import PlayerName from '@/components/PlayerName.vue';
import { formatDateTime } from '@/helpers/datetime';
import { useColumns } from '@/helpers/columns';

const authStore = useAuthStore();
const configStore = useConfigStore();
const playerStore = usePlayerStore();
const { players } = storeToRefs(playerStore);

const admins = ref([]);
const isLoading = ref(false);
const isSaving = ref(false);
const errorMessage = ref(null);
// True while the load failed, so an empty table does not read as "no admins"
const loadFailed = ref(false);
const successMessage = ref(null);
const dialogError = ref(null);
const addDialog = ref(false);
const picked = ref(null);  // a discordId from the list, or a raw one typed in
const showDeleteDialog = ref(false);
const deleteRow = ref(null);

const headers = useColumns([
  { title: 'Name', value: 'name', sortable: true },
  { mobile: false, title: 'Discord ID', value: 'discord_id', sortable: true },
  { mobile: false, title: 'Granted', value: 'granted_at', sortable: true },
  { title: 'Source', value: 'source', sortable: true },
  { title: '', value: 'actions', align: 'end', sortable: false }
]);

// An admin is usually a player, so the name carries the flag and the link the rest of the app gives it
const playerOf = (row) => players.value.find(p => String(p.discordId) === String(row.discord_id));

// env rows are granted outside the app, and an admin cannot remove themself
const canRemove = (row) => row.source === 'app' && row.discord_id !== authStore.me?.discord_id;

const fetchAll = async () => {
  isLoading.value = true;
  errorMessage.value = null;
  loadFailed.value = false;
  try {
    [admins.value] = await Promise.all([configStore.fetchAdmins(), playerStore.fetchPlayers()]);
  } catch (error) {
    loadFailed.value = true;
    errorMessage.value = 'Failed to load the admins: ' + error.message;
  } finally {
    isLoading.value = false;
  }
};

const openAdd = () => {
  picked.value = null;
  dialogError.value = null;
  addDialog.value = true;
};

const saveAdmin = async () => {
  dialogError.value = null;
  isSaving.value = true;
  try {
    const discord_id = String(picked.value).trim();
    const name = players.value.find(p => String(p.discordId) === discord_id)?.name;
    await configStore.addAdmin({ discord_id, name });
    admins.value = await configStore.fetchAdmins();
    addDialog.value = false;
    successMessage.value = 'Admin added.';
  } catch (error) {
    dialogError.value = 'Failed to add the admin: ' + error.message;
  } finally {
    isSaving.value = false;
  }
};

const openDeleteDialog = (row) => {
  deleteRow.value = row;
  showDeleteDialog.value = true;
};

const confirmDelete = async () => {
  showDeleteDialog.value = false;
  errorMessage.value = null;
  try {
    await configStore.removeAdmin(deleteRow.value.discord_id);
    admins.value = await configStore.fetchAdmins();
    successMessage.value = 'Admin removed.';
  } catch (error) {
    errorMessage.value = 'Failed to remove the admin: ' + error.message;
  }
};

onMounted(fetchAll);
</script>

// next/src/app/(app)/config/access/AccessView.tsx
"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DataTable } from "@/components/ui/DataTable";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Combobox } from "@/components/ui/Combobox";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { PageHeader } from "@/components/PageHeader";
import { PlayerName } from "@/components/PlayerName";
import { RowActions } from "@/components/RowActions";
import { StatusAlert } from "@/components/StatusAlert";
import { MD_AND_UP, useBreakpoint } from "@/hooks/breakpoint";
import { useAuth, useConfigStore, usePlayerStore } from "@/stores";
import { formatDateTime } from "@/helpers/datetime";

type Admin = { discord_id: string; name?: string; granted_at?: string | null; source: string };

/** The people the app grants admin rights to, beside the ones the environment names. */
export function AccessView() {
  const { me } = useAuth();
  const configStore = useConfigStore();
  const playerStore = usePlayerStore();

  const [players, setPlayers] = useState<any[]>([]);
  const [admins, setAdmins] = useState<Admin[]>([]);
  // The page opens on its load, so the overlay is up before the first request goes out
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  // True while the load failed, so an empty table does not read as "no admins"
  const [loadFailed, setLoadFailed] = useState(false);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [dialogError, setDialogError] = useState<string | null>(null);
  const [addDialog, setAddDialog] = useState(false);
  const [picked, setPicked] = useState(""); // a discordId from the list, or a raw one typed in
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deleteRow, setDeleteRow] = useState<Admin | null>(null);

  const mdAndUp = useBreakpoint(MD_AND_UP);

  // An admin is usually a player, so the name carries the flag and the link the rest of the app gives it
  const playerOf = (row: Admin) => players.find((p) => String(p.discordId) === String(row.discord_id));

  // The pick list: a name to read, the Discord tag under it, and the id the write sends
  const playerItems = players
    .filter((player) => player.discordId)
    .map((player) => ({ value: String(player.discordId), title: player.name, tag: player.discordTag || String(player.discordId) }));

  // env rows are granted outside the app, and an admin cannot remove themself
  const canRemove = (row: Admin) => row.source === "app" && row.discord_id !== me?.discord_id;

  useEffect(() => {
    Promise.all([configStore.fetchAdmins(), playerStore.fetchPlayers()])
      .then(([rows, playerRows]) => {
        setAdmins(rows);
        setPlayers(playerRows);
      })
      .catch((error: any) => {
        setLoadFailed(true);
        setErrorMessage("Failed to load the admins: " + error.message);
      })
      .finally(() => setIsLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const openAdd = () => {
    setPicked("");
    setDialogError(null);
    setAddDialog(true);
  };

  const saveAdmin = async () => {
    setDialogError(null);
    setIsSaving(true);
    try {
      const discord_id = String(picked).trim();
      const name = players.find((p) => String(p.discordId) === discord_id)?.name;
      await configStore.addAdmin({ discord_id, name });
      setAdmins(await configStore.fetchAdmins());
      setAddDialog(false);
      setSuccessMessage("Admin added.");
    } catch (error: any) {
      setDialogError("Failed to add the admin: " + error.message);
    } finally {
      setIsSaving(false);
    }
  };

  const openDeleteDialog = (row: Admin) => {
    setDeleteRow(row);
    setShowDeleteDialog(true);
  };

  const confirmDelete = async () => {
    setShowDeleteDialog(false);
    setErrorMessage(null);
    try {
      await configStore.removeAdmin(deleteRow!.discord_id);
      setAdmins(await configStore.fetchAdmins());
      setSuccessMessage("Admin removed.");
    } catch (error: any) {
      setErrorMessage("Failed to remove the admin: " + error.message);
    }
  };

  return (
    <div className="p-4">
      {/* The page dims while the admins load. */}
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <span className="size-16 animate-spin rounded-full border-8 border-primary border-t-transparent" />
        </div>
      ) : null}

      <PageHeader title={<><Icon name="mdi-shield-account" className="mr-2" />Access</>} />

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      <StatusAlert modelValue={successMessage} type="success" onClose={() => setSuccessMessage(null)} />

      <Card className="card gap-0 py-0">
        <CardHeader className="bg-primary-darken-1 p-4">
          <CardTitle className="flex items-center gap-2 text-on-primary-darken-1">
            <Icon name="mdi-account-key" />
            <span>Gym admins</span>
          </CardTitle>
        </CardHeader>

        <CardContent className="p-0">
          <div className="flex p-2 sm:justify-end">
            <Button className="w-full sm:w-auto" onClick={openAdd}>
              <Icon name="mdi-plus" />
              Add admin
            </Button>
          </div>

          <DataTable
            data={admins}
            pageSize={10}
            columnVisibility={{ discord_id: mdAndUp, granted_at: mdAndUp }}
            empty={
              <div className="p-8 text-center">
                <Icon name={loadFailed ? "mdi-alert-circle-outline" : "mdi-account-off-outline"} size={64} className="text-muted-foreground" />
                <div className="mt-4 text-xl text-muted-foreground">{loadFailed ? "Could not load the admins" : "No admins granted yet"}</div>
              </div>
            }
            columns={[
              {
                id: "name",
                accessorKey: "name",
                header: "Name",
                cell: ({ row }) => {
                  const player = playerOf(row.original);
                  return player ? <PlayerName player={player} /> : row.original.name;
                },
              },
              { id: "discord_id", accessorKey: "discord_id", header: "Discord ID" },
              {
                id: "granted_at",
                accessorKey: "granted_at",
                header: "Granted",
                cell: ({ row }) => formatDateTime(row.original.granted_at),
              },
              {
                id: "source",
                accessorKey: "source",
                header: "Source",
                cell: ({ row }) => (
                  <Badge variant={row.original.source === "env" ? "outline" : "secondary"}>
                    {row.original.source === "env" ? "Environment" : "App"}
                  </Badge>
                ),
              },
              {
                id: "actions",
                header: "",
                enableSorting: false,
                cell: ({ row }) =>
                  canRemove(row.original) ? (
                    <RowActions actions={[{ icon: "mdi-delete", label: "Remove admin", color: "error", onClick: () => openDeleteDialog(row.original) }]} />
                  ) : null,
              },
            ]}
          />
        </CardContent>
      </Card>

      <Dialog open={addDialog} onOpenChange={setAddDialog} disablePointerDismissal>
        <DialogContent showCloseButton={false} className="gap-0 p-0 sm:max-w-[600px]">
          <DialogTitle className="flex items-center gap-2 bg-primary-darken-1 px-4 py-3 text-on-primary-darken-1">
            <Icon name="mdi-plus-circle" />
            Add admin
          </DialogTitle>

          <StatusAlert modelValue={dialogError} className="mx-4 my-2" onClose={() => setDialogError(null)} />

          <div className="p-4">
            {/* The port of the free-text combobox: the list carries the names, the field below the raw id */}
            <Field label="User" hint="Pick a user or type a Discord ID" htmlFor="admin-user">
              <Combobox label="Pick a user" items={playerItems} value={picked || null} onChange={(value) => setPicked(value ?? "")} row={(item) => (
                <span className="flex flex-col text-left">
                  <span>{item.title}</span>
                  <span className="text-xs text-muted-foreground">{item.tag}</span>
                </span>
              )} />
              <Input id="admin-user" value={picked} placeholder="Discord ID" onChange={(event) => setPicked(event.target.value)} />
            </Field>
          </div>

          <div className="flex justify-end gap-2 px-4 py-3">
            <Button variant="ghost" onClick={() => setAddDialog(false)}>
              Cancel
            </Button>
            <Button onClick={saveAdmin} disabled={!picked || isSaving}>
              <Icon name={isSaving ? "mdi-loading mdi-spin" : "mdi-check"} />
              Add admin
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      <ConfirmDeleteDialog
        modelValue={showDeleteDialog}
        message="Remove this admin?"
        onUpdateModelValue={setShowDeleteDialog}
        onConfirm={confirmDelete}
        onCancel={() => setShowDeleteDialog(false)}
      />
    </div>
  );
}

export default AccessView;
