// next/src/app/(app)/admin-login/AdminLoginView.tsx
"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { InputGroup, InputGroupAddon, InputGroupInput } from "@/components/ui/input-group";
import { Note } from "@/components/ui/Note";
import { useAuth } from "@/stores";

/** The admin-token login: a super admin session with no Discord account. */
export function AdminLoginView() {
  const { login } = useAuth();
  const [password, setPassword] = useState("");
  const [passwordError, setPasswordError] = useState<string | null>(null);
  const [apiError, setApiError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const onSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setPasswordError(password ? null : "Password is required");
    if (!password) return;

    setIsSubmitting(true);
    try {
      await login(password);
    } catch (error) {
      setApiError((error as Error).message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="flex min-h-[80vh] flex-col items-center justify-center p-4">
      <Card className="w-full max-w-[500px] gap-0 p-0">
        <CardHeader className="bg-primary p-4">
          <CardTitle className="flex items-center gap-2 text-on-primary">
            <Icon name="mdi-lock" />
            Admin token login
          </CardTitle>
        </CardHeader>

        <CardContent className="p-6">
          <form noValidate onSubmit={onSubmit}>
            <Field label="Admin token" htmlFor="admin-token" error={passwordError}>
              <InputGroup>
                <InputGroupAddon>
                  <Icon name="mdi-lock-outline" />
                </InputGroupAddon>
                <InputGroupInput
                  id="admin-token"
                  name="password"
                  type="password"
                  value={password}
                  aria-invalid={!!passwordError}
                  onChange={(event) => {
                    setPassword(event.target.value);
                    setPasswordError(event.target.value ? null : "Password is required");
                  }}
                />
              </InputGroup>
            </Field>

            <Button type="submit" size="lg" className="mt-4 h-11 w-full" disabled={isSubmitting}>
              <Icon name={isSubmitting ? "mdi-loading" : "mdi-login"} className={isSubmitting ? "animate-spin" : undefined} />
              Log in
            </Button>

            {apiError ? (
              <Note type="error" className="mt-4">
                {apiError}
              </Note>
            ) : null}
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

export default AdminLoginView;

// src/views/AdminLoginView.vue
<template>
    <v-container fluid class="pa-4 d-flex flex-column align-center justify-center" style="min-height: 80vh;">
        <v-card elevation="2" max-width="500" width="100%">
            <v-card-title class="bg-primary">
                <v-icon class="mr-2">mdi-lock</v-icon>
                Admin token login
            </v-card-title>

            <v-card-text class="pt-6">
                <form novalidate @submit.prevent="onSubmit">
                    <v-text-field
                        ref="passwordField"
                        v-model="password"
                        name="password"
                        label="Admin token"
                        type="password"
                        variant="outlined"
                        prepend-inner-icon="mdi-lock-outline"
                        :rules="passwordRules"
                    />

                    <v-btn
                        type="submit"
                        color="primary"
                        variant="elevated"
                        block
                        size="large"
                        prepend-icon="mdi-login"
                        :loading="isSubmitting"
                        :disabled="isSubmitting"
                        class="mt-4"
                    >
                        Log in
                    </v-btn>

                    <v-alert
                        v-if="apiError"
                        type="error"
                        variant="tonal"
                        border="start"
                        border-color="error"
                        class="mt-4"
                    >
                        {{ apiError }}
                    </v-alert>
                </form>
            </v-card-text>
        </v-card>
    </v-container>
</template>

<script setup>
import { ref } from 'vue';

import { useAuthStore } from '@/stores';

const password = ref('');
const passwordField = ref(null);
const apiError = ref(null);
const isSubmitting = ref(false);
const passwordRules = [value => !!value || 'Password is required'];

async function onSubmit() {
    const authStore = useAuthStore();

    const errors = await passwordField.value.validate();
    if (errors.length) return;

    isSubmitting.value = true;
    try {
        await authStore.login(password.value);
    } catch (error) {
        apiError.value = error.message;
    } finally {
        isSubmitting.value = false;
    }
}
</script>
