// next/src/app/(app)/availability/AvailabilityView.tsx
"use client";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Combobox } from "@/components/ui/Combobox";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { BlockedTimesEditor } from "@/components/BlockedTimesEditor";
import { PageHeader } from "@/components/PageHeader";
import { StatusAlert } from "@/components/StatusAlert";
import { backendUrl, fetchWrapper } from "@/helpers";
import { viewerZone } from "@/helpers/timezone.mjs";
import { authBox, useAuth } from "@/stores";

// Every write lands back on the session's player row
const patchUser = (part: Record<string, unknown>) => {
  const me = authBox.get().me;
  if (me?.user) authBox.set({ ...authBox.get(), me: { ...me, user: { ...me.user, ...part } } });
};

/** Everything a player answers about time: the zone his hours are read in, and
 *  the hours he cannot play. */
export function AvailabilityView() {
  const { me } = useAuth();
  const [zoneError, setZoneError] = useState<string | null>(null);
  const [savingZone, setSavingZone] = useState(false);

  // The backend reads the blocks against the profile zone; the editor writes it when the profile carries none
  const profileZone: string | null = me?.user?.timezone ?? null;
  const browserZone = viewerZone();
  // The field shows what is stored, so an empty field reads as the unsaved zone it is
  const [zone, setZone] = useState(profileZone);
  // /me may answer after the page renders, and every write lands back on the profile
  const [seenProfileZone, setSeenProfileZone] = useState(profileZone);
  if (seenProfileZone !== profileZone) {
    setSeenProfileZone(profileZone);
    setZone(profileZone);
  }
  const zones = [...new Set([...Intl.supportedValuesOf("timeZone"), zone].filter(Boolean) as string[])].map((value) => ({ value, title: value }));

  // The editor wrote the browser zone, so the field and the profile follow it
  const onZone = (timezone: string) => {
    setZone(timezone);
    patchUser({ timezone });
  };

  const saveZone = async (timezone: string | null) => {
    setZone(timezone);
    setSavingZone(true);
    setZoneError(null);
    try {
      const { user } = await fetchWrapper.put(`${backendUrl}/user-info`, { timezone });
      patchUser(user);
    } catch (error) {
      setZoneError((error as Error).message || "Could not save your timezone.");
    } finally {
      setSavingZone(false);
    }
  };

  return (
    <div className="max-w-[900px] p-4">
      <PageHeader title="Availability" />
      <p className="-mt-5 mb-3 text-sm text-muted-foreground">Open hours are a starting point, not a promise. Agree the time with your opponent.</p>

      <StatusAlert modelValue={zoneError} onClose={() => setZoneError(null)} />
      <Field label="Times are in" htmlFor="availability-zone" hint={profileZone ? undefined : "Saved with your first block."} className="mb-6 max-w-96">
        <Combobox id="availability-zone" items={zones} value={zone} placeholder={browserZone} disabled={savingZone} onChange={saveZone} className={zone ? undefined : "text-muted-foreground"} />
      </Field>

      <Card className="gap-0 p-0">
        <CardHeader className="bg-primary p-4">
          <CardTitle className="flex items-center gap-2 text-on-primary">
            <Icon name="mdi-calendar-remove" />
            When you can&apos;t play
          </CardTitle>
        </CardHeader>
        <CardContent className="p-4">
          <BlockedTimesEditor zone={profileZone} onZone={onZone} />
        </CardContent>
      </Card>
    </div>
  );
}

export default AvailabilityView;

// src/views/AvailabilityView.vue
<!-- Everything a player answers about time: the zone his hours are read in, and
     the hours he cannot play. -->
<template>
  <v-container fluid class="pa-4 page">
    <h1>Availability</h1>
    <p class="text-body-2 text-medium-emphasis mt-1 mb-3">
      Open hours are a starting point, not a promise. Agree the time with your opponent.
    </p>

    <StatusAlert v-model="zoneError" />
    <v-autocomplete
      v-model="zone"
      label="Times are in"
      prepend-inner-icon="mdi-clock-outline"
      density="compact"
      variant="outlined"
      hide-details="auto"
      class="zone-field mb-6"
      persistent-placeholder
      :placeholder="browserZone"
      :persistent-hint="!profileZone"
      :hint="profileZone ? '' : 'Saved with your first block.'"
      :items="zones"
      :menu-props="{ scrollStrategy: 'close' }"
      :loading="savingZone"
      @update:modelValue="saveZone"
    />

    <v-card elevation="2">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-calendar-remove</v-icon>
        When you can't play
      </v-card-title>
      <v-card-text class="pt-4">
        <BlockedTimesEditor :zone="profileZone" @zone="onZone" />
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { computed, ref, watch } from 'vue';
import { backendUrl, fetchWrapper } from '@/helpers';
import { viewerZone } from '@/helpers/timezone.mjs';
import { useAuthStore } from '@/stores';
import BlockedTimesEditor from '@/components/BlockedTimesEditor.vue';
import StatusAlert from '@/components/StatusAlert.vue';

const authStore = useAuthStore();

const zoneError = ref(null);
const savingZone = ref(false);

// The backend reads the blocks against the profile zone; the editor writes it when the profile carries none
const profileZone = computed(() => authStore.me?.user?.timezone ?? null);
const browserZone = viewerZone();
// The field shows what is stored, so an empty field reads as the unsaved zone it is
const zone = ref(profileZone.value);
const zones = computed(() => [...new Set([...Intl.supportedValuesOf('timeZone'), zone.value].filter(Boolean))]);
// /me may answer after the page renders, and every write lands back on the profile
watch(profileZone, (value) => { zone.value = value; });

// The editor wrote the browser zone, so the field and the profile follow it
const onZone = (timezone) => {
  zone.value = timezone;
  if (authStore.me?.user) authStore.me.user = { ...authStore.me.user, timezone };
};

const saveZone = async (timezone) => {
  savingZone.value = true;
  zoneError.value = null;
  try {
    const { user } = await fetchWrapper.put(`${backendUrl}/user-info`, { timezone });
    if (authStore.me?.user) authStore.me.user = { ...authStore.me.user, ...user };
  } catch (error) {
    zoneError.value = error.message || 'Could not save your timezone.';
  } finally {
    savingZone.value = false;
  }
};
</script>

<style scoped>
.page { max-width: 900px; }
.zone-field { max-width: 24rem; }
</style>
