// next/src/app/(app)/fantasy/bets/FantasyBetsView.tsx
"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useRef, useState } from "react";
import type { SortingState } from "@tanstack/react-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Combobox } from "@/components/ui/Combobox";
import { DataTable } from "@/components/ui/DataTable";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { BetIcon } from "@/components/fantasy/BetIcon";
import { PageHeader } from "@/components/PageHeader";
import { PlayerName } from "@/components/PlayerName";
import { RowActions } from "@/components/RowActions";
import { SeasonSelect } from "@/components/SeasonSelect";
import { StatusAlert } from "@/components/StatusAlert";
import { VsRaces } from "@/components/VsRaces";
import { W3CIcon } from "@/components/W3CIcon";
import { MD_AND_UP, SM_AND_DOWN, useBreakpoint } from "@/hooks/breakpoint";
import { useConfigStore, useFantasyStore, useSeason, useSeasonStore, useSeriesStore } from "@/stores";
import { isScored, sides, validateBetPoints as checkBetPoints } from "@/helpers/bets.mjs";
import { cn } from "@/lib/utils";

const PAGE_SIZES = [
  { value: 10, title: "10" },
  { value: 25, title: "25" },
  { value: 50, title: "50" },
  { value: 100, title: "100" },
  { value: -1, title: "All" },
];

const emptyBet = () => ({ captain_id: null as number | null, series_id: null as number | null, winner_id: null as number | null, bet_points: null as number | null });

// One instance each, so a read that has not landed yet does not redraw the table every render
const EMPTY_LADDER = new Map<number, any>();
const EMPTY_IDS: number[] = [];

// The picker filters on the title it shows, so both sides of the series belong in it
const seriesTitle = (series: any) => `${series.player1?.name || "Player 1"} vs ${series.player2?.name || "Player 2"}`;

/** Every bet of one season, one server page at a time, with the admin's add, edit and delete. */
export function FantasyBetsView() {
  const fantasyStore = useFantasyStore();
  const seriesStore = useSeriesStore();
  const configStore = useConfigStore();
  const seasonStore = useSeasonStore();
  const { selectedSeasonId } = useSeason();

  const [bets, setBets] = useState<any[]>([]);
  const [totalBets, setTotalBets] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [isBetSaving, setIsBetSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [betDialog, setBetDialog] = useState(false);
  const [addBetDialog, setAddBetDialog] = useState(false);
  const [deleteDialog, setDeleteDialog] = useState(false);
  const [editingBet, setEditingBet] = useState<any>(null);
  const [deletingBet, setDeletingBet] = useState<any>(null);
  const [selectedWinnerId, setSelectedWinnerId] = useState<number | null>(null);
  const [selectedBetPoints, setSelectedBetPoints] = useState<number | null>(null);
  const [allSeries, setAllSeries] = useState<any[]>([]);
  const [fantasyTeams, setFantasyTeams] = useState<any[]>([]);
  // The season ladder record of every signup, by user id, for the MMR and the record against each race.
  // It carries the season it was read for, so a season change shows no record until its own read lands.
  const [ladder, setLadder] = useState<{ season: number | null; by: Map<number, any> }>({ season: null, by: EMPTY_LADDER });
  const [page, setPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(25);
  const [sorting, setSorting] = useState<SortingState>([{ id: "id", desc: false }]); // a hidden sort key: the order the server pages by
  // The series this captain already bet on, carrying the captain it was read for
  const [captainBets, setCaptainBets] = useState<{ captain: number | null; ids: number[] }>({ captain: null, ids: EMPTY_IDS });
  const [useFixedBetPoints, setUseFixedBetPoints] = useState(false);
  const [fixedBetPointsValue, setFixedBetPointsValue] = useState(0);
  const [minBetPoints, setMinBetPoints] = useState<number | null>(null);
  const [maxBetPoints, setMaxBetPoints] = useState<number | null>(null);
  const [betPointsError, setBetPointsError] = useState<string | null>(null);
  const [editBetPointsError, setEditBetPointsError] = useState<string | null>(null);
  const [dialogError, setDialogError] = useState<string | null>(null); // the open dialog's own error, so a refused write is read where it happened
  const [newBet, setNewBet] = useState(emptyBet());
  const [selectedSeriesForNew, setSelectedSeriesForNew] = useState<any>(null);

  const mdAndUp = useBreakpoint(MD_AND_UP);
  const smAndDown = useBreakpoint(SM_AND_DOWN);

  const ladderById = ladder.season === selectedSeasonId ? ladder.by : EMPTY_LADDER;
  const captainBetSeriesIds = captainBets.captain === newBet.captain_id ? captainBets.ids : EMPTY_IDS;

  // A bet row carries the captain, not their fantasy team; the season's teams supply the name
  const teamNameByCaptain = useMemo(() => new Map(fantasyTeams.map((t) => [t.captain_id, t.name])), [fantasyTeams]);

  // Enrich bets with series data
  const enrichedBets = useMemo(
    () => bets.map((bet) => ({ ...bet, series: allSeries.find((s) => s.id === bet.series_id) || bet.series })),
    [bets, allSeries],
  );

  // The series a bet can be placed on: a fantasy match, not yet played, and one this captain has no bet on
  const availableSeries = useMemo(() => {
    if (!newBet.captain_id) return [];
    return allSeries.filter((s) => s.is_fantasy_match === true && !isScored(s) && !captainBetSeriesIds.includes(s.id));
  }, [newBet.captain_id, allSeries, captainBetSeriesIds]);

  const validateBetPoints = (points: number | null) => checkBetPoints(points, minBetPoints, maxBetPoints);
  const mmrOf = (player: any) => ladderById.get(player?.id)?.mmr?.current ?? null;

  const getWinner = (bet: any) => {
    if (!bet?.series) return null;
    if (bet.winner_id === bet.series.player1_id) return bet.series.player1;
    if (bet.winner_id === bet.series.player2_id) return bet.series.player2;
    return null;
  };

  // the race the winner played in that series, not the one he signed the season up on
  const winnerRace = (bet: any) => {
    if (!bet?.series) return null;
    if (bet.winner_id === bet.series.player1_id) return bet.series.player1_race;
    if (bet.winner_id === bet.series.player2_id) return bet.series.player2_race;
    return null;
  };

  const resultBadge = (result: string) =>
    result === "WIN" ? "bg-win text-on-win" : result === "LOSS" ? "bg-loss text-on-loss" : "bg-secondary text-on-secondary";

  const fetchData = async (readPage = page) => {
    if (!selectedSeasonId) return; // the picker resolves one
    setIsLoading(true);
    setErrorMessage(null);
    try {
      const sort = sorting[0];
      const { bets: rows, total } = await fantasyStore.searchBetsPage(`season_id == ${selectedSeasonId}`, {
        limit: itemsPerPage,
        offset: itemsPerPage === -1 ? 0 : (readPage - 1) * itemsPerPage,
        sort: sort ? sort.id : undefined,
        order: sort ? (sort.desc ? "desc" : "asc") : undefined,
      });

      // A delete can empty the last page; step back onto the table
      if (rows.length === 0 && readPage > 1 && total > 0 && itemsPerPage !== -1) {
        setPage(Math.max(1, Math.ceil(total / itemsPerPage)));
        return;
      }
      setBets(rows);
      setTotalBets(total);

      setAllSeries((await seriesStore.searchSeriesBySeason(selectedSeasonId, "is_fantasy_match==True")) || []);
      setFantasyTeams((await fantasyStore.searchTeams(`season_id == ${selectedSeasonId}`)) || []);
    } catch (error: any) {
      console.error("Failed to fetch data:", error);
      setErrorMessage("Failed to load data. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  // The one page read: the season, the sort and the page state are all it depends on.
  // A new season reads from its first page, so the page resets before the read goes out.
  const pagedSeason = useRef<number | null>(null);
  useEffect(() => {
    if (!selectedSeasonId) return;
    if (pagedSeason.current !== selectedSeasonId && page !== 1) {
      setPage(1);
      return;
    }
    pagedSeason.current = selectedSeasonId;
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedSeasonId, page, itemsPerPage, sorting]);

  // One read per season for the whole page: the ladder record of every signup
  useEffect(() => {
    if (!selectedSeasonId) return;
    seasonStore
      .fetchSeasonLadderPlayers(selectedSeasonId)
      .then((rows: any[]) => setLadder({ season: selectedSeasonId, by: new Map((rows || []).map((p) => [p.id, p])) }))
      .catch((error: any) => console.error("Failed to load the season ladder:", error));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedSeasonId]);

  // The table holds one page, so the duplicate check asks the server
  useEffect(() => {
    const captain = newBet.captain_id;
    if (!captain || !selectedSeasonId) return;
    fantasyStore
      .queryBets(`user_id == ${captain} and season_id == ${selectedSeasonId}`)
      .then((rows: any[]) => setCaptainBets({ captain, ids: rows.map((bet) => bet.series_id) }))
      .catch((error: any) => {
        console.error("Failed to load the captain bets:", error);
        setCaptainBets({ captain, ids: EMPTY_IDS });
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [newBet.captain_id, selectedSeasonId]);

  useEffect(() => {
    configStore
      .fetchSettings()
      .then((settings: any[]) => {
        const value = (key: string) => settings.find((s) => s.key === key)?.value;
        const fixed = value("fantasy_fixed_bet_points");
        if (fixed !== undefined) setUseFixedBetPoints(fixed === "true");
        const points = value("fantasy_bet_points_value");
        if (points !== undefined) setFixedBetPointsValue(parseInt(points) || 0);
        const min = value("fantasy_min_bet_points");
        if (min) setMinBetPoints(parseInt(min));
        const max = value("fantasy_max_bet_points");
        if (max) setMaxBetPoints(parseInt(max));
      })
      .catch((error: any) => console.error("Error loading bet points settings:", error));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const openAddBetDialog = () => {
    setNewBet(emptyBet());
    setSelectedSeriesForNew(null);
    setBetPointsError(null);
    setDialogError(null);
    setAddBetDialog(true);
  };

  const closeAddBetDialog = () => {
    setAddBetDialog(false);
    setDialogError(null);
    setNewBet(emptyBet());
    setSelectedSeriesForNew(null);
    setBetPointsError(null);
  };

  const onSeriesSelected = (seriesId: number | null) => {
    setNewBet({ ...newBet, series_id: seriesId, winner_id: null });
    setSelectedSeriesForNew(seriesId ? allSeries.find((s) => s.id === seriesId) : null);
  };

  const createNewBet = async () => {
    if (!newBet.captain_id || !newBet.series_id || !newBet.winner_id) {
      setDialogError("Please fill in all fields.");
      return;
    }
    setIsBetSaving(true);
    setDialogError(null);
    try {
      await fantasyStore.createBet({
        user_id: newBet.captain_id,
        series_id: newBet.series_id,
        season_id: selectedSeasonId,
        winner_id: newBet.winner_id,
        bet_points: newBet.bet_points, // Send as-is, the backend applies fixed points if configured
      });
      await fetchData();
      closeAddBetDialog();
    } catch (error: any) {
      console.error("Failed to create bet:", error);
      setDialogError(error.message || "Failed to create bet. Please try again.");
    } finally {
      setIsBetSaving(false);
    }
  };

  const editBet = (bet: any) => {
    setEditingBet({ ...bet });
    setSelectedWinnerId(bet.winner_id);
    setSelectedBetPoints(bet.bet_points);
    setEditBetPointsError(validateBetPoints(bet.bet_points));
    setDialogError(null);
    setBetDialog(true);
  };

  const closeBetDialog = () => {
    setBetDialog(false);
    setDialogError(null);
    setEditingBet(null);
    setSelectedWinnerId(null);
    setSelectedBetPoints(null);
    setEditBetPointsError(null);
  };

  const saveBet = async () => {
    if (!editingBet || !selectedWinnerId) {
      setDialogError("Please select a winner.");
      return;
    }
    setIsBetSaving(true);
    setDialogError(null);
    try {
      await fantasyStore.updateBet(editingBet.id, { ...editingBet, winner_id: selectedWinnerId, bet_points: selectedBetPoints });
      await fetchData();
      closeBetDialog();
    } catch (error: any) {
      console.error("Failed to update bet:", error);
      setDialogError(error.message || "Failed to update bet. Please try again.");
    } finally {
      setIsBetSaving(false);
    }
  };

  const deleteBet = async () => {
    if (!deletingBet) return;
    setIsDeleting(true);
    setDialogError(null);
    try {
      await fantasyStore.deleteBet(deletingBet.id);
      // The module keeps no list, so the page drops the row itself
      setBets((was) => was.filter((bet) => bet.id !== deletingBet.id));
      await fetchData();
      setDeleteDialog(false);
      setDeletingBet(null);
    } catch (error: any) {
      console.error("Failed to delete bet:", error);
      setDialogError(error.message || "Failed to delete bet. Please try again.");
    } finally {
      setIsDeleting(false);
    }
  };

  // The server sorts the columns it stores; the columns joined in the browser stay unsorted
  const columns: any[] = [
    {
      id: "captain",
      // the accessor only makes the column sortable; the server orders on the key, not on this value
      accessorFn: (row: any) => row.user?.name ?? "",
      header: "Fantasy Captain",
      cell: ({ row }: any) => (
        <>
          {/* no race: the fantasy captain bets, they don't play */}
          {row.original.user ? <PlayerName player={row.original.user} /> : "N/A"}
          <div className="text-xs opacity-(--v-medium-emphasis-opacity)">{teamNameByCaptain.get(row.original.user_id) ?? "No team"}</div>
        </>
      ),
    },
    {
      id: "series",
      header: "Series",
      enableSorting: false,
      cell: ({ row }: any) =>
        row.original.series ? (
          // one row per player of the series, so the two MMRs and the two records line up
          <div className="inline-grid grid-cols-[max-content_max-content] items-center gap-x-3 gap-y-0.5 min-[960px]:grid-cols-[max-content_max-content_max-content]">
            {sides(row.original.series).map((side: any, i: number) => (
              <div key={i} className="col-span-full grid grid-cols-subgrid items-center">
                {side.player ? <PlayerName player={side.player} race={side.race} /> : <span>Player {i + 1}</span>}
                <span className="whitespace-nowrap">
                  <W3CIcon size={14} /> {mmrOf(side.player) ?? "—"}
                </span>
                {/* A phone has room for the name and the MMR, not the race record */}
                {!smAndDown ? <VsRaces player={ladderById.get(side.player?.id)} race={side.vsRace} /> : null}
              </div>
            ))}
          </div>
        ) : (
          <div>N/A</div>
        ),
    },
    {
      id: "bet_on",
      header: "Bet on",
      enableSorting: false,
      cell: ({ row }: any) =>
        getWinner(row.original) ? (
          <PlayerName player={getWinner(row.original)} race={winnerRace(row.original)} />
        ) : (
          <strong>{row.original.series ? "Unknown" : "N/A"}</strong>
        ),
    },
    {
      id: "score",
      header: "Score",
      enableSorting: false,
      cell: ({ row }: any) =>
        row.original.series ? (
          <div>
            {row.original.series.player1_score || 0} : {row.original.series.player2_score || 0}
          </div>
        ) : (
          <div>-</div>
        ),
    },
    {
      id: "bet_result",
      header: "Result",
      enableSorting: false,
      cell: ({ row }: any) => <Badge className={cn("font-medium", resultBadge(row.original.bet_result))}>{row.original.bet_result || "PENDING"}</Badge>,
    },
    { id: "bet_points", accessorKey: "bet_points", header: "Points", cell: ({ row }: any) => row.original.bet_points || 0 },
    {
      id: "is_locked",
      header: "Locked",
      enableSorting: false,
      cell: ({ row }: any) =>
        isScored(row.original.series) ? <Icon name="mdi-lock" className="text-error" /> : <Icon name="mdi-lock-open" className="text-success" />,
    },
    {
      id: "actions",
      header: "",
      enableSorting: false,
      // An admin edits and deletes any bet, scored or not; the dialog says what that costs
      cell: ({ row }: any) => (
        <RowActions
          actions={[
            { icon: "mdi-pencil", label: "Edit", onClick: () => editBet(row.original) },
            { icon: "mdi-delete", label: "Delete", color: "error", onClick: () => { setDeletingBet(row.original); setDialogError(null); setDeleteDialog(true); } },
          ]}
        />
      ),
    },
  ];

  const captainItems = fantasyTeams.map((team) => ({
    value: String(team.captain_id),
    title: `${team.captain?.name || "N/A"} · Team: ${team.drafted_team?.name || "N/A"}`,
  }));
  const seriesItems = availableSeries.map((series) => ({ value: String(series.id), title: seriesTitle(series) }));

  const pointsHint = minBetPoints && maxBetPoints
    ? `Enter between ${minBetPoints} and ${maxBetPoints} points`
    : minBetPoints
      ? `Minimum ${minBetPoints} points`
      : maxBetPoints
        ? `Maximum ${maxBetPoints} points`
        : "Enter the number of points for this bet";

  const winnerRadios = (series: any, value: number | null, onChange: (id: number) => void) => (
    <RadioGroup value={value} onValueChange={(next) => onChange(next as number)}>
      <span className="text-sm">Select winner:</span>
      {[
        { id: series.player1_id, name: series.player1?.name || "Player 1" },
        { id: series.player2_id, name: series.player2?.name || "Player 2" },
      ].map((side) => (
        <Label key={side.id} className="flex items-center gap-2 font-normal">
          <RadioGroupItem value={side.id} />
          {side.name}
        </Label>
      ))}
    </RadioGroup>
  );

  return (
    <div className="p-4">
      {/* The page dims while the bets load. */}
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <span className="size-16 animate-spin rounded-full border-8 border-primary border-t-transparent" />
        </div>
      ) : null}

      <PageHeader title={<><BetIcon size={24} className="mr-2" />Fantasy Bets</>} />

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      <Card className="card gap-0 py-0">
        <CardContent className="p-0">
          <div className="flex flex-wrap items-center gap-2 p-2">
            <div className="w-full sm:w-auto">
              <SeasonSelect />
            </div>
            <Button className="w-full sm:ml-auto sm:w-auto" onClick={openAddBetDialog}>
              <Icon name="mdi-plus" />
              Add bet
            </Button>
          </div>

          <div className="px-0 md:px-4">
            <DataTable
              data={enrichedBets}
              columns={columns}
              rowId={(bet: any) => String(bet.id)}
              rowCount={totalBets}
              page={page - 1}
              onPageChange={(next) => setPage(next + 1)}
              pageSize={itemsPerPage}
              pageSizeOptions={PAGE_SIZES}
              onPageSizeChange={setItemsPerPage}
              sorting={sorting}
              // A header click reloads from the first page in the new order
              onSortingChange={(next) => {
                setSorting(next);
                setPage(1);
              }}
              columnVisibility={{ score: mdAndUp, is_locked: mdAndUp }}
              empty="No bets in this season yet. Bets appear here once Fantasy Captains place them."
            />
          </div>
        </CardContent>
      </Card>

      {/* Add Bet Dialog */}
      <Dialog open={addBetDialog} onOpenChange={(open) => (open ? setAddBetDialog(true) : closeAddBetDialog())} disablePointerDismissal>
        <DialogContent showCloseButton={false} className="gap-0 p-0 sm:max-w-[600px]">
          <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-plus" />
            Add new fantasy bet
          </DialogTitle>

          <div className="flex flex-col gap-4 p-4">
            <StatusAlert modelValue={dialogError} onClose={() => setDialogError(null)} />

            <Field label="Fantasy Captain" htmlFor="bet-captain">
              <Combobox
                id="bet-captain"
                items={captainItems}
                value={newBet.captain_id == null ? null : String(newBet.captain_id)}
                onChange={(value) => setNewBet({ ...newBet, captain_id: value == null ? null : Number(value), series_id: null, winner_id: null })}
                label="Fantasy Captain"
              />
            </Field>

            <Field label="Select series" hint={!newBet.captain_id ? "Pick a Fantasy Captain first" : undefined} htmlFor="bet-series">
              <Combobox
                id="bet-series"
                items={seriesItems}
                value={newBet.series_id == null ? null : String(newBet.series_id)}
                onChange={(value) => onSeriesSelected(value == null ? null : Number(value))}
                label="Select series"
                disabled={!newBet.captain_id}
              />
            </Field>

            {selectedSeriesForNew ? winnerRadios(selectedSeriesForNew, newBet.winner_id, (id) => setNewBet({ ...newBet, winner_id: id })) : null}

            {!useFixedBetPoints ? (
              <Field label="Bet points" hint={pointsHint} error={betPointsError} htmlFor="bet-points">
                <Input
                  id="bet-points"
                  type="number"
                  min={minBetPoints || 1}
                  max={maxBetPoints ?? undefined}
                  value={newBet.bet_points ?? ""}
                  onChange={(event) => {
                    const points = event.target.value === "" ? null : Number(event.target.value);
                    setNewBet({ ...newBet, bet_points: points });
                    setBetPointsError(validateBetPoints(points));
                  }}
                  onBlur={() => setBetPointsError(validateBetPoints(newBet.bet_points))}
                />
              </Field>
            ) : (
              <StatusAlert modelValue={`This bet will be worth ${fixedBetPointsValue} points`} type="info" />
            )}
          </div>

          <div className="flex justify-end gap-2 px-4 py-3">
            <Button variant="ghost" onClick={closeAddBetDialog} disabled={isBetSaving}>
              Cancel
            </Button>
            <Button
              onClick={createNewBet}
              disabled={isBetSaving || !newBet.captain_id || !newBet.series_id || !newBet.winner_id || (!useFixedBetPoints && (!!betPointsError || !newBet.bet_points))}
            >
              <Icon name={isBetSaving ? "mdi-loading mdi-spin" : "mdi-plus"} />
              Create bet
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Edit Bet Dialog */}
      <Dialog open={betDialog} onOpenChange={(open) => (open ? setBetDialog(true) : closeBetDialog())} disablePointerDismissal>
        <DialogContent showCloseButton={false} className="gap-0 p-0 sm:max-w-[500px]">
          <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-pencil" />
            Edit fantasy bet
          </DialogTitle>

          <div className="flex flex-col gap-4 p-4">
            <StatusAlert modelValue={dialogError} onClose={() => setDialogError(null)} />
            {isScored(editingBet?.series) ? <StatusAlert modelValue="This series is already scored; changing the bet changes the leaderboard." type="warning" /> : null}

            {editingBet?.series ? (
              <>
                <div>
                  <div className="mb-2">
                    <strong>Series:</strong> {editingBet.series.player1?.name || "Player 1"} vs {editingBet.series.player2?.name || "Player 2"}
                  </div>
                  <div className="mb-2 text-sm">
                    <strong>Captain:</strong> {editingBet.user?.name || "N/A"}
                  </div>
                  <div className="text-sm">
                    <strong>Current score:</strong> {editingBet.series.player1_score || 0} : {editingBet.series.player2_score || 0}
                  </div>
                </div>

                {winnerRadios(editingBet.series, selectedWinnerId, setSelectedWinnerId)}

                {!useFixedBetPoints ? (
                  <Field label="Bet points" hint={pointsHint} error={editBetPointsError} htmlFor="edit-bet-points">
                    <Input
                      id="edit-bet-points"
                      type="number"
                      min={minBetPoints || 1}
                      max={maxBetPoints ?? undefined}
                      value={selectedBetPoints ?? ""}
                      onChange={(event) => {
                        const points = event.target.value === "" ? null : Number(event.target.value);
                        setSelectedBetPoints(points);
                        setEditBetPointsError(validateBetPoints(points));
                      }}
                      onBlur={() => setEditBetPointsError(validateBetPoints(selectedBetPoints))}
                    />
                  </Field>
                ) : (
                  <StatusAlert modelValue={`This bet will be worth ${fixedBetPointsValue} points`} type="info" />
                )}
              </>
            ) : null}
          </div>

          <div className="flex justify-end gap-2 px-4 py-3">
            <Button variant="ghost" onClick={closeBetDialog} disabled={isBetSaving}>
              Cancel
            </Button>
            <Button onClick={saveBet} disabled={isBetSaving || !selectedWinnerId || (!useFixedBetPoints && (!!editBetPointsError || !selectedBetPoints))}>
              <Icon name={isBetSaving ? "mdi-loading mdi-spin" : "mdi-content-save"} />
              Save changes
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialog} onOpenChange={setDeleteDialog}>
        <DialogContent showCloseButton={false} className="gap-0 p-0 sm:max-w-[400px]">
          {/* DESIGN.md: a dialog that deletes something wears bg-error */}
          <DialogTitle className="flex items-center gap-2 bg-error px-4 py-3 text-on-error">
            <Icon name="mdi-alert" />
            Confirm delete
          </DialogTitle>
          <div className="p-4">
            <StatusAlert modelValue={dialogError} onClose={() => setDialogError(null)} />
            Are you sure you want to delete this bet?
            {deletingBet ? (
              <div className="mt-2">
                <strong>Captain:</strong> {deletingBet.user?.name}
                <br />
                <strong>Bet:</strong> {getWinner(deletingBet) ? <PlayerName player={getWinner(deletingBet)} race={winnerRace(deletingBet)} /> : "N/A"}
              </div>
            ) : null}
            {isScored(deletingBet?.series) ? (
              <StatusAlert modelValue="This series is already scored; deleting the bet changes the leaderboard." type="warning" className="mt-3 mb-0" />
            ) : null}
          </div>
          <div className="flex justify-end gap-2 px-4 py-3">
            <Button variant="ghost" onClick={() => setDeleteDialog(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={deleteBet} disabled={isDeleting}>
              <Icon name={isDeleting ? "mdi-loading mdi-spin" : "mdi-delete"} />
              Delete
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default FantasyBetsView;

// src/views/FantasyBetsView.vue
<template>
  <v-overlay v-model="isLoading" persistent absolute class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <!-- Page Header -->
    <v-row class="mb-4">
      <v-col>
        <h1>
          <BetIcon size="24" class="mr-2" />
          Fantasy bets
        </h1>
      </v-col>
    </v-row>

    <StatusAlert v-model="errorMessage" />

    <v-card elevation="2">
      <v-card-text class="pa-0">
        <v-toolbar flat height="auto">
          <v-row align="center" class="flex-wrap ma-0 pa-2">
            <v-col cols="12" sm="auto">
              <SeasonSelect />
            </v-col>
            <v-spacer />
            <v-col cols="12" sm="auto">
              <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openAddBetDialog" block>
                Add bet
              </v-btn>
            </v-col>
          </v-row>
        </v-toolbar>
      </v-card-text>
          <v-card-text class="px-0 px-md-4">
            <v-data-table-server
              :headers="headers"
              :items="enrichedBets"
              :items-length="totalBets"
              no-data-text="No bets in this season yet. Bets appear here once bettors place them."
              v-model:page="page"
              v-model:items-per-page="itemsPerPage"
              :items-per-page-options="[10, 25, 50, 100, { value: -1, title: 'All' }]"
              v-model:sort-by="sortBy"
              must-sort
              :loading="isLoading"
              class="elevation-1"
              density="comfortable"
              mobile-breakpoint="sm"
            >
              <template v-slot:[`item.captain`]="{ item }">
                <!-- no race: the bettor bets, they don't play -->
                <PlayerName v-if="item.user" :player="item.user" />
                <template v-else>N/A</template>
              </template>

              <template v-slot:[`item.series`]="{ item }">
                <div v-if="item.series" class="series-sides">
                  <template v-for="(side, i) in sides(item.series)" :key="i">
                    <PlayerName v-if="side.player" :player="side.player" :race="side.race" />
                    <span v-else>Player {{ i + 1 }}</span>
                    <span class="text-no-wrap"><W3CIcon size="14" /> {{ mmrOf(side.player) ?? '—' }}</span>
                    <VsRaces v-if="!smAndDown" :player="ladderById.get(side.player?.id)" :race="side.vsRace" />
                  </template>
                </div>
                <div v-else>N/A</div>
              </template>

              <template v-slot:[`item.bet_on`]="{ item }">
                <PlayerName v-if="getWinner(item)" :player="getWinner(item)" :race="winnerRace(item)" />
                <strong v-else>{{ item.series ? 'Unknown' : 'N/A' }}</strong>
              </template>

              <template v-slot:[`item.score`]="{ item }">
                <div v-if="item.series">
                  {{ item.series.player1_score || 0 }} : {{ item.series.player2_score || 0 }}
                </div>
                <div v-else>-</div>
              </template>

              <template v-slot:[`item.bet_result`]="{ item }">
                <v-chip
                  :color="getBetResultColor(item.bet_result)"
                  size="small"
                  variant="flat"
                >
                  {{ item.bet_result || 'PENDING' }}
                </v-chip>
              </template>

              <template v-slot:[`item.bet_points`]="{ item }">
                {{ item.bet_points || 0 }}
              </template>

              <template v-slot:[`item.is_locked`]="{ item }">
                <v-icon v-if="isScored(item.series)" color="error">mdi-lock</v-icon>
                <v-icon v-else color="success">mdi-lock-open</v-icon>
              </template>

              <template v-slot:[`item.actions`]="{ item }">
                <!-- An admin edits and deletes any bet, scored or not; the dialog says what that costs -->
                <RowActions :actions="[
                  { icon: 'mdi-pencil', label: 'Edit', onClick: () => editBet(item) },
                  { icon: 'mdi-delete', label: 'Delete', color: 'error', onClick: () => confirmDeleteBet(item) },
                ]" />
              </template>
            </v-data-table-server>
          </v-card-text>
        </v-card>

  <!-- Add Bet Dialog -->
  <v-dialog v-model="addBetDialog" max-width="600px" persistent>
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-plus</v-icon>
        Add new fantasy bet
      </v-card-title>
      <v-card-text class="pt-4">
        <StatusAlert v-model="dialogError" />
        <v-form ref="addBetForm">
          <v-autocomplete
            v-model="newBet.captain_id"
            :items="fantasyTeams"
            item-value="captain_id"
            :item-title="(team) => team.captain?.name || 'N/A'"
            label="Select bettor"
            variant="outlined"
            density="comfortable"
            class="mb-4"
            required
          >
            <template v-slot:item="{ props, item }">
              <v-list-item
                :value="props.value"
                @click="props.onClick"
              >
                <v-list-item-title>{{ item.raw.captain?.name || 'N/A' }}</v-list-item-title>
                <v-list-item-subtitle>Team: {{ item.raw.drafted_team?.name || 'N/A' }}</v-list-item-subtitle>
              </v-list-item>
            </template>
          </v-autocomplete>

          <v-autocomplete
            v-model="newBet.series_id"
            :items="availableSeries"
            item-value="id"
            :item-title="seriesTitle"
            label="Select series"
            variant="outlined"
            density="comfortable"
            class="mb-4"
            required
            :disabled="!newBet.captain_id"
            :hint="!newBet.captain_id ? 'Please select a bettor first' : ''"
            persistent-hint
            @update:modelValue="onSeriesSelected"
          >
          </v-autocomplete>

          <v-radio-group v-model="newBet.winner_id" label="Select winner:" v-if="selectedSeriesForNew">
            <v-radio
              :label="selectedSeriesForNew.player1?.name || 'Player 1'"
              :value="selectedSeriesForNew.player1_id"
            ></v-radio>
            <v-radio
              :label="selectedSeriesForNew.player2?.name || 'Player 2'"
              :value="selectedSeriesForNew.player2_id"
            ></v-radio>
          </v-radio-group>

          <v-text-field
            v-if="!useFixedBetPoints"
            v-model.number="newBet.bet_points"
            label="Bet points"
            type="number"
            :min="minBetPoints || 1"
            :max="maxBetPoints"
            :hint="minBetPoints && maxBetPoints ? `Enter between ${minBetPoints} and ${maxBetPoints} points` : minBetPoints ? `Minimum ${minBetPoints} points` : maxBetPoints ? `Maximum ${maxBetPoints} points` : 'Enter the number of points for this bet'"
            :error-messages="betPointsError"
            variant="outlined"
            density="comfortable"
            class="mt-4"
            @input="betPointsError = validateBetPoints(newBet.bet_points)"
            @blur="betPointsError = validateBetPoints(newBet.bet_points)"
          ></v-text-field>
          <v-alert v-else type="info" variant="tonal" class="mt-4">
            This bet will be worth {{ fixedBetPointsValue }} points
          </v-alert>
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn @click="closeAddBetDialog" :disabled="isBetSaving">Cancel</v-btn>
        <v-btn 
          color="primary" 
          variant="elevated" 
          prepend-icon="mdi-plus"
          @click="createNewBet" 
          :loading="isBetSaving"
          :disabled="!newBet.captain_id || !newBet.series_id || !newBet.winner_id || (!useFixedBetPoints && (betPointsError || !newBet.bet_points))"
        >
          Create Bet
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <!-- Edit Bet Dialog -->
  <v-dialog v-model="betDialog" max-width="500px" persistent>
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-pencil</v-icon>
        Edit fantasy bet
      </v-card-title>
      <v-card-text class="pt-4">
        <StatusAlert v-model="dialogError" />
        <v-alert v-if="isScored(editingBet?.series)" type="warning" variant="tonal" density="compact" class="mb-4">
          This series is already scored; changing the bet changes the leaderboard.
        </v-alert>
        <div v-if="editingBet && editingBet.series" class="mb-4">
          <div class="text-subtitle-1 mb-2">
            <strong>Series:</strong> {{ editingBet.series.player1?.name || 'Player 1' }} vs {{ editingBet.series.player2?.name || 'Player 2' }}
          </div>
          <div class="text-subtitle-2 mb-2">
            <strong>Captain:</strong> {{ editingBet.user?.name || 'N/A' }}
          </div>
          <div class="text-subtitle-2 mb-4">
            <strong>Current score:</strong> {{ editingBet.series.player1_score || 0 }} : {{ editingBet.series.player2_score || 0 }}
          </div>

          <v-radio-group v-model="selectedWinnerId" label="Select winner:">
            <v-radio
              :label="editingBet.series.player1?.name || 'Player 1'"
              :value="editingBet.series.player1_id"
            ></v-radio>
            <v-radio
              :label="editingBet.series.player2?.name || 'Player 2'"
              :value="editingBet.series.player2_id"
            ></v-radio>
          </v-radio-group>

          <v-text-field
            v-if="!useFixedBetPoints"
            v-model.number="selectedBetPoints"
            label="Bet points"
            type="number"
            :min="minBetPoints || 1"
            :max="maxBetPoints"
            :hint="minBetPoints && maxBetPoints ? `Enter between ${minBetPoints} and ${maxBetPoints} points` : minBetPoints ? `Minimum ${minBetPoints} points` : maxBetPoints ? `Maximum ${maxBetPoints} points` : 'Enter the number of points for this bet'"
            :error-messages="editBetPointsError"
            variant="outlined"
            density="comfortable"
            class="mt-4"
            @input="editBetPointsError = validateBetPoints(selectedBetPoints)"
            @blur="editBetPointsError = validateBetPoints(selectedBetPoints)"
          ></v-text-field>
          <v-alert v-else type="info" variant="tonal" class="mt-4">
            This bet will be worth {{ fixedBetPointsValue }} points
          </v-alert>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn @click="closeBetDialog" :disabled="isBetSaving">Cancel</v-btn>
        <v-btn 
          color="primary" 
          variant="elevated" 
          prepend-icon="mdi-content-save"
          @click="saveBet" 
          :loading="isBetSaving"
          :disabled="!selectedWinnerId || (!useFixedBetPoints && (editBetPointsError || !selectedBetPoints))"
        >
          Save Changes
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <!-- Delete Confirmation Dialog -->
  <v-dialog v-model="deleteDialog" max-width="400px">
    <v-card>
      <v-card-title class="bg-error text-on-error">
        <v-icon class="mr-2">mdi-alert</v-icon>
        Confirm delete
      </v-card-title>
      <v-card-text class="pt-4">
        <StatusAlert v-model="dialogError" />
        Are you sure you want to delete this bet?
        <div v-if="deletingBet" class="mt-2">
          <strong>Captain:</strong> {{ deletingBet.user?.name }}<br>
          <strong>Bet:</strong>
          <PlayerName v-if="getWinner(deletingBet)" :player="getWinner(deletingBet)" :race="winnerRace(deletingBet)" />
          <template v-else>N/A</template>
        </div>
        <v-alert v-if="isScored(deletingBet?.series)" type="warning" variant="tonal" density="compact" class="mt-3">
          This series is already scored; deleting the bet changes the leaderboard.
        </v-alert>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn @click="deleteDialog = false" variant="text">Cancel</v-btn>
        <v-btn color="error" variant="elevated" prepend-icon="mdi-delete" @click="deleteBet" :loading="isDeleting">Delete</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
  </v-container>
</template>

<script setup>
import BetIcon from '@/components/BetIcon.vue';
import RowActions from '@/components/RowActions.vue';
import VsRaces from '@/components/VsRaces.vue';
import W3CIcon from '@/components/W3CIcon.vue';
import { ref, computed, onMounted, watch } from 'vue';
import { useFantasyStore, useSeriesStore, useConfigStore, useSeasonStore } from '@/stores';
import { storeToRefs } from 'pinia';
import { useDisplay } from 'vuetify';
import SeasonSelect from '@/components/SeasonSelect.vue';
import { isScored, sides, validateBetPoints as checkBetPoints } from '@/helpers/bets';
import StatusAlert from '@/components/StatusAlert.vue';
import { useColumns } from '@/helpers/columns';


const fantasyStore = useFantasyStore();
const seriesStore = useSeriesStore();
const configStore = useConfigStore();
const seasonStore = useSeasonStore();

const { bets, totalBets } = storeToRefs(fantasyStore);
const { selectedSeasonId } = storeToRefs(seasonStore);

const isLoading = ref(false);
const isBetSaving = ref(false);
const isDeleting = ref(false);
const errorMessage = ref(null);
const betDialog = ref(false);
const addBetDialog = ref(false);
const deleteDialog = ref(false);
const editingBet = ref(null);
const deletingBet = ref(null);
const selectedWinnerId = ref(null);
const selectedBetPoints = ref(null);
const allSeries = ref([]);
const fantasyTeams = ref([]);
// The season ladder record of every signup, by user id, for the MMR and the record against each race
const ladderById = ref(new Map());
const page = ref(1);
const itemsPerPage = ref(25);
const sortBy = ref([{ key: 'id', order: 'asc' }]);  // the order the server pages by
const captainBetSeriesIds = ref([]);
const useFixedBetPoints = ref(false);
const fixedBetPointsValue = ref(0);
const minBetPoints = ref(null);
const maxBetPoints = ref(null);
const betPointsError = ref(null);
const editBetPointsError = ref(null);
const dialogError = ref(null);  // the open dialog's own error, so a refused write is read where it happened
const newBet = ref({
  captain_id: null,
  series_id: null,
  winner_id: null,
  bet_points: null
});
const selectedSeriesForNew = ref(null);
// The picker filters on the title it shows, so both sides of the series belong in it
const seriesTitle = (series) => `${series.player1?.name || 'Player 1'} vs ${series.player2?.name || 'Player 2'}`;

// The server sorts the columns it stores; the columns joined in the browser stay unsorted
const allHeaders = [
  { title: 'ID', value: 'id', width: '70px', sortable: true },
  { title: 'Captain', value: 'captain', sortable: true },
  { title: 'Series', value: 'series', sortable: false },
  { title: 'Bet on', value: 'bet_on', sortable: false },
  { mobile: false, title: 'Score', value: 'score', sortable: false, align: 'center' },
  { title: 'Result', value: 'bet_result', sortable: false, align: 'center' },
  { title: 'Points', value: 'bet_points', sortable: true, align: 'end' },
  { mobile: false, title: 'Locked', value: 'is_locked', sortable: false, align: 'center' },
  { title: '', value: 'actions', sortable: false, align: 'center' }
];
const headers = useColumns(allHeaders);
const { smAndDown } = useDisplay();

// Enrich bets with series data
const enrichedBets = computed(() => {
  return bets.value.map(bet => {
    const series = allSeries.value.find(s => s.id === bet.series_id);
    return {
      ...bet,
      series: series || bet.series
    };
  });
});

// Filter only fantasy series for adding bets
const availableSeries = computed(() => {
  if (!newBet.value.captain_id) {
    // No captain selected, return empty array
    return [];
  }

  // Filter series that are:
  // 1. Fantasy matches
  // 2. Not yet played (both scores are 0 or null)
  // 3. Captain doesn't have a bet on them yet
  return allSeries.value.filter(s => {
    const isFantasy = s.is_fantasy_match === true;
    const notPlayed = !isScored(s);
    const noBetYet = !captainBetSeriesIds.value.includes(s.id);
    
    return isFantasy && notPlayed && noBetYet;
  });
});

// The table holds one page, so the duplicate check asks the server
watch(() => newBet.value.captain_id, async (captainId) => {
  if (!captainId || !selectedSeasonId.value) {
    captainBetSeriesIds.value = [];
    return;
  }
  try {
    const captainBets = await fantasyStore.queryBets(
      `user_id == ${captainId} and season_id == ${selectedSeasonId.value}`
    );
    captainBetSeriesIds.value = captainBets.map(bet => bet.series_id);
  } catch (error) {
    console.error('Failed to load the captain bets:', error);
    captainBetSeriesIds.value = [];
  }
});

const validateBetPoints = (points) => checkBetPoints(points, minBetPoints.value, maxBetPoints.value);

const mmrOf = (player) => ladderById.value.get(player?.id)?.mmr?.current ?? null;

const getWinner = (bet) => {
  if (!bet.series) return null;
  if (bet.winner_id === bet.series.player1_id) return bet.series.player1;
  if (bet.winner_id === bet.series.player2_id) return bet.series.player2;
  return null;
};

// the race the winner played in that series, not the one he signed the season up on
const winnerRace = (bet) => {
  if (!bet.series) return null;
  if (bet.winner_id === bet.series.player1_id) return bet.series.player1_race;
  if (bet.winner_id === bet.series.player2_id) return bet.series.player2_race;
  return null;
};

const getBetResultColor = (result) => {
  if (!result || result === 'PENDING') return 'secondary';
  if (result === 'WIN') return 'win';
  if (result === 'LOSS') return 'loss';
  return 'secondary';
};

const fetchData = async () => {
  if (!selectedSeasonId.value) return;  // the picker resolves one
  isLoading.value = true;
  errorMessage.value = null;
  
  try {
    // Fetch one page of bets for the selected season
    const betsQuery = `season_id == ${selectedSeasonId.value}`;
    const sort = sortBy.value[0];
    await fantasyStore.searchBetsPage(betsQuery, {
      limit: itemsPerPage.value,
      offset: itemsPerPage.value === -1 ? 0 : (page.value - 1) * itemsPerPage.value,
      sort: sort ? sort.key : undefined,
      order: sort ? sort.order : undefined
    });

    // A delete can empty the last page; step back onto the table
    if (bets.value.length === 0 && page.value > 1 && totalBets.value > 0 && itemsPerPage.value !== -1) {
      page.value = Math.max(1, Math.ceil(totalBets.value / itemsPerPage.value));
      return fetchData();
    }
    
    // Fetch series for selected season
    const seriesResponse = await seriesStore.searchSeriesBySeason(selectedSeasonId.value, 'is_fantasy_match==True');
    allSeries.value = seriesResponse || [];
    
    // Fetch fantasy teams for selected season
    const teamsQuery = `season_id == ${selectedSeasonId.value}`;
    const teamsResponse = await fantasyStore.searchTeams(teamsQuery);
    fantasyTeams.value = teamsResponse || [];
    
  } catch (error) {
    console.error('Failed to fetch data:', error);
    errorMessage.value = 'Failed to load data. Please try again later.';
  } finally {
    isLoading.value = false;
  }
};

// One read per season for the whole page: the ladder record of every signup
watch(selectedSeasonId, async (seasonId) => {
  ladderById.value = new Map();
  if (!seasonId) return;
  try {
    const rows = await seasonStore.fetchSeasonLadderPlayers(seasonId);
    ladderById.value = new Map((rows || []).map(p => [p.id, p]));
  } catch (error) {
    console.error('Failed to load the season ladder:', error);
  }
}, { immediate: true });

// A new season reads from its first page
watch(selectedSeasonId, () => {
  if (page.value !== 1) {
    page.value = 1; // The watcher fetches
    return;
  }
  fetchData();
}, { immediate: true });

// The table controls drive the page state
watch([page, itemsPerPage], () => {
  if (selectedSeasonId.value) fetchData();
});

// A header click reloads from the first page in the new order
watch(sortBy, () => {
  if (page.value === 1) {
    fetchData();
  } else {
    page.value = 1;
  }
});

const openAddBetDialog = () => {
  newBet.value = {
    captain_id: null,
    series_id: null,
    winner_id: null,
    bet_points: null
  };
  selectedSeriesForNew.value = null;
  betPointsError.value = null;
  dialogError.value = null;
  addBetDialog.value = true;
};

const closeAddBetDialog = () => {
  addBetDialog.value = false;
  dialogError.value = null;
  newBet.value = {
    captain_id: null,
    series_id: null,
    winner_id: null,
    bet_points: null
  };
  selectedSeriesForNew.value = null;
  betPointsError.value = null;
};

const onSeriesSelected = () => {
  if (newBet.value.series_id) {
    selectedSeriesForNew.value = allSeries.value.find(s => s.id === newBet.value.series_id);
  } else {
    selectedSeriesForNew.value = null;
  }
  newBet.value.winner_id = null;
};

const createNewBet = async () => {
  if (!newBet.value.captain_id || !newBet.value.series_id || !newBet.value.winner_id) {
    dialogError.value = 'Please fill in all fields.';
    return;
  }

  isBetSaving.value = true;
  dialogError.value = null;

  try {
    const betData = {
      user_id: newBet.value.captain_id,
      series_id: newBet.value.series_id,
      season_id: selectedSeasonId.value,
      winner_id: newBet.value.winner_id,
      bet_points: newBet.value.bet_points // Send as-is, backend will apply fixed points if configured
    };

    await fantasyStore.createBet(betData);
    await fetchData(); // Refresh data
    closeAddBetDialog();
  } catch (error) {
    console.error('Failed to create bet:', error);
    dialogError.value = error.message || 'Failed to create bet. Please try again.';
  } finally {
    isBetSaving.value = false;
  }
};

const editBet = (bet) => {
  editingBet.value = { ...bet };
  selectedWinnerId.value = bet.winner_id;
  selectedBetPoints.value = bet.bet_points;
  editBetPointsError.value = validateBetPoints(bet.bet_points);
  dialogError.value = null;
  betDialog.value = true;
};

const closeBetDialog = () => {
  betDialog.value = false;
  dialogError.value = null;
  editingBet.value = null;
  selectedWinnerId.value = null;
  selectedBetPoints.value = null;
  editBetPointsError.value = null;
};

const saveBet = async () => {
  if (!editingBet.value || !selectedWinnerId.value) {
    dialogError.value = 'Please select a winner.';
    return;
  }

  isBetSaving.value = true;
  dialogError.value = null;

  try {
    const updatedBet = {
      ...editingBet.value,
      winner_id: selectedWinnerId.value,
      bet_points: selectedBetPoints.value // Send as-is, backend will apply fixed points if configured
    };

    await fantasyStore.updateBet(editingBet.value.id, updatedBet);
    await fetchData(); // Refresh data
    closeBetDialog();
  } catch (error) {
    console.error('Failed to update bet:', error);
    dialogError.value = error.message || 'Failed to update bet. Please try again.';
  } finally {
    isBetSaving.value = false;
  }
};

const confirmDeleteBet = (bet) => {
  deletingBet.value = bet;
  dialogError.value = null;
  deleteDialog.value = true;
};

const deleteBet = async () => {
  if (!deletingBet.value) return;

  isDeleting.value = true;
  dialogError.value = null;

  try {
    await fantasyStore.deleteBet(deletingBet.value.id);
    await fetchData(); // Refresh data
    deleteDialog.value = false;
    deletingBet.value = null;
  } catch (error) {
    console.error('Failed to delete bet:', error);
    dialogError.value = error.message || 'Failed to delete bet. Please try again.';
  } finally {
    isDeleting.value = false;
  }
};

const loadBetPointsSettings = async () => {
  try {
    await configStore.fetchSettings();
    const settings = configStore.settings;
    
    // Get fixed bet points setting
    const fixedBetPointsSetting = settings.find(s => s.key === 'fantasy_fixed_bet_points');
    if (fixedBetPointsSetting) {
      useFixedBetPoints.value = fixedBetPointsSetting.value === 'true';
    }

    // Get fixed bet points value
    const betPointsValueSetting = settings.find(s => s.key === 'fantasy_bet_points_value');
    if (betPointsValueSetting) {
      fixedBetPointsValue.value = parseInt(betPointsValueSetting.value) || 0;
    }
    
    // Get min bet points
    const minBetPointsSetting = settings.find(s => s.key === 'fantasy_min_bet_points');
    if (minBetPointsSetting && minBetPointsSetting.value) {
      minBetPoints.value = parseInt(minBetPointsSetting.value);
    }
    
    // Get max bet points
    const maxBetPointsSetting = settings.find(s => s.key === 'fantasy_max_bet_points');
    if (maxBetPointsSetting && maxBetPointsSetting.value) {
      maxBetPoints.value = parseInt(maxBetPointsSetting.value);
    }
  } catch (error) {
    console.error('Error loading bet points settings:', error);
  }
};

onMounted(loadBetPointsSettings);
</script>

<style scoped>
.v-chip {
  font-weight: 500;
}
/* one row per player of the series, so the two MMRs and the two records line up */
.series-sides {
  display: inline-grid;
  grid-template-columns: max-content max-content max-content;
  align-items: center;
  column-gap: 12px;
  row-gap: 2px;
}
/* A phone has room for the name and the MMR, not the race record */
@media (max-width: 959px) {
  .series-sides { grid-template-columns: max-content max-content; }
}
</style>
