// next/src/app/(app)/koth/dashboard/KothDashboard.tsx
"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Icon } from "@/components/ui/Icon";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { toneClass } from "@/components/ui/tone";
import { EventHeader } from "@/components/EventHeader";
import { PlayerName } from "@/components/PlayerName";
import { RaceIcon } from "@/components/RaceIcon";
import { SignupDialog } from "@/components/SignupDialog";
import { StageView } from "@/components/StageView";
import { StatusAlert } from "@/components/StatusAlert";
import { byPlayer, bySeed, entrantName, raceRows } from "@/helpers/entrants.mjs";
import { myRaces, openNight } from "@/helpers/koth.mjs";
import { raceWrapper } from "@/helpers/races.js";
import { inDivision, isScored } from "@/helpers/stage-view.mjs";
import { useAuth, useEventStore } from "@/stores";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const solo = (item: Row) => !raceRows(item).length;
const raceName = (race: string) => raceWrapper.getRaceObject(race)?.name || race;
const byPosition = (rows: Row[] = []) => [...rows].sort((a, b) => a.position - b.position);

/** Tonight's KOTH night, open to everyone and drawn from the event reads: one column per
 *  bracket with its standing king, everyone signed up for it, and the chain the throne is
 *  played on. `?mode=clean` drops the two buttons, so the page can sit in a stream. */
export function KothDashboard() {
  const router = useRouter();
  const auth = useAuth();
  const store = useEventStore();

  // A stream reads the brackets alone, so the clean page offers nothing to click
  const cleanMode = useSearchParams().get("mode") === "clean";

  const [event, setEvent] = useState<Row | null>(null);
  const [entrants, setEntrants] = useState<Row[]>([]);
  const [series, setSeries] = useState<Row[]>([]);
  const [rounds, setRounds] = useState<Row[]>([]);
  const [standings, setStandings] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [withdrawing, setWithdrawing] = useState<string | boolean>(false); // true, or the race on its way out
  const [error, setError] = useState<string | null>(null);
  const [dialog, setDialog] = useState(false);

  // A night plays one koth stage; a night nobody drew yet has none of its series
  const stage: Row | null = byPosition(event?.stages)[0] || null;
  const standing = entrants.filter((row) => !row.withdrawn_at);
  // A player on two races is one entrant
  const players = byPlayer(standing).length;
  const myId = auth.me?.user?.id;
  const mine = standing.find((row) => row.user?.id && row.user.id === myId) || null;
  const held: string[] = myRaces(standing, myId);

  // One column per bracket, strongest first. The king is the top of the bracket's table,
  // which the engine sorts him to once the chain has scored a series.
  const brackets: Row[] = byPosition(event?.divisions).map((division) => {
    const chain: Row[] = inDivision(series, division.id);
    const top = standings.find((group) => group.division_id === division.id)?.rows?.[0];
    return {
      ...division,
      entrants: byPlayer(bySeed(standing.filter((row) => row.division_id === division.id))),
      king: chain.some(isScored) ? entrants.find((row) => row.id === top?.entrant_id) || null : null,
      chain,
    };
  });

  const load = async () => {
    const night = openNight(await store.fetchEvents(null, "koth"));
    if (!night) {
      setEvent(null);
      return;
    }
    const [full, rows] = await Promise.all([store.fetchEvent(night.id), store.fetchEntrants(night.id)]);
    setEvent(full);
    setEntrants(rows);
    const first = byPosition(full.stages)[0];
    // A stage nobody drew yet answers nothing, and the columns show the signups alone
    const [drawn, table] = first
      ? await Promise.all([store.fetchStage(full.id, first.id).catch(() => null), store.fetchStandings(full.id, first.id).catch(() => [])])
      : [null, []];
    setSeries(drawn?.series || []);
    setRounds(drawn?.rounds || []);
    setStandings(table);
  };

  const withdraw = async (race: string | null = null) => {
    if (!window.confirm(race ? `Withdraw ${raceName(race)} from tonight?` : "Withdraw from tonight?")) return;
    setWithdrawing(race ?? true);
    try {
      await store.withdraw(event!.id, race);
      await load();
    } catch (e) {
      setError(`The withdraw did not go through: ${(e as Error).message}`);
    } finally {
      setWithdrawing(false);
    }
  };

  useEffect(() => {
    const reload = async () => {
      try {
        await load();
        setError(null);
      } catch (e) {
        setError(`The night did not load: ${(e as Error).message}`);
      }
    };
    reload().then(() => setLoading(false));
    // The page hangs on a stream all night, so it reads itself again every 30 seconds
    const timer = setInterval(reload, 30000);
    return () => clearInterval(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="p-2">
      <StatusAlert modelValue={error} onClose={() => setError(null)} />
      {loading ? <Progress value={null} /> : null}

      {!event && !loading ? (
        <div className="py-12 text-center text-muted-foreground">
          <Icon name="mdi-crown-outline" size={64} className="opacity-40" />
          <p className="mt-3 mb-0 text-xl font-medium">No night open tonight</p>
        </div>
      ) : null}

      {event ? (
        <>
          <EventHeader event={event} />

          {!cleanMode ? (
            <div className="mt-4 flex flex-wrap items-center gap-3">
              {event.signups_open && (!mine || (event.multi_entry && held.length < raceWrapper.races.length)) ? (
                <Button size="sm" onClick={() => setDialog(true)}>
                  <Icon name="mdi-account-plus" />
                  {mine ? "Enter another race" : "Sign up"}
                </Button>
              ) : null}
              {/* A player on more than one race withdraws one race at a time */}
              {(held.length > 1 ? held : []).map((race) => (
                <Button key={race} size="sm" variant="destructive" disabled={withdrawing === race} onClick={() => withdraw(race)}>
                  <Icon name={withdrawing === race ? "mdi-loading mdi-spin" : "mdi-account-minus"} />
                  Withdraw {raceName(race)}
                </Button>
              ))}
              {mine && held.length < 2 ? (
                <Button size="sm" variant="destructive" disabled={withdrawing === true} onClick={() => withdraw()}>
                  <Icon name={withdrawing === true ? "mdi-loading mdi-spin" : "mdi-account-minus"} />
                  Withdraw
                </Button>
              ) : null}
              <Badge className={toneClass(null)}>
                <Icon name="mdi-account-multiple" />
                {`${players} ${players === 1 ? "entrant" : "entrants"}`}
              </Badge>
            </div>
          ) : null}

          <div className="mt-4 grid gap-4 min-[960px]:grid-cols-3">
            {brackets.map((bracket) => (
              <Card key={bracket.id} className="card h-full gap-0 py-0">
                <CardHeader className="bg-primary p-4">
                  <CardTitle className="text-on-primary">{bracket.name}</CardTitle>
                </CardHeader>

                <div className="flex min-h-[84px] items-center gap-3 p-4">
                  {bracket.king ? (
                    <>
                      <Icon name="mdi-crown" size={28} className="text-primary-text" aria-hidden="true" />
                      <div>
                        <span className="text-xl font-medium">
                          <PlayerName player={bracket.king.user} race={bracket.king.race} mmr={bracket.king.mmr || false} />
                        </span>
                        <div className="text-xs text-muted-foreground">Holds the throne</div>
                      </div>
                    </>
                  ) : (
                    <div className="text-muted-foreground">No king yet</div>
                  )}
                </div>

                <Separator />

                {bracket.entrants.length ? (
                  <ul className="flex flex-col">
                    {bracket.entrants.map((entrant: Row) => (
                      <li key={entrant.id} className="px-4 py-1">
                        <div className="flex items-center gap-3">
                          {entrant.user ? (
                            <PlayerName player={entrant.user} race={solo(entrant) ? entrant.race : undefined} mmr={(solo(entrant) && entrant.mmr) || false} />
                          ) : (
                            <span>{entrantName(entrant)}</span>
                          )}
                        </div>
                        {/* A player on two races of one bracket sits once in its chain and reads once here */}
                        {raceRows(entrant).map((race: Row) => (
                          <div key={race.id} className="flex items-center gap-2 pl-6 text-xs text-muted-foreground">
                            <RaceIcon raceIdentifier={race.race} />
                            <span>{raceName(race.race)}</span>
                            {race.mmr ? <span className="tnum">{race.mmr} MMR</span> : null}
                          </div>
                        ))}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="mb-0 px-4 py-3 text-muted-foreground">Nobody signed up yet</p>
                )}

                {stage && bracket.chain.length ? (
                  <div className="px-4 pb-2">
                    <StageView stage={stage} series={bracket.chain} rounds={rounds} divisions={[bracket]} onOpenSeries={(row) => router.push(`/series/${row.id}`)} />
                  </div>
                ) : null}
              </Card>
            ))}
          </div>

          {dialog ? <SignupDialog event={event} held={held} open onOpenChange={setDialog} onSignedUp={load} /> : null}
        </>
      ) : null}
    </div>
  );
}

export default KothDashboard;

// src/views/KothDashboard.vue
<!-- Tonight's KOTH night, open to everyone and drawn from the event reads: one column per
     bracket with its standing king, everyone signed up for it, and the chain the throne is
     played on. `?mode=clean` drops the two buttons, so the page can sit in a stream. -->
<template>
  <div class="night">
    <v-container fluid class="pa-6">
      <StatusAlert v-model="error" />
      <v-progress-linear v-if="loading" indeterminate />

      <div v-if="!event && !loading" class="text-center py-12 text-medium-emphasis">
        <v-icon size="64" class="text-disabled" icon="mdi-crown-outline" />
        <p class="text-h6 mt-3 mb-0">No night open tonight</p>
      </div>

      <template v-if="event">
        <EventHeader :event="event" />

        <div v-if="!cleanMode" class="d-flex flex-wrap align-center ga-3 mt-4">
          <v-btn v-if="event.signups_open && (!mine || (event.multi_entry && held.length < raceWrapper.races.length))" color="primary" variant="elevated" size="small"
            prepend-icon="mdi-account-plus" @click="dialog.open()">
            {{ mine ? 'Enter another race' : 'Sign up' }}
          </v-btn>
          <!-- A player on more than one race withdraws one race at a time -->
          <v-btn v-for="race in held.length > 1 ? held : []" :key="race" color="error" variant="tonal" size="small"
            prepend-icon="mdi-account-minus" :loading="withdrawing === race" @click="withdraw(race)">
            Withdraw {{ raceName(race) }}
          </v-btn>
          <v-btn v-if="mine && held.length < 2" color="error" variant="tonal" size="small" prepend-icon="mdi-account-minus"
            :loading="withdrawing === true" @click="withdraw()">
            Withdraw
          </v-btn>
          <v-chip size="small" variant="tonal" prepend-icon="mdi-account-multiple">
            {{ players }} entrants
          </v-chip>
        </div>

        <v-row class="mt-2">
          <v-col v-for="bracket in brackets" :key="bracket.id" cols="12" md="4">
            <v-card elevation="2" class="h-100">
              <v-card-title class="bg-primary">{{ bracket.name }}</v-card-title>

              <div class="king pa-4">
                <template v-if="bracket.king">
                  <v-icon size="28" icon="mdi-crown" class="crown" aria-hidden="true" />
                  <div>
                    <PlayerName class="text-h6" :player="bracket.king.user" :race="bracket.king.race" />
                    <div class="text-caption text-medium-emphasis">
                      {{ bracket.king.mmr ? `${bracket.king.mmr} MMR` : 'Holds the throne' }}
                    </div>
                  </div>
                </template>
                <div v-else class="text-medium-emphasis">No king yet</div>
              </div>

              <v-divider />

              <v-list v-if="bracket.entrants.length" density="compact" class="py-0">
                <v-list-item v-for="entrant in bracket.entrants" :key="entrant.id">
                  <div class="d-flex align-center ga-3">
                    <PlayerName v-if="entrant.user" :player="entrant.user" :race="solo(entrant) ? entrant.race : undefined" />
                    <span v-else>{{ entrantName(entrant) }}</span>
                    <span v-if="solo(entrant) && entrant.mmr" class="text-caption text-medium-emphasis">{{ entrant.mmr }} MMR</span>
                  </div>
                  <!-- A player on two races of one bracket sits once in its chain and reads once here -->
                  <div v-for="race in raceRows(entrant)" :key="race.id" class="d-flex align-center ga-2 pl-6 text-caption text-medium-emphasis">
                    <RaceIcon :raceIdentifier="race.race" />
                    <span>{{ raceName(race.race) }}</span>
                    <span v-if="race.mmr">{{ race.mmr }} MMR</span>
                  </div>
                </v-list-item>
              </v-list>
              <p v-else class="text-medium-emphasis px-4 py-3 mb-0">Nobody signed up yet</p>

              <div v-if="stage && bracket.chain.length" class="px-4 pb-2">
                <StageView :stage="stage" :series="bracket.chain" :rounds="rounds" :divisions="[bracket]"
                  @open-series="row => router.push(`/series/${row.id}`)" />
              </div>
            </v-card>
          </v-col>
        </v-row>

        <SignupDialog ref="dialog" :event="event" :held="held" @signed-up="load" />
      </template>
    </v-container>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { useRoute } from 'vue-router';

import EventHeader from '@/components/EventHeader.vue';
import PlayerName from '@/components/PlayerName.vue';
import RaceIcon from '@/components/RaceIcon.vue';
import SignupDialog from '@/components/SignupDialog.vue';
import StageView from '@/components/StageView.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import { byPlayer, bySeed, entrantName, raceRows } from '@/helpers/entrants.mjs';
import { myRaces, openNight } from '@/helpers/koth.mjs';
import { raceWrapper } from '@/helpers/races.js';
import { router } from '@/helpers/router.js';
import { inDivision, isScored } from '@/helpers/stage-view.mjs';
import { useAuthStore, useEventStore } from '@/stores';

const route = useRoute();
const auth = useAuthStore();
const store = useEventStore();

// A stream reads the brackets alone, so the clean page offers nothing to click
const cleanMode = computed(() => route.query.mode === 'clean');

const event = ref(null);
const entrants = ref([]);
const series = ref([]);
const rounds = ref([]);
const standings = ref([]);
const loading = ref(true);
const withdrawing = ref(false);  // true, or the race on its way out
const error = ref(null);
const dialog = ref(null);
let timer = null;

// A night plays one koth stage; a night nobody drew yet has none of its series
const stage = computed(() => [...(event.value?.stages || [])].sort((a, b) => a.position - b.position)[0] || null);
const standing = computed(() => entrants.value.filter((row) => !row.withdrawn_at));
// A player on two races is one entrant
const players = computed(() => byPlayer(standing.value).length);
const mine = computed(() => standing.value.find((row) => row.user?.id && row.user.id === auth.me?.user?.id) || null);
const held = computed(() => myRaces(standing.value, auth.me?.user?.id));

// One column per bracket, strongest first. The king is the top of the bracket's table,
// which the engine sorts him to once the chain has scored a series.
const brackets = computed(() => [...(event.value?.divisions || [])]
  .sort((a, b) => a.position - b.position)
  .map((division) => {
    const chain = inDivision(series.value, division.id);
    const top = standings.value.find((group) => group.division_id === division.id)?.rows?.[0];
    return {
      ...division,
      entrants: byPlayer(bySeed(standing.value.filter((row) => row.division_id === division.id))),
      king: chain.some(isScored) ? entrants.value.find((row) => row.id === top?.entrant_id) || null : null,
      chain,
    };
  }));

const solo = (item) => !raceRows(item).length;
const raceName = (race) => raceWrapper.getRaceObject(race)?.name || race;

const load = async () => {
  const night = openNight(await store.fetchEvents(null, 'koth'));
  if (!night) {
    event.value = null;
    return;
  }
  const [full, rows] = await Promise.all([store.fetchEvent(night.id), store.fetchEntrants(night.id)]);
  event.value = full;
  entrants.value = rows;
  const first = [...(full.stages || [])].sort((a, b) => a.position - b.position)[0];
  // A stage nobody drew yet answers nothing, and the columns show the signups alone
  const [drawn, table] = first
    ? await Promise.all([
      store.fetchStage(full.id, first.id).catch(() => null),
      store.fetchStandings(full.id, first.id).catch(() => []),
    ])
    : [null, []];
  series.value = drawn?.series || [];
  rounds.value = drawn?.rounds || [];
  standings.value = table;
};

const reload = async () => {
  try {
    await load();
    error.value = null;
  } catch (e) {
    error.value = `The night did not load: ${e.message}`;
  }
};

const withdraw = async (race = null) => {
  if (!confirm(race ? `Withdraw ${raceName(race)} from tonight?` : 'Withdraw from tonight?')) return;
  withdrawing.value = race ?? true;
  try {
    await store.withdraw(event.value.id, race);
    await load();
  } catch (e) {
    error.value = `The withdraw did not go through: ${e.message}`;
  } finally {
    withdrawing.value = false;
  }
};

onMounted(async () => {
  await reload();
  loading.value = false;
  // The page hangs on a stream all night, so it reads itself again every 30 seconds
  timer = setInterval(reload, 30000);
});

onUnmounted(() => clearInterval(timer));
</script>

<style scoped>
.night { background: rgb(var(--v-theme-background)); min-height: 100vh; }
.king { display: flex; align-items: center; gap: 12px; min-height: 84px; }
.crown { color: rgb(var(--v-theme-primary-text)); }
</style>
