// next/src/app/(app)/ladder/LadderView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState } from "react";
import type { SortingState } from "@tanstack/react-table";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AchievementChip } from "@/components/AchievementChip";
import { ColumnNote } from "@/components/ColumnNote";
import { FilterPanel } from "@/components/FilterPanel";
import { PageHeader } from "@/components/PageHeader";
import { PlayerName } from "@/components/PlayerName";
import { RaceIcon } from "@/components/RaceIcon";
import { SeasonSelect } from "@/components/SeasonSelect";
import { StatusAlert } from "@/components/StatusAlert";
import { SyncProgress } from "@/components/SyncProgress";
import { W3CIcon } from "@/components/W3CIcon";
import { W3CMmr } from "@/components/W3CMmr";
import { W3CSyncResultDialog, type SyncEntry } from "@/components/W3CSyncResultDialog";
import { BadgeRarity } from "@/components/ladder/BadgeRarity";
import { LadderLeaderboards } from "@/components/ladder/LadderLeaderboards";
import { PlayerLadderTab } from "@/components/ladder/PlayerLadderTab";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { TapTooltip } from "@/components/ui/TapTooltip";
import { MD_AND_UP, useBreakpoint } from "@/hooks/breakpoint";
import { useTheme } from "@/hooks/theme";
import { useAuth, useLadderStore, usePlayerStore, useSeason } from "@/stores";
import w3championsLogo from "@/assets/media/w3champions-logo.png";
import w3championsLogoWhite from "@/assets/media/w3champions-logo-white.png";
import w3cLogo from "@/assets/media/w3c-logo.png";
import w3cLogoWhite from "@/assets/media/w3c-logo-white.png";
import { ACHIEVEMENTS_NOTE, LADDER_NOTE, SCORED_NOTE, TEAM_BADGES_NOTE, achievementPoints } from "@/helpers/achievements.js";
import { playerPath } from "@/helpers/players.mjs";
import { roundLabel } from "@/helpers/rounds.mjs";
import { showDefaultTeamImage, teamImageUrl } from "@/helpers/team-image.js";
import { agoFromIso, localFromIso } from "@/helpers/w3c-stats.js";
import { cn } from "@/lib/utils";

type Row = Record<string, any>;
// A standings column the table drops below the sm breakpoint
const SM = "hidden min-[600px]:table-cell";

// The roster's badge points plus the team badges; the standing column and the season total
const teamBadgePoints = (team: Row) => team.points - team.ladder_points + achievementPoints(team.achievements);

export function LadderView() {
  const router = useRouter();
  const ladderStore = useLadderStore();
  const playerStore = usePlayerStore();
  const { isAdmin } = useAuth();
  const { seasons, selectedSeasonId, slugOf } = useSeason();
  // The dark-ink wordmark is made for the light theme; the dark theme takes the white original.
  const { activeTheme } = useTheme();
  // The wide columns show from the md breakpoint
  const mdAndUp = useBreakpoint(MD_AND_UP);
  const wordmark = activeTheme === "dark" ? w3championsLogoWhite : w3championsLogo;
  // The Sync button is a primary fill, so its mark follows on-primary: the inverse of the surface rule
  const syncMark = activeTheme === "dark" ? w3cLogo : w3cLogoWhite;

  const [ladder, setLadder] = useState<Row | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const [searchName, setSearchName] = useState("");
  const [searchRace, setSearchRace] = useState<string | null>(null);
  const [searchTeam, setSearchTeam] = useState<number | null>(null);

  const [syncDialog, setSyncDialog] = useState(false);
  const [syncEntries, setSyncEntries] = useState<SyncEntry[]>([]);
  const [fullPlayers, setFullPlayers] = useState<Record<number, Row>>({});
  const [sorting, setSorting] = useState<SortingState>([{ id: "points", desc: true }]);

  const loadLadder = async (seasonId: number) => {
    setIsLoading(true);
    setErrorMessage(null);
    try {
      setLadder(await ladderStore.seasonLadder(seasonId));
    } catch (error) {
      setLadder(null);
      setErrorMessage((error as Error).message);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (!selectedSeasonId) return;
    // the loader sets state, so it runs just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(() => loadLadder(selectedSeasonId));
    // the store's members are rebuilt every render, so the season drives the read
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedSeasonId]);

  // The ladder row carries no gnl_stats, so an expanding row reads the full player once
  const openRow = async (row: Row) => {
    if (fullPlayers[row.id]) return;
    try {
      const player = await playerStore.getPlayer(row.id);
      setFullPlayers((old) => ({ ...old, [row.id]: player }));
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  };

  const seasonName = seasons.find((season: Row) => season.id === selectedSeasonId)?.name ?? "";
  // The round label formats a start/end pair exactly as every other date on the page reads
  const season = ladder?.season;
  const seasonDates = season?.start_date && season?.end_date ? roundLabel(season) : "";
  const teams: Row[] = ladder?.teams ?? [];
  const seasonPoints = teams.reduce((sum, team) => sum + team.points, 0);
  const seasonBadgePoints = teams.reduce((sum, team) => sum + teamBadgePoints(team), 0);
  const seasonPlayers = teams.reduce((sum, team) => sum + team.players.length, 0);
  const teamOptions = teams.map((team) => ({ id: team.id, name: team.name }));

  // One row per player of the season, carrying the team he plays for; one array per ladder read
  const allPlayers: Row[] = useMemo(
    () =>
      ((ladder?.teams ?? []) as Row[]).flatMap((team) =>
        team.players.map((player: Row) => ({
          ...player,
          teamId: team.id,
          teamName: team.name,
          badgePoints: player.points - player.ladder_points,
          mmr: player.mmr?.current ?? null,
          // A player still in his placement games has no MMR, so there is no span to subtract
          mmrDiff: player.mmr?.current != null && player.mmr?.start != null ? player.mmr.current - player.mmr.start : null,
        })),
      ),
    [ladder],
  );

  // The backend leaves the season stamp null until every signup is stamped, so the
  // newest player stamp is what the caption and its tooltip read
  const newestSync = allPlayers.map((player) => player.synced_at).filter(Boolean).sort().at(-1) ?? null;
  // A season counts as synced only while every player of it carries a stamp
  const synced = allPlayers.filter((player) => player.synced_at).length;
  const syncCaption = !synced
    ? "never synced"
    : synced < allPlayers.length
      ? `partly synced · ${synced} of ${allPlayers.length} players`
      : `synced ${agoFromIso(newestSync)}`;

  // The table's `data` keeps one reference until a filter changes, so an opening row holds the page
  const filtered = useMemo(() => {
    const term = searchName.trim().toLowerCase();
    let list = allPlayers;
    if (term) list = list.filter((p) => (p.name || "").toLowerCase().includes(term) || (p.battleTag || "").toLowerCase().includes(term));
    if (searchRace) list = list.filter((p) => p.race === searchRace);
    if (searchTeam) list = list.filter((p) => p.teamId === searchTeam);
    return list;
  }, [allPlayers, searchName, searchRace, searchTeam]);
  const resetFilters = () => {
    setSearchName("");
    setSearchRace(null);
    setSearchTeam(null);
  };

  const syncLadder = async () => {
    setIsSyncing(true);
    setErrorMessage(null);
    try {
      const result = await ladderStore.syncSeason(selectedSeasonId as number);
      setSyncEntries([{ title: seasonName, result }]);
      setSyncDialog(true);
      await loadLadder(selectedSeasonId as number);
    } catch (error) {
      setErrorMessage((error as Error).message);
    } finally {
      setIsSyncing(false);
    }
  };

  const goToPlayer = (player: Row) => router.push(playerPath(player));

  const syncButton = (
    <Button disabled={isSyncing || !selectedSeasonId} onClick={syncLadder}>
      <TapTooltip content="MMR and ladder matches" className="inline-flex items-baseline">
        <Icon name={isSyncing ? "mdi-loading mdi-spin" : "mdi-sync"} className="mr-1" />
        Sync
        <img src={syncMark.src} alt="W3C" className="ml-1 h-[1.4em] translate-y-[3%]" />
      </TapTooltip>
    </Button>
  );

  const teamAvatar = (team: Row | number, size: string) => (
    <span className={cn("block shrink-0 overflow-hidden rounded-sm", size)}>
      <img className="size-full object-contain" src={teamImageUrl(team)} alt="" onError={showDefaultTeamImage} />
    </span>
  );

  return (
    <div className="relative p-4">
      {/* The overlay covers the page area only */}
      {isLoading ? (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-background/60">
          <Icon name="mdi-loading mdi-spin" size={64} className="text-primary" />
        </div>
      ) : null}

      <PageHeader title={<img src={wordmark.src} alt="W3Champions" className="h-[1.35em]" />} />

      {/* Season picker and the sync of that season */}
      <div className="mb-2 flex flex-wrap items-center gap-3">
        <div className="w-full sm:w-[240px]"><SeasonSelect /></div>
        <div className="ms-auto min-w-[240px] text-right"><SyncProgress caption={syncCaption} stamp={localFromIso(newestSync)} /></div>
        {isAdmin ? syncButton : null}
      </div>

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      {/* Empty state */}
      {ladder && !ladder.total_games ? (
        <Card className="card">
          <CardContent className="p-8 text-center">
            <W3CIcon size={64} className="mx-auto opacity-35" />
            <div className="mt-4 mb-2 text-xl text-muted-foreground">No ladder games synced for {seasonName}</div>
            <p className="mb-4 text-muted-foreground">
              {isAdmin ? "Sync the season to fetch its W3Champions matches" : "An admin syncs the season from W3Champions."}
            </p>
            {isAdmin ? syncButton : null}
            <div className="mx-auto mt-4 max-w-[320px]"><SyncProgress /></div>
          </CardContent>
        </Card>
      ) : null}

      {ladder && ladder.total_games ? (
        <>
          {/* Team standings */}
          <Card className="card mb-4 gap-0 py-0">
            <CardTitle className="flex items-center gap-2 bg-primary p-4 text-on-primary">
              <Icon name="mdi-trophy" />
              <span>Team standings</span>
            </CardTitle>
            <div className="p-2 text-xs text-muted-foreground">{seasonDates}</div>
            <div className="table-scroll overflow-x-auto">
              <Table className="tnum">
                <TableHeader>
                  <TableRow className="[&_th]:text-xs [&_th]:text-muted-foreground">
                    <TableHead>Team</TableHead>
                    <TableHead className="text-center"><ColumnNote title="Total points" note={SCORED_NOTE} /></TableHead>
                    <TableHead className={cn(SM, "text-center")}><ColumnNote title="Achievement points" note={TEAM_BADGES_NOTE} /></TableHead>
                    <TableHead className="text-center">Games</TableHead>
                    <TableHead className={cn(SM, "text-center")}>Players</TableHead>
                    <TableHead className={SM}>Team badges</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {teams.map((team, idx) => (
                    <TableRow key={team.id} className={cn(idx === 0 && "bg-primary/6")}>
                      <TableCell>
                        <div className="flex items-center">
                          {teamAvatar(team, "mr-2 size-6")}
                          <Link href={`/team/${team.id}/season/${slugOf(selectedSeasonId as number)}`}>{team.long_name || team.name}</Link>
                        </div>
                      </TableCell>
                      <TableCell className="text-center font-bold">{team.points}</TableCell>
                      <TableCell className={cn(SM, "text-center")}>{teamBadgePoints(team)}</TableCell>
                      <TableCell className="text-center">{team.games}</TableCell>
                      <TableCell className={cn(SM, "text-center")}>{team.players.length}</TableCell>
                      <TableCell className={SM}><AchievementChip badges={team.achievements} showPoints={false} /></TableCell>
                    </TableRow>
                  ))}
                </TableBody>
                {/* The season totals, under the column each one belongs to */}
                <tfoot>
                  <TableRow className="border-t">
                    <TableCell className="text-muted-foreground">{teams.length} teams</TableCell>
                    <TableCell className="text-center font-bold">{seasonPoints}</TableCell>
                    <TableCell className={cn(SM, "text-center")}>{seasonBadgePoints}</TableCell>
                    <TableCell className="text-center">{ladder.total_games}</TableCell>
                    <TableCell className={cn(SM, "text-center")}>{seasonPlayers}</TableCell>
                    <TableCell className={SM} />
                  </TableRow>
                </tfoot>
              </Table>
            </div>
          </Card>

          <LadderLeaderboards players={allPlayers} onOpenPlayer={goToPlayer} />
          <BadgeRarity rules={ladder.achievement_rules} teamRules={ladder.team_achievement_rules} players={allPlayers} teams={teams} />

          {/* Filters (reusable) */}
          <FilterPanel
            searchName={searchName}
            onSearchNameChange={setSearchName}
            searchRace={searchRace}
            onSearchRaceChange={setSearchRace}
            showSeason={false}
            showMMR={false}
            extraActive={searchTeam ? 1 : 0}
            onReset={resetFilters}
            after={
              <Select items={teamOptions.map((team) => ({ value: team.id, label: team.name }))} value={searchTeam} onValueChange={(value) => setSearchTeam(value as number | null)}>
                <SelectTrigger aria-label="Team" className="w-full md:w-[220px]">
                  <Icon name="mdi-shield-account" className="text-muted-foreground" />
                  <SelectValue placeholder="Team" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={null}>All teams</SelectItem>
                  {teamOptions.map((team) => (
                    <SelectItem key={team.id} value={team.id}>{team.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            }
          />

          {/* Players */}
          <Card className="card gap-0 py-0">
            <CardTitle className="flex items-center gap-2 bg-primary p-4 text-on-primary">
              <Icon name="mdi-account-group" />
              <span>Players</span>
            </CardTitle>
            {/* The season change remounts the table, so no row of the season before stays open */}
            <DataTable
              key={selectedSeasonId}
              className="tnum"
              data={filtered}
              pageSize={10}
              sorting={sorting}
              onSortingChange={setSorting}
              rowId={(row) => String(row.id)}
              columnVisibility={{
                race: mdAndUp,
                teamName: mdAndUp,
                ladder_points: mdAndUp,
                badgePoints: mdAndUp,
                wins: mdAndUp,
                losses: mdAndUp,
                mmr: mdAndUp,
                mmrDiff: mdAndUp,
              }}
              expandLabel="Show ladder record"
              onExpand={openRow}
              expand={(row) => (
                /* sticky: stays in view when the summary row scrolls sideways on a narrow window */
                <div className="sticky left-0 max-w-[calc(100vw-48px)] p-4">
                  {!fullPlayers[row.id] ? (
                    <div className="p-4 text-center"><Icon name="mdi-loading mdi-spin" size={32} className="text-primary" /></div>
                  ) : (
                    <PlayerLadderTab player={fullPlayers[row.id]} seasonId={selectedSeasonId as number} />
                  )}
                </div>
              )}
              columns={[
                {
                  id: "name",
                  accessorKey: "name",
                  header: "Name",
                  cell: ({ row }) => (
                    <PlayerName player={row.original}>
                      {!row.original.synced_at ? (
                        <TapTooltip content="not fully synced" className="inline-flex">
                          <Icon name="mdi-sync-alert" size={12} className="text-warning" />
                        </TapTooltip>
                      ) : null}
                    </PlayerName>
                  ),
                },
                {
                  id: "race",
                  accessorKey: "race",
                  header: "Race",
                  cell: ({ row }) => (row.original.race ? <RaceIcon raceIdentifier={row.original.race} /> : null),
                },
                {
                  id: "teamName",
                  accessorKey: "teamName",
                  header: "Team",
                  cell: ({ row }) => (
                    <div className="flex items-center">
                      {teamAvatar(row.original.teamId, "mr-2 size-5")}
                      <span>{row.original.teamName}</span>
                    </div>
                  ),
                },
                {
                  id: "ladder_points",
                  accessorKey: "ladder_points",
                  header: () => <ColumnNote title="Ladder points" note={LADDER_NOTE} />,
                },
                {
                  id: "badgePoints",
                  accessorKey: "badgePoints",
                  header: () => <ColumnNote title="Achievements" note={ACHIEVEMENTS_NOTE} />,
                  cell: ({ row }) => <AchievementChip badges={row.original.achievements} />,
                },
                {
                  id: "points",
                  accessorKey: "points",
                  header: () => <ColumnNote title="Total points" note={SCORED_NOTE} />,
                  cell: ({ row }) => <span className="font-bold">{row.original.points}</span>,
                },
                { id: "wins", accessorKey: "wins", header: "Wins" },
                { id: "losses", accessorKey: "losses", header: "Losses" },
                {
                  id: "mmr",
                  accessorKey: "mmr",
                  header: () => <W3CMmr />,
                  cell: ({ row }) => row.original.mmr ?? "—",
                },
                {
                  id: "mmrDiff",
                  accessorKey: "mmrDiff",
                  header: () => <W3CMmr suffix=" +/-" />,
                  cell: ({ row }) => (row.original.mmrDiff == null ? "—" : row.original.mmrDiff > 0 ? `+${row.original.mmrDiff}` : row.original.mmrDiff),
                },
              ]}
            />
          </Card>
        </>
      ) : null}

      <W3CSyncResultDialog modelValue={syncDialog} entries={syncEntries} onUpdateModelValue={setSyncDialog} />
    </div>
  );
}

export default LadderView;

// src/views/LadderView.vue
<template>
  <v-overlay v-model="isLoading" persistent contained class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <!-- Page Header -->
    <v-row class="mb-4">
      <v-col>
        <h1 class="d-inline-flex">
          <img :src="wordmark" style="height: 1.35em" alt="W3Champions">
        </h1>
      </v-col>
    </v-row>

    <!-- Season picker and the sync of that season -->
    <v-row align="center" class="mb-2 flex-wrap">
      <v-col cols="12" sm="4" md="3">
        <SeasonSelect />
      </v-col>
      <v-spacer />
      <v-col cols="auto" class="text-right" style="min-width: 240px">
        <SyncProgress :caption="syncCaption" :stamp="syncStamp" />
      </v-col>
      <v-col cols="auto">
        <v-btn
          variant="elevated"
          color="primary"
          prepend-icon="mdi-sync"
          :loading="isSyncing"
          :disabled="isSyncing || !selectedSeasonId"
          v-if="auth.isAdmin"
          @click="syncLadder"
        >
          <span class="d-inline-flex align-baseline">Sync<img :src="w3cLogoWhite" style="height: 1.4em; transform: translateY(3%)" alt="W3C" class="ml-1"></span>
          <v-tooltip activator="parent" location="top">MMR and ladder matches</v-tooltip>
        </v-btn>
      </v-col>
    </v-row>

    <StatusAlert v-model="errorMessage" />

    <!-- Empty State -->
    <v-card v-if="ladder && !ladder.total_games" elevation="2">
      <v-card-text class="text-center pa-8">
        <W3CIcon :size="64" style="opacity: 0.35" />
        <div class="text-h6 text-medium-emphasis mt-4 mb-2">No ladder games synced for {{ seasonName }}</div>
        <p class="text-medium-emphasis mb-4">{{ auth.isAdmin ? 'Sync the season to fetch its W3Champions matches' : 'An admin syncs the season from W3Champions.' }}</p>
        <v-btn
          variant="elevated"
          color="primary"
          prepend-icon="mdi-sync"
          :loading="isSyncing"
          :disabled="isSyncing"
          v-if="auth.isAdmin"
          @click="syncLadder"
        >
          <span class="d-inline-flex align-baseline">Sync<img :src="w3cLogoWhite" style="height: 1.4em; transform: translateY(3%)" alt="W3C" class="ml-1"></span>
          <v-tooltip activator="parent" location="top">MMR and ladder matches</v-tooltip>
        </v-btn>
        <SyncProgress class="mt-4 mx-auto" style="max-width: 320px" />
      </v-card-text>
    </v-card>

    <template v-if="ladder && ladder.total_games">
      <!-- Team Standings -->
      <v-card elevation="2" class="mb-4">
        <v-card-title class="bg-primary d-flex align-center">
          <v-icon class="mr-2">mdi-trophy</v-icon>
          <span>Team standings</span>
        </v-card-title>
        <v-toolbar flat height="auto">
          <v-row align="center" class="flex-wrap ma-0 pa-2" style="gap: 8px">
            <span class="text-caption text-medium-emphasis">{{ seasonDates }}</span>
            <v-spacer />
          </v-row>
        </v-toolbar>
        <v-table density="comfortable" class="standings-table">
          <thead>
            <tr>
              <th>Team</th>
              <th class="text-center">
                <ColumnNote title="Total points" :note="SCORED_NOTE" />
              </th>
              <th class="text-center d-none d-sm-table-cell">
                <ColumnNote title="Achievement points" :note="TEAM_BADGES_NOTE" />
              </th>
              <th class="text-center">Games</th>
              <th class="text-center d-none d-sm-table-cell">Players</th>
              <th class="d-none d-sm-table-cell">Team badges</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="(team, idx) in ladder.teams"
              :key="team.id"
              :class="idx === 0 ? 'standings-first' : ''"
            >
              <td>
                <div class="d-flex align-center">
                  <v-avatar size="24" rounded="sm" class="mr-2" style="flex-shrink:0">
                    <img class="team-icon" :src="teamImageUrl(team)" @error="showDefaultTeamImage">
                  </v-avatar>
                  <RouterLink :to="`/team/${team.id}/season/${seasonStore.slugOf(selectedSeasonId)}`">{{ team.long_name || team.name }}</RouterLink>
                </div>
              </td>
              <td class="text-center font-weight-bold">{{ team.points }}</td>
              <td class="text-center d-none d-sm-table-cell">{{ teamBadgePoints(team) }}</td>
              <td class="text-center">{{ team.games }}</td>
              <td class="text-center d-none d-sm-table-cell">{{ team.players.length }}</td>
              <td class="d-none d-sm-table-cell"><AchievementChip :badges="team.achievements" :show-points="false" /></td>
            </tr>
          </tbody>
          <tfoot>
            <tr class="standings-total">
              <td class="text-medium-emphasis">{{ ladder.teams.length }} teams</td>
              <td class="text-center font-weight-bold">{{ seasonPoints }}</td>
              <td class="text-center d-none d-sm-table-cell">{{ seasonBadgePoints }}</td>
              <td class="text-center">{{ ladder.total_games }}</td>
              <td class="text-center d-none d-sm-table-cell">{{ seasonPlayers }}</td>
              <td class="d-none d-sm-table-cell"></td>
            </tr>
          </tfoot>
        </v-table>
      </v-card>

      <LadderLeaderboards :players="allPlayers" @open-player="goToPlayer" />
      <BadgeRarity
        :rules="ladder.achievement_rules"
        :teamRules="ladder.team_achievement_rules"
        :players="allPlayers"
        :teams="ladder.teams"
      />

      <!-- Filters (reusable) -->
      <FilterPanel
        v-model:searchName="searchName"
        v-model:searchRace="searchRace"
        :showName="true"
        :showRace="true"
        :showSeason="false"
        :showMMR="false"
        :showReset="true"
        @reset="resetFilters"
      >
        <template #after>
          <v-col cols="12" md="6">
            <v-select
              v-model="searchTeam"
              :items="teamOptions"
              item-title="name"
              item-value="id"
              placeholder="Team"
              aria-label="Team"
              clearable
              variant="outlined"
              density="compact"
              hide-details
              prepend-inner-icon="mdi-shield-account"
            ></v-select>
          </v-col>
        </template>
      </FilterPanel>

      <!-- Players -->
      <v-card elevation="2">
        <v-card-title class="bg-primary d-flex align-center">
          <v-icon class="mr-2">mdi-account-group</v-icon>
          <span>Players</span>
        </v-card-title>
        <v-card-text class="pa-0">
          <v-data-table
            v-model:expanded="expanded"
            :headers="tableHeader"
            :items="filteredPlayers"
            :sort-by="[{ key: 'points', order: 'desc' }]"
            item-value="id"
            show-expand
            expand-on-click
            fixed-header
            hover
          >
            <template v-slot:[`header.points`]="{ column, isSorted, getSortIcon }">
              <ColumnNote :title="column.title" :note="SCORED_NOTE"
                :sort-icon="isSorted(column) ? getSortIcon(column) : null" />
            </template>
            <template v-slot:[`header.ladder_points`]="{ column, isSorted, getSortIcon }">
              <ColumnNote :title="column.title" :note="LADDER_NOTE"
                :sort-icon="isSorted(column) ? getSortIcon(column) : null" />
            </template>
            <template v-slot:[`header.badgePoints`]="{ column, isSorted, getSortIcon }">
              <ColumnNote :title="column.title" :note="ACHIEVEMENTS_NOTE"
                :sort-icon="isSorted(column) ? getSortIcon(column) : null" />
            </template>
            <template v-slot:[`item.badgePoints`]="{ item }">
              <AchievementChip :badges="item.achievements" />
            </template>
            <template v-slot:[`item.ladder_points`]="{ item }">{{ item.ladder_points }}</template>
            <template v-slot:[`header.mmr`]="{ column, isSorted, getSortIcon }">
              <W3CMmr :sort-icon="isSorted(column) ? getSortIcon(column) : null" />
            </template>
            <template v-slot:[`header.mmrDiff`]="{ column, isSorted, getSortIcon }">
              <W3CMmr suffix=" +/-" :sort-icon="isSorted(column) ? getSortIcon(column) : null" />
            </template>
            <template v-slot:[`item.race`]="{ item }">
              <RaceIcon v-if="item.race" :raceIdentifier="item.race" />
            </template>
            <template v-slot:[`item.name`]="{ item }">
              <PlayerName :player="item">
                <span v-if="!item.synced_at" class="d-inline-flex">
                  <v-icon size="x-small" color="warning">mdi-sync-alert</v-icon>
                  <v-tooltip activator="parent" location="top">not fully synced</v-tooltip>
                </span>
              </PlayerName>
            </template>
            <template v-slot:[`item.teamName`]="{ item }">
              <div class="d-flex align-center">
                <v-avatar size="20" rounded="sm" class="mr-2" style="flex-shrink:0">
                  <img class="team-icon" :src="teamImageUrl(item.teamId)" @error="showDefaultTeamImage">
                </v-avatar>
                <span>{{ item.teamName }}</span>
              </div>
            </template>
            <template v-slot:[`item.points`]="{ item }">
              <span class="font-weight-bold">{{ item.points }}</span>
            </template>
            <template v-slot:[`item.wins`]="{ item }">
              <span class="text-win">{{ item.wins }}</span>
            </template>
            <template v-slot:[`item.losses`]="{ item }">
              <span class="text-loss">{{ item.losses }}</span>
            </template>
            <template v-slot:[`item.mmr`]="{ item }">{{ item.mmr ?? '—' }}</template>
            <template v-slot:[`item.mmrDiff`]="{ item }">
              <span v-if="item.mmrDiff == null">—</span>
              <span v-else :class="item.mmrDiff > 0 ? 'text-win' : item.mmrDiff < 0 ? 'text-loss' : ''">
                {{ item.mmrDiff > 0 ? `+${item.mmrDiff}` : item.mmrDiff }}
              </span>
            </template>
            <template v-slot:expanded-row="{ columns, item }">
              <tr>
                <td :colspan="columns.length" class="pa-0">
                  <!-- sticky: stays in view when the summary row scrolls sideways on a narrow window -->
                  <div class="pa-4 expanded-details">
                    <div v-if="!fullPlayers[item.id]" class="text-center pa-4">
                      <v-progress-circular indeterminate color="primary" />
                    </div>
                    <PlayerLadderTab
                      v-else
                      :player="fullPlayers[item.id]"
                      :seasonId="selectedSeasonId"
                      @open-player="openOpponent"
                    />
                  </div>
                </td>
              </tr>
            </template>
          </v-data-table>
        </v-card-text>
      </v-card>
    </template>


    <W3CSyncResultDialog v-model="syncDialog" :entries="syncEntries" />
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import { useTheme } from 'vuetify';
import { useRouter } from 'vue-router';
import { playerPath } from '@/helpers/players';
import { storeToRefs } from 'pinia';
import { useAuthStore, useLadderStore, usePlayerStore, useSeasonStore } from '@/stores';
import { resolveCurrentW3CSeason } from '@/helpers/current-season';
import { agoFromIso, localFromIso } from '@/helpers/w3c-stats';
import W3CIcon from '@/components/W3CIcon.vue';
import w3championsLogo from '@/assets/media/w3champions-logo.png';
import w3championsLogoWhite from '@/assets/media/w3champions-logo-white.png';
import w3cLogoWhite from '@/assets/media/w3c-logo-white.png';
import { teamImageUrl, showDefaultTeamImage } from '@/helpers/team-image';
import { SCORED_NOTE, ACHIEVEMENTS_NOTE, LADDER_NOTE, TEAM_BADGES_NOTE, achievementPoints } from '@/helpers/achievements';
import LadderLeaderboards from '@/components/LadderLeaderboards.vue';
import BadgeRarity from '@/components/BadgeRarity.vue';
import ColumnNote from '@/components/ColumnNote.vue';
import W3CMmr from '@/components/W3CMmr.vue';
import FilterPanel from '@/components/FilterPanel.vue';
import PlayerLadderTab from '@/components/PlayerLadderTab.vue';
import AchievementChip from '@/components/AchievementChip.vue';
import W3CSyncResultDialog from '@/components/W3CSyncResultDialog.vue';
import SyncProgress from '@/components/SyncProgress.vue';
import SeasonSelect from '@/components/SeasonSelect.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import { useColumns } from '@/helpers/columns';

// The dark-ink wordmark is made for the light theme; the dark theme takes the white original.
const ladderTheme = useTheme();
const wordmark = computed(() => (ladderTheme.global.current.value.dark ? w3championsLogoWhite : w3championsLogo));

const ladderStore = useLadderStore();
const seasonStore = useSeasonStore();
const playerStore = usePlayerStore();
const auth = useAuthStore();

const { seasons, selectedSeasonId } = storeToRefs(seasonStore);

const ladder = ref(null);
const currentW3CSeason = ref(null);
const isLoading = ref(false);
const isSyncing = ref(false);
const errorMessage = ref(null);

const searchName = ref('');
const searchRace = ref(null);
const searchTeam = ref(null);

const syncDialog = ref(false);
const syncEntries = ref([]);
const expanded = ref([]);
const fullPlayers = ref({});

// The ladder row carries no gnl_stats, so an expanding row reads the full player once
watch(expanded, async (ids) => {
  for (const id of ids) {
    if (fullPlayers.value[id]) continue;
    try {
      fullPlayers.value[id] = await playerStore.getPlayer(id);
    } catch (error) {
      errorMessage.value = error.message;
    }
  }
});

// Points and Achievements sit together because the first is the sum of the second and the ladder
const allTableHeader = computed(() => [
  { title: '', key: 'data-table-expand', sortable: false, width: 48 },
  { title: 'Name', key: 'name', sortable: true },
  { mobile: false, title: 'Race', key: 'race', sortable: true, width: 64 },
  { mobile: false, title: 'Team', key: 'teamName', sortable: true },
  { mobile: false, title: 'Ladder points', key: 'ladder_points', sortable: true },
  { mobile: false, title: 'Achievements', key: 'badgePoints', sortable: true },
  { title: 'Total points', key: 'points', sortable: true },
  { mobile: false, title: 'Wins', key: 'wins', sortable: true },
  { mobile: false, title: 'Losses', key: 'losses', sortable: true },
  { mobile: false, title: 'MMR', key: 'mmr', sortable: true },
  { mobile: false, title: 'MMR +/-', key: 'mmrDiff', sortable: true },
]);
const tableHeader = useColumns(allTableHeader);

const seasonName = computed(() =>
  seasons.value.find(s => s.id === selectedSeasonId.value)?.name ?? ''
);

const seasonDates = computed(() => {
  const season = ladder.value?.season;
  return season?.start_date && season?.end_date ? `${season.start_date} to ${season.end_date}` : '';
});

const seasonPoints = computed(() =>
  (ladder.value?.teams ?? []).reduce((sum, team) => sum + team.points, 0)
);

// The roster's badge points plus the team badges; the standing column and the season total
const teamBadgePoints = (team) => team.points - team.ladder_points + achievementPoints(team.achievements);
const seasonBadgePoints = computed(() =>
  (ladder.value?.teams ?? []).reduce((sum, team) => sum + teamBadgePoints(team), 0)
);
const seasonPlayers = computed(() =>
  (ladder.value?.teams ?? []).reduce((sum, team) => sum + team.players.length, 0)
);

// A season counts as synced only while every player of it carries a stamp
const syncCaption = computed(() => {
  const players = allPlayers.value;
  const synced = players.filter(player => player.synced_at).length;
  if (!synced) return 'never synced';
  if (synced < players.length) return `partly synced \u00b7 ${synced} of ${players.length} players`;
  return `synced ${agoFromIso(ladder.value?.season?.synced_at)}`;
});

const syncStamp = computed(() => localFromIso(ladder.value?.season?.synced_at));

const teamOptions = computed(() =>
  (ladder.value?.teams ?? []).map(team => ({ id: team.id, name: team.name }))
);

// One row per player of the season, carrying the team he plays for
const allPlayers = computed(() =>
  (ladder.value?.teams ?? []).flatMap(team =>
    team.players.map(player => ({
      ...player,
      teamId: team.id,
      teamName: team.name,
      badgePoints: player.points - player.ladder_points,
      mmr: player.mmr?.current ?? null,
      // A player still in his placement games has no MMR, so there is no span to subtract
      mmrDiff: player.mmr?.current != null && player.mmr?.start != null
        ? player.mmr.current - player.mmr.start
        : null,
    }))
  )
);

const filteredPlayers = computed(() => {
  let list = allPlayers.value;
  const term = (searchName.value || '').trim().toLowerCase();
  if (term) {
    list = list.filter(p =>
      (p.name || '').toLowerCase().includes(term) || (p.battleTag || '').toLowerCase().includes(term)
    );
  }
  if (searchRace.value) list = list.filter(p => p.race === searchRace.value);
  if (searchTeam.value) list = list.filter(p => p.teamId === searchTeam.value);
  return list;
});

const resetFilters = () => {
  searchName.value = '';
  searchRace.value = null;
  searchTeam.value = null;
};

const loadLadder = async () => {
  if (!selectedSeasonId.value) return;
  expanded.value = [];
  isLoading.value = true;
  errorMessage.value = null;
  try {
    ladder.value = await ladderStore.seasonLadder(selectedSeasonId.value);
  } catch (error) {
    ladder.value = null;
    errorMessage.value = error.message;
  } finally {
    isLoading.value = false;
  }
};

const syncLadder = async () => {
  isSyncing.value = true;
  errorMessage.value = null;
  try {
    const result = await ladderStore.syncSeason(selectedSeasonId.value);
    syncEntries.value = [{ title: seasonName.value, result }];
    syncDialog.value = true;
    await loadLadder();
  } catch (error) {
    errorMessage.value = error.message;
  } finally {
    isSyncing.value = false;
  }
};

const router = useRouter();
const goToPlayer = (player) => router.push(playerPath(player));
// An opponent clicked inside an expanded panel carries only an id
const openOpponent = (userId) => goToPlayer({ id: userId });

watch(selectedSeasonId, loadLadder, { immediate: true });

onMounted(async () => {
  currentW3CSeason.value = await resolveCurrentW3CSeason();
});
</script>

<style scoped>
/* The season totals, under the column each one belongs to */
.standings-total td {
  border-top: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
}
.team-icon {
  width: 100%;
  height: 100%;
  object-fit: contain;
}
.standings-table thead tr th {
  font-size: 0.75rem;
  color: rgba(var(--v-theme-on-surface), 0.6) !important;
}
.standings-first {
  background: rgba(var(--v-theme-primary), 0.06);
}
.expanded-details {
  position: sticky;
  left: 0;
  max-width: calc(100vw - 48px);
}
</style>
