// next/src/app/(app)/maps/MapsView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { LadderImportDialog } from "@/components/LadderImportDialog";
import type { ImportRow } from "@/components/LadderImportDialog";
import { PageHeader } from "@/components/PageHeader";
import { RowActions } from "@/components/RowActions";
import { StatusAlert } from "@/components/StatusAlert";
import { W3CIcon } from "@/components/W3CIcon";
import { useDeleteDialog } from "@/hooks/delete-dialog";
import { hideMissingImage } from "@/helpers/team-image";
import { useMapStore } from "@/stores";

type MapRow = Record<string, any>;

export function MapsView() {
  const mapStore = useMapStore();

  // State
  const [maps, setMaps] = useState<MapRow[]>([]);
  const [selectedMap, setSelectedMap] = useState<MapRow | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [mapDialogOpen, setMapDialogOpen] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [pictureFile, setPictureFile] = useState<File | null>(null);
  const [importOpen, setImportOpen] = useState(false);
  const [importLoading, setImportLoading] = useState(false);
  const [importRows, setImportRows] = useState<ImportRow[]>([]);
  // the picked file while one is picked, else the picture the map already has
  const picturePreview = useMemo(() => (pictureFile ? URL.createObjectURL(pictureFile) : selectedMap?.image), [pictureFile, selectedMap?.image]);

  // Delete dialog state
  const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

  const fetchMaps = async () => {
    setIsLoading(true);
    setErrorMessage(null);
    try {
      setMaps((await mapStore.fetchMaps()) || []);
    } catch (error) {
      console.error("Failed to fetch maps", error);
      setErrorMessage("Failed to load maps. Please try again later.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    // the loaders set state, so they run just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(fetchMaps);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const openCreateMap = () => {
    setSelectedMap({ name: "", shortname: "" });
    setPictureFile(null);
    setFormError(null);
    setIsEditing(false);
    setMapDialogOpen(true);
  };

  const editMap = (map: MapRow) => {
    setSelectedMap({ ...map });
    setPictureFile(null);
    setFormError(null);
    setIsEditing(true);
    setMapDialogOpen(true);
  };

  const uploadPicture = async (mapId: number) => {
    if (pictureFile) await mapStore.uploadMapImage(mapId, pictureFile);
  };

  const updateMap = async () => {
    setFormError(null);
    try {
      await mapStore.updateMap(selectedMap);
      await uploadPicture(selectedMap!.id);
      await fetchMaps();
      closeMapDialog();
    } catch (error) {
      console.error("Error updating map:", error);
      setFormError("Failed to update map. Please try again.");
    }
  };

  const createNewMap = async () => {
    setFormError(null);
    try {
      const created = await mapStore.createMap(selectedMap);
      await uploadPicture(created.id);
      await fetchMaps();
      closeMapDialog();
    } catch (error) {
      console.error("Error creating map:", error);
      setFormError("Failed to create map. Please try again.");
    }
  };

  const removeMap = async (mapId?: number | string) => {
    try {
      await mapStore.deleteMap(Number(mapId));
      await fetchMaps();
    } catch (error) {
      console.error("Error deleting map:", error);
    }
  };

  const openImport = async () => {
    setImportOpen(true);
    setImportLoading(true);
    setImportRows([]);
    try {
      setImportRows(await mapStore.fetchLadderMapImport());
    } catch (error) {
      console.error("Failed to read the ladder pool", error);
      setErrorMessage((error as Error).message);
      setImportOpen(false);
    } finally {
      setImportLoading(false);
    }
  };

  // a known map is renamed to the ladder name and gets its picture; no season pool changes
  const confirmImport = async (names: string[]) => {
    try {
      await mapStore.importLadderMaps(names);
      setImportOpen(false);
      await fetchMaps();
    } catch (error) {
      console.error("Failed to import the ladder pool", error);
      setErrorMessage((error as Error).message);
    }
  };

  const closeMapDialog = () => {
    setMapDialogOpen(false);
    setFormError(null);
    setSelectedMap(null);
    setPictureFile(null);
  };

  return (
    <div className="p-4">
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <Icon name="mdi-loading" size={64} className="animate-spin text-primary" />
        </div>
      ) : null}

      <PageHeader title={<><Icon name="mdi-map" className="mr-2" />1v1 Maps</>} />

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      {/* Main Card */}
      <Card className="card gap-0 py-0">
        <CardHeader className="bg-primary p-4">
          <CardTitle className="flex items-center gap-2 text-on-primary">
            <Icon name="mdi-map" />
            <span>All maps</span>
          </CardTitle>
        </CardHeader>

        <CardContent className="p-4">
          <div className="mb-4 flex flex-wrap justify-end gap-2">
            <Button variant="outline" onClick={openImport}>
              <W3CIcon size={20} />
              Import W3C map pool
            </Button>
            <Button onClick={openCreateMap}>
              <Icon name="mdi-plus" />
              Add map
            </Button>
          </div>

          {maps.length ? (
            <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {maps.map((item) => (
                <Card key={item.id} className="card gap-0 py-0">
                  <div className="relative aspect-3/2 bg-band">
                    {item.image ? (
                      <img src={item.image} alt={item.name} className="h-full w-full object-cover" onError={hideMissingImage} />
                    ) : (
                      // an empty band says the map has no picture rather than reading as one still loading
                      <div className="flex h-full flex-col items-center justify-center text-on-band">
                        <Icon name="mdi-map-outline" size={40} />
                        <span className="mt-1 text-xs">No picture</span>
                      </div>
                    )}
                    {item.shortname ? (
                      <Badge variant="secondary" className="absolute bottom-2 left-2 rounded-[4px]">
                        {item.shortname}
                      </Badge>
                    ) : null}
                  </div>
                  <div className="flex items-center gap-2 p-4">
                    <div className="flex-1 font-medium">{item.name}</div>
                    <RowActions
                      actions={[
                        { icon: "mdi-pencil", label: "Edit", onClick: () => editMap(item) },
                        { icon: "mdi-delete", label: "Delete", color: "error", onClick: () => openDeleteDialog(item.id, removeMap) },
                      ]}
                    />
                  </div>
                </Card>
              ))}
            </div>
          ) : !errorMessage ? (
            // Empty State: only a read that worked proves the pool is empty
            <div className="p-8 text-center">
              <Icon name="mdi-map-outline" size={64} className="text-muted-foreground" />
              <div className="mt-4 mb-2 text-muted-foreground">No maps found</div>
              <p className="mb-4 text-muted-foreground">Get started by adding your first map</p>
              <Button onClick={openCreateMap}>
                <Icon name="mdi-plus" />
                Add the first map
              </Button>
            </div>
          ) : null}
        </CardContent>
      </Card>

      {/* Add / Edit Map Dialog */}
      <Dialog open={mapDialogOpen} onOpenChange={(open) => open || closeMapDialog()}>
        {selectedMap ? (
          <DialogContent showCloseButton={false} className="max-w-[600px] gap-0 p-0 sm:max-w-[600px]">
            <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
              <Icon name={isEditing ? "mdi-pencil" : "mdi-map-plus"} />
              {isEditing ? `Edit map: ${selectedMap.name}` : "Add map"}
            </DialogTitle>

            <StatusAlert modelValue={formError} className="mx-4 my-2" onClose={() => setFormError(null)} />

            <div className="p-4">
              <div className="grid gap-4 md:grid-cols-2">
                <Field label="Map name" htmlFor="map-name">
                  <Input id="map-name" value={selectedMap.name ?? ""} onChange={(e) => setSelectedMap({ ...selectedMap, name: e.target.value })} />
                </Field>
                <Field label="Short name" htmlFor="map-shortname">
                  <Input id="map-shortname" value={selectedMap.shortname ?? ""} onChange={(e) => setSelectedMap({ ...selectedMap, shortname: e.target.value })} />
                </Field>
              </div>
              <div className="mt-4 flex items-center gap-4">
                <span className="block h-16 w-[100px] shrink-0 overflow-hidden rounded-[3px] bg-band">
                  {picturePreview ? <img src={picturePreview} alt={selectedMap.name} onError={hideMissingImage} className="block h-full w-full object-cover" /> : null}
                </span>
                <Field className="flex-1" label="Picture" htmlFor="map-picture">
                  <Input id="map-picture" type="file" accept="image/png,image/jpeg" onChange={(e) => setPictureFile(e.target.files?.[0] ?? null)} />
                </Field>
              </div>
            </div>

            <div className="flex justify-end gap-2 p-4 pt-0">
              <Button variant="ghost" onClick={closeMapDialog}>
                Cancel
              </Button>
              <Button onClick={() => (isEditing ? updateMap() : createNewMap())}>
                <Icon name={isEditing ? "mdi-content-save" : "mdi-plus"} />
                {isEditing ? "Save changes" : "Add map"}
              </Button>
            </div>
          </DialogContent>
        ) : null}
      </Dialog>

      <LadderImportDialog modelValue={importOpen} rows={importRows} loading={importLoading} onUpdateModelValue={setImportOpen} onConfirm={confirmImport} />

      <ConfirmDeleteDialog
        modelValue={showDeleteDialog}
        message="Are you sure you want to delete this map? This action cannot be undone."
        deleteIcon="mdi-delete"
        onUpdateModelValue={(open) => !open && cancelDeleteDialog()}
        onConfirm={confirmDelete}
        onCancel={cancelDeleteDialog}
      />
    </div>
  );
}

export default MapsView;

// src/views/MapsView.vue
<template>
  <v-overlay v-model="isLoading" persistent contained class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <!-- Page Header -->
    <v-row class="mb-4">
      <v-col>
        <h1>
          <v-icon class="mr-2">mdi-map</v-icon>
          1v1 Maps
        </h1>
      </v-col>
    </v-row>

    <v-alert v-if="errorMessage" type="error" variant="tonal" class="mb-4" closable @click:close="errorMessage = null">
      {{ errorMessage }}
    </v-alert>

    <!-- Main Card -->
    <v-card elevation="2">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-map</v-icon>
        <span>All maps</span>
      </v-card-title>

      <v-card-text class="pt-4">
        <div class="d-flex justify-end flex-wrap ga-2 mb-4">
          <v-btn variant="outlined" color="primary" @click="openImport">
            <template #prepend><W3CIcon :size="20" /></template>
            Import W3C map pool
          </v-btn>
          <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openCreateMap">Add map</v-btn>
        </div>
        <v-row v-if="maps.length">
          <v-col v-for="item in maps" :key="item.id" cols="12" sm="6" md="4" lg="3">
            <v-card variant="outlined">
              <v-img :src="item.image" :aspect-ratio="3 / 2" cover class="bg-band">
                <v-chip v-if="item.shortname" class="shortname" size="small" label>{{ item.shortname }}</v-chip>
                <!-- v-img draws nothing without a src, so the empty band says it has no picture rather than reading as one still loading -->
                <div v-if="!item.image" class="d-flex flex-column align-center justify-center fill-height text-on-band">
                  <v-icon size="40">mdi-map-outline</v-icon>
                  <span class="text-caption mt-1">No picture</span>
                </div>
              </v-img>
              <v-card-item>
                <div class="text-subtitle-1 font-weight-medium">{{ item.name }}</div>
                <template #append>
                  <RowActions :actions="[
                    { icon: 'mdi-pencil', label: 'Edit', onClick: () => editMap(item) },
                    { icon: 'mdi-delete', label: 'Delete', color: 'error', onClick: () => openDeleteDialog(item.id, removeMap) },
                  ]" />
                </template>
              </v-card-item>
            </v-card>
          </v-col>
        </v-row>

        <!-- Empty State: only a read that worked proves the pool is empty -->
        <div v-else-if="!errorMessage" class="text-center pa-8">
          <v-icon size="64" class="text-disabled">mdi-map-outline</v-icon>
          <div class="text-h6 text-medium-emphasis mt-4 mb-2">No maps found</div>
          <p class="text-medium-emphasis mb-4">Get started by adding your first map</p>
          <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openCreateMap">
            Add the first map
          </v-btn>
        </div>
      </v-card-text>
    </v-card>

    <!-- Add / Edit Map Dialog -->
    <v-dialog v-model="mapDialogOpen" max-width="600">
      <v-card v-if="selectedMap">
        <v-card-title class="bg-primary">
          <v-icon class="mr-2">{{ isEditing ? 'mdi-pencil' : 'mdi-map-plus' }}</v-icon>
          {{ isEditing ? `Edit map: ${selectedMap.name}` : 'Add map' }}
        </v-card-title>

        <v-alert v-if="formError" type="error" variant="tonal" border="start" border-color="error" class="mx-4 my-2" closable @click:close="formError = null">
          {{ formError }}
        </v-alert>

        <v-card-text class="pt-4">
          <v-row>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="selectedMap.name"
                label="Map name"
                variant="outlined"
                prepend-inner-icon="mdi-map"
                density="comfortable"
              ></v-text-field>
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="selectedMap.shortname"
                label="Short name"
                variant="outlined"
                prepend-inner-icon="mdi-text-short"
                density="comfortable"
              ></v-text-field>
            </v-col>
            <v-col cols="12" class="d-flex align-center ga-4">
              <span class="map-thumb thumb-lg"><img v-if="picturePreview" :src="picturePreview" :alt="selectedMap.name" @error="hideMissingImage"></span>
              <v-file-input
                v-model="pictureFile"
                label="Picture"
                accept="image/png,image/jpeg"
                variant="outlined"
                density="comfortable"
                prepend-icon=""
                prepend-inner-icon="mdi-image"
                hide-details
                clearable
              />
            </v-col>
          </v-row>
        </v-card-text>

        <v-card-actions>
          <v-spacer />
          <v-btn @click="closeMapDialog">Cancel</v-btn>
          <v-btn @click="isEditing ? updateMap() : createNewMap()" color="primary" variant="elevated" :prepend-icon="isEditing ? 'mdi-content-save' : 'mdi-plus'">
            {{ isEditing ? 'Save changes' : 'Add map' }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <LadderImportDialog v-model="importOpen" :rows="importRows" :loading="importLoading" @confirm="confirmImport" />

    <ConfirmDeleteDialog
      v-model="showDeleteDialog"
      message="Are you sure you want to delete this map? This action cannot be undone."
      delete-icon="mdi-delete"
      @confirm="confirmDelete"
      @cancel="cancelDeleteDialog"
    />
  </v-container>
</template>
<script setup>
import RowActions from '@/components/RowActions.vue';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';
import LadderImportDialog from '@/components/LadderImportDialog.vue';
import W3CIcon from '@/components/W3CIcon.vue';
import { useMapStore } from '@/stores';
import { hideMissingImage } from '@/helpers/team-image';
import { computed, onMounted, ref } from 'vue';
import { storeToRefs } from 'pinia';
import { useDeleteDialog } from '@/helpers/delete-dialog';


// Store
const mapStore = useMapStore();
const { maps } = storeToRefs(mapStore);

// State
const selectedMap = ref(null);
const isLoading = ref(false);
const errorMessage = ref(null);
const mapDialogOpen = ref(false);
const isEditing = ref(false);
const formError = ref(null);
const pictureFile = ref(null);
const importOpen = ref(false);
const importLoading = ref(false);
const importRows = ref([]);
// the picked file while one is picked, else the picture the map already has
const picturePreview = computed(() => (pictureFile.value ? URL.createObjectURL(pictureFile.value) : selectedMap.value?.image));

// Delete dialog state
const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

const fetchMaps = async () => {
  isLoading.value = true;
  errorMessage.value = null;
  try {
    await mapStore.fetchMaps();
  } catch (error) {
    console.error('Failed to fetch maps', error);
    errorMessage.value = 'Failed to load maps. Please try again later.';
  } finally {
    isLoading.value = false;
  }
};

const openCreateMap = () => {
  selectedMap.value = {
    name: '',
    shortname: ''
  };
  pictureFile.value = null;
  formError.value = null;
  isEditing.value = false;
  mapDialogOpen.value = true;
};

const editMap = (map) => {
  selectedMap.value = { ...map };
  pictureFile.value = null;
  formError.value = null;
  isEditing.value = true;
  mapDialogOpen.value = true;
};

const updateMap = async () => {
  formError.value = null;
  try {
    await mapStore.updateMap(selectedMap.value);
    await uploadPicture(selectedMap.value.id);
    await fetchMaps();
    closeMapDialog();
  } catch (error) {
    console.error('Error updating map:', error);
    formError.value = 'Failed to update map. Please try again.';
  }
};

const createNewMap = async () => {
  formError.value = null;
  try {
    const created = await mapStore.createMap(selectedMap.value);
    await uploadPicture(created.id);
    await fetchMaps();
    closeMapDialog();
  } catch (error) {
    console.error('Error creating map:', error);
    formError.value = 'Failed to create map. Please try again.';
  }
};

const uploadPicture = async (mapId) => {
  if (pictureFile.value) await mapStore.uploadMapImage(mapId, pictureFile.value);
};

const removeMap = async (mapId) => {
  try {
    await mapStore.deleteMap(mapId);
    await fetchMaps();
  } catch (error) {
    console.error('Error deleting map:', error);
  }
};

const openImport = async () => {
  importOpen.value = true;
  importLoading.value = true;
  importRows.value = [];
  try {
    importRows.value = await mapStore.fetchLadderMapImport();
  } catch (error) {
    console.error('Failed to read the ladder pool', error);
    errorMessage.value = error.message;
    importOpen.value = false;
  } finally {
    importLoading.value = false;
  }
};

// a known map is renamed to the ladder name and gets its picture; no season pool changes
const confirmImport = async (names) => {
  try {
    await mapStore.importLadderMaps(names);
    importOpen.value = false;
    await fetchMaps();
  } catch (error) {
    console.error('Failed to import the ladder pool', error);
    errorMessage.value = error.message;
  }
};

const closeMapDialog = () => {
  mapDialogOpen.value = false;
  formError.value = null;
  selectedMap.value = null;
  pictureFile.value = null;
};

// Lifecycle hooks
onMounted(() => {
  fetchMaps();
});
</script>

<style scoped>
.map-thumb {
  display: block;
  background: rgb(var(--v-theme-band));
  border-radius: 3px;
  overflow: hidden;
}

.shortname {
  position: absolute;
  left: 8px;
  bottom: 8px;
}

.map-thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.thumb-lg {
  width: 100px;
  height: 64px;
}
</style>
