// next/src/app/(app)/players/PlayersView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { CareerStatsDialog, type CareerStatsDialogHandle } from "@/components/CareerStatsDialog";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { CountrySelect } from "@/components/CountrySelect";
import { EditPlayerDialog, type EditPlayerDialogHandle } from "@/components/EditPlayerDialog";
import { FilterPanel } from "@/components/FilterPanel";
import { PageHeader } from "@/components/PageHeader";
import { PlayerName } from "@/components/PlayerName";
import { RaceMmrChips } from "@/components/RaceMmrChips";
import { RaceSelect } from "@/components/RaceSelect";
import { RowActions } from "@/components/RowActions";
import { SeasonSignupDialog, type SeasonSignupDialogHandle } from "@/components/SeasonSignupDialog";
import { StatusAlert } from "@/components/StatusAlert";
import { W3CMmr } from "@/components/W3CMmr";
import { useDeleteDialog } from "@/hooks/delete-dialog";
import { resolveCurrentW3CSeason } from "@/helpers/current-season.js";
import { findSeason } from "@/helpers/season-slug.mjs";
import { filterByMmrRange, matchesPlayerSearch, playerPath, playersWithCareers } from "@/helpers/players.mjs";
import { getAllRaceStats, getW3CGamesCount, hasLowGamesTwoSeasons, hasW3CStatsTwoSeasons } from "@/helpers/w3c-stats.js";
import { useAuth, usePlayerCareerStatsStore, usePlayerStore, useSeason } from "@/stores";

type Row = Record<string, any>;
type Flag = "no_stats" | "low_games" | "unlinked";
const WIDE = "hidden min-[960px]:table-cell";
const PAGE_SIZE = 25;

const emptyPlayer = () => ({ name: "", battleTag: "", country: "", discordTag: "", discordId: "", mmr: 0, race: "" });

function Warning({ row, season }: { row: Row; season: number | null }) {
  const missing = !hasW3CStatsTwoSeasons(row, season ?? 0, row.race);
  const low = !missing && hasLowGamesTwoSeasons(row, season ?? 0, row.race);
  if (!missing && !low) return null;
  const text = missing ? `No W3C stats found for ${row.race}` : `Less than 20 games (${getW3CGamesCount(row, season ?? 0, row.race)} games) for ${row.race}`;
  return <Tooltip><TooltipTrigger render={<span tabIndex={0}><Icon name="mdi-alert" className={missing ? "text-error" : "text-warning"} /></span>} /><TooltipContent>{text}</TooltipContent></Tooltip>;
}

export function PlayersView() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const playerStore = usePlayerStore();
  const careerStore = usePlayerCareerStatsStore();
  const seasonStore = useSeason();
  const { isAdmin } = useAuth();
  const editDialog = useRef<EditPlayerDialogHandle>(null);
  const signupDialog = useRef<SeasonSignupDialogHandle>(null);
  const careerDialog = useRef<CareerStatsDialogHandle>(null);

  const [players, setPlayers] = useState<Row[]>([]);
  const [careers, setCareers] = useState<Row[]>([]);
  const [w3cSeason, setW3cSeason] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [race, setRace] = useState<string | null>(null);
  const [range, setRange] = useState<number[]>([0, 3000]);
  const [flags, setFlags] = useState<Flag[]>([]);
  const [sort, setSort] = useState<{ key: string; desc: boolean }>({ key: "rating", desc: true });
  const [page, setPage] = useState(0);
  const [newOpen, setNewOpen] = useState(false);
  const [newPlayer, setNewPlayer] = useState<Row>(emptyPlayer);
  const [creating, setCreating] = useState(false);
  const [creationError, setCreationError] = useState<string | null>(null);
  const [sync, setSync] = useState<Record<number, "loading" | "success" | "error">>({});
  const deletion = useDeleteDialog();

  const load = async () => {
    setLoading(true); setError(null);
    try {
      const [playerRows, careerRows, current] = await Promise.all([playerStore.fetchPlayers(), careerStore.fetchAll(), resolveCurrentW3CSeason()]);
      setPlayers(playerRows || []); setCareers(careerRows || []); setW3cSeason(current);
    } catch (e) { console.error("Failed to load players:", e); setError("Failed to load players. Please try again later."); }
    finally { setLoading(false); }
  };

  useEffect(() => {
    const start = async () => {
      try {
        await seasonStore.fetchSeasons();
      } catch (e) { console.error("Failed to fetch seasons:", e); }
      await load();
    };
    start();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const seasonId = findSeason(seasonStore.seasons, searchParams.get("season"))?.id ?? null;

  const chooseSeason = (id: number | null) => {
    setPage(0);
    const query = new URLSearchParams(searchParams.toString());
    if (id) query.set("season", seasonStore.slugOf(id)); else query.delete("season");
    router.replace(query.size ? `/players?${query}` : "/players", { scroll: false });
  };
  const bestMmr = (player: Row) => Math.max(0, ...getAllRaceStats(player, w3cSeason ?? undefined).filter((stat: Row) => (stat.games || 0) > 0).map((stat: Row) => stat.mmr || 0));
  const joined: Row[] = playersWithCareers(players, careers).map((row: Row) => ({ ...row, best_mmr: row.id != null ? bestMmr(row) || null : null }));
  const base = flags.includes("unlinked") ? joined : joined.filter((row) => row.id != null);
  let filtered = base.filter((row) => !name.trim() || matchesPlayerSearch(row, name));
  if (race) filtered = filtered.filter((row) => row.race === race);
  if (seasonId) filtered = filtered.filter((row) => (row.signup_seasons || []).some((season: Row) => season.id === seasonId));
  filtered = filterByMmrRange(filtered, range, (row: Row) => row.best_mmr ?? 0);
  if (flags.length) filtered = filtered.filter((row) => flags.some((flag) => flag === "unlinked" ? row.id == null && row.career?.id != null : flag === "no_stats" ? row.id != null && !hasW3CStatsTwoSeasons(row, w3cSeason ?? 0, row.race) : row.id != null && hasLowGamesTwoSeasons(row, w3cSeason ?? 0, row.race)));
  const sorted = [...filtered].sort((a, b) => {
    const av = a[sort.key] ?? a.career?.[sort.key] ?? null;
    const bv = b[sort.key] ?? b.career?.[sort.key] ?? null;
    if (av == null) return 1; if (bv == null) return -1;
    const order = typeof av === "number" && typeof bv === "number" ? av - bv : String(av).localeCompare(String(bv), undefined, { numeric: true });
    return order * (sort.desc ? -1 : 1);
  });
  const pages = Math.max(1, Math.ceil(sorted.length / PAGE_SIZE));
  const shown = sorted.slice(Math.min(page, pages - 1) * PAGE_SIZE, (Math.min(page, pages - 1) + 1) * PAGE_SIZE);
  const count = filtered.length === base.length ? `${base.length} players` : `${filtered.length} of ${base.length} players`;

  const toggleSort = (key: string) => { setSort((old) => ({ key, desc: old.key === key ? !old.desc : false })); setPage(0); };
  const head = (label: React.ReactNode, key?: string, className = "") => <TableHead className={className}>{key ? <button type="button" className="whitespace-nowrap" onClick={() => toggleSort(key)}>{label}<Icon name={sort.key === key && sort.desc ? "mdi-arrow-down" : "mdi-arrow-up"} className={`ml-1 text-xs ${sort.key === key ? "text-primary" : "opacity-25"}`} /></button> : label}</TableHead>;
  const clear = () => { setName(""); setRace(null); chooseSeason(null); setRange([0, 3000]); setFlags([]); setPage(0); };
  const toggleFlag = (flag: Flag) => { setFlags((old) => old.includes(flag) ? old.filter((item) => item !== flag) : [...old, flag]); setPage(0); };
  const setNew = (key: string, value: unknown) => setNewPlayer((old) => ({ ...old, [key]: value }));
  const create = async () => {
    setCreating(true); setCreationError(null);
    try { await playerStore.createPlayer(newPlayer); await load(); setNewOpen(false); }
    catch (e) { setCreationError("Error creating user: " + (e as Error).message); }
    finally { setCreating(false); }
  };
  const remove = async (id?: number | string) => { try { await playerStore.deletePlayer(Number(id)); await load(); } catch (e) { console.error("Error deleting player:", e); } };
  const syncPlayer = async (id: number) => {
    setSync((old) => ({ ...old, [id]: "loading" }));
    try { const updated = await playerStore.syncW3CPlayer(id); if (updated) setPlayers((old) => playerStore.patchPlayers(old, updated)); setSync((old) => ({ ...old, [id]: "success" })); }
    catch (e) { console.error("Error syncing player:", id, e); setSync((old) => ({ ...old, [id]: "error" })); }
  };

  return <div className="p-4">
    {loading && !players.length ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60" role="status" aria-label="Loading"><Icon name="mdi-loading" size={64} className="animate-spin text-primary" /></div> : null}
    <div className="flex flex-wrap items-start justify-between gap-3"><PageHeader title={<span className="inline-flex items-center gap-2"><Icon name="mdi-account-group" />Players</span>} />{isAdmin ? <Button onClick={() => { setNewPlayer(emptyPlayer()); setCreationError(null); setNewOpen(true); }}><Icon name="mdi-plus" />Add Player</Button> : null}</div>
    <FilterPanel
      seasons={seasonStore.seasons as { id: number; name: string }[]} searchName={name} onSearchNameChange={(value) => { setName(value); setPage(0); }} searchRace={race} onSearchRaceChange={(value) => { setRace(value); setPage(0); }}
      selectedSeasonFilter={seasonId} onSelectedSeasonFilterChange={chooseSeason} rangeValues={range} onRangeValuesChange={(value) => { setRange(value); setPage(0); }} extraActive={flags.length} onReset={clear} summary={<span className="text-sm text-muted-foreground">{count}</span>}
      after={<DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" className="min-w-40 justify-between" />}><span className="inline-flex items-center gap-2"><Icon name="mdi-alert-outline" />{flags.length ? `${flags.length} selected` : "Show only"}</span><Icon name="mdi-chevron-down" /></DropdownMenuTrigger><DropdownMenuContent align="start">
        {([["no_stats", "No W3C stats"], ["low_games", "Less than 20 games"], ...(isAdmin ? [["unlinked", "Unlinked players"]] : [])] as [Flag, string][]).map(([value, label]) => <DropdownMenuItem key={value} onClick={(event) => { event.preventDefault(); toggleFlag(value); }}><Icon name={flags.includes(value) ? "mdi-checkbox-marked" : "mdi-checkbox-blank-outline"} />{label}</DropdownMenuItem>)}
      </DropdownMenuContent></DropdownMenu>}
    />
    <Card className="card gap-0 py-0">
      <StatusAlert modelValue={error} className="m-4" onClose={() => setError(null)} />
      {!error ? <div className="table-scroll overflow-x-auto"><Table className="tnum"><TableHeader><TableRow>
        {head("Name", "name")}{head(<W3CMmr suffix={w3cSeason ? ` (S${w3cSeason})` : ""} />, "best_mmr", WIDE)}{head("Rating", "rating", "text-right")}{head("Series", "series_winrate", "text-right")}{head("Games", "games_winrate", `${WIDE} text-right`)}{head("Seasons", "seasons_played", `${WIDE} text-right`)}{head("Events", undefined, WIDE)}{isAdmin ? <TableHead /> : null}
      </TableRow></TableHeader><TableBody>
        {shown.map((row) => <TableRow key={row.key} className={row.id != null ? "cursor-pointer" : undefined} onClick={(event) => {
          if ((event.target as Element).closest('[data-slot="tooltip-trigger"]')) return;
          if (row.id != null) router.push(playerPath(row));
        }}>
          <TableCell>{row.id != null ? <PlayerName player={row}><Warning row={row} season={w3cSeason} /></PlayerName> : <span className="text-muted-foreground">{row.name}</span>}</TableCell>
          <TableCell className={WIDE}>{row.id != null ? <RaceMmrChips player={row} w3cSeason={w3cSeason ?? undefined} max={2} /> : null}</TableCell>
          <TableCell className="text-right">{row.rating ?? "—"}</TableCell>
          <TableCell className="text-right">{row.career ? <>{row.career.series_won}-{row.career.series_lost} <span className="text-muted-foreground">{row.career.series_winrate}%</span></> : "—"}</TableCell>
          <TableCell className={`${WIDE} text-right`}>{row.career ? <>{row.career.games_won}-{row.career.games_lost} <span className="text-muted-foreground">{row.career.games_winrate}%</span></> : "—"}</TableCell>
          <TableCell className={`${WIDE} text-right`}>{row.seasons_played ?? "—"}</TableCell>
          <TableCell className={WIDE}>{row.signup_seasons?.length ? <span className="inline-flex items-center gap-1"><Badge variant="secondary" title={[...row.signup_seasons].sort((a: Row, b: Row) => b.id - a.id)[0].name} className="max-w-[120px] truncate">{[...row.signup_seasons].sort((a: Row, b: Row) => b.id - a.id)[0].name}</Badge>{row.signup_seasons.length > 1 ? <DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" size="sm" onClick={(e) => e.stopPropagation()} />}>+{row.signup_seasons.length - 1}</DropdownMenuTrigger><DropdownMenuContent>{[...row.signup_seasons].sort((a: Row, b: Row) => b.id - a.id).map((season: Row) => <DropdownMenuItem key={season.id}>{season.name}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu> : null}</span> : "—"}</TableCell>
          {isAdmin ? <TableCell onClick={(event) => event.stopPropagation()}><RowActions actions={row.id == null ? [{ icon: "mdi-history", label: "Career stats", onClick: () => careerDialog.current?.open(row.career) }] : [
            { icon: "mdi-pencil", label: "Edit", onClick: () => editDialog.current?.open(row) }, { icon: "mdi-account-check", label: "Add to season", onClick: () => signupDialog.current?.open({ player: row }) },
            { icon: sync[row.id] === "success" ? "mdi-check-circle" : sync[row.id] === "error" ? "mdi-alert-circle" : "mdi-sync", label: sync[row.id] === "success" ? "Synced" : sync[row.id] === "error" ? "Retry Sync" : "Sync W3C", color: sync[row.id] === "success" ? "success" : sync[row.id] === "error" ? "error" : undefined, loading: sync[row.id] === "loading", onClick: () => syncPlayer(row.id) },
            ...(row.career?.id != null ? [{ icon: "mdi-history", label: "Career stats", onClick: () => careerDialog.current?.open(row.career) }] : []), { icon: "mdi-delete", label: "Delete", color: "error", onClick: () => deletion.openDeleteDialog(row.id, remove) },
          ]} /></TableCell> : null}
        </TableRow>)}
        {!shown.length && !loading ? <TableRow><TableCell colSpan={isAdmin ? 8 : 7} className="py-8 text-center text-muted-foreground">No players match these filters</TableCell></TableRow> : null}
      </TableBody></Table></div> : null}
      {!error && sorted.length ? <div className="flex items-center justify-end gap-4 px-4 py-2 text-sm text-muted-foreground"><span>Items per page: {PAGE_SIZE}</span><span>{Math.min(page, pages - 1) * PAGE_SIZE + 1}-{Math.min(sorted.length, (Math.min(page, pages - 1) + 1) * PAGE_SIZE)} of {sorted.length}</span><Button variant="ghost" size="icon-sm" aria-label="Previous page" disabled={page <= 0} onClick={() => setPage((p) => Math.max(0, p - 1))}><Icon name="mdi-chevron-left" /></Button><Button variant="ghost" size="icon-sm" aria-label="Next page" disabled={page >= pages - 1} onClick={() => setPage((p) => Math.min(pages - 1, p + 1))}><Icon name="mdi-chevron-right" /></Button></div> : null}
    </Card>

    <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent showCloseButton={false} className="max-w-[800px] gap-0 p-0 sm:max-w-[800px]"><DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary"><Icon name="mdi-account-plus" />Add new player</DialogTitle><div className="p-4 pb-0"><StatusAlert modelValue={creationError} onClose={() => setCreationError(null)} /></div><div className="grid gap-4 p-4 md:grid-cols-2"><Field label="Player Name" htmlFor="new-player-name"><Input id="new-player-name" value={newPlayer.name} onChange={(e) => setNew("name", e.target.value)} /></Field><Field label="BattleTag" htmlFor="new-player-battle-tag"><Input id="new-player-battle-tag" value={newPlayer.battleTag} onChange={(e) => setNew("battleTag", e.target.value)} /></Field><CountrySelect value={newPlayer.country || null} onChange={(value) => setNew("country", value || "")} /><Field label="Discord Tag" htmlFor="new-player-discord-tag"><Input id="new-player-discord-tag" value={newPlayer.discordTag} onChange={(e) => setNew("discordTag", e.target.value)} /></Field><Field label="Discord ID" htmlFor="new-player-discord-id" hint="Numeric Discord user ID (required)"><Input id="new-player-discord-id" value={newPlayer.discordId} onChange={(e) => setNew("discordId", e.target.value)} /></Field><RaceSelect value={newPlayer.race || null} onChange={(value) => setNew("race", value || "")} /></div><div className="flex justify-end gap-2 p-4 pt-0"><Button variant="ghost" onClick={() => setNewOpen(false)}>Cancel</Button>{isAdmin ? <Button disabled={creating} onClick={create}><Icon name={creating ? "mdi-loading mdi-spin" : "mdi-plus"} />Add Player</Button> : null}</div></DialogContent></Dialog>
    <EditPlayerDialog ref={editDialog} canSave={isAdmin} refresh={load} />
    <SeasonSignupDialog ref={signupDialog} onAdded={load} />
    {isAdmin ? <CareerStatsDialog ref={careerDialog} players={players} onChanged={load} /> : null}
    <ConfirmDeleteDialog modelValue={deletion.showDeleteDialog} message="Are you sure you want to delete this player? This action cannot be undone." deleteIcon="mdi-delete" canDelete={isAdmin} onConfirm={deletion.confirmDelete} onCancel={deletion.cancelDeleteDialog} onUpdateModelValue={(open) => !open && deletion.cancelDeleteDialog()} />
  </div>;
}

export default PlayersView;

// src/views/PlayersView.vue
<template>
  <v-container fluid class="pa-4">
    <div class="d-flex align-center flex-wrap ga-3 mb-4">
      <h1>
        <v-icon class="mr-2">mdi-account-group</v-icon>
        Players
      </h1>
      <v-spacer />
      <v-btn v-if="auth.isAdmin" variant="elevated" color="primary" prepend-icon="mdi-plus" @click="openCreateNew">
        Add Player
      </v-btn>
    </div>

    <FilterPanel
      v-model:searchName="searchName"
      v-model:searchRace="searchRace"
      v-model:selectedSeasonFilter="selectedSeasonFilter"
      v-model:rangeValues="rangeValues"
      :seasons="seasons"
      :extra-active="selectedFlags.length"
      @reset="clearFilters"
    >
      <template #after>
        <v-col cols="12" md="3">
          <v-select
            v-model="selectedFlags"
            :items="flagOptions"
            placeholder="Show only"
            aria-label="Show only"
            prepend-inner-icon="mdi-alert-outline"
            multiple
            chips
            closable-chips
            clearable
            variant="outlined"
            density="compact"
            hide-details
          />
        </v-col>
      </template>
      <template #summary>
        <span class="text-body-2 text-medium-emphasis">{{ countLabel }}</span>
      </template>
    </FilterPanel>

    <v-card elevation="1">
      <v-alert v-if="errorMessage" type="error" variant="tonal" class="ma-4">{{ errorMessage }}</v-alert>
      <v-data-table
        v-else
        :headers="tableHeader"
        :items="filteredRows"
        item-value="key"
        :loading="isLoading"
        v-model:sort-by="sortBy"
        must-sort
        :items-per-page="25"
        no-data-text="No players match these filters"
        class="tabular"
        hover
      >
        <template #loading>
          <v-skeleton-loader type="table-row@10" />
        </template>

        <template #[`header.best_mmr`]="{ column, isSorted, getSortIcon }">
          <W3CMmr
            :suffix="currentW3CSeason ? ` (S${currentW3CSeason})` : ''"
            :sort-icon="isSorted(column) ? getSortIcon(column) : null"
          />
        </template>

        <template #item="{ item }">
          <tr class="text-no-wrap" :class="{ 'player-row': item.id != null }" @click="go(item)">
            <td>
              <PlayerName v-if="item.id != null" :player="item">
                <template v-if="!hasW3CStatsTwoSeasons(item, currentW3CSeason, item.race)">
                  <v-tooltip>
                    <template #activator="{ props }">
                      <v-icon v-bind="props" small color="error">mdi-alert</v-icon>
                    </template>
                    <span>No W3C stats found for {{ item.race }}</span>
                  </v-tooltip>
                </template>
                <template v-else-if="hasLowGamesTwoSeasons(item, currentW3CSeason, item.race)">
                  <v-tooltip>
                    <template #activator="{ props }">
                      <v-icon v-bind="props" small color="warning">mdi-alert</v-icon>
                    </template>
                    <span>Less than 20 games ({{ getW3CGamesCount(item, currentW3CSeason, item.race) }} games) for {{ item.race }}</span>
                  </v-tooltip>
                </template>
              </PlayerName>
              <span v-else class="text-medium-emphasis">{{ item.name }}</span>
            </td>
            <td class="d-none d-md-table-cell">
              <RaceMmrChips v-if="item.id != null" :player="item" :w3cSeason="currentW3CSeason" :max="2" />
            </td>
            <td class="text-end">{{ item.rating ?? '—' }}</td>
            <td class="text-end">
              <template v-if="item.career">
                {{ item.career.series_won }}-{{ item.career.series_lost }}
                <span class="text-medium-emphasis ml-1">{{ item.career.series_winrate }}%</span>
              </template>
              <template v-else>—</template>
            </td>
            <td class="text-end d-none d-md-table-cell">
              <template v-if="item.career">
                {{ item.career.games_won }}-{{ item.career.games_lost }}
                <span class="text-medium-emphasis ml-1">{{ item.career.games_winrate }}%</span>
              </template>
              <template v-else>—</template>
            </td>
            <td class="text-end d-none d-md-table-cell">{{ item.seasons_played ?? '—' }}</td>
            <td class="d-none d-md-table-cell">
              <div v-if="item.signup_seasons && item.signup_seasons.length > 0">
                <template v-for="s in item.signup_seasons.slice().sort((a,b) => b.id - a.id).slice(0,1)" :key="s.id">
                  <v-chip small class="ma-1 event-chip" :title="s.name">{{ s.name }}</v-chip>
                </template>
                <v-menu v-if="item.signup_seasons.length > 1" offset-y>
                  <template #activator="{ props }">
                    <v-chip v-bind="props" class="ma-1" small @click.stop>+{{ item.signup_seasons.length - 1 }}</v-chip>
                  </template>
                  <v-list>
                    <v-list-item v-for="s in item.signup_seasons.slice().sort((a,b) => b.id - a.id)" :key="s.id">
                      <v-list-item-title>{{ s.name }}</v-list-item-title>
                    </v-list-item>
                  </v-list>
                </v-menu>
              </div>
              <div v-else>—</div>
            </td>
            <td v-if="auth.isAdmin" @click.stop>
              <RowActions :actions="rowActions(item)" />
            </td>
          </tr>
        </template>
      </v-data-table>
    </v-card>

    <!-- Add New Player Dialog -->
    <v-dialog v-model="showNewPlayerModal" max-width="800">
      <v-card>
        <v-card-title class="bg-primary">
          <v-icon class="mr-2">mdi-account-plus</v-icon>
          Add New Player
        </v-card-title>

        <v-alert
          v-if="creationError"
          type="error"
          variant="tonal"
          border="start"
          border-color="error"
          class="mx-4 my-2"
          closable
          @click:close="creationError = null"
        >
          {{ creationError }}
        </v-alert>

        <v-card-text class="pt-4">
          <v-row>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="newPlayer.name"
                label="Player Name"
                variant="outlined"
                prepend-inner-icon="mdi-account"
                density="comfortable"
              ></v-text-field>
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="newPlayer.battleTag"
                label="BattleTag"
                variant="outlined"
                prepend-inner-icon="mdi-shield-account"
                density="comfortable"
              ></v-text-field>
            </v-col>
          </v-row>
          <v-row>
            <v-col cols="12" md="6">
              <CountrySelect v-model="newPlayer.country" />
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="newPlayer.discordTag"
                label="Discord Tag"
                variant="outlined"
                prepend-inner-icon="$discord"
                density="comfortable"
              ></v-text-field>
            </v-col>
          </v-row>
          <v-row>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="newPlayer.discordId"
                label="Discord ID"
                hint="Numeric Discord user ID (required)"
                variant="outlined"
                prepend-inner-icon="mdi-identifier"
                density="comfortable"
              ></v-text-field>
            </v-col>
          </v-row>
          <v-row>
            <v-col cols="12" md="6">
              <RaceSelect v-model="newPlayer.race" />
            </v-col>
          </v-row>
        </v-card-text>

        <v-card-actions>
          <v-spacer />
          <v-btn @click="cancelAddNewPlayer">Cancel</v-btn>
          <v-btn
            v-if="auth.isAdmin"
            @click="createNewPlayer"
            color="primary"
            variant="elevated"
            prepend-icon="mdi-plus"
            :loading="isCreating"
            :disabled="isCreating"
          >
            Add Player
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <EditPlayerDialog
      ref="editPlayerDialog"
      :can-save="auth.isAdmin"
      :refresh="load"
    />

    <SeasonSignupDialog ref="signupDialog" @added="load" />

    <CareerStatsDialog v-if="auth.isAdmin" ref="careerDialog" :players="players" @changed="load" />

    <ConfirmDeleteDialog
      v-model="showDeleteDialog"
      message="Are you sure you want to delete this player? This action cannot be undone."
      delete-icon="mdi-delete"
      :can-delete="auth.isAdmin"
      @confirm="confirmDelete"
      @cancel="cancelDeleteDialog"
    />
  </v-container>
</template>
<script setup>
import RowActions from '@/components/RowActions.vue';
import { useAuthStore, usePlayerStore, useSeasonStore } from '@/stores';
import { usePlayerCareerStatsStore } from '@/stores/player_career_stats.store';
import { storeToRefs } from 'pinia';
import { onMounted, ref, computed, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { findSeason } from '@/helpers/season-slug.mjs';
import EditPlayerDialog from '@/components/EditPlayerDialog.vue';
import SeasonSignupDialog from '@/components/SeasonSignupDialog.vue';
import CareerStatsDialog from '@/components/CareerStatsDialog.vue';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';
import FilterPanel from '@/components/FilterPanel.vue';
import { useDeleteDialog } from '@/helpers/delete-dialog';
import { resolveCurrentW3CSeason } from '@/helpers/current-season';
import {
  getAllRaceStats,
  getW3CGamesCount,
  hasW3CStatsTwoSeasons,
  hasLowGamesTwoSeasons
} from '@/helpers/w3c-stats';
import RaceMmrChips from '@/components/RaceMmrChips.vue';
import W3CMmr from '@/components/W3CMmr.vue';
import { matchesPlayerSearch, filterByMmrRange, playerPath, playersWithCareers } from '@/helpers/players';
import { useColumns } from '@/helpers/columns';

const editPlayerDialog = ref(null);
const signupDialog = ref(null);
const careerDialog = ref(null);
const isLoading = ref(false);
const isCreating = ref(false);
const errorMessage = ref(null);
const creationError = ref(null);
const showNewPlayerModal = ref(false);
const newPlayer = ref({
  name: '',
  battleTag: '',
  country: '',
  discordTag: '',
  discordId: '',
  race: '',
});
const router = useRouter();
const route = useRoute();
const playerStore = usePlayerStore();
const careerStore = usePlayerCareerStatsStore();
const seasonStore = useSeasonStore();
const auth = useAuthStore();
const { players } = storeToRefs(playerStore);
const { stats: careers } = storeToRefs(careerStore);
const { seasons } = storeToRefs(seasonStore);
const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

// Filters
const searchName = ref('');
const searchRace = ref(null);
const selectedSeasonFilter = ref(null);
const rangeValues = ref([0, 3000]);
const selectedFlags = ref([]);

// Current W3C season number (for stats fallback logic)
const currentW3CSeason = ref(null);

// The best raced MMR, so the range filter matches a player on any race they play
const bestMmr = (player) => Math.max(0, ...getAllRaceStats(player, currentW3CSeason.value)
  .filter((stat) => (stat.games || 0) > 0)
  .map((stat) => stat.mmr || 0));

const FLAGS = {
  no_stats: row => row.id != null && !hasW3CStatsTwoSeasons(row, currentW3CSeason.value, row.race),
  low_games: row => row.id != null && hasLowGamesTwoSeasons(row, currentW3CSeason.value, row.race),
  unlinked: row => row.id == null && row.career?.id != null,
};
const flagOptions = computed(() => [
  { title: 'No W3C stats', value: 'no_stats' },
  { title: 'Less than 20 games', value: 'low_games' },
  ...(auth.isAdmin ? [{ title: 'Unlinked players', value: 'unlinked' }] : []),
]);

const rows = computed(() => playersWithCareers(players.value || [], careers.value || [])
  .map(row => ({ ...row, best_mmr: row.id != null ? bestMmr(row) || null : null })));

// Career rows no player claims stay out until an admin asks for them to link them
const baseRows = computed(() => selectedFlags.value.includes('unlinked')
  ? rows.value
  : rows.value.filter(row => row.id != null));

const filteredRows = computed(() => {
  let list = baseRows.value;
  if (searchName.value && searchName.value.trim().length > 0) {
    list = list.filter(row => matchesPlayerSearch(row, searchName.value));
  }
  if (searchRace.value) {
    list = list.filter(row => row.race === searchRace.value);
  }
  if (selectedSeasonFilter.value) {
    list = list.filter(row => (row.signup_seasons || []).some(s => s.id === selectedSeasonFilter.value));
  }
  list = filterByMmrRange(list, rangeValues.value, row => row.best_mmr ?? 0);
  if (selectedFlags.value.length > 0) {
    list = list.filter(row => selectedFlags.value.some(flag => FLAGS[flag](row)));
  }
  return list;
});

const countLabel = computed(() => filteredRows.value.length === baseRows.value.length
  ? `${baseRows.value.length} players`
  : `${filteredRows.value.length} of ${baseRows.value.length} players`);

// Rows without career totals sort last, because Vuetify orders empty values first on ascending
const sortBy = ref([{ key: 'rating', order: 'desc' }]);

const allTableHeader = computed(() => [
  { title: 'Name', key: 'name' },
  { mobile: false, title: 'W3C MMR', key: 'best_mmr' },
  { title: 'Rating', key: 'rating', align: 'end' },
  { title: 'Series', key: 'series_winrate', align: 'end' },
  { mobile: false, title: 'Games', key: 'games_winrate', align: 'end' },
  { mobile: false, title: 'Seasons', key: 'seasons_played', align: 'end' },
  { mobile: false, title: 'Events', key: 'events', sortable: false },
  ...(auth.isAdmin ? [{ title: '', key: 'actions', align: 'end', sortable: false }] : []),
]);
const tableHeader = useColumns(allTableHeader);

// A history row has no player page to open
const go = (row) => {
  if (row.id != null) router.push(playerPath(row));
};

const openCareer = (row) => careerDialog.value.open(row.career);
const rowActions = (row) => row.id == null
  ? [{ icon: 'mdi-history', label: 'Career stats', onClick: () => openCareer(row) }]
  : [
    { icon: 'mdi-pencil', label: 'Edit', onClick: () => editPlayerDialog.value.open(row) },
    { icon: 'mdi-account-check', label: 'Add to season', onClick: () => signupDialog.value.open({ player: row }) },
    { icon: syncIcon(row.id), label: syncLabel(row.id), color: syncColor(row.id), loading: syncState(row.id) === 'loading', onClick: () => syncW3CPlayer(row.id) },
    ...(row.career?.id != null ? [{ icon: 'mdi-history', label: 'Career stats', onClick: () => openCareer(row) }] : []),
    { icon: 'mdi-delete', label: 'Delete', color: 'error', onClick: () => openDeleteDialog(row.id, removePlayer) },
  ];

const load = async () => {
  isLoading.value = true;
  errorMessage.value = null;
  try {
    const [, , w3cSeason] = await Promise.all([
      playerStore.fetchPlayers(), careerStore.fetchAll(), resolveCurrentW3CSeason(),
    ]);
    // the season gates every W3C stat on the table, so it lands before the rows do
    currentW3CSeason.value = w3cSeason;
  } catch (error) {
    console.error('Failed to load players:', error);
    errorMessage.value = 'Failed to load players. Please try again later.';
  } finally {
    isLoading.value = false;
  }
};

const clearFilters = () => {
  searchName.value = '';
  searchRace.value = null;
  selectedSeasonFilter.value = null;
  rangeValues.value = [0, 3000];
  selectedFlags.value = [];
};

// ?season= drives the events filter both ways; no key shows every season
const readSeasonQuery = () => { selectedSeasonFilter.value = findSeason(seasons.value, route.query.season)?.id ?? null; };
watch(() => route.query.season, readSeasonQuery);
watch(selectedSeasonFilter, (id) => {
  const season = id ? seasonStore.slugOf(id) : undefined;
  if (route.query.season !== season) router.replace({ query: { ...route.query, season } });
});

onMounted(async () => {
  // Seasons feed the events filter
  try {
    await seasonStore.fetchSeasons();
  } catch (err) {
    console.error('Failed to fetch seasons:', err);
  }
  readSeasonQuery();
  await load();
});

// per-player sync status map: { [playerId]: { state: 'loading'|'success'|'error', message?: string } }
const perPlayerSyncStatus = ref({});

const openCreateNew = () => {
  newPlayer.value = {
    name: '',
    battleTag: '',
    country: '',
    discordTag: '',
    discordId: '',
    mmr: 0,
    race: '',
  };
  creationError.value = '';
  showNewPlayerModal.value = true;
};

const createNewPlayer = async () => {
  creationError.value = '';
  isCreating.value = true;
  try {
    // send newPlayer directly — fields use backend schema names
    await playerStore.createPlayer(newPlayer.value);
    await load();
    cancelAddNewPlayer();
  } catch (error) {
    console.error('Error creating user:', error);
    creationError.value = 'Error creating user: ' + error.message;
  } finally {
    isCreating.value = false;
  }
};

const removePlayer = async (playerId) => {
  try {
    await playerStore.deletePlayer(playerId);
    await load();
  } catch (error) {
    console.error('Error deleting player:', error);
  }
};

const syncState = (playerId) => perPlayerSyncStatus.value[playerId]?.state;
const syncIcon = (playerId) => ({ success: 'mdi-check-circle', error: 'mdi-alert-circle' }[syncState(playerId)] ?? 'mdi-sync');
const syncLabel = (playerId) => ({ success: 'Synced', error: 'Retry Sync' }[syncState(playerId)] ?? 'Sync W3C');
const syncColor = (playerId) => ({ success: 'success', error: 'error' }[syncState(playerId)]);

const syncW3CPlayer = async (playerId) => {
  if (!playerId) return;
  perPlayerSyncStatus.value = { ...perPlayerSyncStatus.value, [playerId]: { state: 'loading' } };
  try {
    await playerStore.syncW3CPlayer(playerId);
    perPlayerSyncStatus.value = { ...perPlayerSyncStatus.value, [playerId]: { state: 'success' } };
  } catch (error) {
    console.error('Error syncing player:', playerId, error);
    perPlayerSyncStatus.value = { ...perPlayerSyncStatus.value, [playerId]: { state: 'error', message: error.message } };
  }
};

const cancelAddNewPlayer = () => {
  showNewPlayerModal.value = false;
  newPlayer.value = {
    name: '',
    battleTag: '',
    country: '',
    discordTag: '',
    discordId: '',
    race: '',
  };
};
</script>

<style scoped>
.player-row {
  cursor: pointer;
}
/* Fixed-width digits, so ratings and records line up down a column */
.tabular :deep(td) {
  font-variant-numeric: tabular-nums;
}
/* Eight columns fit a 1440px screen with the admin menu; phones keep base.css padding */
@media (min-width: 960px) {
  .tabular :deep(.v-table__wrapper > table > tbody > tr > td),
  .tabular :deep(.v-table__wrapper > table > thead > tr > th) {
    padding-inline: 12px;
  }
}
/* A long event name ends in an ellipsis rather than push the table off the card */
.event-chip {
  max-width: 120px;
}
/* Vuetify lays the chip content out as a flex row, where text-overflow does nothing */
.event-chip :deep(.v-chip__content) {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
