// next/src/app/(app)/profile/ProfileView.tsx
"use client";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { DiscordJoinCard } from "@/components/DiscordJoinCard";
import { profileState } from "@/helpers/profile.mjs";
import { playerPath } from "@/helpers/players.mjs";
import { useAuth } from "@/stores";
import { PublicSignupView } from "../signup/PublicSignupView";

/** The profile body a signed-in viewer sees: the join card, the signup form, or his player page. */
export function ProfileView() {
  const router = useRouter();
  const { me } = useAuth();
  const state = profileState(me);
  // a member with a player row reads his profile at his own player page
  useEffect(() => {
    if (state === "dashboard") router.replace(playerPath(me!.user));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);

  if (state === "guest") {
    return (
      <div className="flex min-h-[80vh] items-center justify-center p-4">
        <DiscordJoinCard />
      </div>
    );
  }
  return state === "signup" ? <PublicSignupView /> : null;
}

export default ProfileView;

// src/views/ProfileView.vue
<script setup>
import { computed, watch } from 'vue';
import { useRouter } from 'vue-router';
import { storeToRefs } from 'pinia';

import { useAuthStore } from '@/stores';
import { profileState } from '@/helpers/profile.mjs';
import { playerPath } from '@/helpers/players';
import DiscordJoinCard from '@/components/DiscordJoinCard.vue';
import PublicSignupView from './PublicSignupView.vue';

const router = useRouter();
const { me } = storeToRefs(useAuthStore());
const state = computed(() => profileState(me.value));
// a member with a player row reads his profile at his own player page
watch(state, (now) => { if (now === 'dashboard') router.replace(playerPath(me.value.user)); }, { immediate: true });
</script>

<template>
    <v-container v-if="state === 'guest'" fluid class="pa-4 d-flex align-center justify-center" style="min-height: 80vh;">
        <DiscordJoinCard />
    </v-container>
    <PublicSignupView v-else-if="state === 'signup'" />
</template>
