// next/src/app/(app)/random-stats/RandomStatsView.tsx
"use client";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { InputGroup, InputGroupAddon, InputGroupInput } from "@/components/ui/input-group";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageHeader } from "@/components/PageHeader";
import { RaceIcon } from "@/components/RaceIcon";
import { StatusAlert } from "@/components/StatusAlert";
import { raceWrapper } from "@/helpers/races.js";

const W3C_MATCH_API = "https://website-backend.w3champions.com/api/matches/search";

// W3C race codes: 0 = Random picked, 1 = Human, 2 = Orc, 4 = Night Elf, 8 = Undead, 16 and 32 = Random
const W3C_RACE_NAMES: Record<string | number, string> = {
  1: "Human",
  2: "Orc",
  4: "Night Elf",
  8: "Undead",
  16: "Random",
  32: "Random",
  // String variants returned by some API versions
  "HUMAN": "Human",
  "ORC": "Orc",
  "NIGHTELF": "Night Elf",
  "NIGHT_ELF": "Night Elf",
  "UNDEAD": "Undead",
  "RANDOM": "Random",
};

// Map from display name to RaceIcon identifier
const raceIdMap: Record<string, string> = Object.fromEntries(raceWrapper.races.map((race: { id: string; name: string }) => [race.name, race.id]));

// Seasons to offer — show 1 through 35
const seasonOptions = Array.from({ length: 35 }, (_, i) => 35 - i);

type Matchup = { wins: number; losses: number };
type RaceRow = { wins: number; losses: number; matchups: Record<string, Matchup> };
type Breakdown = Record<string, RaceRow>;
type W3cPlayer = { battleTag?: string; race?: number | string; rndRace?: number | null };
type W3cTeam = { won?: boolean; players?: W3cPlayer[] };
type W3cMatch = { gameMode?: number; teams?: W3cTeam[] };

function raceName(raceValue: number | string | undefined) {
  return raceValue == null ? "Random" : W3C_RACE_NAMES[raceValue] ?? "Random";
}

// Sort matchups by total games descending
function sortedMatchups(matchups: Record<string, Matchup>) {
  return Object.entries(matchups).sort(([, a], [, b]) => (b.wins + b.losses) - (a.wins + a.losses));
}

async function fetchPage(tag: string, season: number, offset: number) {
  const params = new URLSearchParams({
    playerId: tag,
    gateway: "20",
    offset: String(offset),
    pageSize: "50",
    season: String(season),
    playerIncludeRandom: "true",
    opponentIncludeRandom: "true",
  });
  const res = await fetch(`${W3C_MATCH_API}?${params}`);
  if (!res.ok) throw new Error(`W3C API responded with ${res.status} ${res.statusText}`);
  return res.json() as Promise<{ matches?: W3cMatch[]; count?: number; total?: number }>;
}

function processMatches(matches: W3cMatch[], tagLower: string, breakdown: Breakdown) {
  for (const match of matches) {
    if (!Array.isArray(match.teams) || match.teams.length < 2) continue;

    // Only 1v1 solo games
    if (match.gameMode !== 1) continue;

    let playerTeam: W3cTeam | null = null;
    let opponentTeam: W3cTeam | null = null;

    for (const team of match.teams) {
      const hasPlayer = team.players?.some((p) =>
        p.battleTag?.toLowerCase() === tagLower ||
        p.battleTag?.toLowerCase().startsWith(tagLower.split("#")[0].toLowerCase() + "#")
      );
      if (hasPlayer) playerTeam = team;
      else opponentTeam = team;
    }

    if (!playerTeam || !opponentTeam) continue;

    const playerEntry = playerTeam.players?.[0];
    const opponentEntry = opponentTeam.players?.[0];
    if (!playerEntry || !opponentEntry) continue;

    // Only process Random games (race === 0)
    if (playerEntry.race !== 0) continue;

    // Use rndRace (the actual drawn race) as the grouping key.
    // rndRace may be 0/null when the API doesn't report the drawn race (common for losses).
    const drawnRace = (playerEntry.rndRace != null && playerEntry.rndRace !== 0)
      ? raceName(playerEntry.rndRace)
      : "Random=?";
    const oppRace = raceName(opponentEntry.race);
    const won = playerTeam.won === true;

    if (!breakdown[drawnRace]) {
      breakdown[drawnRace] = { wins: 0, losses: 0, matchups: {} };
    }
    if (!breakdown[drawnRace].matchups[oppRace]) {
      breakdown[drawnRace].matchups[oppRace] = { wins: 0, losses: 0 };
    }

    breakdown[drawnRace].wins += won ? 1 : 0;
    breakdown[drawnRace].losses += won ? 0 : 1;
    breakdown[drawnRace].matchups[oppRace].wins += won ? 1 : 0;
    breakdown[drawnRace].matchups[oppRace].losses += won ? 0 : 1;
  }
}

/** The drawn race a Random player rolled, against the race he met, read from the W3Champions match API. */
export function RandomStatsView() {
  const [battleTag, setBattleTag] = useState("");
  const [selectedSeasons, setSelectedSeasons] = useState<number[]>([25, 26]);
  const [isLoading, setIsLoading] = useState(false);
  const [loadingMessage, setLoadingMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [hasSearched, setHasSearched] = useState(false);
  const [resolvedTag, setResolvedTag] = useState("");

  // raceBreakdown: { 'Human': { wins, losses, matchups: { 'Orc': { wins, losses }, ... } }, ... }
  const [raceBreakdown, setRaceBreakdown] = useState<Breakdown | null>(null);

  const canSearch = battleTag.trim().length > 0 && selectedSeasons.length > 0;
  const rows = raceBreakdown ? Object.entries(raceBreakdown) : [];
  const hasResults = rows.length > 0;
  const totalGames = rows.reduce((s, [, r]) => s + r.wins + r.losses, 0);
  const totalWins = rows.reduce((s, [, r]) => s + r.wins, 0);
  const totalLosses = totalGames - totalWins;
  const overallWinRate = totalGames === 0 ? 0 : Math.round(totalWins / totalGames * 100);

  const loadStats = async () => {
    if (!canSearch) return;

    setErrorMessage(null);
    setRaceBreakdown(null);
    setHasSearched(true);
    setIsLoading(true);

    const tag = battleTag.trim();
    setResolvedTag(tag);
    const tagLower = tag.toLowerCase();
    const breakdown: Breakdown = {};

    try {
      for (const season of [...selectedSeasons].sort((a, b) => a - b)) {
        setLoadingMessage(`Fetching season ${season} — page 1...`);

        const firstPage = await fetchPage(tag, season, 0);
        const total = firstPage.count ?? firstPage.total ?? (firstPage.matches?.length ?? 0);
        processMatches(firstPage.matches ?? [], tagLower, breakdown);

        const totalPages = Math.ceil(total / 50);
        for (let page = 1; page < totalPages; page++) {
          setLoadingMessage(`Fetching season ${season} — page ${page + 1} of ${totalPages}...`);
          const data = await fetchPage(tag, season, page * 50);
          processMatches(data.matches ?? [], tagLower, breakdown);
        }
      }

      // Sort races by total games descending
      setRaceBreakdown(Object.fromEntries(
        Object.entries(breakdown).sort(([, a], [, b]) => (b.wins + b.losses) - (a.wins + a.losses))
      ));
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      if (message.includes("Failed to fetch") || message.includes("NetworkError")) {
        setErrorMessage("Network error — the W3C Champions API may be unreachable or blocking cross-origin requests.");
      } else {
        setErrorMessage(`Failed to load stats: ${message}`);
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="mx-auto max-w-[960px] p-6">
      <PageHeader
        title={<><Icon name="mdi-dice-multiple" className="mr-3 text-primary" />Random Stats Helper</>}
        lead="Breakdown of drawn race vs opponent race for Random games only"
      />

      {/* Search form */}
      <Card className="card mb-6 gap-0 py-0">
        <CardHeader className="bg-primary p-4">
          <CardTitle className="text-on-primary">Player &amp; seasons</CardTitle>
        </CardHeader>
        <CardContent className="p-4">
          <div className="grid items-start gap-4 md:grid-cols-12">
            <Field className="md:col-span-5" label="BattleTag  (e.g. Player#1234)" hint="Exact BattleTag as shown on W3Champions" htmlFor="battle-tag">
              <InputGroup>
                <InputGroupAddon>
                  <Icon name="mdi-account" />
                </InputGroupAddon>
                <InputGroupInput
                  id="battle-tag"
                  value={battleTag}
                  onChange={(e) => setBattleTag(e.target.value)}
                  onKeyUp={(e) => { if (e.key === "Enter") loadStats(); }}
                />
              </InputGroup>
            </Field>

            <Field className="md:col-span-5" label="W3C seasons" hint="Select one or more seasons to analyse" htmlFor="w3c-seasons">
              {/* one open list, so a season leaves the choice the same way it joined it */}
              <Select multiple value={selectedSeasons} onValueChange={setSelectedSeasons}>
                <SelectTrigger id="w3c-seasons" className="h-auto min-h-8 w-full py-1.5">
                  <Icon name="mdi-calendar-range" className="text-muted-foreground" />
                  <SelectValue>
                    {(seasons: number[]) => (
                      <span className="flex flex-wrap gap-1">
                        {seasons.map((season) => <Badge key={season} variant="outline" className="tnum">{season}</Badge>)}
                      </span>
                    )}
                  </SelectValue>
                </SelectTrigger>
                <SelectContent>
                  {seasonOptions.map((season) => <SelectItem key={season} value={season}>{season}</SelectItem>)}
                </SelectContent>
              </Select>
            </Field>

            <div className="md:col-span-2 md:pt-6">
              <Button className="w-full" disabled={!canSearch || isLoading} onClick={loadStats}>
                <Icon name={isLoading ? "mdi-loading" : "mdi-chart-bar"} className={isLoading ? "mr-2 animate-spin" : "mr-2"} />
                Analyse
              </Button>
            </div>
          </div>

          <StatusAlert modelValue={errorMessage} className="mt-4" onClose={() => setErrorMessage(null)} />
        </CardContent>
      </Card>

      {/* Loading progress */}
      {isLoading ? (
        <Card className="card mb-6">
          <CardContent className="py-4">
            <div className="mb-3 text-sm">{loadingMessage}</div>
            <Progress
              value={null}
              className="[&_[data-slot=progress-indicator]]:w-full [&_[data-slot=progress-indicator]]:animate-pulse [&_[data-slot=progress-track]]:h-1.5"
            />
          </CardContent>
        </Card>
      ) : null}

      {/* Overall summary */}
      {hasResults && !isLoading ? (
        <Card className="card mb-6 gap-0 py-0">
          <CardHeader className="bg-primary p-4">
            <CardTitle className="text-on-primary">
              Summary — {resolvedTag}
              <span className="ml-2 text-sm opacity-80">(seasons {selectedSeasons.join(", ")})</span>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-4">
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <div className="text-center">
                <div className="text-2xl font-bold tnum">{totalGames}</div>
                <div className="text-xs text-muted-foreground">Total games</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold tnum text-win">{totalWins}</div>
                <div className="text-xs text-muted-foreground">Wins</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold tnum text-loss">{totalLosses}</div>
                <div className="text-xs text-muted-foreground">Losses</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold tnum">{overallWinRate}%</div>
                <div className="text-xs text-muted-foreground">Win rate</div>
              </div>
            </div>
          </CardContent>
        </Card>
      ) : null}

      {/* Per-race breakdown cards */}
      {hasResults && !isLoading ? rows.map(([raceName, data]) => (
        <Card key={raceName} className="card mb-5 gap-0 py-0">
          <CardHeader className="bg-primary p-4">
            <CardTitle className="flex flex-wrap items-center gap-1 text-on-primary">
              <RaceIcon raceIdentifier={raceIdMap[raceName]} />
              <span className="mr-2">Playing as {raceName}</span>
              <span className="flex-1" />
              {/* outlined, not tonal: a tonal wash over the bronze band leaves its own text at 4.02:1 */}
              <Badge variant="outline" className="mr-2 border-on-primary text-on-primary">
                {data.wins + data.losses} games
              </Badge>
              <Badge variant="outline" className="border-on-primary text-on-primary">
                {Math.round(data.wins / (data.wins + data.losses) * 100)}% WR
              </Badge>
            </CardTitle>
          </CardHeader>

          <Table className="table-scroll">
            <TableHeader>
              <TableRow>
                <TableHead className="text-left">Opponent race</TableHead>
                <TableHead className="text-right text-win">Wins</TableHead>
                <TableHead className="text-right text-loss">Losses</TableHead>
                <TableHead className="text-right">Total</TableHead>
                <TableHead className="min-w-[90px] text-right">Win %</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {sortedMatchups(data.matchups).map(([oppRace, matchup]) => (
                <TableRow key={oppRace}>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <RaceIcon raceIdentifier={raceIdMap[oppRace]} />
                      <span>{oppRace}</span>
                    </div>
                  </TableCell>
                  <TableCell className="text-right font-medium tnum text-win">{matchup.wins}</TableCell>
                  <TableCell className="text-right font-medium tnum text-loss">{matchup.losses}</TableCell>
                  <TableCell className="text-right tnum">{matchup.wins + matchup.losses}</TableCell>
                  <TableCell className="text-right">
                    <Badge variant="secondary" className="tnum">
                      {Math.round(matchup.wins / (matchup.wins + matchup.losses) * 100)}%
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
            {/* Row totals */}
            <TableFooter>
              <TableRow className="border-t-2">
                <TableCell className="font-bold">Total</TableCell>
                <TableCell className="text-right font-bold tnum text-win">{data.wins}</TableCell>
                <TableCell className="text-right font-bold tnum text-loss">{data.losses}</TableCell>
                <TableCell className="text-right font-bold tnum">{data.wins + data.losses}</TableCell>
                <TableCell className="text-right">
                  <Badge className="tnum">
                    {Math.round(data.wins / (data.wins + data.losses) * 100)}%
                  </Badge>
                </TableCell>
              </TableRow>
            </TableFooter>
          </Table>
        </Card>
      )) : null}

      {/* No data */}
      {hasSearched && !isLoading && !hasResults ? (
        <StatusAlert
          type="info"
          modelValue={`No Random games found for ${resolvedTag} in the selected seasons. Make sure the BattleTag is correct and the player has Random games in those seasons.`}
        />
      ) : null}
    </div>
  );
}

export default RandomStatsView;

// src/views/RandomStatsView.vue
<template>
  <v-container fluid style="max-width: 960px; margin: 0 auto;" class="pa-6">

    <!-- Header -->
    <div class="d-flex align-center mb-6">
      <v-icon size="x-large" color="primary" class="mr-3">mdi-dice-multiple</v-icon>
      <div>
        <div class="text-h5 font-weight-bold">Random stats helper</div>
        <div class="text-body-2 text-medium-emphasis">Breakdown of drawn race vs opponent race for Random games only</div>
      </div>
    </div>

    <!-- Search form -->
    <v-card elevation="2" class="mb-6">
      <v-card-title class="bg-primary">Player &amp; seasons</v-card-title>
      <v-card-text class="pt-4">
        <v-row align="start">
          <v-col cols="12" md="5">
            <v-text-field
              v-model="battleTag"
              label="BattleTag  (e.g. Player#1234)"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-account"
              clearable
              hint="Exact BattleTag as shown on W3Champions"
              persistent-hint
              @keyup.enter="loadStats"
            />
          </v-col>
          <v-col cols="12" md="5">
            <v-select
              v-model="selectedSeasons"
              :items="seasonOptions"
              label="W3C seasons"
              variant="outlined"
              density="comfortable"
              multiple
              chips
              closable-chips
              prepend-inner-icon="mdi-calendar-range"
              hint="Select one or more seasons to analyse"
              persistent-hint
            />
          </v-col>
          <v-col cols="12" md="2" class="d-flex align-center" style="padding-top: 4px;">
            <v-btn
              color="primary"
              variant="elevated"
              block
              size="large"
              :loading="isLoading"
              :disabled="!canSearch"
              prepend-icon="mdi-chart-bar"
              @click="loadStats"
            >
              Analyse
            </v-btn>
          </v-col>
        </v-row>

        <v-alert
          v-if="errorMessage"
          type="error"
          variant="tonal"
          class="mt-4"
          closable
          @click:close="errorMessage = null"
        >
          {{ errorMessage }}
        </v-alert>
      </v-card-text>
    </v-card>

    <!-- Loading progress -->
    <v-card v-if="isLoading" elevation="2" class="mb-6">
      <v-card-text class="py-4">
        <div class="text-body-2 mb-3">{{ loadingMessage }}</div>
        <v-progress-linear indeterminate color="primary" rounded height="6" />
      </v-card-text>
    </v-card>

    <!-- Overall summary -->
    <v-card v-if="hasResults && !isLoading" elevation="2" class="mb-6">
      <v-card-title class="bg-primary">
        Summary — {{ resolvedTag }}
        <span class="text-body-2 ml-2 text-on-primary opacity-80">(seasons {{ selectedSeasons.join(', ') }})</span>
      </v-card-title>
      <v-card-text class="pt-4">
        <v-row>
          <v-col cols="6" sm="3" class="text-center">
            <div class="text-h5 font-weight-bold">{{ totalGames }}</div>
            <div class="text-caption text-medium-emphasis">Total games</div>
          </v-col>
          <v-col cols="6" sm="3" class="text-center">
            <div class="text-h5 font-weight-bold text-win">{{ totalWins }}</div>
            <div class="text-caption text-medium-emphasis">Wins</div>
          </v-col>
          <v-col cols="6" sm="3" class="text-center">
            <div class="text-h5 font-weight-bold text-loss">{{ totalLosses }}</div>
            <div class="text-caption text-medium-emphasis">Losses</div>
          </v-col>
          <v-col cols="6" sm="3" class="text-center">
            <div class="text-h5 font-weight-bold">{{ overallWinRate }}%</div>
            <div class="text-caption text-medium-emphasis">Win rate</div>
          </v-col>
        </v-row>
      </v-card-text>
    </v-card>

    <!-- Per-race breakdown cards -->
    <template v-if="hasResults && !isLoading">
      <v-card
        v-for="(data, raceName) in raceBreakdown"
        :key="raceName"
        elevation="2"
        class="mb-5"
      >
        <v-card-title class="bg-primary d-flex align-center flex-wrap ga-1">
          <RaceIcon :raceIdentifier="raceIdMap[raceName]" class="mr-2" />
          <span>Playing as {{ raceName }}</span>
          <v-spacer />
          <!-- outlined, not tonal: a tonal wash over the bronze band leaves its own text at 4.02:1 -->
          <v-chip color="on-primary" variant="outlined" size="small" class="mr-2">
            {{ data.wins + data.losses }} games
          </v-chip>
          <v-chip color="on-primary" variant="outlined" size="small">
            {{ Math.round(data.wins / (data.wins + data.losses) * 100) }}% WR
          </v-chip>
        </v-card-title>

        <v-table density="comfortable">
          <thead>
            <tr>
              <th class="text-left">Opponent race</th>
              <th class="text-right text-win">Wins</th>
              <th class="text-right text-loss">Losses</th>
              <th class="text-right">Total</th>
              <th class="text-right" style="min-width:90px">Win %</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="(matchup, oppRace) in sortedMatchups(data.matchups)"
              :key="oppRace"
            >
              <td>
                <div class="d-flex align-center" style="gap: 8px;">
                  <RaceIcon :raceIdentifier="raceIdMap[oppRace]" />
                  <span>{{ oppRace }}</span>
                </div>
              </td>
              <td class="text-right text-win font-weight-medium">{{ matchup.wins }}</td>
              <td class="text-right text-loss font-weight-medium">{{ matchup.losses }}</td>
              <td class="text-right">{{ matchup.wins + matchup.losses }}</td>
              <td class="text-right">
                <v-chip
                  size="small"
                  variant="tonal"
                >
                  {{ Math.round(matchup.wins / (matchup.wins + matchup.losses) * 100) }}%
                </v-chip>
              </td>
            </tr>
          </tbody>
          <!-- Row totals -->
          <tfoot>
            <tr style="border-top: 2px solid rgba(var(--v-theme-on-surface), 0.12);">
              <td class="font-weight-bold">Total</td>
              <td class="text-right font-weight-bold text-win">{{ data.wins }}</td>
              <td class="text-right font-weight-bold text-loss">{{ data.losses }}</td>
              <td class="text-right font-weight-bold">{{ data.wins + data.losses }}</td>
              <td class="text-right">
                <v-chip size="small">
                  {{ Math.round(data.wins / (data.wins + data.losses) * 100) }}%
                </v-chip>
              </td>
            </tr>
          </tfoot>
        </v-table>
      </v-card>
    </template>

    <!-- No data -->
    <v-alert
      v-if="hasSearched && !isLoading && !hasResults"
      type="info"
      variant="tonal"
    >
      No Random games found for <strong>{{ resolvedTag }}</strong> in the selected seasons.
      Make sure the BattleTag is correct and the player has Random games in those seasons.
    </v-alert>

  </v-container>
</template>

<script setup>
import { ref, computed } from 'vue';
import { raceWrapper } from '@/helpers/races';


const W3C_MATCH_API = 'https://website-backend.w3champions.com/api/matches/search';

// W3C API returns race as a number. Mapping to display name.
// Confirmed from match data (heroes played):
//   0 = Random (selected race), 1 = Human, 2 = Orc, 4 = Night Elf, 8 = Undead, 16/32 = Random
const W3C_RACE_NAMES = {
  1: 'Human',
  2: 'Orc',
  4: 'Night Elf',
  8: 'Undead',
  16: 'Random',
  32: 'Random',
  // String variants returned by some API versions
  'HUMAN': 'Human',
  'ORC': 'Orc',
  'NIGHTELF': 'Night Elf',
  'NIGHT_ELF': 'Night Elf',
  'UNDEAD': 'Undead',
  'RANDOM': 'Random',
};

// Map from display name to RaceIcon identifier
const raceIdMap = Object.fromEntries(raceWrapper.races.map(race => [race.name, race.id]));

// Seasons to offer — show 1 through 35
const seasonOptions = Array.from({ length: 35 }, (_, i) => 35 - i);

// ── State ─────────────────────────────────────────────────────────────────────
const battleTag = ref('');
const selectedSeasons = ref([25, 26]);
const isLoading = ref(false);
const loadingMessage = ref('');
const errorMessage = ref(null);
const hasSearched = ref(false);
const resolvedTag = ref('');

// raceBreakdown: { 'Human': { wins, losses, matchups: { 'Orc': { wins, losses }, ... } }, ... }
const raceBreakdown = ref(null);

// ── Computed ──────────────────────────────────────────────────────────────────
const canSearch = computed(() =>
  battleTag.value?.trim().length > 0 && selectedSeasons.value.length > 0
);

const hasResults = computed(() =>
  raceBreakdown.value && Object.keys(raceBreakdown.value).length > 0
);

const totalGames = computed(() => {
  if (!raceBreakdown.value) return 0;
  return Object.values(raceBreakdown.value).reduce((s, r) => s + r.wins + r.losses, 0);
});

const totalWins = computed(() => {
  if (!raceBreakdown.value) return 0;
  return Object.values(raceBreakdown.value).reduce((s, r) => s + r.wins, 0);
});

const totalLosses = computed(() => totalGames.value - totalWins.value);

const overallWinRate = computed(() =>
  totalGames.value === 0 ? 0 : Math.round(totalWins.value / totalGames.value * 100)
);

// ── Helpers ───────────────────────────────────────────────────────────────────
function raceName(raceValue) {
  return W3C_RACE_NAMES[raceValue] ?? `Random`;
}

// Sort matchups by total games descending
function sortedMatchups(matchups) {
  return Object.fromEntries(
    Object.entries(matchups).sort(([, a], [, b]) => (b.wins + b.losses) - (a.wins + a.losses))
  );
}

// ── API ───────────────────────────────────────────────────────────────────────
async function fetchPage(tag, season, offset) {
  const params = new URLSearchParams({
    playerId: tag,
    gateway: 20,
    offset,
    pageSize: 50,
    season,
    playerIncludeRandom: true,
    opponentIncludeRandom: true,
  });
  const res = await fetch(`${W3C_MATCH_API}?${params}`);
  if (!res.ok) throw new Error(`W3C API responded with ${res.status} ${res.statusText}`);
  return res.json();
}

function processMatches(matches, tagLower, breakdown) {
  for (const match of matches) {
    if (!Array.isArray(match.teams) || match.teams.length < 2) continue;

    // Only 1v1 solo games
    if (match.gameMode !== 1) continue;

    let playerTeam = null;
    let opponentTeam = null;

    for (const team of match.teams) {
      const hasPlayer = team.players?.some(p =>
        p.battleTag?.toLowerCase() === tagLower ||
        p.battleTag?.toLowerCase().startsWith(tagLower.split('#')[0].toLowerCase() + '#')
      );
      if (hasPlayer) playerTeam = team;
      else opponentTeam = team;
    }

    if (!playerTeam || !opponentTeam) continue;

    const playerEntry = playerTeam.players?.[0];
    const opponentEntry = opponentTeam.players?.[0];
    if (!playerEntry || !opponentEntry) continue;

    // Only process Random games (race === 0)
    if (playerEntry.race !== 0) continue;

    // Use rndRace (the actual drawn race) as the grouping key.
    // rndRace may be 0/null when the API doesn't report the drawn race (common for losses).
    const drawnRace = (playerEntry.rndRace != null && playerEntry.rndRace !== 0)
      ? raceName(playerEntry.rndRace)
      : 'Random=?';
    const oppRace = raceName(opponentEntry.race);
    const won = playerTeam.won === true;

    if (!breakdown[drawnRace]) {
      breakdown[drawnRace] = { wins: 0, losses: 0, matchups: {} };
    }
    if (!breakdown[drawnRace].matchups[oppRace]) {
      breakdown[drawnRace].matchups[oppRace] = { wins: 0, losses: 0 };
    }

    breakdown[drawnRace].wins += won ? 1 : 0;
    breakdown[drawnRace].losses += won ? 0 : 1;
    breakdown[drawnRace].matchups[oppRace].wins += won ? 1 : 0;
    breakdown[drawnRace].matchups[oppRace].losses += won ? 0 : 1;
  }
}

// ── Main action ───────────────────────────────────────────────────────────────
async function loadStats() {
  if (!canSearch.value) return;

  errorMessage.value = null;
  raceBreakdown.value = null;
  hasSearched.value = true;
  isLoading.value = true;
  resolvedTag.value = battleTag.value.trim();

  const tag = resolvedTag.value;
  const tagLower = tag.toLowerCase();
  const breakdown = {};

  try {
    for (const season of [...selectedSeasons.value].sort((a, b) => a - b)) {
      loadingMessage.value = `Fetching season ${season} — page 1...`;

      const firstPage = await fetchPage(tag, season, 0);
      const total = firstPage.count ?? firstPage.total ?? (firstPage.matches?.length ?? 0);
      processMatches(firstPage.matches ?? [], tagLower, breakdown);

      const totalPages = Math.ceil(total / 50);
      for (let page = 1; page < totalPages; page++) {
        loadingMessage.value = `Fetching season ${season} — page ${page + 1} of ${totalPages}...`;
        const data = await fetchPage(tag, season, page * 50);
        processMatches(data.matches ?? [], tagLower, breakdown);
      }
    }

    // Sort races by total games descending
    raceBreakdown.value = Object.fromEntries(
      Object.entries(breakdown).sort(([, a], [, b]) => (b.wins + b.losses) - (a.wins + a.losses))
    );
  } catch (err) {
    if (err.message.includes('Failed to fetch') || err.message.includes('NetworkError')) {
      errorMessage.value = 'Network error — the W3C Champions API may be unreachable or blocking cross-origin requests.';
    } else {
      errorMessage.value = `Failed to load stats: ${err.message}`;
    }
  } finally {
    isLoading.value = false;
  }
}
</script>
