// next/src/app/(app)/seasons/[id]/assign/SeasonTeamAssignView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import type { SortingState } from "@tanstack/react-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { DataTable } from "@/components/ui/DataTable";
import { Icon } from "@/components/ui/Icon";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { TapTooltip } from "@/components/ui/TapTooltip";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { EditPlayerDialog, type EditPlayerDialogHandle } from "@/components/EditPlayerDialog";
import { FilterPanel } from "@/components/FilterPanel";
import { PlayerName } from "@/components/PlayerName";
import { RaceIcon } from "@/components/RaceIcon";
import { SeasonSignupDialog, type SeasonSignupDialogHandle } from "@/components/SeasonSignupDialog";
import { StatusAlert } from "@/components/StatusAlert";
import { SyncProgress } from "@/components/SyncProgress";
import { W3CIcon } from "@/components/W3CIcon";
import { W3CMmr } from "@/components/W3CMmr";
import { W3CSyncResultDialog, type SyncEntry } from "@/components/W3CSyncResultDialog";
import { useDeleteDialog } from "@/hooks/delete-dialog";
import { PanelLinksContext } from "@/hooks/player-panel";
import { resolveCurrentW3CSeason } from "@/helpers/current-season";
import { draftOrder } from "@/helpers/draft.mjs";
import { filterByMmrRange, matchesPlayerSearch } from "@/helpers/players.mjs";
import { raceWrapper } from "@/helpers/races";
import { getW3CGamesCount, getW3CMMR, hasLowGamesTwoSeasons, hasW3CStatsTwoSeasons, syncedAgo, syncedAt } from "@/helpers/w3c-stats";
import { useAuth, useLadderStore, useSeason, useTeamStore } from "@/stores";

type Row = Record<string, any>;
// { state: 'idle'|'loading'|'success'|'error', message?: string }
type SyncStatus = { state: string; message?: string };

// The helpers are plain JS, so their defaults type the parameters; the seam names the real shapes.
const hasStats = hasW3CStatsTwoSeasons as (player: Row, currentSeason?: number, race?: string | null) => boolean;
const hasLowGames = hasLowGamesTwoSeasons as (player: Row, currentSeason?: number, race?: string | null) => boolean;
const gamesCount = getW3CGamesCount as (player: Row, currentSeason?: number, race?: string | null) => number;

const SYNC_ICON: Record<string, { icon: string; className: string; note?: string }> = {
  loading: { icon: "mdi-sync", className: "text-muted-foreground" },
  success: { icon: "mdi-check-circle", className: "text-success" },
  skipped: { icon: "mdi-clock-outline", className: "text-muted-foreground", note: "Synced in the last 10 minutes" },
  error: { icon: "mdi-alert-circle", className: "text-error" },
};

/** The W3C warnings and the sync state of one signup, as the icons that ride beside his name. */
function PlayerCues({ player, w3cSeason, status }: { player: Row; w3cSeason?: number; status?: SyncStatus }) {
  const cue = status ? SYNC_ICON[status.state] : null;
  // Only the skipped and the error cue carry text, so the other two draw a bare icon
  const cueText = cue ? (cue.note ?? (status?.state === "error" ? status.message || "Sync failed" : null)) : null;
  return (
    <>
      {!hasStats(player, w3cSeason, player.signup_race) ? (
        <TapTooltip content={`No W3C stats found for ${player.signup_race}`}>
          <Icon name="mdi-alert" size={16} className="text-error" />
        </TapTooltip>
      ) : hasLowGames(player, w3cSeason, player.signup_race) ? (
        <TapTooltip content={`Less than 20 games (${gamesCount(player, w3cSeason, player.signup_race)} games) for ${player.signup_race}`}>
          <Icon name="mdi-alert" size={16} className="text-warning" />
        </TapTooltip>
      ) : null}
      {cue ? (
        cueText ? (
          <TapTooltip content={cueText}>
            <Icon name={cue.icon} size={16} className={cue.className} />
          </TapTooltip>
        ) : (
          <Icon name={cue.icon} size={16} className={cue.className} />
        )
      ) : null}
    </>
  );
}

export function SeasonTeamAssignView({ id }: { id: string }) {
  const auth = useAuth();
  const ladderStore = useLadderStore();
  const teamStore = useTeamStore();
  const { current_season, seasonIdOf, fetchSeason, updateSeasonSignup, removeUserSignup, fetchSeasonSignups } = useSeason();

  const seasonId = seasonIdOf(id);
  const seasonName = current_season?.name || "";

  const [teams, setTeams] = useState<Row[]>([]);
  // Local state for signed up players
  const [signedUpPlayersData, setSignedUpPlayersData] = useState<Row[]>([]);
  // Every write on this page reports its failure here
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const [searchName, setSearchName] = useState("");
  const [searchRace, setSearchRace] = useState<string | null>(null);
  const [rangeValues, setRangeValues] = useState([0, 3000]);

  // Track team selection per player
  const [playerTeamSelection, setPlayerTeamSelection] = useState<Record<number, number | null>>({});
  const [perPlayerSyncStatus, setPerPlayerSyncStatus] = useState<Record<number, SyncStatus>>({});

  const [syncDialog, setSyncDialog] = useState(false);
  const [syncEntries, setSyncEntries] = useState<SyncEntry[]>([]);

  const editPlayerDialog = useRef<EditPlayerDialogHandle>(null);
  const signupDialog = useRef<SeasonSignupDialogHandle>(null);
  const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

  // Current W3C season for stats fallback
  const [currentW3CSeason, setCurrentW3CSeason] = useState<number | undefined>(undefined);

  // per-team loading state to avoid double-clicks
  const [removeLoading, setRemoveLoading] = useState<Record<string, boolean>>({});
  const [syncAllLoading, setSyncAllLoading] = useState(false);
  const [assignAllLoading, setAssignAllLoading] = useState(false);

  // The draft order, so a reversed sort keeps the moved players in place
  const [sorting, setSorting] = useState<SortingState>([{ id: "w3c_mmr", desc: false }]);

  const mmrOf = (p: Row) => getW3CMMR(p, currentW3CSeason, p.signup_race) || 0;

  // The players an admin took out of the pick list
  const excludedPlayers = signedUpPlayersData.filter((p) => p.draft_excluded);

  // The draft order: MMR ascending, each moved player at his slot, no excluded player
  const orderedPlayers: Row[] = draftOrder(signedUpPlayersData, mmrOf);
  const positionOf = new Map<number, number>(orderedPlayers.map((p, i) => [p.id, i]));
  // One round = one pick per team
  const roundSize = teams.length || 10;
  const rounds = Array.from({ length: Math.ceil(orderedPlayers.length / roundSize) }, (_, i) => i + 1);
  const roundOf = (p: Row) => Math.floor((positionOf.get(p.id) ?? 0) / roundSize) + 1;

  // fetch data — prefer fetching teams for the specific season when seasonId is available
  const fetchData = async () => {
    const [rows] = await Promise.all([teamStore.fetchTeamsBySeason(seasonId as number), fetchSeason(seasonId as number)]);
    setTeams(rows || []);
    try {
      setSignedUpPlayersData((await fetchSeasonSignups(seasonId as number)) || []);
    } catch (err) {
      console.error("Failed to fetch season signups:", err);
      setSignedUpPlayersData([]);
    }
  };

  useEffect(() => {
    if (!seasonId) return;
    // the loaders set state, so they run just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(async () => {
      setCurrentW3CSeason((await resolveCurrentW3CSeason()) ?? undefined);
      await fetchData();
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId]);

  // The row moves at once and rolls back when the write is refused, so it never shows a value the server rejected
  const writeSignup = async (player: Row, field: string, value: unknown, fields: Row, message: string) => {
    const before = player[field];
    const patch = (to: unknown) => setSignedUpPlayersData((was) => was.map((row) => (row.id === player.id ? { ...row, [field]: to } : row)));
    patch(value);
    setErrorMessage(null);
    try {
      await updateSeasonSignup(seasonId as number, player.id, fields);
    } catch (error) {
      console.error(message, error);
      patch(before);
      setErrorMessage((error as Error).message);
    }
  };

  const setExcluded = (player: Row, draft_excluded: boolean) =>
    writeSignup(player, "draft_excluded", draft_excluded, { draft_excluded }, "Failed to change the pick list:");

  const setDraftPosition = (player: Row, draft_position: number | null) =>
    writeSignup(player, "draft_position", draft_position, { draft_position }, "Failed to move the player:");
  const moveToRound = (player: Row, round: number) => setDraftPosition(player, (round - 1) * roundSize);

  // The race the MMR, the icon and the race filters read
  const setSignupRace = (player: Row, race: string | null) => {
    if (!race) return Promise.resolve();
    return writeSignup(player, "signup_race", race, { race }, "Failed to set the race:");
  };

  // compute assigned player ids across all teams for this season
  const assignedPlayerIds = (() => {
    const sid = String(seasonId);
    const set = new Set<number>();
    teams.forEach((team) => {
      const v = team.player_by_season?.[sid] || team.player_by_season?.[Number(sid)];
      if (!v) return;
      if (Array.isArray(v)) v.forEach((p: Row) => p && p.id && set.add(p.id));
      else if (typeof v === "object") Object.values(v).forEach((p: any) => p && p.id && set.add(p.id));
    });
    return set;
  })();

  // players signed up for this season, in draft order
  const filteredPlayers: Row[] = (() => {
    let list = orderedPlayers;
    if (searchName.trim().length > 0) list = list.filter((p) => matchesPlayerSearch(p, searchName));
    if (searchRace) list = list.filter((p) => p.signup_race === searchRace);
    // filter by mmr range — only apply if user changed from defaults
    return filterByMmrRange(list, rangeValues, mmrOf);
  })();

  // available players = signed up players minus assigned players
  const availablePlayers = filteredPlayers.filter((p: Row) => !assignedPlayerIds.has(p.id));

  // Count players with team selected
  const playersWithTeamSelected = Object.values(playerTeamSelection).filter((teamId) => teamId != null).length;

  const onResetFilters = async () => {
    setSearchName("");
    setSearchRace(null);
    setRangeValues([0, 3000]);
    // refresh available players after clearing filters
    await fetchData();
  };

  const getTeamPlayersForSeason = (team: Row): Row[] => {
    const sid = String(seasonId);
    if (!team || !team.player_by_season) return [];
    const v = team.player_by_season[sid] || team.player_by_season[Number(sid)];
    if (!v) return [];
    const teamPlayers: Row[] = Array.isArray(v) ? v : typeof v === "object" ? Object.values(v) : [];
    // Sort by W3C MMR descending
    return [...teamPlayers].sort((a, b) => mmrOf(b) - mmrOf(a));
  };

  const isRemoveLoading = (teamId: number, playerId: number) => !!removeLoading[`${teamId}_${playerId}`];

  const assignAllPlayers = async () => {
    setAssignAllLoading(true);
    setErrorMessage(null);
    try {
      // Group players by team
      const playersByTeam: Record<number, number[]> = {};
      for (const [playerId, teamId] of Object.entries(playerTeamSelection)) {
        if (teamId != null) (playersByTeam[teamId] ||= []).push(parseInt(playerId));
      }
      // Add players to each team
      for (const [teamId, playerIds] of Object.entries(playersByTeam)) {
        if (playerIds.length > 0) await teamStore.addPlayersToTeamForSeason(parseInt(teamId), seasonId as number, playerIds);
      }
      // Clear selections and refresh
      setPlayerTeamSelection({});
      await fetchData();
    } catch (err) {
      console.error("Failed to assign players to teams:", err);
      setErrorMessage((err as Error).message);
    } finally {
      setAssignAllLoading(false);
    }
  };

  const removePlayerFromTeam = async (teamId: number, playerId: number) => {
    setErrorMessage(null);
    setRemoveLoading((was) => ({ ...was, [`${teamId}_${playerId}`]: true }));
    try {
      await teamStore.removePlayersFromTeamForSeason(teamId, seasonId as number, [playerId]);
      await fetchData();
    } catch (err) {
      console.error("Failed to remove player from team:", err);
      setErrorMessage((err as Error).message);
    } finally {
      setRemoveLoading((was) => ({ ...was, [`${teamId}_${playerId}`]: false }));
    }
  };

  // sync every player signed up to the season, one chunk of players per request
  const syncAllDraftPlayers = async () => {
    setSyncAllLoading(true);
    setErrorMessage(null);
    const list = orderedPlayers;
    setPerPlayerSyncStatus(Object.fromEntries(list.map((p) => [p.id, { state: "loading" }])));
    try {
      const result = await ladderStore.syncSeason(seasonId as number);
      const status: Record<number, SyncStatus> = {};
      for (const syncedId of result.synced ?? []) status[syncedId as number] = { state: "success" };
      for (const skippedId of result.skipped ?? []) status[skippedId as number] = { state: "skipped" };
      for (const f of result.failed ?? []) status[f.id as number] = { state: "error", message: f.reason };
      setPerPlayerSyncStatus(status);
      setSyncEntries([{ title: seasonName, result }]);
      setSyncDialog(true);
    } catch (err) {
      console.error("Failed to sync season players:", err);
      setErrorMessage((err as Error).message);
      setPerPlayerSyncStatus(Object.fromEntries(list.map((p) => [p.id, { state: "error", message: (err as Error).message }])));
    } finally {
      await fetchData();
      setSyncAllLoading(false);
    }
  };

  const removeSignup = async (player: Row) => {
    setErrorMessage(null);
    try {
      await removeUserSignup(seasonId as number, [player.id]);
      await fetchData();
    } catch (error) {
      console.error("Failed to remove the signup:", error);
      setErrorMessage((error as Error).message);
    }
  };

  const teamItems = teams.map((team) => ({ value: team.id as number, label: team.name as string }));

  // a drafting page: a name opens the panel, so the roster ticks survive
  return (
    <PanelLinksContext.Provider value>
      <div className="p-4">
        {/* Page Header */}
        <div className="mb-4 flex flex-wrap items-center gap-3">
          <h1 className="flex flex-1 items-center gap-2">
            <Icon name="mdi-account-multiple-check" />
            Draft Players for Season
          </h1>
          <Button variant="ghost" nativeButton={false} render={<Link href={`/seasons/${id}`} />}>
            <Icon name="mdi-arrow-left" />
            Back to season
          </Button>
        </div>

        {/* Top: Filters + Draft players for season */}
        <Card className="card mb-4 gap-0 py-0">
          <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-account-multiple" />
            <span>{seasonName}</span>
          </CardTitle>
          {auth.isAdmin ? (
            <div className="flex flex-wrap items-center justify-end gap-2 p-2">
              <div className="min-w-[240px]">
                <SyncProgress />
              </div>
              <TapTooltip content="MMR and ladder matches">
                <Button onClick={syncAllDraftPlayers} disabled={syncAllLoading}>
                  {syncAllLoading ? <Icon name="mdi-loading mdi-spin" /> : <W3CIcon size={18} />}
                  Sync W3C
                </Button>
              </TapTooltip>
              <Button onClick={() => signupDialog.current?.open({ season: { id: seasonId as number, name: seasonName } })}>
                <Icon name="mdi-account-plus" />
                Add signup
              </Button>
            </div>
          ) : null}

          <CardContent className="pt-4">
            <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />
            <FilterPanel
              searchName={searchName}
              onSearchNameChange={setSearchName}
              searchRace={searchRace}
              onSearchRaceChange={setSearchRace}
              rangeValues={rangeValues}
              onRangeValuesChange={setRangeValues}
              showName
              showRace
              showSeason={false}
              showMMR
              showReset
              onReset={onResetFilters}
            />
          </CardContent>

          {/* One page is one round, so the table starts over when the team count arrives */}
          <DataTable
            key={roundSize}
            data={availablePlayers}
            pageSize={roundSize}
            sorting={sorting}
            onSortingChange={setSorting}
            empty="No available signed-up players for this season."
            columns={[
              {
                id: "name",
                accessorKey: "name",
                header: "Name",
                enableSorting: false,
                cell: ({ row }) => (
                  <PlayerName player={row.original}>
                    <PlayerCues player={row.original} w3cSeason={currentW3CSeason} status={perPlayerSyncStatus[row.original.id]} />
                  </PlayerName>
                ),
              },
              {
                id: "w3c_mmr",
                accessorFn: (row: Row) => positionOf.get(row.id) ?? 0,
                header: () => <W3CMmr />,
                cell: ({ row }) => (
                  <>
                    <div className="tnum">{getW3CMMR(row.original, currentW3CSeason, row.original.signup_race) ?? "N/A"}</div>
                    <TapTooltip className="text-xs text-muted-foreground" content={syncedAt(row.original)}>
                      {syncedAgo(row.original)}
                    </TapTooltip>
                  </>
                ),
              },
              {
                id: "race",
                header: "Race",
                enableSorting: false,
                cell: ({ row }) =>
                  auth.isAdmin ? (
                    <Select
                      items={raceWrapper.races.map((race: Row) => ({ value: race.id, label: race.name }))}
                      value={row.original.signup_race ?? null}
                      onValueChange={(value) => setSignupRace(row.original, value as string | null)}
                    >
                      <SelectTrigger size="sm" aria-label="Race" className="w-[140px]">
                        <SelectValue placeholder="Race" />
                      </SelectTrigger>
                      <SelectContent>
                        {raceWrapper.races.map((race: Row) => (
                          <SelectItem key={race.id} value={race.id}>
                            <RaceIcon raceIdentifier={race.id} /> {race.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  ) : row.original.signup_race ? (
                    <RaceIcon raceIdentifier={row.original.signup_race} />
                  ) : null,
              },
              {
                id: "round",
                header: "Round",
                enableSorting: false,
                cell: ({ row }) => (
                  <div className="flex items-center gap-1">
                    {auth.isAdmin ? (
                      <Select
                        items={rounds.map((round) => ({ value: round, label: String(round) }))}
                        value={roundOf(row.original)}
                        onValueChange={(value) => moveToRound(row.original, Number(value))}
                      >
                        <SelectTrigger size="sm" aria-label="Round" className="w-16">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {rounds.map((round) => (
                            <SelectItem key={round} value={round}>
                              {round}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    ) : (
                      <span className="tnum">{roundOf(row.original)}</span>
                    )}
                    {auth.isAdmin && row.original.draft_position != null ? (
                      <TapTooltip content="Moved by hand. Click to sort by MMR again">
                        <Button variant="ghost" size="icon-sm" aria-label="Sort by MMR again" onClick={() => setDraftPosition(row.original, null)}>
                          <Icon name="mdi-pin-off" />
                        </Button>
                      </TapTooltip>
                    ) : row.original.draft_position != null ? (
                      <TapTooltip content="Moved by hand">
                        <Icon name="mdi-pin" size={16} />
                      </TapTooltip>
                    ) : null}
                  </div>
                ),
              },
              // the table lists players no team holds yet, so the picker is the whole column
              ...(auth.isAdmin
                ? [
                    {
                      id: "team",
                      header: "Team",
                      enableSorting: false,
                      cell: ({ row }: { row: { original: Row } }) => (
                        <div className="flex items-center gap-1">
                          <Select
                            items={teamItems}
                            value={playerTeamSelection[row.original.id] ?? null}
                            onValueChange={(value) => setPlayerTeamSelection((was) => ({ ...was, [row.original.id]: value as number | null }))}
                          >
                            <SelectTrigger size="sm" aria-label="Team" className="w-full min-w-[150px]">
                              <SelectValue placeholder="Team" />
                            </SelectTrigger>
                            <SelectContent>
                              {teamItems.map((team) => (
                                <SelectItem key={team.value} value={team.value}>
                                  {team.label}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          {playerTeamSelection[row.original.id] != null ? (
                            <Button
                              variant="ghost"
                              size="icon-sm"
                              aria-label="Clear the team"
                              onClick={() => setPlayerTeamSelection((was) => ({ ...was, [row.original.id]: null }))}
                            >
                              <Icon name="mdi-close" />
                            </Button>
                          ) : null}
                        </div>
                      ),
                    },
                  ]
                : []),
              {
                id: "actions",
                header: "",
                enableSorting: false,
                cell: ({ row }) =>
                  auth.isAdmin ? (
                    <div className="flex justify-end">
                      <Button variant="ghost" size="icon-sm" aria-label="Edit player" onClick={() => editPlayerDialog.current?.open(row.original)}>
                        <Icon name="mdi-pencil" />
                      </Button>
                      <TapTooltip content="Take out of the pick list">
                        <Button variant="ghost" size="icon-sm" aria-label="Take out of the pick list" onClick={() => setExcluded(row.original, true)}>
                          <Icon name="mdi-account-off" />
                        </Button>
                      </TapTooltip>
                      <TapTooltip content="Remove signup">
                        <Button
                          variant="ghost"
                          size="icon-sm"
                          aria-label="Remove signup"
                          onClick={() => openDeleteDialog(row.original.id, () => removeSignup(row.original))}
                        >
                          <Icon name="mdi-account-remove" />
                        </Button>
                      </TapTooltip>
                    </div>
                  ) : null,
              },
            ]}
          />

          {excludedPlayers.length ? (
            <CardContent className="pt-2 pb-0">
              <div className="mb-1 text-xs text-muted-foreground">Out of the pick list ({excludedPlayers.length})</div>
              <div className="flex flex-wrap gap-2">
                {excludedPlayers.map((p) => (
                  <Badge key={p.id} variant="secondary">
                    {p.signup_race ? <RaceIcon raceIdentifier={p.signup_race} /> : null}
                    {p.name}
                    {auth.isAdmin ? (
                      <TapTooltip content="Put back in the pick list">
                        <button type="button" aria-label={`Put ${p.name} back in the pick list`} onClick={() => setExcluded(p, false)}>
                          <Icon name="mdi-undo" />
                        </button>
                      </TapTooltip>
                    ) : null}
                  </Badge>
                ))}
              </div>
            </CardContent>
          ) : null}

          {auth.isAdmin ? (
            <CardContent className="px-4 py-4">
              <Button onClick={assignAllPlayers} disabled={assignAllLoading || playersWithTeamSelected === 0}>
                <Icon name={assignAllLoading ? "mdi-loading mdi-spin" : "mdi-account-multiple-plus"} />
                Assign {playersWithTeamSelected} player{playersWithTeamSelected !== 1 ? "s" : ""} to teams
              </Button>
            </CardContent>
          ) : null}
        </Card>

        <EditPlayerDialog ref={editPlayerDialog} refresh={fetchData} />

        <SeasonSignupDialog ref={signupDialog} onAdded={fetchData} />

        <ConfirmDeleteDialog
          modelValue={showDeleteDialog}
          message="Remove this player's signup for the season?"
          deleteIcon="mdi-account-remove"
          onUpdateModelValue={(open) => (open ? undefined : cancelDeleteDialog())}
          onConfirm={confirmDelete}
          onCancel={cancelDeleteDialog}
        />

        {/* Teams grid below */}
        <h2 className="mb-4 flex items-center gap-2">
          <Icon name="mdi-shield-account" />
          Team assignments
        </h2>
        {/* as many team cards as fit the window, so the page never scrolls sideways */}
        <div className="grid grid-cols-[repeat(auto-fill,minmax(240px,1fr))] gap-3">
          {teams.map((team) => (
            <Card key={team.id} className="card gap-0 py-0">
              <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
                <Icon name="mdi-shield-account" />
                {team.name}
              </CardTitle>
              <CardContent className="py-3">
                {getTeamPlayersForSeason(team).length ? (
                  getTeamPlayersForSeason(team).map((p) => (
                    <div key={p.id} className="flex items-center justify-between py-1.5">
                      <div>
                        <div className="flex items-center gap-2">
                          <PlayerName player={p} />
                          <PlayerCues player={p} w3cSeason={currentW3CSeason} status={perPlayerSyncStatus[p.id]} />
                        </div>
                        <div className="flex items-center gap-1 text-muted-foreground">
                          <span className="tnum">{getW3CMMR(p, currentW3CSeason, p.signup_race) ?? "N/A"}</span>
                          {p.signup_race ? (
                            <>
                              <span>—</span>
                              <RaceIcon raceIdentifier={p.signup_race} />
                            </>
                          ) : null}
                        </div>
                        <TapTooltip className="text-xs text-muted-foreground" content={syncedAt(p)}>
                          {syncedAgo(p)}
                        </TapTooltip>
                      </div>
                      {auth.isAdmin ? (
                        <Button
                          variant="ghost"
                          size="icon-sm"
                          aria-label="Remove from the team"
                          className="text-error"
                          disabled={isRemoveLoading(team.id, p.id)}
                          onClick={() => removePlayerFromTeam(team.id, p.id)}
                        >
                          <Icon name={isRemoveLoading(team.id, p.id) ? "mdi-loading mdi-spin" : "mdi-delete"} />
                        </Button>
                      ) : null}
                    </div>
                  ))
                ) : (
                  <em className="text-muted-foreground">No players assigned for this season</em>
                )}
              </CardContent>
            </Card>
          ))}
        </div>

        <W3CSyncResultDialog modelValue={syncDialog} entries={syncEntries} onUpdateModelValue={setSyncDialog} />
      </div>
    </PanelLinksContext.Provider>
  );
}

export default SeasonTeamAssignView;

// src/views/SeasonTeamAssignView.vue
<template>
  <v-container fluid class="pa-4">
    <!-- Page Header -->
    <v-row class="mb-4">
      <v-col>
        <h1>
          <v-icon class="mr-2">mdi-account-multiple-check</v-icon>
          Draft Players for Season
        </h1>
      </v-col>
    </v-row>

    <!-- Top: Filters + Draft players for season -->
    <v-card elevation="2" class="mb-4">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-account-multiple</v-icon>
        <span>{{ seasonName }}</span>
      </v-card-title>
      <v-card-text class="pa-0">
        <v-toolbar flat height="auto">
          <v-row align="center" class="flex-wrap ma-0 pa-2">
            <v-spacer />
            <v-col cols="12" sm="auto" style="min-width: 240px">
              <SyncProgress />
            </v-col>
            <v-col v-if="auth.isAdmin" cols="12" sm="auto">
              <v-btn variant="elevated" color="primary" @click="syncAllDraftPlayers" :loading="syncAllLoading" block>
                <template #prepend><W3CIcon :size="18" /></template>
                Sync W3C
                <v-tooltip activator="parent" location="top">MMR and ladder matches</v-tooltip>
              </v-btn>
            </v-col>
            <v-col v-if="auth.isAdmin" cols="12" sm="auto">
              <v-btn variant="elevated" color="primary" prepend-icon="mdi-account-plus" @click="signupDialog.open({ season: { id: seasonId, name: seasonName } })" block>
                Add signup
              </v-btn>
            </v-col>
          </v-row>
        </v-toolbar>
      </v-card-text>
      <v-card-text class="pt-4">
        <FilterPanel
          v-model:searchName="searchName"
          v-model:searchRace="searchRace"
          v-model:rangeValues="rangeValues"
          :seasons="null"
          :showName="true"
          :showRace="true"
          :showSeason="false"
          :showMMR="true"
          :showReset="true"
          @reset="onResetFilters"
        />
      </v-card-text>
      <v-data-table
              :headers="playerTableHeaders"
              :items="availablePlayers"
              :items-per-page="teams.length || 10"
              :sort-by="[{ key: 'w3c_mmr', order: 'asc' }]"
              return-object
              mobile-breakpoint="sm"
            >
              <template v-slot:[`header.w3c_mmr`]="{ column, isSorted, getSortIcon }">
                <W3CMmr :sort-icon="isSorted(column) ? getSortIcon(column) : null" />
              </template>
              <template #item.team="{ item }">
                <v-select
                  v-model="playerTeamSelection[item.id]"
                  :items="teams"
                  item-title="name"
                  item-value="id"
                  density="compact"
                  clearable
                  hide-details
                  style="min-width: 150px;"
                  :disabled="!auth.isAdmin"
                ></v-select>
              </template>
              <template #item.name="{ item }">
                <PlayerName :player="item">
                  <template v-if="!hasW3CStatsTwoSeasons(item, currentW3CSeason, item.signup_race)">
                    <v-tooltip>
                      <template #activator="{ props }">
                        <v-icon v-bind="props" small color="red">mdi-alert</v-icon>
                      </template>
                      <span>No W3C stats found for {{ item.signup_race }}</span>
                    </v-tooltip>
                  </template>
                  <template v-else-if="hasLowGamesTwoSeasons(item, currentW3CSeason, item.signup_race)">
                    <v-tooltip>
                      <template #activator="{ props }">
                        <v-icon v-bind="props" small color="orange">mdi-alert</v-icon>
                      </template>
                      <span>Less than 20 games ({{ getW3CGamesCount(item, currentW3CSeason, item.signup_race) }} games) for {{ item.signup_race }}</span>
                    </v-tooltip>
                  </template>
                  <template v-if="perPlayerSyncStatus[item.id] && perPlayerSyncStatus[item.id].state === 'loading'">
                    <v-icon small class="text--secondary">mdi-sync</v-icon>
                  </template>
                  <template v-else-if="perPlayerSyncStatus[item.id] && perPlayerSyncStatus[item.id].state === 'success'">
                    <v-icon small color="green">mdi-check-circle</v-icon>
                  </template>
                  <template v-else-if="perPlayerSyncStatus[item.id] && perPlayerSyncStatus[item.id].state === 'skipped'">
                    <v-tooltip>
                      <template #activator="{ props }">
                        <v-icon v-bind="props" small color="grey">mdi-clock-outline</v-icon>
                      </template>
                      <span>Synced in the last 10 minutes</span>
                    </v-tooltip>
                  </template>
                  <template v-else-if="perPlayerSyncStatus[item.id] && perPlayerSyncStatus[item.id].state === 'error'">
                    <v-tooltip>
                      <template #activator="{ props }">
                        <v-icon v-bind="props" small color="red">mdi-alert-circle</v-icon>
                      </template>
                      <span>{{ perPlayerSyncStatus[item.id].message || 'Sync failed' }}</span>
                    </v-tooltip>
                  </template>
                </PlayerName>
              </template>
              <template #item.w3c_mmr="{ item }">
                <div>{{ getW3CMMR(item, currentW3CSeason, item.signup_race) ?? 'N/A' }}</div>
                <div class="text-caption text-medium-emphasis">{{ syncedAgo(item) }}<v-tooltip activator="parent" location="top">{{ syncedAt(item) }}</v-tooltip></div>
              </template>
              <template #item.race="{ item }">
                <v-select
                  v-if="auth.isAdmin"
                  :model-value="item.signup_race"
                  :items="raceWrapper.races"
                  item-title="name"
                  item-value="id"
                  density="compact"
                  variant="underlined"
                  hide-details
                  style="width: 140px"
                  @update:model-value="setSignupRace(item, $event)"
                >
                  <template #selection="{ item: race }">
                    <RaceIcon :raceIdentifier="race.raw.id" /> {{ race.raw.name }}
                  </template>
                </v-select>
                <RaceIcon v-else-if="item.signup_race" :raceIdentifier="item.signup_race" />
              </template>
              <template #item.round="{ item }">
                <div class="d-flex align-center ga-1">
                  <v-select
                    v-if="auth.isAdmin"
                    :model-value="roundOf(item)"
                    :items="rounds"
                    density="compact"
                    variant="underlined"
                    hide-details
                    style="width: 64px"
                    @update:model-value="moveToRound(item, $event)"
                  ></v-select>
                  <span v-else>{{ roundOf(item) }}</span>
                  <v-btn v-if="auth.isAdmin && item.draft_position != null" icon size="x-small" variant="text" @click="setDraftPosition(item, null)">
                    <v-icon>mdi-pin-off</v-icon>
                    <v-tooltip activator="parent" location="top">Moved by hand. Click to sort by MMR again</v-tooltip>
                  </v-btn>
                  <span v-else-if="item.draft_position != null">
                    <v-icon size="small">mdi-pin</v-icon>
                    <v-tooltip activator="parent" location="top">Moved by hand</v-tooltip>
                  </span>
                </div>
              </template>
              <template #item.actions="{ item }">
                <v-btn
                  v-if="auth.isAdmin"
                  icon
                  size="small"
                  variant="text"
                  @click="editPlayer(item)"
                >
                  <v-icon>mdi-pencil</v-icon>
                </v-btn>
                <v-btn
                  v-if="auth.isAdmin"
                  icon
                  size="small"
                  variant="text"
                  @click="setExcluded(item, true)"
                >
                  <v-icon>mdi-account-off</v-icon>
                  <v-tooltip activator="parent" location="top">Take out of the pick list</v-tooltip>
                </v-btn>
                <v-btn
                  v-if="auth.isAdmin"
                  icon
                  size="small"
                  variant="text"
                  @click="openDeleteDialog(item.id, () => removeSignup(item))"
                >
                  <v-icon>mdi-account-remove</v-icon>
                  <v-tooltip activator="parent" location="top">Remove signup</v-tooltip>
                </v-btn>
              </template>
              <template #no-data>
                <div>No available signed-up players for this season.</div>
              </template>
            </v-data-table>
      <v-card-text v-if="excludedPlayers.length" class="pt-2 pb-0">
        <div class="text-caption text-medium-emphasis mb-1">
          Out of the pick list ({{ excludedPlayers.length }})
        </div>
        <v-chip
          v-for="p in excludedPlayers"
          :key="p.id"
          class="mr-2 mb-2"
          size="small"
          :closable="auth.isAdmin"
          close-icon="mdi-undo"
          @click:close="setExcluded(p, false)"
        >
          <RaceIcon v-if="p.signup_race" :raceIdentifier="p.signup_race" class="mr-1" />
          {{ p.name }}
          <v-tooltip activator="parent" location="top">Put back in the pick list</v-tooltip>
        </v-chip>
      </v-card-text>

      <v-card-actions v-if="auth.isAdmin" class="px-4 pb-4">
        <v-btn
          color="primary"
          variant="elevated"
          prepend-icon="mdi-account-multiple-plus"
          @click="assignAllPlayers"
          :loading="assignAllLoading"
          :disabled="assignAllLoading || playersWithTeamSelected === 0"
        >
          Assign {{ playersWithTeamSelected }} Player{{ playersWithTeamSelected !== 1 ? 's' : '' }} to Teams
        </v-btn>
      </v-card-actions>
    </v-card>

    <EditPlayerDialog ref="editPlayerDialog" :refresh="fetchData" />

    <SeasonSignupDialog ref="signupDialog" @added="fetchData" />

    <ConfirmDeleteDialog
      v-model="showDeleteDialog"
      message="Remove this player's signup for the season?"
      delete-icon="mdi-account-remove"
      @confirm="confirmDelete"
      @cancel="cancelDeleteDialog"
    />

    <!-- Teams grid below -->
    <v-row>
      <v-col cols="12">
        <h2 class="mb-4">
          <v-icon class="mr-2">mdi-shield-account</v-icon>
          Team Assignments
        </h2>
        <div class="teams-grid" :style="{ gridTemplateColumns: `repeat(${colsCount}, 1fr)` }">
          <div v-for="team in teams" :key="team.id" class="team-card-grid">
            <v-card elevation="2">
              <v-card-title class="bg-primary">
                <v-icon class="mr-2">mdi-shield-account</v-icon>
                {{ team.name }}
              </v-card-title>
              <v-card-text>
                <div>
                  <div v-if="getTeamPlayersForSeason(team).length > 0">
                    <div v-for="p in getTeamPlayersForSeason(team)" :key="p.id" class="team-player" style="display:flex;align-items:center;justify-content:space-between;padding:6px 0;">
                      <div>
                        <div style="display:flex;align-items:center;gap:8px;">
                          <PlayerName :player="p" />
                          <template v-if="!hasW3CStatsTwoSeasons(p, currentW3CSeason, p.signup_race)">
                            <v-tooltip>
                              <template #activator="{ props }">
                                <v-icon v-bind="props" small color="red">mdi-alert</v-icon>
                              </template>
                              <span>No W3C stats found for {{ p.signup_race }}</span>
                            </v-tooltip>
                          </template>
                          <template v-else-if="hasLowGamesTwoSeasons(p, currentW3CSeason, p.signup_race)">
                            <v-tooltip>
                              <template #activator="{ props }">
                                <v-icon v-bind="props" small color="orange">mdi-alert</v-icon>
                              </template>
                              <span>Less than 20 games ({{ getW3CGamesCount(p, currentW3CSeason, p.signup_race) }} games) for {{ p.signup_race }}</span>
                            </v-tooltip>
                          </template>
                          <template v-if="perPlayerSyncStatus[p.id] && perPlayerSyncStatus[p.id].state === 'loading'">
                            <v-icon small class="text--secondary">mdi-sync</v-icon>
                          </template>
                          <template v-else-if="perPlayerSyncStatus[p.id] && perPlayerSyncStatus[p.id].state === 'success'">
                            <v-icon small color="green">mdi-check-circle</v-icon>
                          </template>
                          <template v-else-if="perPlayerSyncStatus[p.id] && perPlayerSyncStatus[p.id].state === 'skipped'">
                            <v-tooltip>
                              <template #activator="{ props }">
                                <v-icon v-bind="props" small color="grey">mdi-clock-outline</v-icon>
                              </template>
                              <span>Synced in the last 10 minutes</span>
                            </v-tooltip>
                          </template>
                          <template v-else-if="perPlayerSyncStatus[p.id] && perPlayerSyncStatus[p.id].state === 'error'">
                            <v-tooltip>
                              <template #activator="{ props }">
                                <v-icon v-bind="props" small color="red">mdi-alert-circle</v-icon>
                              </template>
                              <span>{{ perPlayerSyncStatus[p.id].message || 'Sync failed' }}</span>
                            </v-tooltip>
                          </template>
                        </div>
                        <div class="text--secondary">{{ getW3CMMR(p, currentW3CSeason, p.signup_race) ?? 'N/A' }} — <RaceIcon v-if="p.signup_race" :raceIdentifier="p.signup_race" /></div>
                        <div class="text-caption text-medium-emphasis">{{ syncedAgo(p) }}<v-tooltip activator="parent" location="top">{{ syncedAt(p) }}</v-tooltip></div>
                      </div>
                      <div style="display:flex;align-items:center;gap:6px;">
                          <v-btn
                            v-if="auth.isAdmin"
                            class="table-action ma-0 pa-0"
                            icon
                            density="compact"
                            color="red"
                            @click.stop.prevent="removePlayerFromTeam(team.id, p.id)"
                            :disabled="isRemoveLoading(team.id, p.id)"
                            :loading="isRemoveLoading(team.id, p.id)"
                          >
                            <template v-if="!isRemoveLoading(team.id, p.id)">
                              <v-icon small>mdi-delete</v-icon>
                            </template>
                          </v-btn>
                      </div>
                    </div>
                  </div>
                  <div v-else>
                    <em>No players assigned for this season</em>
                  </div>
                </div>
              </v-card-text>
            </v-card>
          </div>
        </div>
      </v-col>
    </v-row>
    <W3CSyncResultDialog v-model="syncDialog" :entries="syncEntries" />
  </v-container>
</template>

<script setup>
import { computed, onMounted, provide, ref } from 'vue';
import { useAuthStore, useLadderStore, useTeamStore, useSeasonStore } from '@/stores';
import { resolveCurrentW3CSeason } from '@/helpers/current-season';
import { storeToRefs } from 'pinia';
import { useRouter } from 'vue-router';
import EditPlayerDialog from '@/components/EditPlayerDialog.vue';
import SeasonSignupDialog from '@/components/SeasonSignupDialog.vue';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';
import W3CMmr from '@/components/W3CMmr.vue';
import W3CIcon from '@/components/W3CIcon.vue';
import FilterPanel from '@/components/FilterPanel.vue';
import SyncProgress from '@/components/SyncProgress.vue';
import W3CSyncResultDialog from '@/components/W3CSyncResultDialog.vue';
import { 
  getW3CMMR,
  getW3CGamesCount,
  hasW3CStatsTwoSeasons,
  hasLowGamesTwoSeasons,
  syncedAgo,
  syncedAt
} from '@/helpers/w3c-stats';
import { matchesPlayerSearch, filterByMmrRange, panelLinks } from '@/helpers/players';
import { draftOrder } from '@/helpers/draft.mjs';
import { raceWrapper } from '@/helpers/races';
import { useDeleteDialog } from '@/helpers/delete-dialog';
import { useDisplay } from 'vuetify';


const router = useRouter();
provide(panelLinks, true); // a drafting page: a name opens the panel, so the roster ticks survive
const auth = useAuthStore();

const seasonId = computed(() => {
  const params = router.currentRoute.value.params || {};
  const id = params.season_id || params.id || router.currentRoute.value.query.season_id;
  return id ? useSeasonStore().seasonIdOf(id) : null;
});

const ladderStore = useLadderStore();
const teamStore = useTeamStore();
const seasonStore = useSeasonStore();

const { teams } = storeToRefs(teamStore);
const { current_season } = storeToRefs(seasonStore);

// Local state for signed up players
const signedUpPlayersData = ref([]);

const searchName = ref('');
const searchRace = ref(null);
const rangeValues = ref([0, 3000]);

// Track team selection per player
const playerTeamSelection = ref({});

// per-player sync status: { state: 'idle'|'loading'|'success'|'error', message?: string }
const perPlayerSyncStatus = ref({});

const syncDialog = ref(false);
const syncEntries = ref([]);

// Edit player state
const editPlayerDialog = ref(null);
const signupDialog = ref(null);
const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

// Current W3C season for stats fallback
const currentW3CSeason = ref(null);

const mmrOf = (p) => getW3CMMR(p, currentW3CSeason.value, p.signup_race) || 0;

// The players an admin took out of the pick list
const excludedPlayers = computed(() => (signedUpPlayersData.value || []).filter(p => p.draft_excluded));

// The draft order: MMR ascending, each moved player at his slot, no excluded player
const orderedPlayers = computed(() => draftOrder(signedUpPlayersData.value, mmrOf));
const positionOf = computed(() => new Map(orderedPlayers.value.map((p, i) => [p.id, i])));
// One round = one pick per team
const roundSize = computed(() => teams.value?.length || 10);
const rounds = computed(() => Array.from({ length: Math.ceil(orderedPlayers.value.length / roundSize.value) }, (_, i) => i + 1));
const roundOf = (p) => Math.floor(positionOf.value.get(p.id) / roundSize.value) + 1;

const setExcluded = async (player, draft_excluded) => {
  try {
    await seasonStore.updateSeasonSignup(seasonId.value, player.id, { draft_excluded });
    player.draft_excluded = draft_excluded;
  } catch (error) {
    console.error('Failed to change the pick list:', error);
  }
};

const setDraftPosition = async (player, draft_position) => {
  try {
    await seasonStore.updateSeasonSignup(seasonId.value, player.id, { draft_position });
    player.draft_position = draft_position;
  } catch (error) {
    console.error('Failed to move the player:', error);
  }
};
const moveToRound = (player, round) => setDraftPosition(player, (round - 1) * roundSize.value);

// The race the MMR, the icon and the race filters read
const setSignupRace = async (player, race) => {
  if (!race) return;
  try {
    await seasonStore.updateSeasonSignup(seasonId.value, player.id, { race });
    player.signup_race = race;
  } catch (error) {
    console.error('Failed to set the race:', error);
  }
};

const playerTableHeaders = computed(() => [
  ...(smAndDown.value ? [] : [{ title: 'ID', value: 'id' }]),
  { title: 'Name', value: 'name' },
  // The draft order, so a reversed sort keeps the moved players in place
  { title: 'MMR', key: 'w3c_mmr', sortable: true, sortRaw: (a, b) => positionOf.value.get(a.id) - positionOf.value.get(b.id) },
  { title: 'Race', value: 'race' },
  { title: 'Round', value: 'round', sortable: false },
  { title: 'Team', value: 'team', sortable: false },
  { title: '', value: 'actions', sortable: false, align: 'end' },
]);

// compute assigned player ids across all teams for this season
const assignedPlayerIds = computed(() => {
  const sid = String(seasonId.value);
  const set = new Set();
  (teams.value || []).forEach(team => {
    const v = team.player_by_season?.[sid] || team.player_by_season?.[Number(sid)];
    if (!v) return;
    if (Array.isArray(v)) v.forEach(p => p && p.id && set.add(p.id));
    else if (typeof v === 'object') Object.values(v).forEach(p => p && p.id && set.add(p.id));
  });
  return set;
});

// available players = signed up players minus assigned players
const availablePlayers = computed(() => {
  return (filteredPlayers.value || []).filter(p => !assignedPlayerIds.value.has(p.id));
});

// Count players with team selected
const playersWithTeamSelected = computed(() => {
  return Object.values(playerTeamSelection.value).filter(teamId => teamId != null).length;
});

// columns for teams grid: if exactly 8 teams -> show 4 columns (will wrap to two rows);
// otherwise show all teams side-by-side (one column per team)
const { xs, smAndDown } = useDisplay();
const colsCount = computed(() => {
  if (xs.value) return 1;
  if (smAndDown.value) return 2;
  const n = (teams.value || []).length;
  if (n === 8) return 4; // two rows of 4
  return Math.max(1, n); // side-by-side for fewer than 8 teams
});

// fetch data — prefer fetching teams for the specific season when seasonId is available
const fetchData = async () => {
  await Promise.all([
    (seasonId.value && teamStore.fetchTeamsBySeason)
      ? teamStore.fetchTeamsBySeason(seasonId.value)
      : (teamStore.fetchTeams ? teamStore.fetchTeams() : Promise.resolve()),
    seasonStore.fetchSeason ? seasonStore.fetchSeason(seasonId.value) : Promise.resolve()
  ]);
  
  // Fetch signed up users separately
  if (seasonId.value && seasonStore.fetchSeasonSignups) {
    try {
      signedUpPlayersData.value = await seasonStore.fetchSeasonSignups(seasonId.value);
    } catch (err) {
      console.error('Failed to fetch season signups:', err);
      signedUpPlayersData.value = [];
    }
  }
};

onMounted(async () => {
  currentW3CSeason.value = await resolveCurrentW3CSeason();
  fetchData();
});

const seasonName = computed(() => {
  return current_season.name;
});

// players signed up for this season, in draft order
const signedUpPlayers = orderedPlayers;

const filteredPlayers = computed(() => {
  let list = signedUpPlayers.value || [];
  if (searchName.value && searchName.value.trim().length > 0) {
    list = list.filter(p => matchesPlayerSearch(p, searchName.value));
  }
  if (searchRace.value) list = list.filter(p => p.signup_race === searchRace.value);
  
  // filter by mmr range — only apply if user changed from defaults
  list = filterByMmrRange(list, rangeValues.value, mmrOf);
  
  return list;
});

const clearFilters = () => {
  searchName.value = '';
  searchRace.value = null;
  rangeValues.value = [0, 3000];
};

const onResetFilters = async () => {
  clearFilters();
  // refresh available players after clearing filters
  await fetchData();
};

// Get W3C MMR for player's signed up race (with fallback)
function getTeamPlayersForSeason(team) {
  const sid = String(seasonId.value);
  if (!team || !team.player_by_season) return [];
  const v = team.player_by_season[sid] || team.player_by_season[Number(sid)];
  if (!v) return [];
  let players = [];
  if (Array.isArray(v)) players = v;
  else if (typeof v === 'object') players = Object.values(v);
  
  // Sort by W3C MMR descending
  return players.sort((a, b) => (getW3CMMR(b, currentW3CSeason.value, b.signup_race) || 0) - (getW3CMMR(a, currentW3CSeason.value, a.signup_race) || 0));
}

// per-team loading state to avoid double-clicks
const removeLoading = ref({});
const syncAllLoading = ref(false);
const assignAllLoading = ref(false);

const isRemoveLoading = (teamId, playerId) => {
  return !!removeLoading.value[`${teamId}_${playerId}`];
};

const assignAllPlayers = async () => {
  assignAllLoading.value = true;
  try {
    // Group players by team
    const playersByTeam = {};
    for (const [playerId, teamId] of Object.entries(playerTeamSelection.value)) {
      if (teamId != null) {
        if (!playersByTeam[teamId]) {
          playersByTeam[teamId] = [];
        }
        playersByTeam[teamId].push(parseInt(playerId));
      }
    }

    // Add players to each team
    for (const [teamId, playerIds] of Object.entries(playersByTeam)) {
      if (playerIds.length > 0) {
        await teamStore.addPlayersToTeamForSeason(parseInt(teamId), seasonId.value, playerIds);
      }
    }

    // Clear selections and refresh
    playerTeamSelection.value = {};
    await fetchData();
  } catch (err) {
    console.error('Failed to assign players to teams:', err);
  } finally {
    assignAllLoading.value = false;
  }
};

const removePlayerFromTeam = async (teamId, playerId) => {
  removeLoading.value = { ...removeLoading.value, [`${teamId}_${playerId}`]: true };
  try {
    if (teamStore.removePlayersFromTeamForSeason) {
      await teamStore.removePlayersFromTeamForSeason(teamId, seasonId.value, [playerId]);
    }
    await fetchData();
  } catch (err) {
    console.error('Failed to remove player from team:', err);
  } finally {
    removeLoading.value = { ...removeLoading.value, [`${teamId}_${playerId}`]: false };
  }
};

// sync every player signed up to the season, one chunk of players per request
const syncAllDraftPlayers = async () => {
  syncAllLoading.value = true;
  const list = signedUpPlayers.value || [];
  perPlayerSyncStatus.value = Object.fromEntries(list.map(p => [p.id, { state: 'loading' }]));
  try {
    const result = await ladderStore.syncSeason(seasonId.value);
    const status = {};
    for (const id of result.synced ?? []) status[id] = { state: 'success' };
    for (const id of result.skipped ?? []) status[id] = { state: 'skipped' };
    for (const f of result.failed ?? []) status[f.id] = { state: 'error', message: f.reason };
    perPlayerSyncStatus.value = status;
    syncEntries.value = [{ title: seasonName.value, result }];
    syncDialog.value = true;
  } catch (err) {
    console.error('Failed to sync season players:', err);
    perPlayerSyncStatus.value = Object.fromEntries(list.map(p => [p.id, { state: 'error', message: err.message }]));
  } finally {
    await fetchData();
    syncAllLoading.value = false;
  }
};

const editPlayer = (player) => editPlayerDialog.value.open(player);

const removeSignup = async (player) => {
  try {
    await seasonStore.removeUserSignup(seasonId.value, [player.id]);
    await fetchData();
  } catch (error) {
    console.error('Failed to remove the signup:', error);
  }
};
</script>

<style scoped>
/* small spacing tweaks */
.v-card { margin-bottom: 12px }
 .teams-grid {
   display: grid;
   gap: 12px;
 }
 .team-card-grid {
   display: block;
 }
 .team-player .v-icon {
   font-size: 14px;
 }
</style>
