// next/src/app/(app)/series/[id]/SeriesView.tsx
"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { toneClass } from "@/components/ui/tone";
import { CastChips, type CastSeries } from "@/components/CastChips";
import { FixtureSeries } from "@/components/FixtureSeries";
import { PageHeader } from "@/components/PageHeader";
import { PlayerName } from "@/components/PlayerName";
import { ReportResultDialog, SIDE_BUTTON, type ReportResultDialogHandle } from "@/components/ReportResultDialog";
import { SeriesBox } from "@/components/SeriesBox";
import { StatusAlert } from "@/components/StatusAlert";
import { backendUrl, fetchWrapper } from "@/helpers";
import { eventLabel, MAP_RULES, timeText, titleOf } from "@/helpers/event-labels.mjs";
import { fixtureRosters, modeLabel, pickLabel, rosterSides as sidesFor, sideRoster } from "@/helpers/fixture.mjs";
import { fixedMapOf, rulesOf } from "@/helpers/map-order.mjs";
import { isScored, sideName as nameOfSide } from "@/helpers/stage-view.mjs";
import { useAuth, useEventStore, useMapStore, useTeamStore } from "@/stores";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const phoneOnly = "min-[600px]:hidden";
const wideOnly = "hidden min-[600px]:table-cell";
// The helper is plain JS, so its defaults type the parameters; the seam names the real shapes.
const sidesOf = sidesFor as unknown as (row: Row | null, rosters: Record<string, Row[]>, userId?: number | null, admin?: boolean) => number[];
const rostersOf = fixtureRosters as unknown as (series: Row[], teams: Row[], eventId: number) => Record<string, Row[]>;

/** One series, whatever event it belongs to: the event it is played in, the two sides
 *  and the score, the rule and the map of every game, who casts it, and for a side or
 *  an admin the report action. A bracket box and the fixture page both open it. */
export function SeriesView({ id }: { id: string }) {
  const auth = useAuth();
  const eventStore = useEventStore();
  const mapStore = useMapStore();
  const teamStore = useTeamStore();

  const [series, setSeries] = useState<Row | null>(null);
  const [games, setGames] = useState<Row[]>([]);
  const [maps, setMaps] = useState<Row[]>([]);
  const [fixture, setFixture] = useState<Row[]>([]); // every series the fixture holds, in play order
  const [rounds, setRounds] = useState<Row[]>([]); // the event's rounds, which carry the fixed map of each round
  const [rosters, setRosters] = useState<Record<string, Row[]>>({}); // the roster each team entrant fields for the event, by entrant id
  const [rosterOpen, setRosterOpen] = useState(false);
  const [rosterSide, setRosterSide] = useState(1);
  const [picked, setPicked] = useState<number[]>([]);
  const [rosterError, setRosterError] = useState<string | null>(null);
  const [savingRoster, setSavingRoster] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const reportDialog = useRef<ReportResultDialogHandle>(null);
  const [awardOpen, setAwardOpen] = useState(false);
  const [awardSide, setAwardSide] = useState<number | null>(null);
  const [awardError, setAwardError] = useState<string | null>(null);
  const [awarding, setAwarding] = useState(false);

  // The event of a series inside a fixture is its season; a bracket series names none yet
  const event: Row | null = series?.match?.season || null;
  const title = event ? eventLabel(event) : "Series";
  const scored = isScored(series);

  // The line under the title: where the series is played and when
  const place = [
    series?.match?.playday ? { icon: "mdi-tournament", text: `Round ${series.match.playday}` } : null,
    series?.date_time ? { icon: "mdi-calendar-clock", text: timeText(series.date_time) } : null,
  ].filter(Boolean) as { icon: string; text: string }[];

  // One rule per game, so their count is the best-of
  const rules: string[] = rulesOf(series?.rules?.map_rules);
  const bestOfLine = `Best of ${series?.rules?.best_of || rules.length}`;
  const hasVeto = rules.includes("veto");

  // The stage row of this series carries what it plays and who fields it; GET /series/{id}
  // answers neither, so a series inside a fixture reads them off the fixture.
  const stageRow = fixture.find((row) => row.id === series?.id) || null;
  const box = stageRow || series;
  const mode = modeLabel(stageRow?.side_size);
  const pick = pickLabel(stageRow?.pick_rule);
  const sideSize: number = stageRow?.side_size || 1;
  const teamName = (side: number) => stageRow?.[`team${side}`]?.name || `side ${side}`;
  const sideName = (side: number) => nameOfSide(box, side) || `Side ${side}`;

  // A captain names his own side, an admin either; a side already named is changed, not written
  const rosterSides = sidesOf(stageRow, rosters, auth.me?.user?.id, auth.isAdmin);
  const rosterVerb = (side: number) => (sideRoster(stageRow, side).length ? "Change" : "Name");
  const rosterItems: Row[] = (rosters[stageRow?.[`entrant${rosterSide}_id`]] || []).map((seat) => ({ id: seat.player.id, name: seat.player.name, player: seat.player, race: seat.race }));

  const openRoster = (side: number) => {
    setRosterSide(side);
    setRosterError(null);
    setPicked(sideRoster(stageRow, side).map((player: Row) => player.id));
    setRosterOpen(true);
  };

  const mapName = (mapId?: number | null) => maps.find((row) => row.id === mapId)?.name;

  // The map a fixed game plays: the map of its round, else the map an import wrote on the fixture
  const fixedMapId: number | null = fixedMapOf(series?.rules?.map_rules, rounds.find((row) => row.playday === series?.match?.playday)) ?? series?.match?.fixed_map_id ?? null;

  // One row per game of the best-of: its rule, the map it was played on or the one the
  // rule offers, and the side that won it
  const gameRows = rules.map((rule, index) => {
    const game = games.find((row) => row.game_no === index + 1);
    return {
      game_no: index + 1,
      rule: titleOf(MAP_RULES, rule),
      // a fixed game names its map before it is played; every other rule waits for the veto or the result
      map: mapName(game?.map_id ?? game?.offered_map_id ?? (rule === "fixed" ? fixedMapId : null)) || "—",
      winner: game?.winner_side ? sideName(game.winner_side === "A" ? 1 : 2) : null,
    };
  });

  // A team side names no player of its own, so any logged-in member may open the report
  // and the API answers whether he acts for the side; the 403 reads as the dialog's alert.
  const teamSided = !!series && ((!series.match && !series.player1_id && !series.player2_id) || !!stageRow?.entrant1_id);
  // A side of the series reports it, and so does an admin
  const canReport = auth.isAdmin || (!!auth.me?.user?.id && [series?.player1_id, series?.player2_id].includes(auth.me.user.id)) || (!!auth.me && teamSided);

  // The fixture this series plays, once the event runs it through the events module: its
  // ordered series with their mode, their pick rule and the roster each side fields.
  const loadFixture = async (loaded: Row) => {
    const eventId = loaded.match?.season_id ?? loaded.match?.season?.id;
    if (!loaded.match_id || !eventId) return;
    const answer = await eventStore.fetchFixture(eventId, loaded.match_id).catch(() => null);
    // the same read answers the event, whose rounds name the fixed map of this round
    setRounds(answer?.event?.rounds || []);
    if (!answer?.series?.length) return;
    setFixture(answer.series);
    const teams = await teamStore.fetchTeamsBySeason(eventId).catch(() => []);
    setRosters(rostersOf(answer.series, teams, eventId));
  };

  const load = async () => {
    try {
      const loaded = await fetchWrapper.get(`${backendUrl}/series/${id}`);
      setSeries(loaded);
      // A series nobody reported records no game, and the table shows its rules alone
      setGames(await fetchWrapper.get(`${backendUrl}/series/${id}/games`).catch(() => []));
      await loadFixture(loaded);
    } catch (e) {
      setError(`The series did not load: ${(e as Error).message}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    mapStore.fetchMaps().then((rows: Row[]) => setMaps(rows || [])).catch(() => {}); // names the map of each game
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // A link from one series to the next keeps the page, so the read follows the route
  useEffect(() => {
    // the loader sets state, so it runs just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(load);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const saveRoster = async () => {
    setSavingRoster(true);
    setRosterError(null);
    try {
      await eventStore.setSideRoster(series!.id, rosterSide, picked);
      setRosterOpen(false);
      await load();
    } catch (e) {
      setRosterError((e as Error).message);
    } finally {
      setSavingRoster(false);
    }
  };

  const award = async (kind: string) => {
    setAwarding(true);
    setAwardError(null);
    try {
      await eventStore.awardSeries(series!.id, kind, awardSide);
      setAwardOpen(false);
      await load();
    } catch (e) {
      setAwardError((e as Error).message);
    } finally {
      setAwarding(false);
    }
  };

  return (
    <div className="p-4">
      <StatusAlert modelValue={error} onClose={() => setError(null)} />
      {loading ? <Progress value={null} /> : null}

      {series ? (
        <>
          <PageHeader title={title}>
            {/* One gap for every icon-and-text pair, as the event header sets them */}
            {place.length
              ? place.map((part) => (
                  <span key={part.text} className="inline-flex items-center gap-1.5 whitespace-nowrap text-muted-foreground">
                    <Icon name={part.icon} size={18} />
                    <span>{part.text}</span>
                  </span>
                ))
              : null}
          </PageHeader>

          <div className="grid gap-6 min-[960px]:grid-cols-12">
            <Card className="card gap-0 self-start py-0 min-[960px]:col-span-7">
              <CardHeader className="p-4">
                <CardTitle className="flex flex-wrap items-center gap-3">
                  <span>{bestOfLine}</span>
                  {stageRow ? <Badge className={toneClass(null)}>{mode}</Badge> : null}
                  {stageRow ? <Badge variant="outline">{pick}</Badge> : null}
                </CardTitle>
              </CardHeader>
              <div className="p-3">
                <SeriesBox readonly series={box as Row} rosters={rosters} />
              </div>
              <div className="flex flex-wrap items-center gap-2 px-3 pb-3">
                <CastChips series={series as CastSeries} />
                <span className="flex-1" />
                {hasVeto && canReport ? (
                  <Button nativeButton={false} variant="outline" size="sm" className="text-primary-text" render={<Link href={`/player-series/${series.id}/veto`} />}>
                    <Icon name="mdi-map-outline" />
                    Map veto
                  </Button>
                ) : null}
                {canReport ? (
                  <Button size="sm" onClick={() => reportDialog.current?.open(series)}>
                    <Icon name="mdi-trophy" />
                    {scored ? "Edit result" : "Report result"}
                  </Button>
                ) : null}
                {rosterSides.map((side) => (
                  <Button key={side} variant="outline" size="sm" className="text-primary-text" onClick={() => openRoster(side)}>
                    <Icon name="mdi-account-group" />
                    {rosterVerb(side)} {teamName(side)}
                  </Button>
                ))}
                {auth.isAdmin && !scored ? (
                  <Button variant="outline" size="sm" onClick={() => setAwardOpen(true)}>
                    <Icon name="mdi-account-cancel" />
                    No game played
                  </Button>
                ) : null}
              </div>
            </Card>

            <Card className="card gap-0 self-start py-0 min-[960px]:col-span-5">
              <CardHeader className="p-4">
                <CardTitle>Games</CardTitle>
              </CardHeader>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead style={{ width: "56px" }}>Game</TableHead>
                    <TableHead className={wideOnly}>Rule</TableHead>
                    <TableHead>Map</TableHead>
                    <TableHead>Winner</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {gameRows.map((row) => (
                    <TableRow key={row.game_no}>
                      <TableCell>
                        {row.game_no}
                        <div className={`${phoneOnly} text-xs whitespace-nowrap text-muted-foreground`}>{row.rule}</div>
                      </TableCell>
                      <TableCell className={wideOnly}>{row.rule}</TableCell>
                      <TableCell>{row.map}</TableCell>
                      <TableCell>
                        {/* The winner wears the win mark, never coloured text */}
                        {row.winner ? (
                          <span className="inline-flex items-center gap-1.5">
                            <i className="h-[1em] w-[3px] rounded-[2px] bg-win" />
                            {row.winner}
                          </span>
                        ) : (
                          <span className="text-muted-foreground">—</span>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Card>
          </div>

          {/* The whole fixture, so a reader reads the five series from any one of them */}
          {fixture.length > 1 ? <FixtureSeries className="mt-4" series={fixture} rosters={rosters} currentId={series.id} /> : null}

          {/* A captain names the players his side fields, out of the roster his team holds */}
          <Dialog open={rosterOpen} onOpenChange={setRosterOpen}>
            <DialogContent showCloseButton={false} className="max-w-[520px] gap-0 p-0 sm:max-w-[520px]">
              <DialogTitle className="bg-primary px-4 py-3 text-on-primary">Name the roster</DialogTitle>
              <div className="p-4">
                <StatusAlert modelValue={rosterError} onClose={() => setRosterError(null)} />
                <Field label={teamName(rosterSide)} htmlFor="series-roster" hint={`Pick ${sideSize} ${sideSize === 1 ? "player" : "players"}.`}>
                  <Select multiple value={picked} onValueChange={(value) => setPicked(value as number[])}>
                    <SelectTrigger id="series-roster" className="h-auto min-h-8 w-full py-1.5">
                      <SelectValue>{(ids: number[]) => ids.map((one) => rosterItems.find((item) => item.id === one)?.name ?? one).join(", ")}</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      {rosterItems.map((item) => (
                        <SelectItem key={item.id} value={item.id}>
                          <PlayerName player={item.player} race={item.race || undefined} plain />
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </Field>
              </div>
              <div className="flex justify-end gap-2 p-4 pt-0">
                <Button variant="ghost" disabled={savingRoster} onClick={() => setRosterOpen(false)}>
                  Cancel
                </Button>
                <Button disabled={picked.length !== sideSize || savingRoster} onClick={saveRoster}>
                  <Icon name={savingRoster ? "mdi-loading mdi-spin" : "mdi-content-save"} />
                  Save roster
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          {/* An admin scores a series nobody played: the side that takes it, then the kind */}
          <Dialog open={awardOpen} onOpenChange={setAwardOpen}>
            <DialogContent showCloseButton={false} className="max-w-[480px] gap-0 p-0 sm:max-w-[480px]">
              <DialogTitle className="bg-primary px-4 py-3 text-on-primary">No game played</DialogTitle>
              <div className="p-4">
                <StatusAlert modelValue={awardError} onClose={() => setAwardError(null)} />
                <p className="mb-3">Pick the side that takes the series.</p>
                <ToggleGroup variant="outline" spacing={0} className="w-full" aria-label="Side that takes the series" value={awardSide ? [String(awardSide)] : []} onValueChange={(value) => setAwardSide(value[0] ? Number(value[0]) : null)}>
                  {[1, 2].map((side) => (
                    <ToggleGroupItem key={side} value={String(side)} className={SIDE_BUTTON}>
                      {sideName(side)}
                    </ToggleGroupItem>
                  ))}
                </ToggleGroup>
              </div>
              <div className="flex justify-end gap-2 p-4 pt-0">
                <Button variant="ghost" disabled={awarding} onClick={() => setAwardOpen(false)}>
                  Close
                </Button>
                <Button variant="outline" disabled={!awardSide || awarding} onClick={() => award("walkover")}>
                  Walkover
                </Button>
                <Button variant="outline" disabled={!awardSide || awarding} onClick={() => award("forfeit")}>
                  Forfeit
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          {canReport ? <ReportResultDialog ref={reportDialog} onSaved={load} /> : null}
        </>
      ) : null}
    </div>
  );
}

export default SeriesView;

// src/views/SeriesView.vue
<!-- One series, whatever event it belongs to: the event it is played in, the two sides
     and the score, the rule and the map of every game, who casts it, and for a side or
     an admin the report action. A bracket box and the fixture page both open it. -->
<template>
  <v-container fluid class="pa-4">
    <StatusAlert v-model="error" />
    <v-progress-linear v-if="loading" indeterminate />

    <template v-if="series">
      <h1 class="text-h5 text-md-h3 font-weight-bold">{{ title }}</h1>
      <div class="d-flex flex-wrap align-center facts mt-2">
        <span v-for="part in place" :key="part.text" class="fact text-medium-emphasis">
          <v-icon size="18" :icon="part.icon" /><span>{{ part.text }}</span>
        </span>
      </div>

      <v-row class="mt-2">
        <v-col cols="12" md="7">
          <v-card elevation="2">
            <v-card-title class="d-flex align-center ga-3 flex-wrap">
              <span>{{ bestOfLine }}</span>
              <v-chip v-if="stageRow" size="x-small" variant="tonal">{{ mode }}</v-chip>
              <v-chip v-if="stageRow" size="x-small" variant="outlined">{{ pick }}</v-chip>
            </v-card-title>
            <div class="pa-3">
              <SeriesBox readonly :series="box" :rosters="rosters" />
            </div>
            <v-card-actions class="flex-wrap ga-2 px-3 pb-3">
              <CastChips :series="series" />
              <v-spacer />
              <v-btn v-if="hasVeto && canReport" variant="outlined" color="primary" size="small"
                prepend-icon="mdi-map-outline" :to="`/player-series/${series.id}/veto`">
                Map veto
              </v-btn>
              <v-btn v-if="canReport" variant="elevated" color="primary" size="small"
                prepend-icon="mdi-trophy" @click="reportDialog.open(series)">
                {{ scored ? 'Edit result' : 'Report result' }}
              </v-btn>
              <v-btn v-for="side in rosterSides" :key="side" variant="outlined" color="primary"
                size="small" prepend-icon="mdi-account-group" @click="openRoster(side)">
                {{ rosterVerb(side) }} {{ teamName(side) }}
              </v-btn>
              <v-btn v-if="auth.isAdmin && !scored" variant="outlined" size="small"
                prepend-icon="mdi-account-cancel" @click="awardOpen = true">
                No game played
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-col>

        <v-col cols="12" md="5">
          <v-card elevation="2">
            <v-card-title>Games</v-card-title>
            <v-table density="comfortable">
              <thead>
                <tr>
                  <th style="width: 56px">Game</th>
                  <th class="d-none d-sm-table-cell">Rule</th>
                  <th>Map</th>
                  <th>Winner</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="row in gameRows" :key="row.game_no">
                  <td>
                    {{ row.game_no }}
                    <div class="d-sm-none text-caption text-medium-emphasis text-no-wrap">{{ row.rule }}</div>
                  </td>
                  <td class="d-none d-sm-table-cell">{{ row.rule }}</td>
                  <td>{{ row.map }}</td>
                  <td>
                    <span v-if="row.winner" class="winner">
                      <i class="mark" />{{ row.winner }}
                    </span>
                    <span v-else class="text-medium-emphasis">—</span>
                  </td>
                </tr>
              </tbody>
            </v-table>
          </v-card>
        </v-col>
      </v-row>

      <!-- The whole fixture, so a reader reads the five series from any one of them -->
      <FixtureSeries v-if="fixture.length > 1" class="mt-4" :series="fixture" :rosters="rosters"
        :current-id="series.id" />

      <!-- A captain names the players his side fields, out of the roster his team holds -->
      <v-dialog v-model="rosterOpen" max-width="520">
        <v-card>
          <v-card-title class="bg-primary">Name the roster</v-card-title>
          <v-card-text class="pt-4">
            <StatusAlert v-model="rosterError" />
            <v-select v-model="picked" :items="rosterItems" item-value="id" item-title="name"
              :label="teamName(rosterSide)" variant="outlined" density="comfortable" multiple
              :hint="`Pick ${sideSize} ${sideSize === 1 ? 'player' : 'players'}.`" persistent-hint>
              <template #item="{ props: itemProps, item }">
                <v-list-item v-bind="itemProps" :title="null" :active="picked.includes(item.raw.id)">
                  <template #prepend>
                    <v-checkbox-btn :model-value="picked.includes(item.raw.id)" tabindex="-1" />
                  </template>
                  <PlayerName :player="item.raw.player" :race="item.raw.race || undefined" plain />
                </v-list-item>
              </template>
            </v-select>
          </v-card-text>
          <v-card-actions>
            <v-spacer />
            <v-btn variant="text" :disabled="savingRoster" @click="rosterOpen = false">Cancel</v-btn>
            <v-btn color="primary" variant="elevated" prepend-icon="mdi-content-save"
              :disabled="picked.length !== sideSize || savingRoster" :loading="savingRoster"
              @click="saveRoster">Save roster</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>

      <!-- An admin scores a series nobody played: the side that takes it, then the kind -->
      <v-dialog v-model="awardOpen" max-width="480">
        <v-card>
          <v-card-title class="bg-primary">No game played</v-card-title>
          <v-card-text class="pt-4">
            <StatusAlert v-model="awardError" />
            <p class="mb-3">Pick the side that takes the series.</p>
            <v-btn-toggle v-model="awardSide" color="primary" divided variant="outlined"
              density="comfortable" class="d-flex">
              <v-btn :value="1" class="flex-grow-1">{{ sideName(1) }}</v-btn>
              <v-btn :value="2" class="flex-grow-1">{{ sideName(2) }}</v-btn>
            </v-btn-toggle>
          </v-card-text>
          <v-card-actions>
            <v-spacer />
            <v-btn variant="text" :disabled="awarding" @click="awardOpen = false">Close</v-btn>
            <v-btn variant="outlined" :disabled="!awardSide || awarding" :loading="awarding"
              @click="award('walkover')">Walkover</v-btn>
            <v-btn variant="outlined" :disabled="!awardSide || awarding" :loading="awarding"
              @click="award('forfeit')">Forfeit</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>

      <ReportResultDialog v-if="canReport" ref="reportDialog" @saved="load" />
    </template>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';

import CastChips from '@/components/CastChips.vue';
import FixtureSeries from '@/components/FixtureSeries.vue';
import PlayerName from '@/components/PlayerName.vue';
import ReportResultDialog from '@/components/ReportResultDialog.vue';
import SeriesBox from '@/components/SeriesBox.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import { backendUrl, fetchWrapper } from '@/helpers';
import { eventLabel, MAP_RULES, timeText, titleOf } from '@/helpers/event-labels.mjs';
import {
  fixtureRosters, modeLabel, pickLabel, rosterSides as sidesFor, sideRoster,
} from '@/helpers/fixture.mjs';
import { rulesOf } from '@/helpers/map-order.mjs';
import { isScored, sideName as nameOfSide } from '@/helpers/stage-view.mjs';
import { useAuthStore, useEventStore, useMapStore, useTeamStore } from '@/stores';

const route = useRoute();
const auth = useAuthStore();
const eventStore = useEventStore();
const mapStore = useMapStore();
const teamStore = useTeamStore();

const series = ref(null);
const games = ref([]);
const fixture = ref([]);   // every series the fixture holds, in play order
const rosters = ref({});   // the roster each team entrant fields for the event, by entrant id
const rosterOpen = ref(false);
const rosterSide = ref(1);
const picked = ref([]);
const rosterError = ref(null);
const savingRoster = ref(false);
const loading = ref(true);
const error = ref(null);
const reportDialog = ref(null);
const awardOpen = ref(false);
const awardSide = ref(null);
const awardError = ref(null);
const awarding = ref(false);

// The event of a series inside a fixture is its season; a bracket series names none yet
const event = computed(() => series.value?.match?.season || null);
const title = computed(() => (event.value ? eventLabel(event.value) : 'Series'));
const scored = computed(() => isScored(series.value));

// The line under the title: where the series is played and when
const place = computed(() => [
  series.value?.match?.playday ? { icon: 'mdi-tournament', text: `Round ${series.value.match.playday}` } : null,
  series.value?.date_time ? { icon: 'mdi-calendar-clock', text: timeText(series.value.date_time) } : null,
].filter(Boolean));

// One rule per game, so their count is the best-of
const rules = computed(() => rulesOf(series.value?.rules?.map_rules));
const bestOfLine = computed(() => `Best of ${series.value?.rules?.best_of || rules.value.length}`);
const hasVeto = computed(() => rules.value.includes('veto'));

const sideName = (side) => nameOfSide(box.value, side) || `Side ${side}`;

// The stage row of this series carries what it plays and who fields it; GET /series/{id}
// answers neither, so a series inside a fixture reads them off the fixture.
const stageRow = computed(() => fixture.value.find((row) => row.id === series.value?.id) || null);
const box = computed(() => stageRow.value || series.value);
const mode = computed(() => modeLabel(stageRow.value?.side_size));
const pick = computed(() => pickLabel(stageRow.value?.pick_rule));
const sideSize = computed(() => stageRow.value?.side_size || 1);
const teamName = (side) => stageRow.value?.[`team${side}`]?.name || `side ${side}`;

// A captain names his own side, an admin either; a side already named is changed, not written
const rosterSides = computed(() => sidesFor(
  stageRow.value, rosters.value, auth.me?.user?.id, auth.isAdmin,
));
const rosterVerb = (side) => (sideRoster(stageRow.value, side).length ? 'Change' : 'Name');
const rosterItems = computed(() => (rosters.value[stageRow.value?.[`entrant${rosterSide.value}_id`]] || [])
  .map((seat) => ({ id: seat.player.id, name: seat.player.name, player: seat.player, race: seat.race })));

const openRoster = (side) => {
  rosterSide.value = side;
  rosterError.value = null;
  picked.value = sideRoster(stageRow.value, side).map((player) => player.id);
  rosterOpen.value = true;
};

const saveRoster = async () => {
  savingRoster.value = true;
  rosterError.value = null;
  try {
    await eventStore.setSideRoster(series.value.id, rosterSide.value, picked.value);
    rosterOpen.value = false;
    await load();
  } catch (e) {
    rosterError.value = e.message;
  } finally {
    savingRoster.value = false;
  }
};

const mapName = (id) => mapStore.maps.find((row) => row.id === id)?.name;

// One row per game of the best-of: its rule, the map it was played on or the one the
// rule offers, and the side that won it
const gameRows = computed(() => rules.value.map((rule, index) => {
  const game = games.value.find((row) => row.game_no === index + 1);
  return {
    game_no: index + 1,
    rule: titleOf(MAP_RULES, rule),
    map: mapName(game?.map_id ?? game?.offered_map_id) || '—',
    winner: game?.winner_side ? sideName(game.winner_side === 'A' ? 1 : 2) : null,
  };
}));

// A team side names no player of its own, so any logged-in member may open the report
// and the API answers whether he acts for the side; the 403 reads as the dialog's alert.
const teamSided = computed(() => !!series.value
  && ((!series.value.match && !series.value.player1_id && !series.value.player2_id)
    || !!stageRow.value?.entrant1_id));
// A side of the series reports it, and so does an admin
const canReport = computed(() => auth.isAdmin
  || [series.value?.player1_id, series.value?.player2_id].includes(auth.me?.user?.id)
  || (!!auth.me && teamSided.value));

const award = async (kind) => {
  awarding.value = true;
  awardError.value = null;
  try {
    await eventStore.awardSeries(series.value.id, kind, awardSide.value);
    awardOpen.value = false;
    await load();
  } catch (e) {
    awardError.value = e.message;
  } finally {
    awarding.value = false;
  }
};

// The fixture this series plays, once the event runs it through the events module: its
// ordered series with their mode, their pick rule and the roster each side fields.
const loadFixture = async () => {
  const eventId = series.value?.match?.season_id ?? series.value?.match?.season?.id;
  if (!series.value?.match_id || !eventId) return;
  const answer = await eventStore.fetchFixture(eventId, series.value.match_id).catch(() => null);
  if (!answer?.series?.length) return;
  fixture.value = answer.series;
  await teamStore.fetchTeamsBySeason(eventId).catch(() => {});
  rosters.value = fixtureRosters(answer.series, teamStore.teams, eventId);
};

const load = async () => {
  const id = route.params.id;
  try {
    series.value = await fetchWrapper.get(`${backendUrl}/series/${id}`);
    // A series nobody reported records no game, and the table shows its rules alone
    games.value = await fetchWrapper.get(`${backendUrl}/series/${id}/games`).catch(() => []);
    await loadFixture();
  } catch (e) {
    error.value = `The series did not load: ${e.message}`;
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  if (!mapStore.maps.length) mapStore.fetchMaps().catch(() => {});  // names the map of each game
  load();
});

// A link from one series to the next keeps the page, so the read follows the route
watch(() => route.params.id, load);
</script>

<style scoped>
/* One gap for every icon-and-text pair, as the event header sets them */
.facts { gap: 4px 20px; }
.fact {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  white-space: nowrap;
}
/* The winner wears the win mark, never coloured text */
.winner { display: inline-flex; align-items: center; gap: 6px; }
.mark {
  width: 3px;
  height: 1em;
  border-radius: 2px;
  background: rgb(var(--v-theme-win));
}
</style>
