// next/src/app/(app)/teams/TeamsView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { PageHeader } from "@/components/PageHeader";
import { RowActions } from "@/components/RowActions";
import { StatusAlert } from "@/components/StatusAlert";
import { useDeleteDialog } from "@/hooks/delete-dialog";
import { loadSeasons, resolveCurrentSeasonId } from "@/helpers/current-season.js";
import { showDefaultTeamImage, teamImageUrl } from "@/helpers/team-image.js";
import { useAuth, useSeason, useTeamStore } from "@/stores";

type Row = Record<string, any>;
const WIDE = "hidden min-[960px]:table-cell";
const emptyTeam = () => ({ name: "", long_name: "" });
const errorText = (error: unknown) => error instanceof Error ? error.message : typeof error === "string" ? error : "Unknown error";

export function TeamsView() {
  const router = useRouter();
  const teamStore = useTeamStore();
  const seasonStore = useSeason();
  const { isAdmin } = useAuth();
  const fileInput = useRef<HTMLInputElement>(null);
  const deletion = useDeleteDialog();
  const [teams, setTeams] = useState<Row[]>([]);
  const [currentSeasonId, setCurrentSeasonId] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dialog, setDialog] = useState(false);
  const [editing, setEditing] = useState(false);
  const [selected, setSelected] = useState<Row>(emptyTeam);
  const [file, setFile] = useState<File | null>(null);
  const [formError, setFormError] = useState<string | null>(null);

  const fetchTeams = async () => {
    setLoading(true); setError(null);
    try { setTeams((await teamStore.fetchTeams()) || []); }
    catch (e) { console.error("Failed to load teams:", e); setError("Failed to load Teams. Please try again later."); }
    finally { setLoading(false); }
  };
  useEffect(() => {
    const start = async () => { await loadSeasons(); setCurrentSeasonId(await resolveCurrentSeasonId()); await fetchTeams(); };
    start();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const playedSeasons = (team: Row) => (team.seasons_info || []).map((info: Row) => seasonStore.seasons.find((season) => season.id === info.season_id)).filter(Boolean).sort((a: Row, b: Row) => b.id - a.id);
  const currentName = seasonStore.seasons.find((season) => season.id === currentSeasonId)?.name;
  const playsCurrent = (team: Row) => (team.seasons_info || []).some((info: Row) => info.season_id === currentSeasonId);
  const groups = !currentSeasonId ? [{ title: "All teams", items: teams }] : [{ title: currentName || "Current season", items: teams.filter(playsCurrent) }, { title: "Past teams", items: teams.filter((team) => !playsCurrent(team)) }];
  const set = (key: string, value: unknown) => setSelected((old) => ({ ...old, [key]: value }));
  const close = () => { setDialog(false); setFile(null); setSelected(emptyTeam()); if (fileInput.current) fileInput.current.value = ""; };
  const openCreate = () => { setSelected(emptyTeam()); setFile(null); setFormError(null); setEditing(false); setDialog(true); };
  const openEdit = (team: Row) => { setSelected({ id: team.id, league_id: team.league_id, name: team.name, long_name: team.long_name }); setFile(null); setFormError(null); setEditing(true); setDialog(true); };
  const save = async () => {
    setFormError(null);
    if (editing) {
      try { await teamStore.updateTeam(selected); if (file) await teamStore.uploadTeamImage(selected.id, file, selected.league_id); await fetchTeams(); close(); }
      catch (e) { console.error("Error updating Team:", e); setFormError("Error updating Team: " + errorText(e)); }
      return;
    }
    let created: Row;
    try {
      if (teams.some((team) => team.name.toLowerCase() === selected.name.toLowerCase())) throw new Error(`Team with name ${selected.name} already exists`);
      created = await teamStore.createTeam(selected);
    } catch (e) { console.error("Error creating Team:", e); setFormError("Error creating Team: " + errorText(e)); return; }
    if (file) {
      try { await teamStore.uploadTeamImage(created.id, file, created.league_id); }
      catch (e) { console.error("Error uploading team icon:", e); await fetchTeams(); setFile(null); setSelected({ id: created.id, league_id: created.league_id, name: created.name, long_name: created.long_name }); setFormError("Team created, but icon upload failed: " + errorText(e)); setEditing(true); return; }
    }
    await fetchTeams(); close();
  };
  const remove = async (id?: number | string) => { setError(null); try { await teamStore.deleteTeam(Number(id)); await fetchTeams(); } catch (e) { console.error("Error deleting Team:", e); setError("Error deleting Team: " + errorText(e)); } };

  return <div className="p-4">
    {loading ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60"><Icon name="mdi-loading" size={64} className="animate-spin text-primary" /></div> : null}
    <PageHeader title={<span className="inline-flex items-center gap-2"><Icon name="mdi-shield-account" />Teams</span>} />
    <StatusAlert modelValue={error} onClose={() => setError(null)} />
    {isAdmin ? <div className="mb-4 flex justify-end"><Button onClick={openCreate}><Icon name="mdi-plus" />Add team</Button></div> : null}
    {!error ? groups.map((group) => <Card key={group.title} className="card mb-4 gap-0 py-0">
      <CardTitle className="flex items-center gap-2 bg-primary p-4 text-on-primary"><Icon name="mdi-format-list-bulleted" />{group.title}</CardTitle>
      <CardContent className="p-0"><div className="table-scroll overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="w-16" /><TableHead>Long name</TableHead><TableHead>Handle</TableHead><TableHead className={WIDE}>Seasons</TableHead>{isAdmin ? <TableHead /> : null}</TableRow></TableHeader><TableBody>
        {group.items.map((team) => <TableRow key={team.id} className="cursor-pointer" onClick={() => router.push(`/team/${team.id}`)}><TableCell><span className="block size-10 overflow-hidden rounded-full"><img className="size-full object-cover" src={teamImageUrl(team)} alt="" onError={showDefaultTeamImage} /></span></TableCell><TableCell><Link href={`/team/${team.id}`}><strong>{team.long_name || team.name}</strong></Link></TableCell><TableCell>{team.name}</TableCell><TableCell className={WIDE}>{playedSeasons(team).length ? <span className="flex flex-wrap gap-1">{playedSeasons(team).map((season: Row) => <Badge key={season.id} variant={season.id === currentSeasonId ? "default" : "secondary"}>{season.name}</Badge>)}</span> : "—"}</TableCell>{isAdmin ? <TableCell><RowActions actions={[{ icon: "mdi-pencil", label: "Edit team", onClick: () => openEdit(team) }, { icon: "mdi-delete", label: "Delete team", color: "error", onClick: () => deletion.openDeleteDialog(team.id, remove) }]} /></TableCell> : null}</TableRow>)}
        {!group.items.length ? <TableRow><TableCell colSpan={isAdmin ? 5 : 4} className="py-8 text-center"><Icon name="mdi-shield-off" size={64} className="text-muted-foreground" /><div className="mt-4 text-lg text-muted-foreground">No teams found</div>{isAdmin ? <Button variant="outline" className="mt-4" onClick={openCreate}><Icon name="mdi-plus" />Create first team</Button> : null}</TableCell></TableRow> : null}
      </TableBody></Table></div></CardContent>
    </Card>) : null}
    <Dialog open={dialog} onOpenChange={(open) => open ? setDialog(true) : close()}><DialogContent showCloseButton={false} className="max-w-[600px] gap-0 p-0 sm:max-w-[600px]"><DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary"><Icon name={editing ? "mdi-pencil" : "mdi-plus-circle"} />{editing ? `Edit team: ${selected.name ?? ""}` : "Add team"}</DialogTitle><div className="p-4 pb-0"><StatusAlert modelValue={formError} onClose={() => setFormError(null)} /></div><div className="grid gap-4 p-4 md:grid-cols-2"><Field label="Team name" htmlFor="team-name"><Input id="team-name" value={selected.name ?? ""} onChange={(e) => set("name", e.target.value)} /></Field><Field label="Team long name" htmlFor="team-long-name"><Input id="team-long-name" value={selected.long_name ?? ""} onChange={(e) => set("long_name", e.target.value)} /></Field><Field label="Team icon" htmlFor="team-icon" hint="Max 64 KB · PNG or JPG (MySQL BLOB limit)"><Input id="team-icon" ref={fileInput} type="file" accept=".png,.jpg" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></Field></div><div className="flex justify-end gap-2 p-4 pt-0"><Button variant="ghost" onClick={close}>Cancel</Button>{isAdmin ? <Button onClick={save}><Icon name="mdi-check" />{editing ? "Save changes" : "Create team"}</Button> : null}</div></DialogContent></Dialog>
    <ConfirmDeleteDialog modelValue={deletion.showDeleteDialog} message="Are you sure you want to delete this team? This action cannot be undone." onConfirm={deletion.confirmDelete} onCancel={deletion.cancelDeleteDialog} onUpdateModelValue={(open) => !open && deletion.cancelDeleteDialog()} />
  </div>;
}

export default TeamsView;

// src/views/TeamsView.vue
<template>
  <v-container fluid class="pa-4">
    <v-row class="mb-4">
      <v-col>
        <h1 class="text-h5 text-md-h3 font-weight-bold">
          <v-icon class="mr-2" size="large">mdi-shield-account</v-icon>
          Teams
        </h1>
      </v-col>
    </v-row>

    <v-overlay v-model="isLoading" persistent class="align-center justify-center">
      <v-progress-circular indeterminate size="64" width="8" color="primary" />
    </v-overlay>

    <!-- Error Message -->
    <v-alert v-if="errorMessage" type="error" variant="tonal" class="mb-4" closable @click:close="errorMessage = null">
      {{ errorMessage }}
    </v-alert>

    <div v-if="auth.isAdmin" class="d-flex justify-end mb-4">
      <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" @click="createTeam()">
        Add team
      </v-btn>
    </div>

    <!-- The season's own teams first, so the historical ones do not bury them -->
    <v-card v-for="group in groups" v-show="!errorMessage" :key="group.title" elevation="2" class="mb-4">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-format-list-bulleted</v-icon>
        {{ group.title }}
      </v-card-title>

      <v-card-text class="pa-0">
        <v-data-table
          :headers="tableHeader"
          :items="group.items"
          :loading="isLoading"
          :hide-default-footer="group.items.length <= 10"
          hover
          density="comfortable"
          @click:row="openTeam"
        >
          <template #loading>
            <v-skeleton-loader type="table-row@10" />
          </template>

          <template #[`item.icon`]="{ item }">
            <v-avatar size="40">
              <img class="team-icon" alt="" :src="teamImageUrl(item)" @error="showDefaultTeamImage">
            </v-avatar>
          </template>

          <template #[`item.long_name`]="{ item }">
            <RouterLink :to="`/team/${item.id}`"><strong>{{ item.long_name || item.name }}</strong></RouterLink>
          </template>

          <template #[`item.seasons`]="{ item }">
            <template v-if="playedSeasons(item).length">
              <v-chip
                v-for="season in playedSeasons(item)"
                :key="season.id"
                size="small"
                class="ma-1"
                :color="season.id === currentSeasonId ? 'primary' : undefined"
                :variant="season.id === currentSeasonId ? 'flat' : 'tonal'"
              >
                {{ season.name }}
              </v-chip>
            </template>
            <span v-else>—</span>
          </template>

          <template #[`item.actions`]="{ item }">
            <div @click.stop>
              <RowActions :actions="[
                { icon: 'mdi-pencil', label: 'Edit team', onClick: () => editTeam(item) },
                { icon: 'mdi-delete', label: 'Delete team', color: 'error', onClick: () => openDeleteDialog(item.id, removeTeam) },
              ]" />
            </div>
          </template>

          <template #no-data>
            <div class="text-center pa-8">
              <v-icon size="64" class="text-disabled">mdi-shield-off</v-icon>
              <div class="text-h6 mt-4 text-medium-emphasis">No teams found</div>
              <v-btn
                color="primary"
                variant="tonal"
                class="mt-4"
                prepend-icon="mdi-plus"
                v-if="auth.isAdmin"
                @click="createTeam"
              >
                Create first team
              </v-btn>
            </div>
          </template>
        </v-data-table>
      </v-card-text>
    </v-card>

    <!-- Add / Edit Team Dialog -->
    <v-dialog v-model="showTeamModal" max-width="600px" persistent>
      <v-card>
        <v-card-title class="bg-primary">
          <v-icon class="mr-2">{{ isEditing ? 'mdi-pencil' : 'mdi-plus-circle' }}</v-icon>
          {{ isEditing ? `Edit team: ${selectedTeam?.name ?? ''}` : 'Add team' }}
        </v-card-title>

        <v-alert v-if="formError" type="error" variant="tonal" class="mx-4 mt-4 mb-2" border="start" border-color="error" closable @click:close="formError = ''">
          {{ formError }}
        </v-alert>

        <v-card-text class="pt-4">
          <v-row dense>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="selectedTeam.name"
                label="Team name"
                variant="outlined"
                density="comfortable"
                prepend-inner-icon="mdi-shield"
              />
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field
                v-model="selectedTeam.long_name"
                label="Team long name"
                variant="outlined"
                density="comfortable"
                prepend-inner-icon="mdi-text"
              />
            </v-col>
            <v-col cols="12" md="6">
              <v-file-input
                v-model="file"
                label="Team icon"
                accept=".png,.jpg"
                variant="outlined"
                density="comfortable"
                prepend-icon=""
                prepend-inner-icon="mdi-image"
                hint="Max 64 KB · PNG or JPG (MySQL BLOB limit)"
                persistent-hint
              />
            </v-col>
          </v-row>
        </v-card-text>

        <v-card-actions class="px-4 py-3">
          <v-spacer></v-spacer>
          <v-btn variant="text" @click="closeTeamDialog">Cancel</v-btn>
          <v-btn v-if="auth.isAdmin" color="primary" prepend-icon="mdi-check" @click="isEditing ? updateTeam() : createNewTeam()">{{ isEditing ? 'Save Changes' : 'Create Team' }}</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <ConfirmDeleteDialog
      v-model="showDeleteDialog"
      message="Are you sure you want to delete this team? This action cannot be undone."
      @confirm="confirmDelete"
      @cancel="cancelDeleteDialog"
    />
  </v-container>
</template>
<script setup>
import RowActions from '@/components/RowActions.vue';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';
import { useAuthStore, useSeasonStore, useTeamStore } from '@/stores';
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { storeToRefs } from 'pinia';
import { loadSeasons, resolveCurrentSeasonId } from '@/helpers/current-season';
import { teamImageUrl, showDefaultTeamImage } from '@/helpers/team-image';
import { useDeleteDialog } from '@/helpers/delete-dialog';
import { useColumns } from '@/helpers/columns';

const extractErrorMessage = (error) => {
  if (!error) return 'Unknown error';
  if (typeof error === 'string') return error;
  if (error.error) return error.error;
  if (error.message) return error.message;
  return JSON.stringify(error);
};


// Store initialization and refs
const teamStore = useTeamStore();
const auth = useAuthStore();
const { teams } = storeToRefs(teamStore);

// State for editing
const selectedTeam = ref(null);
const isLoading  = ref(false); // State for selected user
const errorMessage = ref(null);
const showTeamModal = ref(false);
const isEditing = ref(false);
const formError = ref('');


const file = ref(null);

const allTableHeader = computed(() => [
  { title:'', value: 'icon'},
  { title: 'Long name', value: 'long_name', sortable: true },
  { title: 'Handle', value: 'name', sortable: true },
  { mobile: false, title: 'Seasons', value: 'seasons', sortable: false },
  ...(auth.isAdmin ? [{ title: '', value: 'actions', align: 'end', sortable: false }] : []),
])
const tableHeader = useColumns(allTableHeader);

// The seasons a team played, newest first; the team list carries one row per season
const currentSeasonId = ref(null);
const seasonStore = useSeasonStore();
const playedSeasons = (team) => (team.seasons_info || [])
  .map((info) => seasonStore.seasons.find((season) => season.id === info.season_id))
  .filter(Boolean)
  .sort((a, b) => b.id - a.id);

const currentSeasonName = computed(() =>
  seasonStore.seasons.find((season) => season.id === currentSeasonId.value)?.name
);
const playsCurrentSeason = (team) =>
  (team.seasons_info || []).some((info) => info.season_id === currentSeasonId.value);

const groups = computed(() => {
  if (!currentSeasonId.value) return [{ title: 'All teams', items: teams.value }];
  return [
    { title: currentSeasonName.value || 'Current season', items: teams.value.filter(playsCurrentSeason) },
    { title: 'Past teams', items: teams.value.filter((team) => !playsCurrentSeason(team)) },
  ];
});

const router = useRouter();
const openTeam = (event, { item }) => router.push(`/team/${item.id}`);
// Fetch data when the page is loaded
const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

// Fetch users when the component is mounted
const fetchTeams = async () => {
  
  isLoading.value = true;
  errorMessage.value = null; // Reset error message
  try {
    await teamStore.fetchTeams(); // Fetch user data


    if (teamStore.teams.length === 0) {
      errorMessage.value = 'No Teams found.';
    }
  } catch (error) {
    errorMessage.value = 'Failed to load Teams. Please try again later.';
  } finally {
    isLoading.value = false;
  }
};

onMounted(async () => {
  await loadSeasons();  // the season chips need the names
  currentSeasonId.value = await resolveCurrentSeasonId();
  fetchTeams();
});

const createTeam = () => {
  selectedTeam.value = {
    name: '',
    long_name: ''
  }
  formError.value = '';
  isEditing.value = false;
  showTeamModal.value = true;
};

const editTeam = (team) => {
  selectedTeam.value = {
    id: team.id,
    name: team.name,
    long_name: team.long_name
  };
  formError.value = '';
  isEditing.value = true;
  showTeamModal.value = true;
};

const updateTeam = async () => {
  formError.value = '';
  try {
    await teamStore.updateTeam(selectedTeam.value);
    if(file.value){
      await teamStore.uploadTeamImage(selectedTeam.value.id, file.value);
    }
    // Update the local state after a successful PUT request
    await fetchTeams(); // Re-fetch the Teams
    closeTeamDialog(); // Reset the form
  } catch (error) {
    console.error('Error updating Team:', error);
    formError.value = 'Error updating Team: ' + extractErrorMessage(error);
  }
};

const createNewTeam = async () => {
  formError.value = ''; // Reset error
  let createdTeam = null;
  try {
    const nameExists = teamStore.teams.some(
      team => team.name.toLowerCase() === selectedTeam.value.name.toLowerCase()
    );

    if (nameExists) {
      throw Error(`Team with name ${selectedTeam.value.name} already exists`);
    }

    createdTeam = await teamStore.createTeam(selectedTeam.value);
  } catch (error) {
    console.error('Error creating Team:', error);
    formError.value = 'Error creating Team: ' + extractErrorMessage(error);
    return;
  }

  // Team created successfully — now try the image upload separately
  if (file.value) {
    try {
      await teamStore.uploadTeamImage(createdTeam.id, file.value);
    } catch (imgError) {
      console.error('Error uploading team icon:', imgError);
      // Switch to edit mode so retrying the icon doesn't create a duplicate team
      await fetchTeams();
      file.value = null;
      selectedTeam.value = {
        id: createdTeam.id,
        name: createdTeam.name,
        long_name: createdTeam.long_name
      };
      formError.value = 'Team created, but icon upload failed: ' + extractErrorMessage(imgError);
      isEditing.value = true;
      return;
    }
  }

  await fetchTeams();
  closeTeamDialog();
};

const removeTeam = async (teamId) => {
  errorMessage.value = '';
  try {
    await teamStore.deleteTeam(teamId);
    await fetchTeams(); // Refresh the list after deletion
  } catch (error) {
    console.error('Error deleting Team:', error);
    errorMessage.value = 'Error deleting Team:' + error.message;
  }
};


const closeTeamDialog = () => {
  showTeamModal.value = false;
  file.value = null;
  selectedTeam.value = {
    name: '',
    long_name: ''
  };
};

</script>

<style scoped>

.team-icon {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>
