// next/src/app/(app)/upcoming/UpcomingView.tsx
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Icon } from "@/components/ui/Icon";
import { Progress } from "@/components/ui/progress";
import { toneClass } from "@/components/ui/tone";
import { CastChips, type CastSeries } from "@/components/CastChips";
import { GroupedTable } from "@/components/GroupedTable";
import { PlayerName } from "@/components/PlayerName";
import { SeriesCard } from "@/components/SeriesCard";
import { StatusAlert } from "@/components/StatusAlert";
import { SM_AND_DOWN, useBreakpoint } from "@/hooks/breakpoint";
import { resolveCurrentSeason } from "@/helpers/current-season";
import { eventLabel } from "@/helpers/event-labels.mjs";
import { local, scheduleDays } from "@/helpers/schedule.mjs";
import { isUnscored } from "@/helpers/season-phase.mjs";
import { gmt } from "@/helpers/timezone.mjs";
import { useSeriesStore } from "@/stores";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;
type Day = { key: string; title: string; cast: number; rows: CastSeries[] };

const columns = [
  { key: "time", title: "Time" },
  { key: "round", title: "Round" },
  { key: "player1", title: "Player 1" },
  { key: "player2", title: "Player 2" },
  { key: "score", title: "Score" },
  { key: "cast", title: "Cast" },
];

const timeOf = (value: string) => {
  const at = local(value);
  return `${at.toFormat("HH:mm")} ${gmt(at.offset)}`;
};
const scoreOf = (row: Row) => (isUnscored(row) ? "—" : `${row.player1_score}-${row.player2_score}`);
const teamsOf = (row: Row) => (row.match?.team1 && row.match?.team2 ? `${row.match.team1.name} vs ${row.match.team2.name}` : null);
const roundLink = (row: Row) => <Link href={`/match/${row.match_id}`}>Round {row.match?.playday ?? "?"}</Link>;
const dayLine = (group: Day) => (
  <>
    <strong>{group.title}</strong>
    <span className="ml-2 text-muted-foreground">
      {group.rows.length} series, {group.cast} cast
    </span>
  </>
);

/** Every scheduled series of the current season in time order: what is on tonight,
 *  what a caster can still claim, and where last week's VODs go. */
export function UpcomingView() {
  const seriesStore = useSeriesStore();
  const smAndDown = useBreakpoint(SM_AND_DOWN);
  const [season, setSeason] = useState<Row | null>(null);
  const [series, setSeries] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const days: Day[] = scheduleDays(series);

  useEffect(() => {
    const load = async () => {
      try {
        const current = await resolveCurrentSeason();
        setSeason(current);
        if (!current) throw new Error("No current season");
        setSeries((await seriesStore.searchSeriesBySeason(current.id)) || []);
      } catch (e) {
        setError("Failed to load the schedule.");
        console.error("Failed to load the schedule:", e);
      } finally {
        setLoading(false);
      }
    };
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="p-4">
      <Card className="card gap-0 py-0">
        <CardHeader className="bg-primary p-4">
          <CardTitle className="flex items-center gap-2 text-on-primary">
            <Icon name="mdi-calendar-clock" />
            Upcoming series
            {season?.name ? (
              <Badge variant="outline" className="ml-1 border-on-primary text-on-primary">
                {eventLabel(season)}
              </Badge>
            ) : null}
          </CardTitle>
        </CardHeader>
        {loading ? <Progress value={null} /> : null}
        <StatusAlert modelValue={error} onClose={() => setError(null)} className="m-4" />
        {error ? null : !smAndDown ? (
          <GroupedTable
            columns={columns}
            groups={days}
            defaultOpen
            empty="No series is scheduled yet"
            group={({ group }) => <td colSpan={columns.length} className="p-2">{dayLine(group)}</td>}
            rows={({ group }) =>
              group.rows.map((row) => (
                <tr key={row.id} className="detail-row border-b">
                  <td />
                  <td className="p-2 whitespace-nowrap">{timeOf(row.date_time as string)}</td>
                  <td className="p-2 whitespace-nowrap">
                    {roundLink(row)}
                    {teamsOf(row) ? <div className="text-xs text-muted-foreground">{teamsOf(row)}</div> : null}
                  </td>
                  <td className="p-2"><PlayerName player={row.player1} race={row.player1_race} /></td>
                  <td className="p-2"><PlayerName player={row.player2} race={row.player2_race} /></td>
                  <td className="p-2 whitespace-nowrap">{scoreOf(row)}</td>
                  <td className="p-2"><CastChips series={row} /></td>
                </tr>
              ))
            }
          />
        ) : (
          /* A phone has no room for six columns, and the cast is the last of them */
          <div>
            {days.map((group) => (
              <div key={group.key}>
                <div className="bg-on-surface/4 px-3 py-2">{dayLine(group)}</div>
                {group.rows.map((row) => (
                  <SeriesCard
                    key={row.id}
                    series={row}
                    title={<>{timeOf(row.date_time as string)} · {roundLink(row)}{teamsOf(row) ? `· ${teamsOf(row)}` : null}</>}
                    actions={<CastChips series={row} />}
                    side={({ n, won }) =>
                      !isUnscored(row) ? <Badge className={won ? "bg-win text-[rgb(var(--v-theme-on-win))]" : toneClass(null)}>{n ? row.player2_score : row.player1_score}</Badge> : null
                    }
                  />
                ))}
              </div>
            ))}
            {!days.length ? <div className="p-4 text-muted-foreground">No series is scheduled yet</div> : null}
          </div>
        )}
      </Card>
    </div>
  );
}

export default UpcomingView;

// src/views/UpcomingView.vue
<!-- Every scheduled series of the current season in time order: what is on tonight,
     what a caster can still claim, and where last week's VODs go. -->
<template>
  <v-container>
    <v-card elevation="2">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-calendar-clock</v-icon>
        Upcoming series
        <v-chip v-if="season?.name" class="ml-3" size="small" color="on-primary" variant="outlined">{{ eventLabel(season) }}</v-chip>
      </v-card-title>
      <v-card-text class="pa-0">
        <v-progress-linear v-if="loading" indeterminate />
        <StatusAlert v-model="error" />
        <GroupedTable v-if="!error && !smAndDown" :columns="columns" :groups="days" default-open empty="No series is scheduled yet">
          <template #group="{ group }">
            <td :colspan="columns.length">
              <strong>{{ group.title }}</strong>
              <span class="text-medium-emphasis ml-2">{{ group.rows.length }} series, {{ group.cast }} cast</span>
            </td>
          </template>
          <template #rows="{ group }">
            <tr v-for="row in group.rows" :key="row.id" class="detail-row">
              <td></td>
              <td class="text-no-wrap">{{ timeOf(row.date_time) }}</td>
              <td class="text-no-wrap">
                <RouterLink :to="`/match/${row.match_id}`">Round {{ row.match?.playday ?? '?' }}</RouterLink>
                <div v-if="row.match?.team1 && row.match?.team2" class="text-caption text-medium-emphasis">{{ row.match.team1.name }} vs {{ row.match.team2.name }}</div>
              </td>
              <td><PlayerName :player="row.player1" :race="row.player1_race" /></td>
              <td><PlayerName :player="row.player2" :race="row.player2_race" /></td>
              <td class="text-no-wrap">{{ scoreOf(row) }}</td>
              <td><CastChips :series="row" /></td>
            </tr>
          </template>
        </GroupedTable>
        <!-- A phone has no room for six columns, and the cast is the last of them -->
        <div v-else-if="!error">
          <template v-for="group in days" :key="group.key">
            <div class="px-3 py-2 day-row">
              <strong>{{ group.title }}</strong>
              <span class="text-medium-emphasis ml-2">{{ group.rows.length }} series, {{ group.cast }} cast</span>
            </div>
            <SeriesCard v-for="row in group.rows" :key="row.id" :series="row">
              <template #title>
                {{ timeOf(row.date_time) }} ·
                <RouterLink :to="`/match/${row.match_id}`">Round {{ row.match?.playday ?? '?' }}</RouterLink>
                <template v-if="row.match?.team1 && row.match?.team2">· {{ row.match.team1.name }} vs {{ row.match.team2.name }}</template>
              </template>
              <template #actions><CastChips :series="row" /></template>
              <template #side="{ n, won }">
                <v-chip v-if="!isUnscored(row)" size="small" :color="won ? 'win' : 'default'">
                  {{ n ? row.player2_score : row.player1_score }}
                </v-chip>
              </template>
            </SeriesCard>
          </template>
          <div v-if="!days.length" class="pa-4 text-medium-emphasis">No series is scheduled yet</div>
        </div>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import { useDisplay } from 'vuetify';

import CastChips from '@/components/CastChips.vue';
import GroupedTable from '@/components/GroupedTable.vue';
import PlayerName from '@/components/PlayerName.vue';
import SeriesCard from '@/components/SeriesCard.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import { resolveCurrentSeason } from '@/helpers/current-season';
import { eventLabel } from '@/helpers/event-labels.mjs';
import { local, scheduleDays } from '@/helpers/schedule.mjs';
import { isUnscored } from '@/helpers/season-phase.mjs';
import { gmt } from '@/helpers/timezone.mjs';
import { useSeriesStore } from '@/stores';

const columns = [
  { key: 'time', title: 'Time' },
  { key: 'round', title: 'Round' },
  { key: 'player1', title: 'Player 1' },
  { key: 'player2', title: 'Player 2' },
  { key: 'score', title: 'Score' },
  { key: 'cast', title: 'Cast' },
];

const { smAndDown } = useDisplay();
const season = ref(null);
const series = ref([]);
const loading = ref(true);
const error = ref(null);

const timeOf = (value) => {
  const at = local(value);
  return `${at.toFormat('HH:mm')} ${gmt(at.offset)}`;
};
const scoreOf = (row) => (isUnscored(row) ? '—' : `${row.player1_score}-${row.player2_score}`);

const days = computed(() => scheduleDays(series.value));

onMounted(async () => {
  try {
    season.value = await resolveCurrentSeason();
    if (!season.value) throw new Error('No current season');
    series.value = (await useSeriesStore().searchSeriesBySeason(season.value.id, null)) || [];
  } catch (e) {
    error.value = 'Failed to load the schedule.';
    console.error('Failed to load the schedule:', e);
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
.day-row {
  background: rgba(var(--v-theme-on-surface), 0.04);
}
</style>
