// src/views/TeamRoundsView.vue
<template>
  <v-overlay v-model="isLoading" contained class="align-center justify-center">
    <v-progress-circular color="primary" indeterminate size="64"></v-progress-circular>
  </v-overlay>

  <v-container fluid class="pa-4">
    <v-row class="mb-4">
      <v-col>
        <h1>
          <v-icon class="mr-2">mdi-calendar-account</v-icon>
          Team Rounds
        </h1>
      </v-col>
      <v-col cols="auto" class="d-flex align-center">
        <v-btn variant="text" prepend-icon="mdi-arrow-left" :to="`/team/${teamId}/season/${$route.params.season_id}`">Back to team</v-btn>
      </v-col>
    </v-row>

    <StatusAlert v-model="errorMessage" />

    <v-card elevation="2">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-shield-account</v-icon>
        <span>{{ team?.name }}</span>
      </v-card-title>

      <v-select v-if="smAndDown && loaded" v-model="shownRound" :items="roundItems" label="Round" density="compact" hide-details class="ma-2" />
      <v-table v-if="loaded" density="compact">
        <thead>
          <tr>
            <th>Player</th>
            <th v-for="round in shownRounds" :key="round" class="text-center">
              {{ roundLabel(roundOf(round)) }}
              <div class="text-caption text-medium-emphasis font-weight-regular">
                Round {{ round }}<template v-if="opponentOfRound(round)"> · vs {{ opponentOfRound(round).name }}</template>
              </div>
            </th>
            <th v-if="!smAndDown"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="player in players" :key="player.id">
            <td>
              <PlayerName :player="player" :race="player.signup_race" />
              <v-btn v-if="smAndDown" size="small" variant="outlined" class="d-block mt-1" :disabled="!!saving || !rounds.length" @click="outToLastRound(player.id)">
                Out to round {{ rounds.length }}
              </v-btn>
            </td>
            <td v-for="round in shownRounds" :key="round" class="text-center">
              <div class="d-flex ga-2 justify-center">
                <v-btn
                  icon="mdi-check"
                  :size="smAndDown ? 'default' : 'x-small'"
                  color="success"
                  :aria-label="`${player.name} checked in for round ${round}`"
                  :aria-pressed="answerFor(player.id, round) === true"
                  :variant="answerFor(player.id, round) === true ? 'flat' : 'outlined'"
                  :loading="saving === `${player.id}|${round}`"
                  :disabled="!!saving"
                  @click="setRound(player.id, round, true)"
                ></v-btn>
                <v-btn
                  icon="mdi-close"
                  :size="smAndDown ? 'default' : 'x-small'"
                  color="error"
                  :aria-label="`${player.name} can't play round ${round}`"
                  :aria-pressed="answerFor(player.id, round) === false"
                  :variant="answerFor(player.id, round) === false ? 'flat' : 'outlined'"
                  :loading="saving === `${player.id}|${round}`"
                  :disabled="!!saving"
                  @click="setRound(player.id, round, false)"
                ></v-btn>
              </div>
              <div class="text-caption text-medium-emphasis">{{ setByLine(player.id, round) }}</div>
            </td>
            <td v-if="!smAndDown">
              <v-btn
                size="small"
                variant="outlined"
                :disabled="!!saving || !rounds.length"
                @click="outToLastRound(player.id)"
              >
                Out to round {{ rounds.length }}
              </v-btn>
            </td>
          </tr>
        </tbody>
      </v-table>

      <v-card-text v-if="loaded && !players.length && !isLoading" class="text-center pa-8">
        <v-icon size="64" class="text-disabled">mdi-account-off</v-icon>
        <div class="text-h6 text-medium-emphasis mt-4">No players on this team this season</div>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { storeToRefs } from 'pinia';
import { useDisplay } from 'vuetify';

import { useAuthStore, useAvailabilityStore, useMatchStore, useSeasonStore, useTeamStore } from '@/stores';
import { roundLabel } from '@/helpers/rounds.mjs';
import StatusAlert from '@/components/StatusAlert.vue';

const router = useRouter();
const auth = useAuthStore();
const teamStore = useTeamStore();
const seasonStore = useSeasonStore();
const availabilityStore = useAvailabilityStore();
const matchStore = useMatchStore();

const { team } = storeToRefs(teamStore);
const { current_season: season } = storeToRefs(seasonStore);

const teamId = computed(() => Number(router.currentRoute.value.params.id));
const seasonId = computed(() => seasonStore.seasonIdOf(router.currentRoute.value.params.season_id));

const isLoading = ref(false);
const errorMessage = ref(null);
const rows = ref([]);
// The grid speaks for the answers it read: without them every cell would read 'No answer' and stay writable
const loaded = ref(false);
// The round labels: the season's round gives the dates, the team's match names the opponent (#33)
const roundOf = (round) => season.value?.rounds?.find(r => r.playday === round) || { playday: round };
const matches = ref([]);
const matchOfRound = (round) => matches.value.find(m => m.playday === round && [m.team1_id, m.team2_id].includes(teamId.value));
const opponentOfRound = (round) => { const m = matchOfRound(round); return m && (m.team1_id === teamId.value ? m.team2 : m.team1); };
const saving = ref(null);

const players = computed(() => team.value?.player_by_season?.[seasonId.value] || []);
const rounds = computed(() => Array.from({ length: season.value?.round_count || 0 }, (_, i) => i + 1));
// A phone shows one round at a time; wider screens show them all
const { smAndDown } = useDisplay();
const shownRound = ref(1);
const shownRounds = computed(() => smAndDown.value ? rounds.value.filter(w => w === shownRound.value) : rounds.value);
// the picker names each round the way the column header does
const roundItems = computed(() => rounds.value.map(round => ({ value: round, title: `Round ${round} · ${roundLabel(roundOf(round))}` })));

const rowFor = (userId, round) => rows.value.find(row => row.user_id === userId && row.playday === round);
const answerFor = (userId, round) => rowFor(userId, round)?.available ?? null;

const setByLine = (userId, round) => {
  const row = rowFor(userId, round);
  if (!row) return 'No answer';
  if (row.set_by_user_id === userId) return 'Player';
  return row.set_by_user_id === auth.me?.user?.id ? 'You' : row.set_by_name;
};

// the route answers every row of the player it wrote, so their old rows go
const applyRows = (userId, answered) => {
  rows.value = [...rows.value.filter(row => row.user_id !== userId), ...answered];
};

const write = async (userId, round, available) => {
  const answered = await availabilityStore.setTeamAvailability(teamId.value, seasonId.value, {
    user_id: userId,
    playday: round,
    available,
  });
  applyRows(userId, answered);
};

// a second click on the state already set clears the round back to no answer
const setRound = async (userId, round, want) => {
  saving.value = `${userId}|${round}`;
  errorMessage.value = null;
  try {
    await write(userId, round, answerFor(userId, round) === want ? null : want);
  } catch (error) {
    console.error('Error saving availability:', error);
    errorMessage.value = error.message || 'Error saving availability.';
  } finally {
    saving.value = null;
  }
};

const outToLastRound = async (userId) => {
  saving.value = `${userId}|all`;
  errorMessage.value = null;
  try {
    for (const round of rounds.value) {
      if (answerFor(userId, round) !== false) await write(userId, round, false);
    }
  } catch (error) {
    console.error('Error saving availability:', error);
    errorMessage.value = error.message || 'Error saving availability.';
  } finally {
    saving.value = null;
  }
};

onMounted(async () => {
  await seasonStore.ensureSeasons().catch(() => {});  // the slug maps to an id only once the list is in; a failed list fails the gate closed
  // same gate as the link that leads here: admins, or the captain of this team
  if (!auth.isCaptainOf(teamId.value, seasonId.value)) {
    router.replace('/profile');
    return;
  }
  isLoading.value = true;
  try {
    const [answered, seasonMatches] = await Promise.all([
      availabilityStore.fetchTeamAvailability(teamId.value, seasonId.value),
      matchStore.searchMatchesBySeason(seasonId.value).catch(() => []),
      teamStore.fetchTeamBySeason(teamId.value, seasonId.value),
      seasonStore.fetchSeason(seasonId.value),
    ]);
    rows.value = answered;
    matches.value = seasonMatches;
    loaded.value = true;
  } catch (error) {
    console.error(error);
    errorMessage.value = error.message || 'Failed to load the team rounds.';
  } finally {
    isLoading.value = false;
  }
});
</script>

// next/src/app/(app)/team/[id]/season/[season_id]/rounds/TeamRoundsView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Icon } from "@/components/ui/Icon";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PlayerName } from "@/components/PlayerName";
import { StatusAlert } from "@/components/StatusAlert";
import { SM_AND_DOWN, useBreakpoint } from "@/hooks/breakpoint";
import { roundLabel } from "@/helpers/rounds.mjs";
import { useAuth, useAvailabilityStore, useMatchStore, useSeason, useTeamStore } from "@/stores";

type Row = Record<string, any>;

/** The check-in grid of one team: every player against every round of the season.
 *  A captain of the team, or any admin, writes an answer for a player who did not. */
export function TeamRoundsView({ id, seasonKey }: { id: string; seasonKey: string }) {
  const router = useRouter();
  const auth = useAuth();
  const teamStore = useTeamStore();
  const availabilityStore = useAvailabilityStore();
  const matchStore = useMatchStore();
  const { current_season: season, seasonIdOf, fetchSeason } = useSeason();

  const teamId = Number(id);
  const seasonId = seasonIdOf(seasonKey);

  const [team, setTeam] = useState<Row | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [rows, setRows] = useState<Row[]>([]);
  // The grid speaks for the answers it read: without them every cell would read 'No answer' and stay writable
  const [loaded, setLoaded] = useState(false);
  const [matches, setMatches] = useState<Row[]>([]);
  const [saving, setSaving] = useState<string | null>(null);

  // The round labels: the season's round gives the dates, the team's match names the opponent
  const roundOf = (round: number) => season?.rounds?.find((r: Row) => r.playday === round) || { playday: round };
  const matchOfRound = (round: number) => matches.find((m) => m.playday === round && [m.team1_id, m.team2_id].includes(teamId));
  const opponentOfRound = (round: number) => {
    const m = matchOfRound(round);
    return m && (m.team1_id === teamId ? m.team2 : m.team1);
  };

  const players: Row[] = team?.player_by_season?.[seasonId as number] || [];
  const rounds: number[] = Array.from({ length: season?.round_count || 0 }, (_, i) => i + 1);
  // A phone shows one round at a time; wider screens show them all
  const smAndDown = useBreakpoint(SM_AND_DOWN);
  const [shownRound, setShownRound] = useState(1);
  const shownRounds = smAndDown ? rounds.filter((r) => r === shownRound) : rounds;
  // the picker names each round the way the column header does
  const roundItems = rounds.map((round) => ({ value: round, title: `Round ${round} · ${roundLabel(roundOf(round))}` }));

  const rowFor = (userId: number, round: number) => rows.find((row) => row.user_id === userId && row.playday === round);
  const answerFor = (userId: number, round: number): boolean | null => rowFor(userId, round)?.available ?? null;

  const setByLine = (userId: number, round: number) => {
    const row = rowFor(userId, round);
    if (!row) return "No answer";
    if (row.set_by_user_id === userId) return "Player";
    return row.set_by_user_id === auth.me?.user?.id ? "You" : row.set_by_name;
  };

  // the route answers every row of the player it wrote, so their old rows go
  const write = async (userId: number, round: number, available: boolean | null) => {
    const answered = await availabilityStore.setTeamAvailability(teamId, seasonId as number, {
      user_id: userId,
      playday: round,
      available,
    });
    setRows((was) => [...was.filter((row) => row.user_id !== userId), ...answered]);
  };

  // a second click on the state already set clears the round back to no answer
  const setRound = async (userId: number, round: number, want: boolean) => {
    setSaving(`${userId}|${round}`);
    setErrorMessage(null);
    try {
      await write(userId, round, answerFor(userId, round) === want ? null : want);
    } catch (error: any) {
      console.error("Error saving availability:", error);
      setErrorMessage(error.message || "Error saving availability.");
    } finally {
      setSaving(null);
    }
  };

  const outToLastRound = async (userId: number) => {
    setSaving(`${userId}|all`);
    setErrorMessage(null);
    try {
      for (const round of rounds) {
        if (answerFor(userId, round) !== false) await write(userId, round, false);
      }
    } catch (error: any) {
      console.error("Error saving availability:", error);
      setErrorMessage(error.message || "Error saving availability.");
    } finally {
      setSaving(null);
    }
  };

  useEffect(() => {
    // the Guard loads the season list before this page draws, so a null id is a slug of no season
    // same gate as the link that leads here: admins, or the captain of this team
    if (!seasonId || !auth.isCaptainOf(teamId, seasonId)) {
      router.replace("/profile");
      return;
    }
    // the loaders set state, so they run just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(async () => {
      setIsLoading(true);
      try {
        const [answered, seasonMatches, loadedTeam] = await Promise.all([
          availabilityStore.fetchTeamAvailability(teamId, seasonId),
          matchStore.searchMatchesBySeason(seasonId).catch(() => []),
          teamStore.fetchTeamBySeason(teamId, seasonId),
          fetchSeason(seasonId),
        ]);
        setRows(answered);
        setMatches(seasonMatches);
        setTeam(loadedTeam);
        setLoaded(true);
      } catch (error: any) {
        console.error(error);
        setErrorMessage(error.message || "Failed to load the team rounds.");
      } finally {
        setIsLoading(false);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId, teamId]);

  return (
    <div className="p-4">
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <Icon name="mdi-loading" size={64} className="animate-spin text-primary" />
        </div>
      ) : null}

      <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
        <h1 className="flex items-center gap-2">
          <Icon name="mdi-calendar-account" />
          Team Rounds
        </h1>
        <Button nativeButton={false} variant="ghost" render={<Link href={`/team/${teamId}/season/${seasonKey}`} />}>
          <Icon name="mdi-arrow-left" />
          Back to team
        </Button>
      </div>

      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      <Card className="card gap-0 py-0">
        <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
          <Icon name="mdi-shield-account" />
          <span>{team?.name}</span>
        </CardTitle>

        {smAndDown && loaded ? (
          <div className="m-2">
            <Select items={roundItems.map((item) => ({ value: item.value, label: item.title }))} value={shownRound} onValueChange={(value) => setShownRound(value as number)}>
              <SelectTrigger aria-label="Round" className="w-full">
                <SelectValue placeholder="Round" />
              </SelectTrigger>
              <SelectContent>
                {roundItems.map((item) => (
                  <SelectItem key={item.value} value={item.value}>
                    {item.title}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        ) : null}

        {loaded ? (
          <div className="table-scroll overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Player</TableHead>
                  {shownRounds.map((round) => (
                    <TableHead key={round} className="text-center">
                      {roundLabel(roundOf(round))}
                      <div className="text-xs font-normal text-muted-foreground">
                        Round {round}
                        {opponentOfRound(round) ? ` · vs ${opponentOfRound(round).name}` : ""}
                      </div>
                    </TableHead>
                  ))}
                  {!smAndDown ? <TableHead /> : null}
                </TableRow>
              </TableHeader>
              <TableBody>
                {players.map((player) => (
                  <TableRow key={player.id}>
                    <TableCell>
                      <PlayerName player={player} race={player.signup_race} />
                      {smAndDown ? (
                        <Button
                          variant="outline"
                          size="sm"
                          className="mt-1 block"
                          disabled={!!saving || !rounds.length}
                          onClick={() => outToLastRound(player.id)}
                        >
                          Out to round {rounds.length}
                        </Button>
                      ) : null}
                    </TableCell>
                    {shownRounds.map((round) => (
                      <TableCell key={round} className="text-center">
                        <div className="flex justify-center gap-2">
                          <Button
                            size={smAndDown ? "icon" : "icon-xs"}
                            variant={answerFor(player.id, round) === true ? "default" : "outline"}
                            className={answerFor(player.id, round) === true ? "bg-success text-on-success" : "text-success"}
                            aria-label={`${player.name} checked in for round ${round}`}
                            aria-pressed={answerFor(player.id, round) === true}
                            disabled={!!saving}
                            onClick={() => setRound(player.id, round, true)}
                          >
                            <Icon name={saving === `${player.id}|${round}` ? "mdi-loading mdi-spin" : "mdi-check"} />
                          </Button>
                          <Button
                            size={smAndDown ? "icon" : "icon-xs"}
                            variant={answerFor(player.id, round) === false ? "default" : "outline"}
                            className={answerFor(player.id, round) === false ? "bg-error text-on-error" : "text-error"}
                            aria-label={`${player.name} can't play round ${round}`}
                            aria-pressed={answerFor(player.id, round) === false}
                            disabled={!!saving}
                            onClick={() => setRound(player.id, round, false)}
                          >
                            <Icon name={saving === `${player.id}|${round}` ? "mdi-loading mdi-spin" : "mdi-close"} />
                          </Button>
                        </div>
                        <div className="text-xs text-muted-foreground">{setByLine(player.id, round)}</div>
                      </TableCell>
                    ))}
                    {!smAndDown ? (
                      <TableCell>
                        <Button variant="outline" size="sm" disabled={!!saving || !rounds.length} onClick={() => outToLastRound(player.id)}>
                          Out to round {rounds.length}
                        </Button>
                      </TableCell>
                    ) : null}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ) : null}

        {loaded && !players.length && !isLoading ? (
          <div className="p-8 text-center">
            <Icon name="mdi-account-off" size={64} className="text-muted-foreground" />
            <div className="mt-4 text-xl text-muted-foreground">No players on this team this season</div>
          </div>
        ) : null}
      </Card>
    </div>
  );
}

export default TeamRoundsView;
