// src/components/RoundCards.vue
<!-- One card per round of a season: the window, the team faced, and the player's
     series of that round. The player's own page fills the slots with his actions,
     a visitor reads the same facts without them. -->
<template>
  <v-chip v-if="asks && asking.length" size="small" variant="tonal" color="primary" class="mb-3">
    {{ answered }} of {{ asking.length }} answered
  </v-chip>
  <div v-if="cards.length" class="d-flex flex-wrap ga-3">
    <v-sheet
      v-for="card in cards"
      :key="card.playday"
      border
      rounded
      class="pa-3 flex-grow-1"
      :style="card.current ? 'min-width: 230px; border-color: rgb(var(--v-theme-primary)) !important' : 'min-width: 230px'"
    >
      <div class="text-subtitle-2">{{ card.label }}</div>
      <div class="text-caption text-medium-emphasis">
        Round {{ card.playday }}<template v-if="card.opponentTeam"> · vs {{ card.opponentTeam.name }}</template>
      </div>

      <!-- A series replaces the question: the round is already accounted for -->
      <template v-if="card.series">
        <div class="d-flex align-center ga-2 mt-2">
          <PlayerName
            :player="opponent(card.series)"
            :race="opponentRace(card.series)"
            :host="card.series.host_player_id === opponent(card.series).id"
          />
          <v-chip v-if="!isUnscored(card.series)" :color="scoreColor(card.series)" variant="outlined" size="small">
            {{ myScore(card.series) }} - {{ theirScore(card.series) }}
          </v-chip>
        </div>
        <!-- The host bans first and hosts game one, so the card names that side -->
        <div v-if="card.series.host_player_id === player.id" class="text-caption text-primary">
          You host and ban first
        </div>
        <div class="text-caption text-medium-emphasis">{{ formatDateTime(card.series.date_time) }}</div>
        <div v-if="opponentZone(card.series)" class="text-caption text-medium-emphasis">{{ opponentZone(card.series) }}</div>
        <!-- The three maps of the series once the veto has decided them -->
        <div v-for="line in maps(card.series)" :key="line" class="text-caption text-medium-emphasis">
          {{ line }}
        </div>
        <CastChips :series="card.series" class="mt-1" />
        <!-- A scored series keeps its actions: the backend takes a second report -->
        <slot name="series-actions" :series="card.series" />
      </template>

      <!-- the check-in belongs to the player himself; a visitor reads the state -->
      <div v-else-if="card.over || !asks || !card.open" class="mt-2">
        <v-chip size="small" variant="tonal" :color="card.answer === false ? 'error' : undefined">
          {{ roundStateChip(card, asks) }}
        </v-chip>
      </div>

      <slot v-else name="question" :card="card" />
    </v-sheet>
  </div>
  <div v-else class="text-medium-emphasis">No rounds yet.</div>
</template>

<script setup>
import { computed, ref, useSlots, watch } from 'vue';
import { useMatchStore } from '@/stores';
import { formatDateTime } from '@/helpers/datetime';
import { roundCards, roundStateChip } from '@/helpers/rounds.mjs';
import { viewerZone, zoneLabel } from '@/helpers/timezone.mjs';
import { isUnscored } from '@/helpers/season-phase.mjs';
import CastChips from '@/components/CastChips.vue';
import PlayerName from '@/components/PlayerName.vue';

const props = defineProps({
  player: { type: Object, required: true },
  season: { type: Object, required: true },  // carries the rounds
  series: { type: Array, default: () => [] },  // the player's series of this season
  teamId: { type: Number, default: null },
  answers: { type: Array, default: () => [] },  // availability, the player's own page only
});

const slots = useSlots();
const matchStore = useMatchStore();
const matches = ref([]);

// the season's matches name the team the player's team meets each round
watch(() => props.season?.id, async (seasonId) => {
  matches.value = seasonId ? await matchStore.searchMatchesBySeason(seasonId).catch(() => []) : [];
}, { immediate: true });

const cards = computed(() => roundCards({
  rounds: props.season?.rounds ?? [],
  series: props.series,
  matches: matches.value,
  teamId: props.teamId,
  answers: props.answers,
  checkinDays: props.season?.checkin_days ?? null,
}));

// The check-in belongs to the player himself, and only while the season runs the scheduling tools
const asks = computed(() => !!slots.question && props.season?.scheduling_enabled !== false);

// The check-in is open on a round with no series that is not over
const asking = computed(() => cards.value.filter(card => !card.series && !card.over && card.open));
const answered = computed(() => asking.value.filter(card => card.answer !== null).length);

// the other side of a series; the id is the fallback when the payload carries no player row
const opponent = (series) => {
  const mine = series.player1_id === props.player.id;
  return (mine ? series.player2 : series.player1) || { name: `Player ${mine ? series.player2_id : series.player1_id}` };
};

// the opponent's zone against the reader's, at the series time
const opponentZone = (series) => zoneLabel(opponent(series).timezone, viewerZone(), series.date_time);

// the race the opponent played in that series, not the one he signed the season up on
const opponentRace = (series) =>
  (series.player1_id === props.player.id ? series.player2_race : series.player1_race);

// The maps of the series, read from the player's side: game 1 is the season's
// fixed map, and each side picks the map it takes after a loss
const maps = (series) => {
  const mine = series.player1_id === props.player.id;
  const myPick = mine ? series.player1_pick_map : series.player2_pick_map;
  const theirPick = mine ? series.player2_pick_map : series.player1_pick_map;
  return [
    series.match?.fixed_map && `Game 1: ${series.match.fixed_map.name}`,
    myPick && `Your pick: ${myPick}`,
    theirPick && `${opponent(series).name}'s pick: ${theirPick}`,
  ].filter(Boolean);
};

// Scores read from the player's side: his first, the opponent's second
const myScore = (series) => (series.player1_id === props.player.id ? series.player1_score : series.player2_score) || 0;
const theirScore = (series) => (series.player1_id === props.player.id ? series.player2_score : series.player1_score) || 0;
const scoreColor = (series) => {
  if (myScore(series) > theirScore(series)) return 'win';
  if (myScore(series) < theirScore(series)) return 'loss';
  return 'draw';
};
</script>

// next/src/components/player/RoundCards.tsx
"use client";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { toneClass } from "@/components/ui/tone";
import { CastChips, type CastSeries } from "@/components/CastChips";
import { PlayerName } from "@/components/PlayerName";
import { useMatchStore } from "@/stores";
import { formatDateTime } from "@/helpers/datetime";
import { roundCards, roundStateChip } from "@/helpers/rounds.mjs";
import { viewerZone, zoneLabel } from "@/helpers/timezone.mjs";
import { isUnscored } from "@/helpers/season-phase.mjs";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const CAPTION = "text-xs text-muted-foreground";
const SCORE: Record<string, string> = { win: "text-win border-win", loss: "text-loss border-loss", draw: "text-draw border-draw" };

/** One card per round of a season: the window, the team faced, and the player's
 *  series of that round. The player's own page fills `seriesActions` and `question`
 *  with his actions, a visitor reads the same facts without them. */
export function RoundCards({
  player,
  season,
  series = [],
  teamId = null,
  answers = null,
  seriesActions,
  question,
}: {
  player: Row;
  season: Row; // carries the rounds
  series?: Row[]; // the player's series of this season
  teamId?: number | null;
  answers?: Row[] | null; // availability, the player's own page only; null while it is read
  seriesActions?: (series: Row) => React.ReactNode;
  question?: (card: Row) => React.ReactNode;
}) {
  const matchStore = useMatchStore();
  const [matches, setMatches] = useState<Row[]>([]);

  // the season's matches name the team the player's team meets each round
  const seasonId: number | undefined = season?.id;
  useEffect(() => {
    let live = true;
    (seasonId ? matchStore.searchMatchesBySeason(seasonId).catch(() => []) : Promise.resolve([])).then((found: Row[]) => live && setMatches(found));
    return () => { live = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId]);

  const cards: Row[] = roundCards({
    rounds: season?.rounds ?? [],
    series,
    matches,
    teamId,
    answers,
    checkinDays: season?.checkin_days ?? null,
  } as any);

  // The check-in belongs to the player himself, and only while the season runs the scheduling tools
  const asks = !!question && season?.scheduling_enabled !== false;

  // The check-in is open on a round with no series that is not over
  const asking = cards.filter((card) => !card.series && !card.over && card.open);
  const answered = asking.filter((card) => card.answer !== null).length;
  // The answers are still on their way, so the count would read every round as unanswered
  const pending = cards.some((card) => card.pending);

  const mine = (s: Row) => s.player1_id === player.id;
  // the other side of a series; the id is the fallback when the payload carries no player row
  const opponent = (s: Row): Row => (mine(s) ? s.player2 : s.player1) || { name: `Player ${mine(s) ? s.player2_id : s.player1_id}` };
  // the opponent's zone against the reader's, at the series time
  const opponentZone = (s: Row) => zoneLabel(opponent(s).timezone, viewerZone(), s.date_time);
  // the race the opponent played in that series, not the one he signed the season up on
  const opponentRace = (s: Row) => (mine(s) ? s.player2_race : s.player1_race);

  // The maps of the series, read from the player's side: game 1 is the season's
  // fixed map, and each side picks the map it takes after a loss
  const maps = (s: Row): string[] => {
    const myPick = mine(s) ? s.player1_pick_map : s.player2_pick_map;
    const theirPick = mine(s) ? s.player2_pick_map : s.player1_pick_map;
    return [
      s.match?.fixed_map && `Game 1: ${s.match.fixed_map.name}`,
      myPick && `Your pick: ${myPick}`,
      theirPick && `${opponent(s).name}'s pick: ${theirPick}`,
    ].filter(Boolean);
  };

  // Scores read from the player's side: his first, the opponent's second
  const myScore = (s: Row) => (mine(s) ? s.player1_score : s.player2_score) || 0;
  const theirScore = (s: Row) => (mine(s) ? s.player2_score : s.player1_score) || 0;
  const scoreColor = (s: Row) => (myScore(s) > theirScore(s) ? "win" : myScore(s) < theirScore(s) ? "loss" : "draw");

  return (
    <>
      {asks && asking.length ? (
        <Badge className={cn("mb-3", toneClass("primary"), pending && "invisible")}>
          {answered} of {asking.length} answered
        </Badge>
      ) : null}
      {cards.length ? (
        <div className="flex flex-wrap gap-3">
          {cards.map((card) => (
            <div key={card.playday} className={cn("card min-w-[230px] grow rounded p-3", card.current && "border-primary!")}>
              <div className="text-sm font-medium">{card.label}</div>
              <div className={CAPTION}>
                Round {card.playday}
                {card.opponentTeam ? ` · vs ${card.opponentTeam.name}` : null}
              </div>

              {card.series ? (
                // A series replaces the question: the round is already accounted for
                <>
                  <div className="mt-2 flex flex-wrap items-center gap-2">
                    <PlayerName player={opponent(card.series)} race={opponentRace(card.series)} host={card.series.host_player_id === opponent(card.series).id} />
                    {!isUnscored(card.series) ? (
                      <Badge variant="outline" className={cn("tnum", SCORE[scoreColor(card.series)])}>
                        {myScore(card.series)} - {theirScore(card.series)}
                      </Badge>
                    ) : null}
                  </div>
                  {/* The host bans first and hosts game one, so the card names that side */}
                  {card.series.host_player_id === player.id ? <div className="text-xs text-primary-text">You host and ban first</div> : null}
                  <div className={CAPTION}>{formatDateTime(card.series.date_time)}</div>
                  {opponentZone(card.series) ? <div className={CAPTION}>{opponentZone(card.series)}</div> : null}
                  {/* The three maps of the series once the veto has decided them */}
                  {maps(card.series).map((line) => (
                    <div key={line} className={CAPTION}>{line}</div>
                  ))}
                  <div className="mt-1">
                    <CastChips series={card.series as CastSeries} />
                  </div>
                  {/* A scored series keeps its actions: the backend takes a second report */}
                  {seriesActions?.(card.series)}
                </>
              ) : card.over || !asks || !card.open ? (
                // the check-in belongs to the player himself; a visitor reads the state
                <div className="mt-2">
                  <Badge className={cn(toneClass(card.answer === false ? "error" : null), asks && card.pending && "invisible")}>{roundStateChip(card, asks)}</Badge>
                </div>
              ) : (
                question?.(card)
              )}
            </div>
          ))}
        </div>
      ) : (
        <div className="text-muted-foreground">No rounds yet.</div>
      )}
    </>
  );
}

export default RoundCards;
