// src/components/ScheduleDialog.vue
<!-- The player sets the time of one of his series, in his own clock. The hours both
     sides are open are a hint under the pickers, never a reason to refuse a save. -->
<template>
  <v-dialog v-model="show" max-width="500px">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-calendar-edit</v-icon>
        Edit schedule
      </v-card-title>
      <v-card-text class="pt-4">
        <StatusAlert v-model="errorMessage" />
        <v-alert type="info" variant="tonal" density="compact" class="mb-4">
          Enter time in your local timezone ({{ zoneLabel(userTimezone, userTimezone, chosen) }}).
        </v-alert>
        <v-form>
          <v-container>
            <v-row>
              <v-col cols="12" md="6">
                <SimpleDatePicker v-model="series.date" label="Date" />
              </v-col>
              <v-col cols="12" md="6">
                <SimpleTimePicker v-model="series.time" :label="`Time (${userTimezone})`" />
              </v-col>
            </v-row>
            <v-row v-if="opponentZone">
              <v-col cols="12" class="pt-0">
                <div class="d-flex flex-wrap align-center ga-2">
                  <PlayerName :player="series.opponent" plain />
                  <strong v-if="opponentTime" class="text-no-wrap">{{ opponentTime }}</strong>
                </div>
                <div class="text-caption text-medium-emphasis">{{ opponentZone }}</div>
              </v-col>
            </v-row>
            <v-row v-if="freeTime">
              <v-col cols="12" class="pt-0">
                <div class="text-body-2 font-weight-medium">{{ commonHours(freeTime.hours) }}</div>
                <div v-for="line in sharedLines" :key="line" class="text-caption text-medium-emphasis">{{ line }}</div>
                <div v-if="moreLines" class="text-caption text-medium-emphasis">+{{ moreLines }} more</div>
                <div class="text-caption text-medium-emphasis mt-2">
                  Open hours are a starting point, not a promise. Agree the time with your opponent.
                </div>
              </v-col>
            </v-row>
          </v-container>
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" :disabled="saving" @click="show = false">Cancel</v-btn>
        <v-btn color="primary" variant="elevated" prepend-icon="mdi-content-save" :disabled="!isValid || saving" :loading="saving" @click="save">Save</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { computed, ref } from 'vue';
import { backendUrl, fetchWrapper } from '@/helpers';
import { authHeader } from '@/helpers/fetch-wrapper';
import { commonHours, freeLines } from '@/helpers/blocks.mjs';
import { pickedInstant, pickerParts, viewerZone, zoneLabel } from '@/helpers/timezone.mjs';
import PlayerName from '@/components/PlayerName.vue';
import SimpleDatePicker from '@/components/SimpleDatePicker.vue';
import SimpleTimePicker from '@/components/SimpleTimePicker.vue';
import StatusAlert from '@/components/StatusAlert.vue';

const props = defineProps({ playerId: { type: Number, default: null } });
const emit = defineEmits(['saved']);

const show = ref(false);
const saving = ref(false);
const errorMessage = ref(null);
const series = ref({});
const userTimezone = viewerZone();

// The hours both players are open this round; a hint only
const freeTime = ref(null);
const HINT_LINES = 6;
const sharedLines = computed(() => freeLines(freeTime.value?.ranges ?? [], userTimezone).slice(0, HINT_LINES));
const moreLines = computed(() => Math.max((freeTime.value?.ranges?.length ?? 0) - HINT_LINES, 0));

// A season with the tools off, or a series the backend will not answer for, shows nothing
const readFreeTime = async (seriesId) => {
  const found = await fetchWrapper.get(`${backendUrl}/player-series/${seriesId}/free-time`).catch(() => null);
  if (series.value.id === seriesId) freeTime.value = found;
};

const open = (item) => {
  errorMessage.value = null;
  const mine = item.player1_id === props.playerId;
  series.value = {
    id: item.id,
    ...(item.date_time ? pickerParts(item.date_time, userTimezone) : { date: null, time: '' }),
    opponent: (mine ? item.player2 : item.player1) ?? { name: 'your opponent' },
  };
  freeTime.value = null;
  show.value = true;
  readFreeTime(item.id);
};

// the instant the dialog's date and time name, read in the player's zone
const chosen = computed(() => {
  const { date, time } = series.value;
  return date instanceof Date && time ? pickedInstant(date, time, userTimezone) : null;
});
// the opponent's zone and the chosen time on their clock; their availability stays private
const opponentZone = computed(() => zoneLabel(series.value.opponent?.timezone, userTimezone, chosen.value));
const opponentTime = computed(() =>
  opponentZone.value && chosen.value ? chosen.value.setZone(series.value.opponent.timezone).toFormat('ccc d LLL, HH:mm') : '',
);

const isValid = computed(() => !!(series.value.date && series.value.time));

const save = async () => {
  saving.value = true;
  try {
    const formData = new FormData();
    const utcDateTime = chosen.value?.toUTC().toFormat('yyyy-MM-dd HH:mm:ss') ?? null;
    if (utcDateTime) formData.append('date_time', utcDateTime);
    formData.append('action', 'scheduled');

    const url = `${backendUrl}/player-series/${series.value.id}`;
    const response = await fetch(url, { method: 'PUT', headers: await authHeader('PUT', url), body: formData });
    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || 'Update failed');
    }
    show.value = false;
    emit('saved', 'Schedule updated successfully!');
  } catch (error) {
    errorMessage.value = error.message || 'Error saving schedule.';
  } finally {
    saving.value = false;
  }
};

defineExpose({ open });
</script>

// next/src/components/player/ScheduleDialog.tsx
"use client";
import { useImperativeHandle, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Icon } from "@/components/ui/Icon";
import { toneClass } from "@/components/ui/tone";
import { PlayerName } from "@/components/PlayerName";
import { SimpleDatePicker } from "@/components/SimpleDatePicker";
import { SimpleTimePicker } from "@/components/SimpleTimePicker";
import { StatusAlert } from "@/components/StatusAlert";
import { backendUrl, fetchWrapper } from "@/helpers";
import { authHeader } from "@/helpers/fetch-wrapper";
import { commonHours, freeLines } from "@/helpers/blocks.mjs";
import { pickedInstant, pickerParts, viewerZone, zoneLabel } from "@/helpers/timezone.mjs";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;
type Picked = { id?: number; date?: Date | null; time?: string; opponent?: Row };

export type ScheduleDialogHandle = { open: (item: Row) => void };

const HINT_LINES = 6;
const CAPTION = "text-xs text-muted-foreground";

/** The player sets the time of one of his series, in his own clock. The hours both
 *  sides are open are a hint under the pickers, never a reason to refuse a save. */
export function ScheduleDialog({
  playerId = null,
  onSaved,
  ref,
}: {
  playerId?: number | null;
  onSaved?: (message: string) => void;
  ref?: React.Ref<ScheduleDialogHandle>;
}) {
  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [series, setSeries] = useState<Picked>({});
  // The hours both players are open this round; a hint only
  const [freeTime, setFreeTime] = useState<Row | null>(null);
  // the series the dialog holds now, so a late free-time answer for another one is dropped
  const held = useRef<number | null>(null);
  const userTimezone: string = viewerZone();

  // A season with the tools off, or a series the backend will not answer for, shows nothing
  const readFreeTime = async (seriesId: number) => {
    const found = await fetchWrapper.get(`${backendUrl}/player-series/${seriesId}/free-time`).catch(() => null);
    if (held.current === seriesId) setFreeTime(found);
  };

  useImperativeHandle(ref, () => ({
    open: (item: Row) => {
      setErrorMessage(null);
      const mine = item.player1_id === playerId;
      held.current = item.id;
      setSeries({
        id: item.id,
        ...(item.date_time ? pickerParts(item.date_time, userTimezone) : { date: null, time: "" }),
        opponent: (mine ? item.player2 : item.player1) ?? { name: "your opponent" },
      });
      setFreeTime(null);
      setShow(true);
      readFreeTime(item.id);
    },
  }));

  const sharedLines: string[] = freeLines(freeTime?.ranges ?? [], userTimezone).slice(0, HINT_LINES);
  const moreLines = Math.max((freeTime?.ranges?.length ?? 0) - HINT_LINES, 0);

  // the instant the dialog's date and time name, read in the player's zone
  const chosen = series.date instanceof Date && series.time ? pickedInstant(series.date, series.time, userTimezone) : null;
  // the opponent's zone and the chosen time on their clock; their availability stays private
  const opponentZone = zoneLabel(series.opponent?.timezone, userTimezone, chosen);
  const opponentTime = opponentZone && chosen ? chosen.setZone(series.opponent?.timezone).toFormat("ccc d LLL, HH:mm") : "";

  const isValid = !!(series.date && series.time);

  const save = async () => {
    setSaving(true);
    try {
      const formData = new FormData();
      const utcDateTime = chosen?.toUTC().toFormat("yyyy-MM-dd HH:mm:ss") ?? null;
      if (utcDateTime) formData.append("date_time", utcDateTime);
      formData.append("action", "scheduled");

      const url = `${backendUrl}/player-series/${series.id}`;
      const response = await fetch(url, { method: "PUT", headers: await authHeader("PUT", url), body: formData });
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Update failed");
      }
      setShow(false);
      onSaved?.("Schedule updated successfully!");
    } catch (error) {
      setErrorMessage((error as Error).message || "Error saving schedule.");
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={show} onOpenChange={setShow}>
      <DialogContent showCloseButton={false} className="max-w-[500px] gap-0 p-0 sm:max-w-[500px]">
        <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
          <Icon name="mdi-calendar-edit" />
          Edit schedule
        </DialogTitle>
        <div className="flex flex-col gap-3 p-4">
          <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} className="mb-0" />
          <div className={cn("flex items-start gap-2 rounded px-3 py-2 text-sm", toneClass("info"))}>
            <Icon name="mdi-information-outline" />
            <span>Enter time in your local timezone ({zoneLabel(userTimezone, userTimezone, chosen)}).</span>
          </div>
          <form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => event.preventDefault()}>
            <SimpleDatePicker modelValue={series.date} label="Date" onUpdateModelValue={(date) => setSeries((was) => ({ ...was, date }))} />
            <SimpleTimePicker modelValue={series.time} label={`Time (${userTimezone})`} onUpdateModelValue={(time) => setSeries((was) => ({ ...was, time }))} />
          </form>
          {opponentZone ? (
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <PlayerName player={series.opponent ?? {}} plain />
                {opponentTime ? <strong className="whitespace-nowrap">{opponentTime}</strong> : null}
              </div>
              <div className={CAPTION}>{opponentZone}</div>
            </div>
          ) : null}
          {freeTime ? (
            <div>
              <div className="text-sm font-medium">{commonHours(freeTime.hours)}</div>
              {sharedLines.map((line) => (
                <div key={line} className={CAPTION}>{line}</div>
              ))}
              {moreLines ? <div className={CAPTION}>+{moreLines} more</div> : null}
              <div className={cn(CAPTION, "mt-2")}>Open hours are a starting point, not a promise. Agree the time with your opponent.</div>
            </div>
          ) : null}
        </div>
        <div className="flex justify-end gap-2 p-4 pt-0">
          <Button variant="ghost" disabled={saving} onClick={() => setShow(false)}>
            Cancel
          </Button>
          <Button disabled={!isValid || saving} onClick={save}>
            <Icon name={saving ? "mdi-loading mdi-spin" : "mdi-content-save"} />
            Save
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default ScheduleDialog;
