// next/src/components/AchievementChip.tsx
"use client";
import { AchievementIcon } from "@/components/AchievementIcon";
import { TapTooltip } from "@/components/ui/TapTooltip";
import { achievementPoints } from "@/helpers/achievements.js";

type Badge = { id: string; name: string; points: number };

/** The badges a player earned, as a row of icons over the points they paid */
export function AchievementChip({
  badges = [],
  showPoints = true, // off where a Points column already shows the number
}: {
  badges?: Badge[];
  showPoints?: boolean;
}) {
  if (!badges.length) return <span className="text-muted-foreground">&mdash;</span>;
  return (
    <div>
      <div className="flex flex-wrap items-center gap-[2px]">
        {badges.map((badge) => (
          <TapTooltip key={badge.id} className="cursor-help leading-none" content={`${badge.name} (+${badge.points})`}>
            <AchievementIcon id={badge.id} size={16} className="text-primary" />
          </TapTooltip>
        ))}
      </div>
      {/* The number sits right under the badges, so the cell keeps its height */}
      {showPoints ? <div className="mt-[2px] text-xs leading-none text-muted-foreground">{achievementPoints(badges)}</div> : null}
    </div>
  );
}

export default AchievementChip;

// src/components/AchievementChip.vue
<!-- The badges a player earned, as a row of icons over the points they paid -->
<template>
  <div v-if="badges.length">
    <div class="d-flex align-center flex-wrap" style="gap: 2px">
      <span v-for="badge in badges" :key="badge.id" class="badge-icon">
        <AchievementIcon :id="badge.id" :size="16" class="text-primary" />
        <v-tooltip activator="parent" location="top">{{ badge.name }} (+{{ badge.points }})</v-tooltip>
      </span>
    </div>
    <div v-if="showPoints" class="text-caption text-medium-emphasis badge-points">{{ points }}</div>
  </div>
  <span v-else class="text-medium-emphasis">&mdash;</span>
</template>

<script setup>
import { computed } from 'vue';
import AchievementIcon from '@/components/AchievementIcon.vue';
import { achievementPoints } from '@/helpers/achievements';

const props = defineProps({
  badges: { type: Array, default: () => [] },
  // Off where a Points column already shows the number
  showPoints: { type: Boolean, default: true },
});

const points = computed(() => achievementPoints(props.badges));
</script>

<style scoped>
.badge-icon {
  cursor: help;
  line-height: 1;
}
/* The number sits right under the badges, so the cell keeps its height */
.badge-points {
  line-height: 1;
  margin-top: 2px;
}
</style>
