// next/src/components/fantasy/FantasyScoreBreakdown.tsx
"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Fragment, useMemo } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Icon } from "@/components/ui/Icon";
import { TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toneClass } from "@/components/ui/tone";
import { BetIcon } from "@/components/fantasy/BetIcon";
import { GroupedTable, type GroupedColumn } from "@/components/GroupedTable";
import { PlayerName } from "@/components/PlayerName";
import { RaceIcon } from "@/components/RaceIcon";
import { W3CMmr } from "@/components/W3CMmr";
import { raceWrapper } from "@/helpers/races.js";
import { teamImageUrl, showDefaultTeamImage } from "@/helpers/team-image.js";
import { getW3CMMR } from "@/helpers/w3c-stats.js";
import { cn } from "@/lib/utils";

const playerColumns: GroupedColumn[] = [
  { key: "player", title: "Player" },
  { key: "mmr", title: "W3C MMR", align: "right" },
  { key: "record", title: "GNL Record", align: "right" },
  { key: "player_pts", title: "Player Points", align: "right" },
  { key: "bench_pts", title: "Bench Points", align: "right" },
  { key: "total", title: "Total", align: "right" },
];

const betColumns: GroupedColumn[] = [
  { key: "week", title: "Round", width: "110px" },
  { key: "series", title: "Series" },
  { key: "points", title: "Points", align: "right" },
];

// Team, Race and Bets hold a handful of numbers; stretching them to the panel
// pushes the points column an eye-travel away from the row it belongs to.
const NARROW = "[&_table]:w-auto";
// The label keeps its width, so the round names line up over the opponents.
const WEEK_LABEL = "inline-block min-w-16 opacity-(--v-medium-emphasis-opacity)";
const ICON = "size-6 object-contain";

type RosterRow = { key: string | number; label: string; player: any; mmr: any; record: string; bench: number; total: number; weeks: any[] };
type BetWeek = { key: number; label: string; week: number; bets: any[]; summary: string; net: number };

/** The five panels behind one fantasy team's score: its drafted team, its grind team, its race,
 *  its roster and its bets. The breakdown answer carries names (and sometimes ids); the players
 *  list turns them back into full players so every reference renders as PlayerName. */
export function FantasyScoreBreakdown({
  breakdown,
  players = [],
  draftedPlayers = [],
  seasonId = null,
  w3cSeason = null,
}: {
  breakdown: any;
  players?: any[];
  draftedPlayers?: any[];
  seasonId?: number | null;
  w3cSeason?: any;
}) {
  // drafted players last: they carry the season stats the roster table reads
  const pool = useMemo(() => [...players, ...draftedPlayers], [players, draftedPlayers]);
  const byId = useMemo(() => new Map(pool.map((p) => [p.id, p])), [pool]);
  const byName = useMemo(() => new Map(pool.map((p) => [p.name, p])), [pool]);

  const resolve = (name: string, id: number | null = null) => byId.get(id) || byName.get(name) || { name };

  // the MMR of the race the opponent played, on the pool the roster rows read
  const opponentMmr = (series: any) => {
    const player = resolve(series.opponent);
    return series.opponent_race ? getW3CMMR(player, w3cSeason, series.opponent_race) : null;
  };

  const gnlRecord = (player: any) => {
    const stat = player.gnl_stats?.find((s: any) => s.season_id === seasonId);
    return stat ? `${stat.wins || 0}W - ${stat.losses || 0}L` : "-";
  };

  const roster: RosterRow[] = (() => {
    const bench: Record<string, number> = {};
    for (const b of breakdown.bench_breakdown) bench[b.player_name] = (bench[b.player_name] || 0) + b.points;
    return breakdown.player_breakdown.map((b: any) => {
      const player = resolve(b.player_name, b.player_id);
      return {
        ...b,
        key: b.player_id ?? b.player_name,
        label: b.player_name,
        player,
        mmr: getW3CMMR(player, w3cSeason, player.signup_race),
        record: gnlRecord(player),
        bench: bench[b.player_name] || 0,
      };
    });
  })();

  const raceRanking = Object.entries(breakdown.race_breakdown.all_race_points as Record<string, number>)
    .map(([race, points]) => ({ race, points }))
    .sort((a, b) => b.points - a.points);
  const raceRank = raceRanking.findIndex((entry) => entry.race === breakdown.race_breakdown.race) + 1;
  const raceName = raceWrapper.getRaceObject(breakdown.race_breakdown.race)?.name ?? breakdown.race_breakdown.race;

  const betWeeks: BetWeek[] = (() => {
    const weeks = new Map<number, any[]>();
    for (const bet of breakdown.bet_breakdown) weeks.set(bet.week, [...(weeks.get(bet.week) || []), bet]);
    return [...weeks.entries()]
      .sort(([a], [b]) => a - b)
      .map(([week, bets]) => {
        const won = bets.filter((b) => b.won);
        const lost = bets.filter((b) => !b.won);
        const points = (arr: any[]) => arr.reduce((sum, b) => sum + b.result, 0);
        const summary = [won.length && `${won.length} won (+${points(won)})`, lost.length && `${lost.length} lost (${points(lost)})`].filter(Boolean).join(" · ");
        return { key: week, label: `Round ${week}`, week, bets, summary, net: points(bets) };
      });
  })();

  return (
    // `multiple`, as `v-expansion-panels multiple` was: a reader compares two panels side by side
    <Accordion multiple className="w-full">
      {/* Team Points Breakdown */}
      {breakdown.team_breakdown.team_name ? (
        <AccordionItem value="team">
          <AccordionTrigger className="items-center gap-2 font-normal hover:no-underline">
            <span className="flex w-full flex-wrap items-center gap-2">
              <img className={ICON} src={teamImageUrl(breakdown.team_breakdown.team_id)} onError={showDefaultTeamImage} alt="" />
              <strong>Team Points Details</strong>
              <span className="opacity-(--v-medium-emphasis-opacity)">{breakdown.team_breakdown.team_name}</span>
              <Badge className="ml-auto mr-2">{breakdown.totals.team_points} points</Badge>
            </span>
          </AccordionTrigger>
          <AccordionContent className={NARROW}>
            <table className="caption-bottom text-sm">
              <TableHeader>
                <TableRow>
                  <TableHead>Team</TableHead>
                  <TableHead>Final Score</TableHead>
                  <TableHead>Points Against</TableHead>
                  <TableHead>Points Available</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-bold">
                    <span className="inline-flex items-center gap-2">
                      <img className={ICON} src={teamImageUrl(breakdown.team_breakdown.team_id)} onError={showDefaultTeamImage} alt="" />
                      {breakdown.team_breakdown.team_name}
                    </span>
                  </TableCell>
                  <TableCell>{breakdown.team_breakdown.final_score}</TableCell>
                  <TableCell>{breakdown.team_breakdown.points_against}</TableCell>
                  <TableCell>{breakdown.team_breakdown.points_available}</TableCell>
                </TableRow>
              </TableBody>
            </table>
          </AccordionContent>
        </AccordionItem>
      ) : null}

      {/* Grind Points Breakdown: the second team, paying by achievement rank */}
      {breakdown.grind_breakdown?.team_name ? (
        <AccordionItem value="grind">
          <AccordionTrigger className="items-center gap-2 font-normal hover:no-underline">
            <span className="flex w-full flex-wrap items-center gap-2">
              <img className={ICON} src={teamImageUrl(breakdown.grind_breakdown.team_id)} onError={showDefaultTeamImage} alt="" />
              <strong>Grind Points Details</strong>
              <span className="opacity-(--v-medium-emphasis-opacity)">{breakdown.grind_breakdown.team_name}</span>
              <Badge className="ml-auto mr-2">{breakdown.totals.grind_points} points</Badge>
            </span>
          </AccordionTrigger>
          <AccordionContent className={NARROW}>
            <table className="caption-bottom text-sm">
              <TableHeader>
                <TableRow>
                  <TableHead>Team</TableHead>
                  <TableHead>Achievement points</TableHead>
                  <TableHead>Rank</TableHead>
                  <TableHead>Points</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-bold">
                    <span className="inline-flex items-center gap-2">
                      <img className={ICON} src={teamImageUrl(breakdown.grind_breakdown.team_id)} onError={showDefaultTeamImage} alt="" />
                      {breakdown.grind_breakdown.team_name}
                    </span>
                  </TableCell>
                  <TableCell>{breakdown.grind_breakdown.achievement_points}</TableCell>
                  <TableCell>
                    {breakdown.grind_breakdown.rank} of {breakdown.grind_breakdown.teams}
                  </TableCell>
                  <TableCell>{breakdown.grind_breakdown.points}</TableCell>
                </TableRow>
              </TableBody>
            </table>
          </AccordionContent>
        </AccordionItem>
      ) : null}

      {/* Race Points Breakdown */}
      <AccordionItem value="race">
        <AccordionTrigger className="items-center gap-2 font-normal hover:no-underline">
          <span className="flex w-full flex-wrap items-center gap-2">
            <RaceIcon raceIdentifier={breakdown.race_breakdown.race} size={24} />
            <strong>Race Points Details</strong>
            <span className="opacity-(--v-medium-emphasis-opacity)">
              {raceName} · {breakdown.race_breakdown.season_stats.wins}W - {breakdown.race_breakdown.season_stats.losses}L
            </span>
            <Badge className={toneClass("primary")}>
              #{raceRank} of {raceRanking.length}
            </Badge>
            <Badge className="ml-auto mr-2">{breakdown.totals.race_points} points</Badge>
          </span>
        </AccordionTrigger>
        <AccordionContent className={NARROW}>
          <table className="caption-bottom text-sm">
            <TableHeader>
              <TableRow>
                <TableHead style={{ width: "80px" }}>Round</TableHead>
                <TableHead className="text-right">Wins</TableHead>
                <TableHead className="text-right">Losses</TableHead>
                <TableHead className="text-right">Ratio</TableHead>
                <TableHead className="text-right">Rank</TableHead>
                <TableHead className="text-right">Points</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {breakdown.race_breakdown.weekly_breakdown.map((week: any) => (
                <TableRow key={week.week}>
                  <TableCell>{week.week}</TableCell>
                  <TableCell className="text-right">{week.wins}</TableCell>
                  <TableCell className="text-right">{week.losses}</TableCell>
                  <TableCell className="text-right">{week.ratio.toFixed(2)}</TableCell>
                  <TableCell className="text-right">
                    {week.rank ? (
                      <Badge className={week.rank === 1 ? "bg-success text-on-success" : week.rank === 2 ? "bg-info text-on-info" : "bg-warning text-on-warning"}>#{week.rank}</Badge>
                    ) : (
                      <span className="opacity-(--v-medium-emphasis-opacity)">-</span>
                    )}
                  </TableCell>
                  <TableCell className="text-right">
                    {week.points_awarded > 0 ? <strong>+{week.points_awarded}</strong> : <span className="opacity-(--v-medium-emphasis-opacity)">0</span>}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </table>
        </AccordionContent>
      </AccordionItem>

      {/* Player Points Breakdown: the drafted roster; a row opens the player's rounds */}
      <AccordionItem value="player">
        <AccordionTrigger className="items-center gap-2 font-normal hover:no-underline">
          <span className="flex w-full flex-wrap items-center gap-2">
            <Icon name="mdi-account-multiple" className="text-primary-text" />
            <strong>Player Points Details</strong>
            <Badge className="ml-auto">{breakdown.totals.player_points} points</Badge>
            <Badge className="mr-2 bg-warning text-on-warning">{breakdown.totals.bench_points} bench points</Badge>
          </span>
        </AccordionTrigger>
        <AccordionContent>
          <GroupedTable
            columns={playerColumns}
            groups={roster}
            empty="No drafted players"
            head={{ mmr: <W3CMmr /> }}
            group={({ group: row }) => (
              <>
                <TableCell className="font-bold">
                  <PlayerName player={row.player} race={row.player.signup_race} />
                </TableCell>
                <TableCell className="text-right">{row.mmr || "N/A"}</TableCell>
                <TableCell className="text-right">{row.record}</TableCell>
                <TableCell className="text-right">{row.total}</TableCell>
                <TableCell className="text-right text-warning">{row.bench ? `+${row.bench}` : 0}</TableCell>
                <TableCell className="text-right">
                  <strong>{row.total + row.bench}</strong>
                </TableCell>
              </>
            )}
            rows={({ group: row }) =>
              row.weeks.map((week: any) =>
                week.series.length === 0 ? (
                  <tr key={week.week} className="detail-row border-b">
                    <td />
                    <td>
                      <span className={WEEK_LABEL}>Round {week.week}</span>
                      {week.bench_points > 0 ? (
                        <span className="text-warning">
                          <Icon name="mdi-seat" className="text-sm" /> Benched
                        </span>
                      ) : (
                        <span className="opacity-(--v-medium-emphasis-opacity)">No games</span>
                      )}
                    </td>
                    <td />
                    <td />
                    <td />
                    <td className="text-right">
                      {week.bench_points > 0 ? <span className="text-warning">+{week.bench_points}</span> : <span className="opacity-(--v-medium-emphasis-opacity)">0</span>}
                    </td>
                    <td />
                  </tr>
                ) : (
                  week.series.map((series: any, idx: number) => (
                    // only the last row of a round carries the rule, so one round reads as one block
                    <tr key={`${week.week}-${idx}`} className={cn("detail-row", idx === week.series.length - 1 && "border-b")}>
                      <td />
                      <td>
                        <span className="flex flex-wrap items-center gap-1">
                          <span className={WEEK_LABEL}>{idx ? "" : `Round ${week.week}`}</span>
                          <span className="opacity-(--v-medium-emphasis-opacity)">vs</span>
                          <PlayerName player={resolve(series.opponent)} race={series.opponent_race} />
                        </span>
                      </td>
                      <td className="text-right">{opponentMmr(series) || "N/A"}</td>
                      <td className="text-right">{series.score}</td>
                      <td className="text-right">{series.points}</td>
                      <td />
                      <td />
                    </tr>
                  ))
                ),
              )
            }
          />
        </AccordionContent>
      </AccordionItem>

      {/* Bet Points Breakdown */}
      {breakdown.bet_breakdown.length > 0 ? (
        <AccordionItem value="bet">
          <AccordionTrigger className="items-center gap-2 font-normal hover:no-underline">
            <span className="flex w-full flex-wrap items-center gap-2">
              <BetIcon size={24} className="text-primary-text" />
              <strong>Bet Points Details</strong>
              <Badge className={cn("ml-auto mr-2", breakdown.totals.bet_points >= 0 ? "bg-win text-on-win" : "bg-loss text-on-loss")}>
                {breakdown.totals.bet_points} points
              </Badge>
            </span>
          </AccordionTrigger>
          <AccordionContent className={NARROW}>
            <GroupedTable
              columns={betColumns}
              groups={betWeeks}
              empty="No bets"
              group={({ group: week }) => (
                <>
                  <TableCell>Round {week.week}</TableCell>
                  <TableCell className="opacity-(--v-medium-emphasis-opacity)">{week.summary}</TableCell>
                  <TableCell className="text-right">
                    <strong className={week.net >= 0 ? "text-win" : "text-loss"}>
                      {week.net > 0 ? "+" : ""}
                      {week.net}
                    </strong>
                  </TableCell>
                </>
              )}
              rows={({ group: week }) =>
                week.bets.map((bet: any, idx: number) => (
                  <tr key={idx} className="detail-row border-b">
                    <td />
                    <td />
                    <td>
                      {bet.player1 && bet.player2 ? (
                        <span className="flex flex-wrap items-center gap-1">
                          {[bet.player1, bet.player2].map((side: string) => (
                            <Fragment key={side}>
                              {side === bet.player2 ? <span className="opacity-(--v-medium-emphasis-opacity)">{bet.score}</span> : null}
                              <span className={side === bet.actual_winner ? "font-bold" : undefined}>
                                <PlayerName player={resolve(side)} race={resolve(side).signup_race} />
                              </span>
                              {side === bet.bet_on ? <BetIcon className="text-primary-text" /> : null}
                            </Fragment>
                          ))}
                        </span>
                      ) : (
                        <span>{bet.series}</span>
                      )}
                    </td>
                    <td className={cn("text-right", bet.won ? "text-win" : "text-loss")}>
                      {bet.result > 0 ? "+" : ""}
                      {bet.result}
                    </td>
                  </tr>
                ))
              }
            />
          </AccordionContent>
        </AccordionItem>
      ) : null}
    </Accordion>
  );
}

export default FantasyScoreBreakdown;

// src/components/FantasyScoreBreakdown.vue
<template>
  <v-expansion-panels multiple>
    <!-- Team Points Breakdown -->
    <v-expansion-panel v-if="breakdown.team_breakdown.team_name">
      <v-expansion-panel-title>
        <img class="tab-icon mr-2" :src="teamImageUrl(breakdown.team_breakdown.team_id)" @error="showDefaultTeamImage" alt="" />
        <strong>Team Points Details</strong>
        <span class="ml-2 text-medium-emphasis">{{ breakdown.team_breakdown.team_name }}</span>
        <v-spacer></v-spacer>
        <v-chip color="primary" size="small">{{ breakdown.totals.team_points }} points</v-chip>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <v-table density="compact" class="narrow">
          <thead>
            <tr>
              <th>Team</th>
              <th>Final Score</th>
              <th>Points Against</th>
              <th>Points Available</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="font-weight-bold">
                <span class="d-inline-flex align-center ga-2">
                  <img class="row-icon" :src="teamImageUrl(breakdown.team_breakdown.team_id)" @error="showDefaultTeamImage" alt="" />
                  {{ breakdown.team_breakdown.team_name }}
                </span>
              </td>
              <td>{{ breakdown.team_breakdown.final_score }}</td>
              <td>{{ breakdown.team_breakdown.points_against }}</td>
              <td>{{ breakdown.team_breakdown.points_available }}</td>
            </tr>
          </tbody>
        </v-table>
      </v-expansion-panel-text>
    </v-expansion-panel>

    <!-- Grind Points Breakdown: the second team, paying by achievement rank -->
    <v-expansion-panel v-if="breakdown.grind_breakdown?.team_name">
      <v-expansion-panel-title>
        <img class="tab-icon mr-2" :src="teamImageUrl(breakdown.grind_breakdown.team_id)" @error="showDefaultTeamImage" alt="" />
        <strong>Grind Points Details</strong>
        <span class="ml-2 text-medium-emphasis">{{ breakdown.grind_breakdown.team_name }}</span>
        <v-spacer></v-spacer>
        <v-chip color="primary" size="small">{{ breakdown.totals.grind_points }} points</v-chip>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <v-table density="compact" class="narrow">
          <thead>
            <tr>
              <th>Team</th>
              <th>Achievement points</th>
              <th>Rank</th>
              <th>Points</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="font-weight-bold">
                <span class="d-inline-flex align-center ga-2">
                  <img class="row-icon" :src="teamImageUrl(breakdown.grind_breakdown.team_id)" @error="showDefaultTeamImage" alt="" />
                  {{ breakdown.grind_breakdown.team_name }}
                </span>
              </td>
              <td>{{ breakdown.grind_breakdown.achievement_points }}</td>
              <td>{{ breakdown.grind_breakdown.rank }} of {{ breakdown.grind_breakdown.teams }}</td>
              <td>{{ breakdown.grind_breakdown.points }}</td>
            </tr>
          </tbody>
        </v-table>
      </v-expansion-panel-text>
    </v-expansion-panel>

    <!-- Race Points Breakdown -->
    <v-expansion-panel>
      <v-expansion-panel-title>
        <span class="mr-2 d-inline-flex"><RaceIcon :raceIdentifier="breakdown.race_breakdown.race" size="24" /></span>
        <strong>Race Points Details</strong>
        <span class="ml-2 text-medium-emphasis">{{ raceName }} · {{ breakdown.race_breakdown.season_stats.wins }}W - {{ breakdown.race_breakdown.season_stats.losses }}L</span>
        <v-chip class="ml-2" size="x-small" variant="tonal" color="primary">#{{ raceRank }} of {{ raceRanking.length }}</v-chip>
        <v-spacer></v-spacer>
        <v-chip color="primary" size="small">{{ breakdown.totals.race_points }} points</v-chip>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <v-table density="compact" class="narrow">
          <thead>
            <tr>
              <th style="width: 80px">Round</th>
              <th class="text-right">Wins</th>
              <th class="text-right">Losses</th>
              <th class="text-right">Ratio</th>
              <th class="text-right">Rank</th>
              <th class="text-right">Points</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="week in breakdown.race_breakdown.weekly_breakdown" :key="week.week">
              <td>{{ week.week }}</td>
              <td class="text-right">{{ week.wins }}</td>
              <td class="text-right">{{ week.losses }}</td>
              <td class="text-right">{{ week.ratio.toFixed(2) }}</td>
              <td class="text-right">
                <v-chip v-if="week.rank" :color="week.rank === 1 ? 'success' : week.rank === 2 ? 'info' : 'warning'" size="x-small">
                  #{{ week.rank }}
                </v-chip>
                <span v-else class="text-medium-emphasis">-</span>
              </td>
              <td class="text-right">
                <strong v-if="week.points_awarded > 0">+{{ week.points_awarded }}</strong>
                <span v-else class="text-medium-emphasis">0</span>
              </td>
            </tr>
          </tbody>
        </v-table>
      </v-expansion-panel-text>
    </v-expansion-panel>

    <!-- Player Points Breakdown: the drafted roster; a row opens the player's rounds -->
    <v-expansion-panel>
      <v-expansion-panel-title>
        <v-icon class="mr-2" color="primary">mdi-account-multiple</v-icon>
        <strong>Player Points Details</strong>
        <v-spacer></v-spacer>
        <v-chip color="primary" size="small">{{ breakdown.totals.player_points }} points</v-chip>
        <v-chip color="warning" size="small" class="ml-1">{{ breakdown.totals.bench_points }} bench points</v-chip>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <GroupedTable :columns="playerColumns" :groups="roster" empty="No drafted players">
          <template #head.mmr><W3CMmr /></template>
          <template #group="{ group: row }">
            <td class="font-weight-bold"><PlayerName :player="row.player" :race="row.player.signup_race" /></td>
            <td class="text-right">{{ row.mmr || 'N/A' }}</td>
            <td class="text-right">{{ row.record }}</td>
            <td class="text-right">{{ row.total }}</td>
            <td class="text-right text-warning">{{ row.bench ? `+${row.bench}` : 0 }}</td>
            <td class="text-right"><strong>{{ row.total + row.bench }}</strong></td>
          </template>
          <template #rows="{ group: row }">
            <template v-for="week in row.weeks" :key="week.week">
              <tr v-for="(series, idx) in week.series" :key="`${week.week}-${idx}`" class="detail-row" :class="{ 'same-week': idx }">
                <td></td>
                <td>
                  <div class="d-flex align-center ga-1 flex-wrap">
                    <span class="week-label text-medium-emphasis">{{ idx ? '' : `Round ${week.week}` }}</span>
                    <span class="text-medium-emphasis">vs</span>
                    <PlayerName :player="resolve(series.opponent)" :race="series.opponent_race" />
                  </div>
                </td>
                <td class="text-right">{{ opponentMmr(series) || 'N/A' }}</td>
                <td class="text-right">{{ series.score }}</td>
                <td class="text-right">{{ series.points }}</td>
                <td></td>
                <td></td>
              </tr>
              <tr v-if="week.series.length === 0" class="detail-row">
                <td></td>
                <td>
                  <span class="week-label text-medium-emphasis">Round {{ week.week }}</span>
                  <span v-if="week.bench_points > 0" class="text-warning">
                    <v-icon size="small">mdi-seat</v-icon> Benched
                  </span>
                  <span v-else class="text-medium-emphasis">No games</span>
                </td>
                <td></td>
                <td></td>
                <td></td>
                <td class="text-right">
                  <span v-if="week.bench_points > 0" class="text-warning">+{{ week.bench_points }}</span>
                  <span v-else class="text-medium-emphasis">0</span>
                </td>
                <td></td>
              </tr>
            </template>
          </template>
        </GroupedTable>
      </v-expansion-panel-text>
    </v-expansion-panel>

    <!-- Bet Points Breakdown -->
    <v-expansion-panel v-if="breakdown.bet_breakdown.length > 0">
      <v-expansion-panel-title>
        <BetIcon size="24" class="mr-2 text-primary" />
        <strong>Bet Points Details</strong>
        <v-spacer></v-spacer>
        <v-chip :color="breakdown.totals.bet_points >= 0 ? 'win' : 'loss'" size="small">{{ breakdown.totals.bet_points }} points</v-chip>
      </v-expansion-panel-title>
      <v-expansion-panel-text>
        <GroupedTable :columns="betColumns" :groups="betWeeks" empty="No bets" class="narrow">
          <template #group="{ group: week }">
            <td>Round {{ week.week }}</td>
            <td class="text-medium-emphasis">{{ week.summary }}</td>
            <td class="text-right">
              <strong :class="week.net >= 0 ? 'text-win' : 'text-loss'">{{ week.net > 0 ? '+' : '' }}{{ week.net }}</strong>
            </td>
          </template>
          <template #rows="{ group: week }">
            <tr v-for="(bet, idx) in week.bets" :key="idx" class="detail-row">
              <td></td>
              <td></td>
              <td>
                <div v-if="bet.player1 && bet.player2" class="d-flex align-center ga-1 flex-wrap">
                  <template v-for="side in [bet.player1, bet.player2]" :key="side">
                    <span v-if="side === bet.player2" class="text-medium-emphasis">{{ bet.score }}</span>
                    <span :class="{ winner: side === bet.actual_winner }">
                      <PlayerName :player="resolve(side)" :race="resolve(side).signup_race" />
                    </span>
                    <BetIcon v-if="side === bet.bet_on" class="text-primary" />
                  </template>
                </div>
                <span v-else>{{ bet.series }}</span>
              </td>
              <td class="text-right" :class="bet.won ? 'text-win' : 'text-loss'">
                {{ bet.result > 0 ? '+' : '' }}{{ bet.result }}
              </td>
            </tr>
          </template>
        </GroupedTable>
      </v-expansion-panel-text>
    </v-expansion-panel>
  </v-expansion-panels>
</template>

<script setup>
import { computed } from 'vue';
import BetIcon from '@/components/BetIcon.vue';
import GroupedTable from '@/components/GroupedTable.vue';
import PlayerName from '@/components/PlayerName.vue';
import RaceIcon from '@/components/RaceIcon.vue';
import { raceWrapper } from '@/helpers/races';
import { teamImageUrl, showDefaultTeamImage } from '@/helpers/team-image';
import W3CMmr from '@/components/W3CMmr.vue';
import { getW3CMMR } from '@/helpers/w3c-stats';

const playerColumns = [
  { key: 'player', title: 'Player' },
  { key: 'mmr', title: 'W3C MMR', align: 'right' },
  { key: 'record', title: 'GNL Record', align: 'right' },
  { key: 'player_pts', title: 'Player Points', align: 'right' },
  { key: 'bench_pts', title: 'Bench Points', align: 'right' },
  { key: 'total', title: 'Total', align: 'right' },
];

const betColumns = [
  { key: 'week', title: 'Round', width: '110px' },
  { key: 'series', title: 'Series' },
  { key: 'points', title: 'Points', align: 'right' },
];

// The breakdown answer carries names (and sometimes ids); the players list
// turns them back into full players so every reference renders as PlayerName.
const props = defineProps({
  breakdown: { type: Object, required: true },
  players: { type: Array, default: () => [] },
  draftedPlayers: { type: Array, default: () => [] },
  seasonId: { type: Number, default: null },
  w3cSeason: { type: Object, default: null },
});

// drafted players last: they carry the season stats the roster table reads
const byId = computed(() => new Map([...props.players, ...props.draftedPlayers].map(p => [p.id, p])));
const byName = computed(() => new Map([...props.players, ...props.draftedPlayers].map(p => [p.name, p])));

const resolve = (name, id = null) => byId.value.get(id) || byName.value.get(name) || { name };

// the MMR of the race the opponent played, on the pool the roster rows read
const opponentMmr = (series) => {
  const player = resolve(series.opponent);
  return series.opponent_race ? getW3CMMR(player, props.w3cSeason, series.opponent_race) : null;
};

const gnlRecord = (player) => {
  const stat = player.gnl_stats?.find(s => s.season_id === props.seasonId);
  return stat ? `${stat.wins || 0}W - ${stat.losses || 0}L` : '-';
};

const roster = computed(() => {
  const bench = {};
  for (const b of props.breakdown.bench_breakdown) {
    bench[b.player_name] = (bench[b.player_name] || 0) + b.points;
  }
  return props.breakdown.player_breakdown.map(b => {
    const player = resolve(b.player_name, b.player_id);
    return {
      ...b,
      key: b.player_id ?? b.player_name,
      label: b.player_name,
      player,
      mmr: getW3CMMR(player, props.w3cSeason, player.signup_race),
      record: gnlRecord(player),
      bench: bench[b.player_name] || 0,
    };
  });
});

const raceRanking = computed(() =>
  Object.entries(props.breakdown.race_breakdown.all_race_points)
    .map(([race, points]) => ({ race, points }))
    .sort((a, b) => b.points - a.points)
);

const betWeeks = computed(() => {
  const weeks = new Map();
  for (const bet of props.breakdown.bet_breakdown) {
    weeks.set(bet.week, [...(weeks.get(bet.week) || []), bet]);
  }
  return [...weeks.entries()].sort(([a], [b]) => a - b).map(([week, bets]) => {
    const won = bets.filter(b => b.won);
    const lost = bets.filter(b => !b.won);
    const points = arr => arr.reduce((sum, b) => sum + b.result, 0);
    const summary = [
      won.length && `${won.length} won (+${points(won)})`,
      lost.length && `${lost.length} lost (${points(lost)})`,
    ].filter(Boolean).join(' · ');
    return { key: week, label: `Round ${week}`, week, bets, summary, net: points(bets) };
  });
});

const raceName = computed(() => {
  const race = props.breakdown.race_breakdown.race;
  return raceWrapper.getRaceObject(race)?.name ?? race;
});

const raceRank = computed(
  () => raceRanking.value.findIndex(e => e.race === props.breakdown.race_breakdown.race) + 1
);
</script>

<style scoped>
.week-label {
  display: inline-block;
  min-width: 64px;
}
.detail-row:has(+ .same-week) > td {
  border-bottom: none !important;
}
.winner {
  font-weight: 700;
}
/* Team, Race and Bets hold a handful of numbers; stretching them to the panel
   pushes the points column an eye-travel away from the row it belongs to. */
.narrow :deep(table) {
  width: auto;
}
.tab-icon,
.row-icon {
  width: 24px;
  height: 24px;
  object-fit: contain;
}
</style>
