// next/src/components/FilterPanel.tsx
"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Icon } from "@/components/ui/Icon";
import { MD_AND_UP, useBreakpoint } from "@/hooks/breakpoint";
import { raceWrapper } from "@/helpers/races.js";
import { cn } from "@/lib/utils";

type EventRow = { id: number; name: string };

/** The filter bar over a player table: name, event, race and an MMR range. A phone keeps the
 *  search in view and folds the rest behind the Filters button. */
export function FilterPanel({
  seasons = [],
  extraActive = 0, // filters the after render prop holds, counted on the phone button
  showName = true,
  showRace = true,
  showSeason = true,
  showMMR = true,
  showReset = true,
  min = 0,
  max = 3000,
  step = 10,
  searchName = "",
  onSearchNameChange,
  searchRace = null,
  onSearchRaceChange,
  selectedSeasonFilter = null,
  onSelectedSeasonFilterChange,
  rangeValues = [0, 3000],
  onRangeValuesChange,
  onReset,
  after,
  summary,
}: {
  seasons?: EventRow[];
  extraActive?: number;
  showName?: boolean;
  showRace?: boolean;
  showSeason?: boolean;
  showMMR?: boolean;
  showReset?: boolean;
  min?: number;
  max?: number;
  step?: number;
  searchName?: string;
  onSearchNameChange?: (value: string) => void;
  searchRace?: string | null;
  onSearchRaceChange?: (value: string | null) => void;
  selectedSeasonFilter?: number | null;
  onSelectedSeasonFilterChange?: (value: number | null) => void;
  rangeValues?: number[];
  onRangeValuesChange?: (value: number[]) => void;
  onReset?: () => void;
  after?: React.ReactNode;
  summary?: React.ReactNode;
}) {
  const events = [...seasons].sort((a, b) => b.id - a.id);
  const mdAndUp = useBreakpoint(MD_AND_UP);
  const [open, setOpen] = useState(false);
  const expanded = mdAndUp || open;
  const activeCount =
    [searchRace, selectedSeasonFilter, rangeValues[0] !== min || rangeValues[1] !== max].filter(Boolean).length + extraActive;

  const setRange = (i: number, value: string) => {
    const next = [...rangeValues];
    next[i] = Number(value) || 0;
    onRangeValuesChange?.(next);
  };

  return (
    <div className="card mb-4 rounded-lg p-3">
      <div className="flex flex-wrap items-center gap-2">
        {showName ? (
          <div className="relative min-w-[200px] flex-1">
            <Icon name="mdi-magnify" className="pointer-events-none absolute top-1/2 left-2 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={searchName}
              onChange={(event) => onSearchNameChange?.(event.target.value)}
              type="search"
              placeholder="Search name, battle tag or Discord"
              aria-label="Search players"
              className="pl-8"
            />
          </div>
        ) : null}

        {/* A phone keeps the search in view and folds the rest behind this button */}
        {!mdAndUp ? (
          <Button variant="secondary" aria-expanded={open} onClick={() => setOpen(!open)}>
            <Icon name="mdi-tune-variant" />
            Filters
            {activeCount ? <Badge className="ml-1">{activeCount}</Badge> : null}
          </Button>
        ) : null}

        {expanded && showSeason ? (
          <Select
            items={events.map((event) => ({ value: event.id, label: event.name }))}
            value={selectedSeasonFilter}
            onValueChange={(value) => onSelectedSeasonFilterChange?.(value as number | null)}
          >
            <SelectTrigger aria-label="Filter by events" className="w-full md:w-[220px]">
              <Icon name="mdi-calendar" className="text-muted-foreground" />
              <SelectValue placeholder="Filter by events" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value={null}>All events</SelectItem>
              {events.map((event) => (
                <SelectItem key={event.id} value={event.id}>
                  {event.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        ) : null}

        {expanded ? after : null}
      </div>

      {showRace || showMMR || showReset ? (
        <div className="mt-1 flex flex-wrap items-center gap-3">
          {showRace && expanded ? (
            <ToggleGroup
              variant="outline"
              spacing={0}
              value={searchRace ? [searchRace] : []}
              onValueChange={(value) => onSearchRaceChange?.(value[0] ?? null)}
              aria-label="Race"
            >
              {raceWrapper.races.map((race) => {
                const src = typeof race.icon === "string" ? race.icon : race.icon.src;
                return (
                  <ToggleGroupItem key={race.id} value={race.id} title={race.name} aria-label={race.name} className="min-w-12">
                    {/* A race off the filter reads grey, so the chosen one stands out in its own colours */}
                    <img
                      src={src}
                      alt={race.name}
                      className={cn("size-[22px]", searchRace === race.id ? "" : "opacity-60 grayscale")}
                    />
                    {searchRace === race.id ? <span className="ml-2">{race.name}</span> : null}
                  </ToggleGroupItem>
                );
              })}
            </ToggleGroup>
          ) : null}

          {showMMR && expanded ? (
            <div className="flex min-w-[220px] flex-1 items-center gap-3">
              <span className="text-sm text-muted-foreground">MMR</span>
              <Input
                value={rangeValues[0]}
                onChange={(event) => setRange(0, event.target.value)}
                aria-label="Lowest MMR"
                type="number"
                className="max-w-[88px] min-w-16"
              />
              <Slider
                value={rangeValues}
                onValueChange={(value) => onRangeValuesChange?.(value as number[])}
                min={min}
                max={max}
                step={step}
                className="min-w-[100px] flex-1"
              />
              <Input
                value={rangeValues[1]}
                onChange={(event) => setRange(1, event.target.value)}
                aria-label="Highest MMR"
                type="number"
                className="max-w-[88px] min-w-16"
              />
            </div>
          ) : null}

          {showReset ? (
            <div className="ms-auto flex items-center gap-3">
              {summary}
              <Button variant="ghost" onClick={() => onReset?.()}>
                <Icon name="mdi-filter-remove-outline" />
                Clear filters
              </Button>
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

export default FilterPanel;

// src/components/FilterPanel.vue
<template>
  <v-sheet class="mb-4 pa-3" border rounded="lg">
    <v-row dense align="center">
      <v-col v-if="showName">
        <v-text-field
          v-model="searchName"
          placeholder="Search name, battle tag or Discord"
          aria-label="Search players"
          prepend-inner-icon="mdi-magnify"
          variant="outlined"
          density="compact"
          hide-details
          clearable
        />
      </v-col>

      <!-- A phone keeps the search in view and folds the rest behind this button -->
      <v-col v-if="!mdAndUp" cols="auto">
        <v-btn variant="tonal" prepend-icon="mdi-tune-variant" :aria-expanded="open" @click="open = !open">
          Filters
          <v-badge v-if="activeCount" :content="activeCount" color="primary" inline />
        </v-btn>
      </v-col>

      <template v-if="expanded">
      <v-col v-if="showSeason" cols="12" md="3">
        <v-select
          v-model="selectedSeasonFilter"
          :items="events"
          item-title="name"
          item-value="id"
          placeholder="Filter by events"
          aria-label="Filter by events"
          prepend-inner-icon="mdi-calendar"
          variant="outlined"
          density="compact"
          hide-details
          clearable
        />
      </v-col>

      <slot name="after" />
      </template>
    </v-row>

    <v-row v-if="showRace || showMMR || showReset" dense align="center" class="mt-1">
      <v-col v-if="showRace && expanded" cols="12" sm="auto">
        <v-btn-toggle v-model="searchRace" variant="outlined" density="compact" divided rounded="lg" color="primary" aria-label="Race">
          <v-btn v-for="race in raceWrapper.races" :key="race.id" :value="race.id" :title="race.name" :aria-label="race.name" min-width="48">
            <img :src="race.icon" :alt="race.name" class="race-toggle" />
            <span v-if="searchRace === race.id" class="ml-2">{{ race.name }}</span>
          </v-btn>
        </v-btn-toggle>
      </v-col>

      <v-col v-if="showMMR && expanded" cols="12" md class="d-flex align-center ga-3">
        <span class="text-body-2 text-medium-emphasis">MMR</span>
        <v-text-field
          :model-value="rangeValues[0]"
          @update:model-value="v => setRange(0, v)"
          aria-label="Lowest MMR"
          type="number"
          variant="outlined"
          density="compact"
          hide-details
          hide-spin-buttons
          class="mmr-input"
        />
        <v-range-slider
          v-model="rangeValues"
          :min="min"
          :max="max"
          :step="step"
          strict
          color="primary"
          hide-details
          class="flex-grow-1 mmr-slider"
        />
        <v-text-field
          :model-value="rangeValues[1]"
          @update:model-value="v => setRange(1, v)"
          aria-label="Highest MMR"
          type="number"
          variant="outlined"
          density="compact"
          hide-details
          hide-spin-buttons
          class="mmr-input"
        />
      </v-col>
      <v-col v-if="showReset" cols="auto" class="d-flex align-center ga-3 ms-auto">
        <slot name="summary" />
        <v-btn variant="text" prepend-icon="mdi-filter-remove-outline" @click="$emit('reset')">Clear filters</v-btn>
      </v-col>
    </v-row>
  </v-sheet>
</template>

<script setup>
import { computed, ref } from 'vue';
import { useDisplay } from 'vuetify';
import { raceWrapper } from '@/helpers/races.js';

const props = defineProps({
  seasons: { type: Array, default: () => [] },
  extraActive: { type: Number, default: 0 }, // filters the after slot holds, counted on the phone button
  showName: { type: Boolean, default: true },
  showRace: { type: Boolean, default: true },
  showSeason: { type: Boolean, default: true },
  showMMR: { type: Boolean, default: true },
  showReset: { type: Boolean, default: true },
  min: { type: Number, default: 0 },
  max: { type: Number, default: 3000 },
  step: { type: Number, default: 10 },
});
defineEmits(['reset']);

const searchName = defineModel('searchName', { type: String, default: '' });
const searchRace = defineModel('searchRace', { type: [String, null], default: null });
const selectedSeasonFilter = defineModel('selectedSeasonFilter', { type: [String, Number, null], default: null });
const rangeValues = defineModel('rangeValues', { type: Array, default: () => [0, 3000] });

const events = computed(() => [...(props.seasons || [])].sort((a, b) => b.id - a.id));

const { mdAndUp } = useDisplay();
const open = ref(false);
const expanded = computed(() => mdAndUp.value || open.value);
const activeCount = computed(() => [
  searchRace.value,
  selectedSeasonFilter.value,
  rangeValues.value[0] !== props.min || rangeValues.value[1] !== props.max,
].filter(Boolean).length + props.extraActive);

const setRange = (i, value) => {
  const next = [...rangeValues.value];
  next[i] = Number(value) || 0;
  rangeValues.value = next;
};
</script>

<style scoped>
.race-toggle {
  width: 22px;
  height: 22px;
}
/* A race off the filter reads grey, so the chosen one stands out in its own colours */
.v-btn:not(.v-btn--active) .race-toggle {
  filter: grayscale(1);
  opacity: 0.6;
}
.mmr-input {
  min-width: 64px;
  max-width: 88px;
}
.mmr-input :deep(.v-field__input) {
  padding-inline: 8px;
}
.mmr-slider {
  min-width: 100px;
}
</style>
