// next/src/components/GroupedTable.tsx
"use client";
import { useState } from "react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/Icon";
import { cn } from "@/lib/utils";

export type GroupedColumn = {
  key: string;
  title?: string;
  align?: "right";
  width?: string;
  phone?: boolean; // phone: false hides the column under md
};

export type GroupedRow = { key: string | number; label?: string; title?: string };

/** The shared grouped table: one tinted, clickable header row per group opens its detail rows.
 *  Detail rows share the column grid, so their numbers line up under the header's and visibly sum
 *  to it. `group` fills the header cells, `rows` yields whole `<tr className="detail-row">` rows;
 *  `head[key]` replaces a title. A column with `phone: false` hides under md; the slot cell needs
 *  the same class. */
export function GroupedTable<G extends GroupedRow>({
  columns,
  groups,
  empty = "No data",
  defaultOpen,
  head,
  group,
  rows,
  className,
}: {
  columns: GroupedColumn[];
  groups: G[];
  empty?: string;
  defaultOpen?: boolean; // every group starts open, later groups too
  head?: Record<string, React.ReactNode>;
  group: (args: { group: G; open: boolean }) => React.ReactNode;
  rows: (args: { group: G }) => React.ReactNode;
  className?: string;
}) {
  // The set holds the groups the reader turned away from their default, so a group that arrives
  // later opens with `defaultOpen` and needs no effect to catch it up.
  const [toggled, setToggled] = useState<Set<string | number>>(new Set());
  const isOpen = (key: string | number) => !!defaultOpen !== toggled.has(key);
  const toggle = (key: string | number) =>
    setToggled((was) => {
      const next = new Set(was);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });

  return (
    <div className={cn("table-scroll grouped-table overflow-x-auto", className)}>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead style={{ width: "40px" }} />
            {columns.map((col) => (
              <TableHead
                key={col.key}
                className={cn(col.align === "right" && "text-right", col.phone === false && "hidden min-[960px]:table-cell")}
                style={col.width ? { width: col.width } : undefined}
              >
                {head?.[col.key] ?? col.title}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {groups.map((g) => (
            <GroupRows key={g.key} group={g} open={isOpen(g.key)} toggle={toggle} renderGroup={group} renderRows={rows} />
          ))}
          {groups.length === 0 ? (
            <TableRow>
              <TableCell colSpan={columns.length + 1} className="text-muted-foreground">
                {empty}
              </TableCell>
            </TableRow>
          ) : null}
        </TableBody>
      </Table>
    </div>
  );
}

function GroupRows<G extends GroupedRow>({
  group,
  open,
  toggle,
  renderGroup,
  renderRows,
}: {
  group: G;
  open: boolean;
  toggle: (key: string | number) => void;
  renderGroup: (args: { group: G; open: boolean }) => React.ReactNode;
  renderRows: (args: { group: G }) => React.ReactNode;
}) {
  return (
    <>
      <tr className="group-row cursor-pointer border-b" onClick={() => toggle(group.key)}>
        {/* the chevron is the keyboard route into the group; the row click stays for the mouse */}
        <TableCell>
          <Button
            variant="ghost"
            size="icon-sm"
            aria-expanded={open}
            aria-label={group.label || group.title || String(group.key)}
            onClick={(event) => {
              event.stopPropagation();
              toggle(group.key);
            }}
          >
            <Icon name={open ? "mdi-chevron-up" : "mdi-chevron-down"} />
          </Button>
        </TableCell>
        {renderGroup({ group, open })}
      </tr>
      {open ? renderRows({ group }) : null}
    </>
  );
}

export default GroupedTable;

// src/components/GroupedTable.vue
<!-- The shared grouped table: one tinted, clickable header row per group opens its
     detail rows. Detail rows share the column grid, so their numbers line up under
     the header's and visibly sum to it. `#group` fills the header cells, `#rows`
     yields whole `<tr class="detail-row">` rows; `#head.<key>` replaces a title.
     A column with `phone: false` hides under md; the slot cell needs the same class. -->
<template>
  <v-table density="compact" class="grouped-table">
    <thead>
      <tr>
        <th style="width: 40px"></th>
        <th
          v-for="col in columns"
          :key="col.key"
          :class="{ 'text-right': col.align === 'right', 'd-none d-md-table-cell': col.phone === false }"
          :style="col.width ? { width: col.width } : {}"
        >
          <slot :name="`head.${col.key}`">{{ col.title }}</slot>
        </th>
      </tr>
    </thead>
    <tbody>
      <template v-for="group in groups" :key="group.key">
        <tr class="group-row" @click="toggle(group.key)">
          <!-- the chevron is the keyboard route into the group; the row click stays for the mouse -->
          <td>
            <v-btn
              variant="text"
              size="small"
              :icon="open.has(group.key) ? 'mdi-chevron-up' : 'mdi-chevron-down'"
              :aria-expanded="open.has(group.key)"
              :aria-label="group.label || group.title || String(group.key)"
              @click.stop="toggle(group.key)"
            />
          </td>
          <slot name="group" :group="group" :open="open.has(group.key)" />
        </tr>
        <template v-if="open.has(group.key)">
          <slot name="rows" :group="group" />
        </template>
      </template>
      <tr v-if="!groups.length">
        <td :colspan="columns.length + 1" class="text-medium-emphasis">{{ empty }}</td>
      </tr>
    </tbody>
  </v-table>
</template>

<script setup>
import { ref, watch } from 'vue';

const props = defineProps({
  columns: { type: Array, required: true }, // [{ key, title, align?: 'right', width?, phone?: false hides it under md }]
  groups: { type: Array, required: true }, // each needs a unique `key`, and a `label` for the chevron
  empty: { type: String, default: 'No data' },
  defaultOpen: Boolean, // every group starts open, later groups too
});

const open = ref(new Set());
watch(() => props.groups, (groups) => {
  if (props.defaultOpen) open.value = new Set([...open.value, ...groups.map((g) => g.key)]);
}, { immediate: true });
const toggle = (key) => {
  open.value.has(key) ? open.value.delete(key) : open.value.add(key);
  open.value = new Set(open.value);
};
</script>

<style scoped>
.group-row {
  cursor: pointer;
}
.group-row > :deep(td),
.grouped-table :deep(.detail-row > td:first-child) {
  background: rgba(var(--v-theme-on-surface), 0.04);
}
</style>
