// next/src/components/PlayerName.tsx
"use client";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Icon } from "@/components/ui/Icon";
import { FlagIcon } from "@/components/FlagIcon";
import { RaceIcon } from "@/components/RaceIcon";
import { openPlayer, usePanelLinks } from "@/hooks/player-panel";
import { playerPath } from "@/helpers/players.mjs";
import { raceWrapper } from "@/helpers/races.js";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
export type Player = { id?: number | string | null; name?: string; country?: string | null; battleTag?: string | null; signup_race?: string | null } & Record<string, any>;

/** A player as flag, name, race and MMR. It links to the player page. On a drafting page and
 *  inside the side panel it opens the panel instead and shows a dock icon. */
export function PlayerName({
  player,
  race,
  host,
  plain,
  onClick,
  children,
}: {
  player: Player;
  race?: string;
  host?: boolean;
  plain?: boolean; // text only: a form in a dialog must not lose its input to a click
  onClick?: () => void;
  children?: React.ReactNode;
}) {
  // A series where the player played another race marks him, so a reader on a
  // phone sees the exception without hovering anything
  const offRace = !!race && !!player.signup_race && race !== player.signup_race;
  const offRaceHint = `Signed up as ${raceWrapper.getRaceObject(player.signup_race)?.name || player.signup_race}`;

  const inPanelMode = usePanelLinks();
  const clickable = !plain && !onClick && player.id != null;
  const opensPanel = clickable && inPanelMode;
  const to = clickable && !inPanelMode ? playerPath(player) : null;

  const className = cn("player-name inline-flex items-center gap-1.5 whitespace-nowrap text-inherit no-underline border-0 bg-transparent p-0", (onClick || clickable) && "cursor-pointer hover:text-primary [&:hover_.name]:underline");
  const body = (
    <>
      {player.country ? <FlagIcon countryIdentifier={player.country} /> : <span className="fp" />}
      <span className="name">{player.name}</span>
      {race ? <RaceIcon raceIdentifier={race} /> : race !== undefined ? <span className="fp w-[1.4em]" /> : null}
      {/* the cue is always coloured, so a reader knows before the click that the page stays */}
      {opensPanel ? <Icon name="mdi-dock-right" size={16} className="-ml-0.5 text-primary" /> : null}
      {offRace ? <Badge variant="outline" title={offRaceHint} className="text-warning border-warning">off-race</Badge> : null}
      {host ? <Badge variant="outline" className="text-primary-text border-primary">Host</Badge> : null}
      {children}
    </>
  );

  if (to) return <Link href={to} className={className}>{body}</Link>;
  if (opensPanel)
    return (
      <button type="button" className={className} title="Opens in a side panel" onClick={() => openPlayer(player)}>
        {body}
      </button>
    );
  if (onClick)
    return (
      <button type="button" className={className} onClick={onClick}>
        {body}
      </button>
    );
  return <span className={className}>{body}</span>;
}

export default PlayerName;

// src/components/PlayerName.vue
<template>
  <component
    :is="to ? RouterLink : 'span'"
    :to="to"
    class="player-name"
    :class="{ link: !!$attrs.onClick || clickable, 'panel-link': opensPanel }"
    :title="opensPanel ? 'Opens in a side panel' : undefined"
    @click="opensPanel && openPlayer(player)"
  >
    <RaceIcon v-if="race" :raceIdentifier="race" />
    <span v-else-if="race !== undefined" class="fp race-gap" />
    <FlagIcon v-if="player.country" :countryIdentifier="player.country" />
    <span v-else class="fp" />
    <span class="name">{{ player.name }}</span>
    <v-icon v-if="opensPanel" class="panel-cue" size="16" aria-label="Opens in a side panel">mdi-dock-right</v-icon>
    <v-chip v-if="offRace" size="x-small" variant="tonal" color="warning" :title="offRaceHint">off-race</v-chip>
    <v-chip v-if="host" size="x-small" variant="tonal" color="primary">Host</v-chip>
    <slot />
  </component>
</template>

<script setup>
import { computed, inject, useAttrs } from 'vue'
import { RouterLink } from 'vue-router'
import { openPlayer, panelLinks, playerPath } from '@/helpers/players'
import { raceWrapper } from '@/helpers/races.js'

const props = defineProps({
  player: { type: Object, required: true }, // needs name, country
  race: String, // the race for this (race, player) pair; omit to show none
  host: Boolean,
  plain: Boolean, // text only: a form in a dialog must not lose its input to a click
})

// A series where the player played another race marks him, so a reader on a
// phone sees the exception without hovering anything
const offRace = computed(
  () => !!props.race && !!props.player.signup_race && props.race !== props.player.signup_race
)
const offRaceHint = computed(
  () => `Signed up as ${raceWrapper.getRaceObject(props.player.signup_race)?.name || props.player.signup_race}`
)

// The name links to the player page, unless the view handles the click. On a
// drafting page and inside the panel it opens the panel instead, and the dock
// icon says so before the click.
const attrs = useAttrs()
const inPanelMode = inject(panelLinks, false)
const clickable = computed(() => !props.plain && !attrs.onClick && props.player.id != null)
const opensPanel = computed(() => clickable.value && inPanelMode)
const to = computed(() => (clickable.value && !inPanelMode ? playerPath(props.player) : null))
</script>

<style scoped>
.player-name {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  white-space: nowrap;
  color: inherit;
  text-decoration: none;
}
/* A missing icon leaves an empty flag box (same size and baseline), so names line up in a column. */
.race-gap { width: 1.4em; }
.link {
  cursor: pointer;
  transition: color 0.2s;
}
.link:hover {
  color: rgb(var(--v-theme-primary));
}
/* only the name underlines, not the flag or the Host and off-race chips */
.link:hover .name {
  text-decoration: underline;
}
/* the cue is always coloured, so a reader knows before the click that the page stays */
.panel-cue {
  color: rgb(var(--v-theme-primary));
  margin-left: -2px;
}
</style>
