// next/src/components/player/PlayerPanel.tsx
"use client";
import { useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/Icon";
import { Sheet, SheetContent, SheetTitle } from "@/components/ui/sheet";
import { PlayerProfile } from "@/components/player/PlayerProfile";
import { PanelLinksContext, panelPlayerKey, usePanelPlayerKey } from "@/hooks/player-panel";
import { canSeeRole } from "@/lib/routes";
import { useAuth } from "@/stores";

/** The player profile as a sheet on the right edge, over whatever page you are
 *  on. It sits above the page's own dialogs, so it also opens over the Report
 *  Result dialog and the Propose Series dialog. */
export function PlayerPanel() {
  const router = useRouter();
  const { me } = useAuth();
  const key = usePanelPlayerKey();

  // the key is already the address, whether it is a battle tag or an id
  const fullPage = `/player/${encodeURIComponent(key || "")}`;

  // A profile is member-only, and the route guard reads a missing session, not a
  // role. Anyone the panel refuses goes to the page instead, where that guard
  // sends him to the login, exactly as a name click did before the panel.
  const mayRead = !!me && canSeeRole(me.role, "member");
  const open = !!key && mayRead;
  useEffect(() => {
    if (!key || mayRead) return;
    panelPlayerKey.set(null);
    router.push(fullPage);
  }, [key, mayRead, fullPage, router]);

  return (
    <Sheet open={open} onOpenChange={(value) => { if (!value) panelPlayerKey.set(null); }}>
      <SheetContent
        side="right"
        showCloseButton={false}
        className="w-[560px] max-w-full gap-0 p-0 motion-reduce:transition-none sm:max-w-[560px]"
      >
        <SheetTitle className="sr-only">Player Profile</SheetTitle>
        {open ? (
          // a name inside the panel swaps the panel, so the page under it keeps its work
          <PanelLinksContext.Provider value>
            <div className="flex h-full flex-col">
              <div className="flex items-center gap-2 border-b border-border px-2 py-1.5">
                <Button variant="ghost" size="icon" aria-label="Close" onClick={() => panelPlayerKey.set(null)}>
                  <Icon name="mdi-close" />
                </Button>
                <div className="flex-1" />
                <Button
                  variant="ghost"
                  size="sm"
                  nativeButton={false}
                  render={<Link href={fullPage} onClick={() => panelPlayerKey.set(null)} />}
                >
                  Open full page
                  <Icon name="mdi-open-in-new" />
                </Button>
              </div>
              <div className="grow overflow-y-auto p-4">
                <PlayerProfile playerKey={key as string} />
              </div>
            </div>
          </PanelLinksContext.Provider>
        ) : null}
      </SheetContent>
    </Sheet>
  );
}

export default PlayerPanel;

// src/components/PlayerPanel.vue
<!-- The player profile as a sheet on the right edge, over whatever page you are
     on. It is a dialog, not a navigation drawer, so it also opens above the
     Report Result dialog and the Propose Series dialog. -->
<template>
  <v-dialog
    class="player-panel"
    transition="dialog-right-transition"
    :model-value="open"
    @update:model-value="value => { if (!value) panelPlayerKey = null; }"
  >
    <v-card v-if="open" class="d-flex flex-column">
      <v-toolbar density="compact" flat>
        <v-btn icon="mdi-close" variant="text" aria-label="Close" @click="panelPlayerKey = null" />
        <v-spacer />
        <v-btn variant="text" size="small" append-icon="mdi-open-in-new" :to="fullPage" @click="panelPlayerKey = null">
          Open full page
        </v-btn>
      </v-toolbar>
      <div class="flex-grow-1 overflow-y-auto pa-4">
        <PlayerProfile :playerKey="panelPlayerKey" />
      </div>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { computed, provide, watch } from 'vue';
import { useRouter } from 'vue-router';
import { storeToRefs } from 'pinia';
import { useAuthStore } from '@/stores';
import { canSeeRole } from '@/helpers';
import { panelLinks, panelPlayerKey } from '@/helpers/players';
import PlayerProfile from '@/components/PlayerProfile.vue';

const router = useRouter();
const { me } = storeToRefs(useAuthStore());
// a name inside the panel swaps the panel, so the page under it keeps its work
provide(panelLinks, true);

// the key is already the address, whether it is a battle tag or an id
const fullPage = computed(() => `/player/${encodeURIComponent(panelPlayerKey.value || '')}`);

// A profile is member-only, and the route guard reads a missing session, not a
// role. Anyone the panel refuses goes to the page instead, where that guard
// sends him to the login, exactly as a name click did before the panel.
const mayRead = computed(() => !!me.value && canSeeRole(me.value.role, 'member'));
const open = computed(() => !!panelPlayerKey.value && mayRead.value);
watch(panelPlayerKey, (key) => {
  if (!key || mayRead.value) return;
  panelPlayerKey.value = null;
  router.push(fullPage.value);
});
</script>

<style>
.player-panel {
  justify-content: flex-end;
}
.player-panel:not(.v-dialog--fullscreen) > .v-overlay__content {
  margin: 0;
  width: 560px;
  max-width: 100%;
  height: 100%;
  max-height: 100%;
}
.player-panel:not(.v-dialog--fullscreen) > .v-overlay__content > .v-card {
  border-radius: 0;
  height: 100%;
}
.player-panel.v-dialog--fullscreen > .v-overlay__content > .v-card {
  height: 100%;
}

/* Mirrors Vuetify's own dialog-bottom-transition, sliding from the right edge */
.dialog-right-transition-enter-active,
.dialog-right-transition-leave-active {
  transition-property: transform !important;
  pointer-events: none;
}
.dialog-right-transition-enter-active {
  transition-duration: 225ms !important;
  transition-timing-function: cubic-bezier(0, 0, 0.2, 1) !important;
}
.dialog-right-transition-leave-active {
  transition-duration: 125ms !important;
  transition-timing-function: cubic-bezier(0.4, 0, 1, 1) !important;
}
.dialog-right-transition-enter-from,
.dialog-right-transition-leave-to {
  transform: translateX(100%);
}
@media (prefers-reduced-motion: reduce) {
  .dialog-right-transition-enter-from,
  .dialog-right-transition-leave-to {
    transform: none;
  }
}
</style>
