// next/src/components/ladder/PlayerLadderTab.tsx
"use client";
import { useCallback, useEffect, useState } from "react";
import { DateTime } from "luxon";
import { AchievementIcon } from "@/components/AchievementIcon";
import { ColumnNote } from "@/components/ColumnNote";
import { RaceIcon } from "@/components/RaceIcon";
import { StatusAlert } from "@/components/StatusAlert";
import { W3CIcon } from "@/components/W3CIcon";
import { W3CMmr } from "@/components/W3CMmr";
import { Icon } from "@/components/ui/Icon";
import { TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { MD_AND_UP, useBreakpoint } from "@/hooks/breakpoint";
import { useLadderStore } from "@/stores";
import { LadderPlots } from "./LadderPlots";
import { SCORED_NOTE, achievementPoints } from "@/helpers/achievements.js";
import { dayWindow, fillDays } from "@/helpers/ladder-days.mjs";
import { raceWrapper } from "@/helpers/races.js";
import { w3cPlayerUrl } from "@/helpers/w3c-stats.js";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Badge = { id: string; name: string; description?: string; points: number; achieved_at?: string };

// the one subtitle of a sub block: MMR, versus race, achievements
const SUB = "mb-1 text-xs font-medium tracking-[0.0333em] text-muted-foreground";

// Stored in UTC, shown in the viewer's own time
const badgeDate = (iso?: string) => (iso ? DateTime.fromISO(iso, { zone: "utc" }).toLocal().toFormat("LLL d") : "");

/** One player's ladder record in one season: points, record, MMR, versus race and
 *  achievements. The matches themselves stay on W3Champions, linked beside the tiles */
export function PlayerLadderTab({ player, seasonId }: { player: any; seasonId: number }) {
  const mdAndUp = useBreakpoint(MD_AND_UP);
  const ladderStore = useLadderStore();

  const [data, setData] = useState<any>(null);
  const [seasonLadder, setSeasonLadder] = useState<any>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [showLocked, setShowLocked] = useState(false);

  useEffect(() => {
    let live = true;
    (async () => {
      try {
        const row = await ladderStore.userLadder(player.id, { seasonId });
        const season = ladderStore.ladders[seasonId] ?? (await ladderStore.seasonLadder(seasonId));
        if (!live) return;
        // a read that answers clears the message the last one left
        setErrorMessage(null);
        setData(row);
        setSeasonLadder(season);
      } catch (error) {
        if (!live) return;
        setData(null);
        setErrorMessage((error as Error).message);
      }
    })();
    return () => { live = false; };
    // the store's members are rebuilt every render, so the player and the season drive the read
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [player, seasonId]);

  // The MMR line fills whatever width the block has, on the page and in the side panel alike
  const [plotWidth, setPlotWidth] = useState(0);
  const plotBox = useCallback((el: HTMLDivElement) => {
    const observer = new ResizeObserver(([entry]) => setPlotWidth(Math.floor(entry.contentRect.width)));
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  const w3cStatsUrl = `${w3cPlayerUrl(player?.battleTag ?? "")}/statistics`;

  const games = data?.games ?? 0;
  const winrate = games ? `${Math.round((data.wins / games) * 100)}%` : "0%";

  // Where his MMR opened, its range and where it stands; absent until he plays
  const mmr = data?.mmr ?? {};
  const mmrChange = mmr.current != null && mmr.start != null ? mmr.current - mmr.start : 0;

  // One slot per day between his first and last ladder game, so the line reads as a calendar
  const window = dayWindow(data?.per_day);
  const mmrDays = window ? fillDays(data.per_day, window.start, window.end) : [];

  // The earned rules come with the player, the whole catalogue with the season
  const earned: Badge[] = data?.achievements ?? [];
  const achievedPoints = achievementPoints(earned);
  const ladderPoints = (data?.wins ?? 0) * 3 + (data?.losses ?? 0);

  const won = new Set(earned.map((badge) => badge.id));
  const locked: Badge[] = (seasonLadder?.achievement_rules ?? []).filter((rule: Badge) => !won.has(rule.id));

  // Most games first, so the races he meets most sit on top
  const vs = data?.vs_race ?? {};
  const versusRaces = ["HU", "OC", "NE", "UD", "RANDOM"]
    .map((code) => {
      const [w, l] = vs[code] ?? [0, 0];
      const total = w + l;
      return { code, name: raceWrapper.getRaceObject(code)?.name, w, l, total, rate: total ? Math.round((w / total) * 100) : 0 };
    })
    .filter((row) => row.total > 0)
    .sort((a, b) => b.total - a.total);

  return (
    // the block's own width, not the window's: the side panel is narrow on a wide screen
    <div className="@container">
      <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} />

      <section className="pb-4">
        <h4 className="mb-2 text-base font-medium">
          Ladder grind <span className="text-xs text-muted-foreground">{data?.points ?? 0} points</span>
        </h4>
        <div className="mb-3 flex flex-wrap items-start gap-x-10 gap-y-3 @max-[700px]:gap-x-6">
          <div>
            <div className="text-xs text-muted-foreground">
              <ColumnNote title="Ladder points" note={SCORED_NOTE} />
            </div>
            <div className="text-xl">{ladderPoints}</div>
            <div className="text-xs text-muted-foreground">3 per win, 1 per loss</div>
          </div>
          <div>
            <div className="text-xs text-muted-foreground">Achievement points</div>
            <div className="text-xl">{achievedPoints}</div>
            <div className="text-xs text-muted-foreground">
              {earned.length} earned, {locked.length} locked
            </div>
          </div>
          <div>
            <div className="text-xs text-muted-foreground">Record</div>
            <div className="text-xl">
              <span className="text-win">{data?.wins ?? 0}</span>
              <span className="text-muted-foreground"> &ndash; </span>
              <span className="text-loss">{data?.losses ?? 0}</span>
            </div>
            <div className="text-xs text-muted-foreground">
              {winrate} of {games} games
            </div>
          </div>
          {player?.battleTag ? (
            <a href={w3cStatsUrl} target="_blank" className="ml-auto inline-flex items-center self-start text-xs">
              <W3CIcon size={14} className="mr-1" />
              W3Champions
            </a>
          ) : null}
        </div>

        {mmr.current != null ? (
          <div className="mb-4">
            <div className={SUB}>
              <W3CMmr />
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <span className="text-xl">{mmr.current}</span>
              {mmrChange > 0 ? <span className="text-win">&#9650; {mmrChange}</span> : null}
              {mmrChange < 0 ? <span className="text-loss">&#9660; {-mmrChange}</span> : null}
              {mmr.min != null && mmr.max != null ? (
                <span className="text-xs text-muted-foreground">
                  Low {mmr.min} &middot; High {mmr.max}
                </span>
              ) : null}
            </div>
            <div ref={plotBox}>
              {plotWidth && mmrDays.length > 1 ? <LadderPlots days={mmrDays} games={false} width={plotWidth} /> : null}
            </div>
          </div>
        ) : null}

        <div className="grid grid-cols-2 gap-6 @max-[700px]:grid-cols-1 @max-[700px]:gap-3">
          <div>
            <div className={SUB}>Versus race</div>
            <div className="table-scroll overflow-x-auto">
              <table className="w-full caption-bottom text-sm">
                {versusRaces.length ? (
                  <TableHeader>
                    <TableRow>
                      <TableHead>Race</TableHead>
                      <TableHead className="text-right">Record</TableHead>
                      <TableHead />
                      <TableHead className="text-right">Rate</TableHead>
                      <TableHead className="text-right">Games</TableHead>
                    </TableRow>
                  </TableHeader>
                ) : null}
                <TableBody>
                  {!versusRaces.length ? (
                    <TableRow>
                      <TableCell className="text-xs text-muted-foreground">No ladder games yet.</TableCell>
                    </TableRow>
                  ) : null}
                  {versusRaces.map((row) => (
                    <TableRow key={row.code}>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <RaceIcon raceIdentifier={row.code} />
                          {row.name}
                        </div>
                      </TableCell>
                      <TableCell className="text-right whitespace-nowrap">
                        <span className="text-win">{row.w}</span> &ndash; <span className="text-loss">{row.l}</span>
                      </TableCell>
                      <TableCell className="w-[120px] @max-[700px]:w-[72px]">
                        <div className="h-[6px] overflow-hidden rounded-[3px] bg-[rgba(var(--v-theme-on-surface),0.12)]">
                          <div className="h-full rounded-[3px] bg-win" style={{ width: `${row.rate}%` }} />
                        </div>
                      </TableCell>
                      <TableCell className="text-right text-muted-foreground">{row.rate}%</TableCell>
                      <TableCell className="text-right text-muted-foreground">{row.total}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </table>
            </div>
          </div>
          <div>
            <div className={SUB}>Achievements</div>
            {earned.map((badge) => (
              <div key={badge.id} className="flex items-center border-b py-1">
                <AchievementIcon id={badge.id} className="mr-3 text-primary" />
                <span className="mr-3 text-sm font-medium">{badge.name}</span>
                {mdAndUp ? <span className="text-xs text-muted-foreground">{badge.description}</span> : null}
                <span className="ml-auto" />
                <span className="ml-3 text-xs whitespace-nowrap text-muted-foreground">{badgeDate(badge.achieved_at)}</span>
                <span className="ml-3 text-sm text-primary-text">+{badge.points}</span>
              </div>
            ))}
            {!earned.length ? <div className="text-xs text-muted-foreground">None earned yet.</div> : null}
            <button
              type="button"
              className="mt-2 mb-1 flex w-fit cursor-pointer items-center text-xs text-muted-foreground"
              onClick={() => setShowLocked((open) => !open)}
            >
              <span>Locked &middot; {locked.length}</span>
              <Icon name={showLocked ? "mdi-chevron-up" : "mdi-chevron-down"} size="1rem" className="ml-1" />
            </button>
            {showLocked
              ? locked.map((badge) => (
                  <div key={badge.id} className="flex items-center border-b py-1 text-muted-foreground">
                    <AchievementIcon id={badge.id} className="mr-3" />
                    <span className="mr-3 text-sm">{badge.name}</span>
                    {mdAndUp ? <span className="text-xs">{badge.description}</span> : null}
                    <span className="ml-auto" />
                    <span className="ml-3 text-sm">+{badge.points}</span>
                  </div>
                ))
              : null}
          </div>
        </div>
      </section>
    </div>
  );
}

export default PlayerLadderTab;

// src/components/PlayerLadderTab.vue
<!-- One player's ladder record in one season: points, record, MMR, versus race and
     achievements. The matches themselves stay on W3Champions, linked beside the tiles -->
<template>
  <div class="ladder-tab">
    <StatusAlert v-model="errorMessage" />

    <section class="section">
      <h4 class="text-body-1 font-weight-medium">Ladder grind <span class="text-caption text-medium-emphasis">{{ data?.points ?? 0 }} points</span></h4>
      <div class="tiles">
        <div>
          <ColumnNote title="Ladder points" :note="SCORED_NOTE" class="text-caption text-medium-emphasis" />
          <div class="text-h6">{{ ladderPoints }}</div>
          <div class="text-caption text-medium-emphasis">3 per win, 1 per loss</div>
        </div>
        <div>
          <div class="text-caption text-medium-emphasis">Achievement points</div>
          <div class="text-h6">{{ achievedPoints }}</div>
          <div class="text-caption text-medium-emphasis">{{ earned.length }} earned, {{ locked.length }} locked</div>
        </div>
        <div>
          <div class="text-caption text-medium-emphasis">Record</div>
          <div class="text-h6">
            <span class="text-win">{{ data?.wins ?? 0 }}</span>
            <span class="text-medium-emphasis"> – </span>
            <span class="text-loss">{{ data?.losses ?? 0 }}</span>
          </div>
          <div class="text-caption text-medium-emphasis">{{ winrate }} of {{ data?.games ?? 0 }} games</div>
        </div>
        <v-spacer />
        <a v-if="player?.battleTag" :href="w3cStatsUrl" target="_blank" class="text-caption d-inline-flex align-center align-self-start"><W3CIcon :size="14" class="mr-1" />W3Champions</a>
      </div>

      <div v-if="mmr.current != null" class="mb-4">
        <div class="sub"><W3CMmr /></div>
        <div class="d-flex align-center flex-wrap ga-3">
          <span class="text-h6">{{ mmr.current }}</span>
          <span v-if="mmrChange > 0" class="text-win">&#9650; {{ mmrChange }}</span>
          <span v-else-if="mmrChange < 0" class="text-loss">&#9660; {{ -mmrChange }}</span>
          <span v-if="mmr.min != null && mmr.max != null" class="text-caption text-medium-emphasis">Low {{ mmr.min }} &middot; High {{ mmr.max }}</span>
        </div>
        <div ref="plotBox">
          <LadderPlots v-if="plotWidth && mmrDays.length > 1" :days="mmrDays" :games="false" :width="plotWidth" />
        </div>
      </div>

      <div class="split">
        <div>
          <div class="sub">Versus race</div>
          <v-table density="compact" class="versus">
            <thead v-if="versusRaces.length">
              <tr>
                <th>Race</th>
                <th class="text-right">Record</th>
                <th></th>
                <th class="text-right">Rate</th>
                <th class="text-right">Games</th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="!versusRaces.length"><td class="text-caption text-medium-emphasis">No ladder games yet.</td></tr>
              <tr v-for="row in versusRaces" :key="row.code">
                <td><div class="d-flex align-center ga-2"><RaceIcon :raceIdentifier="row.code" />{{ row.name }}</div></td>
                <td class="text-right text-no-wrap"><span class="text-win">{{ row.w }}</span> – <span class="text-loss">{{ row.l }}</span></td>
                <td class="bar"><div class="meter"><div class="fill" :style="{ width: `${row.rate}%` }" /></div></td>
                <td class="text-right text-medium-emphasis">{{ row.rate }}%</td>
                <td class="text-right text-medium-emphasis">{{ row.total }}</td>
              </tr>
            </tbody>
          </v-table>
        </div>
        <div>
          <div class="sub">Achievements</div>
          <div v-for="badge in earned" :key="badge.id" class="d-flex align-center badge-row">
            <AchievementIcon :id="badge.id" class="mr-3 text-primary" />
            <span class="text-body-2 font-weight-medium mr-3">{{ badge.name }}</span>
            <span v-if="mdAndUp" class="text-caption text-medium-emphasis">{{ badge.description }}</span>
            <v-spacer />
            <span class="text-caption text-medium-emphasis text-no-wrap ml-3">{{ badgeDate(badge.achieved_at) }}</span>
            <span class="text-body-2 text-primary-text ml-3">+{{ badge.points }}</span>
          </div>
          <div v-if="!earned.length" class="text-caption text-medium-emphasis">None earned yet.</div>
          <div
            class="text-caption text-medium-emphasis mt-2 mb-1 d-flex align-center locked-toggle"
            @click="showLocked = !showLocked"
          >
            <span>Locked &middot; {{ locked.length }}</span>
            <v-icon size="small" class="ml-1">{{ showLocked ? 'mdi-chevron-up' : 'mdi-chevron-down' }}</v-icon>
          </div>
          <template v-if="showLocked">
            <div v-for="badge in locked" :key="badge.id" class="d-flex align-center badge-row text-medium-emphasis">
              <AchievementIcon :id="badge.id" class="mr-3" />
              <span class="text-body-2 mr-3">{{ badge.name }}</span>
              <span v-if="mdAndUp" class="text-caption">{{ badge.description }}</span>
              <v-spacer />
              <span class="text-body-2 ml-3">+{{ badge.points }}</span>
            </div>
          </template>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { DateTime } from 'luxon';
import { useDisplay } from 'vuetify';
import { useLadderStore } from '@/stores';
import LadderPlots from '@/components/LadderPlots.vue';
import RaceIcon from '@/components/RaceIcon.vue';
import W3CMmr from '@/components/W3CMmr.vue';
import W3CIcon from '@/components/W3CIcon.vue';
import { achievementPoints, SCORED_NOTE } from '@/helpers/achievements';
import { dayWindow, fillDays } from '@/helpers/ladder-days.mjs';
import { raceWrapper } from '@/helpers/races';
import { w3cPlayerUrl } from '@/helpers/w3c-stats';
import AchievementIcon from '@/components/AchievementIcon.vue';
import ColumnNote from '@/components/ColumnNote.vue';
import StatusAlert from '@/components/StatusAlert.vue';

const props = defineProps({
  player: { type: Object, required: true },
  seasonId: { type: Number, required: true },
});

const { mdAndUp } = useDisplay();
const ladderStore = useLadderStore();

const data = ref(null);
const seasonLadder = ref(null);
const errorMessage = ref(null);
const showLocked = ref(false);

const w3cStatsUrl = computed(() => `${w3cPlayerUrl(props.player?.battleTag ?? '')}/statistics`);

const winrate = computed(() => {
  const games = data.value?.games ?? 0;
  return games ? `${Math.round((data.value.wins / games) * 100)}%` : '0%';
});

// Where his MMR opened, its range and where it stands; absent until he plays
const mmr = computed(() => data.value?.mmr ?? {});
const mmrChange = computed(() =>
  (mmr.value.current != null && mmr.value.start != null ? mmr.value.current - mmr.value.start : 0));

// One slot per day between his first and last ladder game, so the line reads as a calendar
const mmrDays = computed(() => {
  const window = dayWindow(data.value?.per_day);
  return window ? fillDays(data.value.per_day, window.start, window.end) : [];
});

// The MMR line fills whatever width the block has, on the page and in the side panel alike
const plotBox = ref(null);
const plotWidth = ref(0);
const observer = new ResizeObserver(([entry]) => { plotWidth.value = Math.floor(entry.contentRect.width); });
watch(plotBox, (el) => { observer.disconnect(); if (el) observer.observe(el); });
onBeforeUnmount(() => observer.disconnect());

// The earned rules come with the player, the whole catalogue with the season
const earned = computed(() => data.value?.achievements ?? []);
const achievedPoints = computed(() => achievementPoints(earned.value));
const ladderPoints = computed(() => (data.value?.wins ?? 0) * 3 + (data.value?.losses ?? 0));

const locked = computed(() => {
  const won = new Set(earned.value.map(badge => badge.id));
  return (seasonLadder.value?.achievement_rules ?? []).filter(rule => !won.has(rule.id));
});

// Most games first, so the races he meets most sit on top
const versusRaces = computed(() => {
  const vs = data.value?.vs_race ?? {};
  return ['HU', 'OC', 'NE', 'UD', 'RANDOM']
    .map(code => {
      const [w, l] = vs[code] ?? [0, 0];
      const total = w + l;
      return { code, name: raceWrapper.getRaceObject(code).name, w, l, total, rate: total ? Math.round((w / total) * 100) : 0 };
    })
    .filter(row => row.total > 0)
    .sort((a, b) => b.total - a.total);
});

// Stored in UTC, shown in the viewer's own time
const badgeDate = (iso) => DateTime.fromISO(iso, { zone: 'utc' }).toLocal().toFormat('LLL d');

const load = async () => {
  errorMessage.value = null;
  try {
    data.value = await ladderStore.userLadder(props.player.id, { seasonId: props.seasonId });
    seasonLadder.value =
      ladderStore.ladders[props.seasonId] ?? (await ladderStore.seasonLadder(props.seasonId));
  } catch (error) {
    data.value = null;
    errorMessage.value = error.message;
  }
};

watch(() => [props.player, props.seasonId], load, { immediate: true });
</script>

<style scoped>
.ladder-tab { container-type: inline-size; }
.section { padding-bottom: 16px; }
.section h4 { margin-bottom: 8px; }
/* the one subtitle of a sub block: MMR, versus race, achievements */
.sub {
  font-size: 0.75rem;
  font-weight: 500;
  letter-spacing: 0.0333em;
  color: rgba(var(--v-theme-on-surface), var(--v-medium-emphasis-opacity));
  margin-bottom: 4px;
}
.tiles { display: flex; flex-wrap: wrap; gap: 12px 40px; align-items: flex-start; margin-bottom: 12px; }
.split { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
.versus .bar { width: 120px; }
.meter { height: 6px; border-radius: 3px; background: rgba(var(--v-theme-on-surface), 0.12); overflow: hidden; }
.fill { height: 100%; background: rgb(var(--v-theme-win)); border-radius: 3px; }
.badge-row {
  padding: 4px 0;
  border-bottom: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
}
.locked-toggle {
  cursor: pointer;
  width: fit-content;
}
/* the block's own width, not the window's: the side panel is narrow on a wide screen */
@container (max-width: 700px) {
  .split { grid-template-columns: 1fr; gap: 12px; }
  .versus .bar { width: 72px; }
  .tiles { gap: 12px 24px; }
}
</style>
