// next/src/components/RaceMmrChips.tsx
"use client";
import { RaceIcon } from "@/components/RaceIcon";
import { Badge } from "@/components/ui/badge";
import { TapTooltip } from "@/components/ui/TapTooltip";
import { raceWrapper } from "@/helpers/races.js";
import { getAllRaceStats } from "@/helpers/w3c-stats.js";

/* eslint-disable @typescript-eslint/no-explicit-any */
type RaceStat = { race: string; mmr?: number; wins?: number; losses?: number; games?: number; wc3_season?: number };

const raceName = (race: string) => raceWrapper.getRaceObject(race)?.name || race;

/** One chip per race the player has ladder games on: race icon + that race's MMR.
 *  A player is not one race, so every raced MMR shows; races without games stay hidden.
 *  `max` keeps the best ones as chips and folds the rest into a "+n" chip. */
export function RaceMmrChips({
  player,
  w3cSeason,
  max = Infinity,
}: {
  player: Record<string, any>; // needs w3c_stats
  w3cSeason?: number; // current W3C season; a stat from an older season names its own
  max?: number;
}) {
  const raceStats: RaceStat[] = getAllRaceStats(player, w3cSeason)
    .filter((stat: RaceStat) => (stat.games || 0) > 0)
    .sort((a: RaceStat, b: RaceStat) => (b.mmr || 0) - (a.mmr || 0));
  return (
    <span className="inline-flex items-center gap-2">
      {raceStats.slice(0, max).map((stat) => (
        <TapTooltip
          key={stat.race}
          content={`${raceName(stat.race)}: ${stat.wins || 0} wins, ${stat.losses || 0} losses in season ${stat.wc3_season}`}
        >
          <Badge variant="secondary">
            <RaceIcon raceIdentifier={stat.race} />
            {stat.mmr}
            {w3cSeason && stat.wc3_season !== w3cSeason ? <span className="ml-1 text-xs text-muted-foreground">S{stat.wc3_season}</span> : null}
          </Badge>
        </TapTooltip>
      ))}
      {raceStats.length > max ? (
        <TapTooltip
          content={
            <div>
              {raceStats.slice(max).map((stat) => (
                <div key={stat.race}>
                  {raceName(stat.race)} {stat.mmr}
                  {w3cSeason && stat.wc3_season !== w3cSeason ? ` (S${stat.wc3_season})` : ""}
                </div>
              ))}
            </div>
          }
        >
          <Badge variant="secondary">+{raceStats.length - max}</Badge>
        </TapTooltip>
      ) : null}
      {!raceStats.length ? <span className="text-xs text-muted-foreground">no ladder games</span> : null}
    </span>
  );
}

export default RaceMmrChips;

// src/components/RaceMmrChips.vue
<!-- One chip per race the player has ladder games on: race icon + that race's MMR.
     A player is not one race, so every raced MMR shows; races without games stay hidden.
     `max` keeps the best ones as chips and folds the rest into a "+n" chip. -->
<template>
  <span class="d-inline-flex align-center ga-2">
    <v-tooltip
      v-for="stat in raceStats.slice(0, max)"
      :key="stat.race"
      location="top"
      :text="`${raceName(stat.race)}: ${stat.wins || 0} wins, ${stat.losses || 0} losses in season ${stat.wc3_season}`"
    >
      <template #activator="{ props: tooltip }">
        <v-chip v-bind="tooltip" size="small" variant="tonal">
          <RaceIcon :raceIdentifier="stat.race" class="mr-1" />
          {{ stat.mmr }}
          <span v-if="w3cSeason && stat.wc3_season !== w3cSeason" class="text-caption text-medium-emphasis ml-1">S{{ stat.wc3_season }}</span>
        </v-chip>
      </template>
    </v-tooltip>
    <v-tooltip v-if="raceStats.length > max" location="top">
      <template #activator="{ props: tooltip }">
        <v-chip v-bind="tooltip" size="small" variant="tonal">+{{ raceStats.length - max }}</v-chip>
      </template>
      <div v-for="stat in raceStats.slice(max)" :key="stat.race">
        {{ raceName(stat.race) }} {{ stat.mmr }}<template v-if="w3cSeason && stat.wc3_season !== w3cSeason"> (S{{ stat.wc3_season }})</template>
      </div>
    </v-tooltip>
    <span v-if="!raceStats.length" class="text-caption text-medium-emphasis">no ladder games</span>
  </span>
</template>

<script setup>
import { computed } from 'vue';
import RaceIcon from '@/components/RaceIcon.vue';
import { raceWrapper } from '@/helpers/races.js';
import { getAllRaceStats } from '@/helpers/w3c-stats';

const props = defineProps({
  player: { type: Object, required: true }, // needs w3c_stats
  w3cSeason: Number, // current W3C season; a stat from an older season names its own
  max: { type: Number, default: Infinity },
});

const raceStats = computed(() =>
  getAllRaceStats(props.player, props.w3cSeason)
    .filter((stat) => (stat.games || 0) > 0)
    .sort((a, b) => (b.mmr || 0) - (a.mmr || 0))
);
const raceName = (race) => raceWrapper.getRaceObject(race)?.name || race;
</script>
