// next/src/components/RaceSelect.tsx
"use client";
import { Combobox } from "@/components/ui/Combobox";
import { RaceIcon } from "@/components/RaceIcon";
import { raceWrapper } from "@/helpers/races.js";

/** The race picker. `exclude` names race ids the list leaves out. */
export function RaceSelect({
  value,
  onChange,
  label = "Race",
  exclude = [],
  id,
}: {
  value: string | null;
  onChange: (value: string | null) => void;
  label?: string;
  exclude?: string[];
  id?: string;
}) {
  const items = raceWrapper.races
    .filter((race: { id: string }) => !exclude.includes(race.id))
    .map((race: { id: string; name: string }) => ({ value: race.id, title: race.name }));
  return (
    <Combobox
      id={id}
      label={label}
      items={items}
      value={value}
      onChange={onChange}
      row={(item) => (
        <span className="flex items-center gap-2">
          <RaceIcon raceIdentifier={item.value} />
          {item.title}
        </span>
      )}
    />
  );
}

export default RaceSelect;

// src/components/RaceSelect.vue
<template>
    <v-autocomplete
        v-model="model"
        :label="label"
        :menu-props="{ scrollStrategy: 'close'}"
        item-title="name"
        item-value="id"
        :items="items">
        <template v-slot:selection="{ item }">            
        <span>            
            <RaceIcon :raceIdentifier="item.raw.id" />
            {{ item.raw.name }}
        </span>     
        </template>
        <template v-slot:item="{ props: itemProps, item }">
        <v-list-item
            v-bind="itemProps"
            :title="item.raw.name">
            <template v-slot:prepend>
                <RaceIcon :raceIdentifier="item.raw.id" />
            </template>                         
        </v-list-item>
        </template>
    </v-autocomplete>
</template>

<script setup>
import { computed } from 'vue'
import { raceWrapper } from '@/helpers/races.js'

const model = defineModel();
const props = defineProps({
  label: { type: String, default: 'Race' },
  exclude: { type: Array, default: () => [] }, // race ids the list leaves out
});
const items = computed(() => raceWrapper.races.filter((race) => !props.exclude.includes(race.id)));
</script>
