// next/src/components/StatusAlert.tsx
"use client";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/** A load or save message. It offers a retry when the page can load again. */
export function StatusAlert({
  modelValue,
  type = "error",
  retry,
  onClose,
  className,
}: {
  modelValue?: string | null;
  type?: "error" | "success" | "info" | "warning";
  retry?: (() => void) | null;
  onClose?: () => void;
  className?: string;
}) {
  if (!modelValue) return null;
  const tone = type === "error" ? "text-error" : type === "success" ? "text-success" : type === "warning" ? "text-warning" : "text-info";
  return (
    <Alert className={cn("alert mb-4", tone, className)}>
      <AlertDescription className="text-foreground">
        <div className="flex items-start gap-2">
          <span className="flex-1">{modelValue}</span>
          {!retry && onClose ? (
            <Button variant="ghost" size="sm" aria-label="Close" onClick={onClose}>
              ×
            </Button>
          ) : null}
        </div>
        {/* A page that can read itself again offers the action its message names */}
        {retry ? (
          <div className="mt-2">
            <Button variant="outline" size="sm" onClick={retry}>
              Try again
            </Button>
          </div>
        ) : null}
      </AlertDescription>
    </Alert>
  );
}

export default StatusAlert;

// src/components/StatusAlert.vue
<template>
  <v-alert
    v-if="modelValue"
    :type="type"
    variant="tonal"
    border="start"
    :border-color="type === 'error' ? 'error' : 'success'"
    class="mb-4"
    :closable="!retry"
    @click:close="emit('update:modelValue', null)"
  >
    {{ modelValue }}
    <!-- A page that can read itself again offers the action its message names -->
    <div v-if="retry" class="mt-2">
      <v-btn variant="outlined" size="small" @click="retry">Try again</v-btn>
    </div>
  </v-alert>
</template>

<script setup>
defineProps({
  modelValue: { type: String, default: null },
  type: { type: String, default: 'error' },
  retry: { type: Function, default: null },
});

const emit = defineEmits(['update:modelValue']);
</script>
