// src/views/LeagueView.vue
<!-- One league and the events it has run, newest first. An admin adds the next run
     here; the stages and the map pool are set on the event's own page. -->
<template>
  <v-container fluid class="pa-4">
    <v-row class="mb-4">
      <v-col>
        <h1 class="text-h5 text-md-h3 font-weight-bold">
          <v-icon class="mr-2" size="large">mdi-shield-star</v-icon>
          {{ league?.name || 'League' }}
        </h1>
        <div class="text-medium-emphasis mt-1">
          {{ titleOf(ENTRANT_KINDS, league?.entrant_kind) }}
          <a v-if="league?.page_url" class="ml-3" :href="league.page_url" target="_blank" rel="noopener noreferrer">Page</a>
        </div>
      </v-col>
    </v-row>

    <StatusAlert v-model="error" />

    <div v-if="auth.isAdmin" class="d-flex justify-end mb-4">
      <v-btn variant="elevated" color="primary" prepend-icon="mdi-plus" :to="`/events/new?league=${leagueId}`">New event</v-btn>
    </div>

    <v-card elevation="2">
      <v-progress-linear v-if="loading" indeterminate />
      <v-table density="comfortable" hover>
        <thead>
          <tr>
            <th>Event</th>
            <th class="d-none d-md-table-cell">Kind</th>
            <th class="d-none d-md-table-cell">Dates</th>
            <th>State</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="event in events" :key="event.id">
            <td class="py-3">
              <RouterLink :to="`/events/${event.id}`"><strong>{{ event.name }}</strong></RouterLink>
              <!-- a phone drops the two middle columns, so their words ride under the name -->
              <div class="d-md-none text-caption text-medium-emphasis">
                {{ [titleOf(EVENT_KINDS, event.kind), dateRange(event)].filter(Boolean).join(' · ') }}
              </div>
            </td>
            <td class="d-none d-md-table-cell">{{ titleOf(EVENT_KINDS, event.kind) }}</td>
            <td class="d-none d-md-table-cell text-no-wrap">{{ dateRange(event) || '—' }}</td>
            <td>
              <v-chip size="small" variant="tonal" :color="STATE_COLOR[stateOf(event)]">
                {{ STATE_LABEL[stateOf(event)] || '—' }}
              </v-chip>
            </td>
          </tr>
          <tr v-if="!events.length && !loading">
            <td colspan="4" class="text-medium-emphasis py-6 text-center">
              No events yet. An event is one run of this league that players sign up for.
            </td>
          </tr>
        </tbody>
      </v-table>
    </v-card>
  </v-container>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';

import StatusAlert from '@/components/StatusAlert.vue';
import { dateRange, ENTRANT_KINDS, EVENT_KINDS, STATE_COLOR, STATE_LABEL, stateOf, titleOf } from '@/helpers/event-labels.mjs';
import { useAuthStore, useEventStore } from '@/stores';

const route = useRoute();
const auth = useAuthStore();
const store = useEventStore();
const leagueId = Number(route.params.id);
const league = ref(null);
const loading = ref(true);
const error = ref(null);

// The read answers every event of the league, drafts included, so a member is filtered out
const events = computed(() => (league.value?.events || []).filter((e) => auth.isAdmin || e.published !== false));

const load = async () => {
  loading.value = true;
  try {
    league.value = await store.fetchLeague(leagueId);
  } catch (e) {
    error.value = `The league did not load: ${e.message}`;
  } finally {
    loading.value = false;
  }
};

onMounted(load);
</script>

// next/src/app/(app)/leagues/[id]/LeagueView.tsx
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Icon } from "@/components/ui/Icon";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toneClass } from "@/components/ui/tone";
import { StatusAlert } from "@/components/StatusAlert";
import { dateRange, ENTRANT_KINDS, EVENT_KINDS, STATE_COLOR, STATE_LABEL, stateOf, titleOf } from "@/helpers/event-labels.mjs";
import { useAuth, useEventStore } from "@/stores";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const phoneCell = "hidden min-[960px]:table-cell";
// event-labels.mjs is plain JS, so its records index by a known key; the seam widens them
const stateColor = STATE_COLOR as Record<string, string>;
const stateLabel = STATE_LABEL as Record<string, string>;

/** One league and the events it has run, newest first. An admin adds the next run
 *  here; the stages and the map pool are set on the event's own page. */
export function LeagueView({ id }: { id: string }) {
  const auth = useAuth();
  const store = useEventStore();
  const leagueId = Number(id);
  const [league, setLeague] = useState<Row | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // The read answers every event of the league, drafts included, so a member is filtered out
  const events: Row[] = (league?.events || []).filter((e: Row) => auth.isAdmin || e.published !== false);

  useEffect(() => {
    const load = async () => {
      try {
        setLeague(await store.fetchLeague(leagueId));
      } catch (e) {
        setError(`The league did not load: ${(e as Error).message}`);
      } finally {
        setLoading(false);
      }
    };
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [leagueId]);

  return (
    <>
      <div className="mb-6">
        <h1>
          <span className="inline-flex items-center gap-2">
            <Icon name="mdi-shield-star" />
            {league?.name || "League"}
          </span>
        </h1>
        <div className="mt-1 text-muted-foreground">
          {titleOf(ENTRANT_KINDS, league?.entrant_kind)}
          {league?.page_url ? (
            <a className="ml-3" href={league.page_url} target="_blank" rel="noopener noreferrer">
              Page
            </a>
          ) : null}
        </div>
      </div>

      <StatusAlert modelValue={error} onClose={() => setError(null)} />

      {auth.isAdmin ? (
        <div className="mb-4 flex justify-end">
          <Button nativeButton={false} render={<Link href={`/events/new?league=${leagueId}`} />}>
            <Icon name="mdi-plus" />
            New event
          </Button>
        </div>
      ) : null}

      <Card className="card">
        {loading ? <Progress value={null} /> : null}
        <div className="table-scroll overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Event</TableHead>
                <TableHead className={phoneCell}>Kind</TableHead>
                <TableHead className={phoneCell}>Dates</TableHead>
                <TableHead>State</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {events.map((event) => (
                <TableRow key={event.id}>
                  <TableCell className="py-3">
                    <Link href={`/events/${event.id}`}>
                      <strong>{event.name}</strong>
                    </Link>
                    {/* a phone drops the two middle columns, so their words ride under the name */}
                    <div className="text-xs text-muted-foreground min-[960px]:hidden">{[titleOf(EVENT_KINDS, event.kind), dateRange(event)].filter(Boolean).join(" · ")}</div>
                  </TableCell>
                  <TableCell className={phoneCell}>{titleOf(EVENT_KINDS, event.kind)}</TableCell>
                  <TableCell className={cn(phoneCell, "whitespace-nowrap")}>{dateRange(event) || "—"}</TableCell>
                  <TableCell>
                    <Badge className={toneClass(stateColor[stateOf(event)])}>{stateLabel[stateOf(event)] || "—"}</Badge>
                  </TableCell>
                </TableRow>
              ))}
              {!events.length && !loading ? (
                <TableRow>
                  <TableCell colSpan={4} className="py-6 text-center text-muted-foreground">
                    No events yet. An event is one run of this league that players sign up for.
                  </TableCell>
                </TableRow>
              ) : null}
            </TableBody>
          </Table>
        </div>
      </Card>
    </>
  );
}

export default LeagueView;
