// src/views/SeasonDetailsView.vue
<template>
  <v-overlay v-model="isLoading" persistent class="align-center justify-center">
    <v-progress-circular
          indeterminate
          size="64" 
          width="8"
          color="primary"
    ></v-progress-circular>
  </v-overlay>

  <!-- Enhanced Hero Section -->
  <div id="seasonHeader">
    <v-parallax class="banner-image" :src="bannerImg" height="250">
      <div class="banner-overlay"></div>
      <v-container class="fill-height">
        <v-row align="center" justify="center">
          <v-col cols="12" md="8" class="text-center">
            <h1 class="text-h5 text-md-h2 font-weight-bold mb-4 season-title">{{ season.name }}</h1>
            <v-row class="justify-center mt-6 d-none d-sm-flex">
              <v-col cols="auto">
                <v-card class="stat-card" elevation="8">
                  <v-card-text class="pa-4">
                    <div class="text-h4 font-weight-bold primary--text">{{ season.number_weeks }}</div>
                    <div class="text-subtitle-2 text-uppercase">Rounds</div>
                  </v-card-text>
                </v-card>
              </v-col>
              <v-col cols="auto">
                <v-card class="stat-card" elevation="8">
                  <v-card-text class="pa-4">
                    <div class="text-h4 font-weight-bold primary--text">{{ teams.length }}</div>
                    <div class="text-subtitle-2 text-uppercase">Teams</div>
                  </v-card-text>
                </v-card>
              </v-col>
            </v-row>
          </v-col>
        </v-row>
      </v-container>
    </v-parallax>
  </div>

  <v-container fluid class="pa-4">
    <!-- Series with no result, reached from the unscored count on the Seasons page -->
    <v-card v-if="unscoredOnly" class="mb-4" elevation="2">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-clipboard-alert</v-icon>
        Series
        <v-chip class="ml-3" size="small" color="white" variant="outlined" closable @click:close="unscoredOnly = false">No result</v-chip>
      </v-card-title>
      <v-card-text class="pa-0">
        <GroupedTable :columns="unscoredColumns" :groups="unscoredGroups" default-open empty="Every series of this season has a result">
          <template #group="{ group }">
            <td :colspan="unscoredColumns.length">
              <strong>Round {{ group.key }}</strong>
              <span class="text-medium-emphasis ml-2">{{ group.rows.length }} with no result</span>
            </td>
          </template>
          <template #rows="{ group }">
            <tr v-for="row in group.rows" :key="row.id" class="detail-row unscored-row" @click="router.push(`/match/${row.match_id}`)">
              <td></td>
              <td class="text-no-wrap">{{ row.match?.team1?.name }} vs {{ row.match?.team2?.name }}</td>
              <td><PlayerName :player="row.player1" /></td>
              <td><PlayerName :player="row.player2" /></td>
              <td class="text-no-wrap">{{ row.date_time ? formatDateTime(row.date_time) : 'Not scheduled' }}</td>
              <td><CastChips :series="row" /></td>
            </tr>
          </template>
        </GroupedTable>
      </v-card-text>
    </v-card>

    <!-- Round navigation tabs -->
    <v-card class="mb-4" elevation="2">
      <v-tabs
        v-model="selectedWeek"
        bg-color="primary"
        slider-color="white"
        show-arrows
        @update:modelValue="fetchMatches"
      >
        <v-tab
          v-for="week in season.number_weeks"
          :key="week"
          :value="week"
        >
          <v-icon start>mdi-calendar-week</v-icon>
          Round {{ week }}
        </v-tab>
      </v-tabs>
    </v-card>

    <!-- Action Bar -->
    <v-card class="mb-4" elevation="1">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-trophy</v-icon>
        Round {{ selectedWeek }} Matches
      </v-card-title>
      <v-card-text class="pa-0">
        <v-toolbar flat height="auto">
          <v-row align="center" class="flex-wrap ma-0 pa-2">
            <v-spacer />
            <v-col cols="12" sm="auto">
              <v-btn
                v-if="auth.isAdmin"
                :to="`/seasons/${route.params.id}/maps`"
                color="primary"
                prepend-icon="mdi-map-outline"
                variant="outlined"
                block
              >
                Series Maps
              </v-btn>
            </v-col>
            <v-col cols="12" sm="auto">
              <v-btn
                v-if="auth.isAdmin"
                :to="`/seasons/${route.params.id}/achievements`"
                color="primary"
                prepend-icon="mdi-trophy-variant-outline"
                variant="outlined"
                block
              >
                Achievements
              </v-btn>
            </v-col>
            <v-col cols="12" sm="auto">
              <v-btn
                v-if="auth.isAdmin"
                @click="openMatchCreationModal"
                color="primary"
                prepend-icon="mdi-plus"
                variant="elevated"
                block
              >
                Add Match
              </v-btn>
            </v-col>
          </v-row>
        </v-toolbar>
      </v-card-text>
    </v-card>

    <!-- Matches for the selected round -->
    <v-row v-if="matches && matches.length > 0">
      <v-col
        v-for="(match, index) in matches"
        :key="index"
        cols="12"
        lg="6"
      >
        <v-card 
          class="match-card-enhanced" 
          elevation="2"
          hover
          @click="$router.push(`/match/${match.id}`)"
        >
          <v-card-text class="pa-4">
            <v-row align="center" class="match-row">
              <!-- Team 1 -->
              <v-col cols="5" class="text-center">
                <div class="team-section">
                  <v-avatar size="80" class="mb-3 team-avatar">
                    <img class="team-icon" :src="teamImageUrl(match.team1)" @error="showDefaultTeamImage">
                  </v-avatar>
                  <div class="team-name-enhanced">{{ match.team1.name }}</div>
                  <v-chip 
                    :color="getScoreColor(match.team1_score, match.team2_score)" 
                    size="large" 
                    class="mt-2 score-chip"
                  >
                    {{ match.team1_score }}
                  </v-chip>
                </div>
              </v-col>

              <!-- VS Divider -->
              <v-col cols="2" class="text-center">
                <div class="vs-section">
                  <v-icon size="40" color="primary">mdi-sword-cross</v-icon>
                  <div class="text-caption mt-2 text-grey">{{ roundLabel(roundOf(match.playday)) }}</div>
                </div>
              </v-col>

              <!-- Team 2 -->
              <v-col cols="5" class="text-center">
                <div class="team-section">
                  <v-avatar size="80" class="mb-3 team-avatar">
                    <img class="team-icon" :src="teamImageUrl(match.team2)" @error="showDefaultTeamImage">
                  </v-avatar>
                  <div class="team-name-enhanced">{{ match.team2.name }}</div>
                  <v-chip 
                    :color="getScoreColor(match.team2_score, match.team1_score)" 
                    size="large" 
                    class="mt-2 score-chip"
                  >
                    {{ match.team2_score }}
                  </v-chip>
                </div>
              </v-col>
            </v-row>

            <!-- Match Info Footer -->
            <v-divider class="my-3"></v-divider>
            <v-row align="center" dense>
              <v-col>
                <v-chip size="small" prepend-icon="mdi-map" variant="text" v-if="match.fixed_map">
                  {{ getMapName(match.fixed_map_id) }}
                </v-chip>
              </v-col>
              <v-col cols="auto">
                <RowActions :actions="[
                  { icon: 'mdi-pencil', label: 'Edit Match', onClick: () => editMatch(match) },
                  { icon: 'mdi-delete', label: 'Delete Match', color: 'error', onClick: () => openDeleteDialog(match.id, removeMatch) },
                ]" />
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Empty State -->
    <v-card v-else elevation="0" class="text-center pa-8">
      <v-icon size="64" color="grey-lighten-1">mdi-calendar-blank</v-icon>
      <div class="text-h6 mt-4 text-grey">No matches scheduled for Round {{ selectedWeek }}</div>
      <v-btn 
        color="primary" 
        variant="tonal" 
        class="mt-4"
        prepend-icon="mdi-plus"
        v-if="auth.isAdmin"
        @click="openMatchCreationModal"
      >
        Schedule First Match
      </v-btn>
    </v-card>

    <!-- Teams Expansion Panel -->
    <v-expansion-panels class="mt-6" v-model="teamsPanel">
      <v-expansion-panel>
        <v-expansion-panel-title class="text-h6">
          <v-icon class="mr-2">mdi-shield-account</v-icon>
          Season Teams ({{ teams.length }})
          <template v-slot:actions="{ expanded }">
            <v-icon :icon="expanded ? 'mdi-chevron-up' : 'mdi-chevron-down'"></v-icon>
          </template>
        </v-expansion-panel-title>
        <v-expansion-panel-text>
          <!-- Team Management Actions -->
          <v-card-actions v-if="auth.isCaptain" class="pa-3">
            <v-btn
              v-if="auth.isAdmin"
              @click="openTeamSelectionModal"
              variant="tonal"
              color="primary"
              prepend-icon="mdi-plus">
              Add Teams
            </v-btn>
            <v-btn
              @click="router.push(`/seasons/${route.params.id}/assign`)"
              variant="tonal"
              color="secondary"
              prepend-icon="mdi-account-multiple-plus">
              Assign Signups
            </v-btn>
          </v-card-actions>

          <!-- Teams Grid -->
          <v-row v-if="teams && teams.length > 0" class="mt-2">
            <v-col v-for="(team, index) in teams" :key="index" cols="12" sm="6" md="4" lg="3">
              <v-card 
                class="team-card-enhanced" 
                elevation="2"
                hover
                @click="$router.push(`/team/${team.id}/season/${route.params.id}`)"
              >
                <v-card-text class="text-center pa-4">
                  <v-avatar size="64" class="mb-3">
                    <img class="team-icon" :src="teamImageUrl(team)" @error="showDefaultTeamImage">
                  </v-avatar>
                  <div class="text-h6 mb-2">{{ team.name }}</div>
                  <v-divider class="my-2"></v-divider>
                  <v-row dense class="text-caption">
                    <v-col cols="12">
                      <v-chip size="small" color="success" variant="flat" class="mb-1">
                        <v-icon start size="small">mdi-trophy</v-icon>
                        {{ team.seasons_info[0].final_score }} pts
                      </v-chip>
                    </v-col>
                    <v-col cols="6" class="text-left">
                      <div class="text-grey">Against:</div>
                      <div class="font-weight-bold">{{ team.seasons_info[0].points_against }}</div>
                    </v-col>
                    <v-col cols="6" class="text-right">
                      <div class="text-grey">Available:</div>
                      <div class="font-weight-bold">{{ team.seasons_info[0].points_available }}</div>
                    </v-col>
                  </v-row>
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
          <v-alert v-else type="info" variant="tonal" class="mt-2">
            No teams have been added to this season yet.
          </v-alert>
        </v-expansion-panel-text>
      </v-expansion-panel>
    </v-expansion-panels>
  </v-container>

  <!-- Team Selection Dialog -->
  <v-dialog v-model="isTeamDialogOpen" max-width="700px">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-shield-plus</v-icon>
        Add Teams to Season
      </v-card-title>
      <v-card-text class="pa-0">
        <v-data-table v-if="availableTeams"
            :headers="addTeamsTableHeader"
            :items="availableTeams"
            select-strategy="all"
            density="compact"
            item-value="id"
            v-model="selectedTeams"
            multi-sort
            fixed-header
            hover
            show-select
          ></v-data-table>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn variant="text" @click="closeTeamSelectionModal">Cancel</v-btn>
        <v-btn v-if="auth.isAdmin" color="primary" @click="addTeamsToSeason" :disabled="!selectedTeams || selectedTeams.length === 0">
          Add {{ selectedTeams?.length || 0 }} Team(s)
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <!-- Create Match Dialog -->
  <v-dialog v-if="newMatch" v-model="isModalOpen" max-width="600px">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-calendar-plus</v-icon>
        Create Match - Round {{ selectedWeek }}
      </v-card-title>
      <v-card-text class="pt-4">
        <v-row>
          <v-col cols="12">
            <v-select
              :items="maps"
              item-title="name"
              item-value="id"
              label="Fixed Map (Optional)"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-map"
              clearable
              v-model="newMatch.fixed_map_id"
            ></v-select>
          </v-col>
          <v-col cols="12" md="6">
            <v-select
              :items="teams"
              item-title="name"
              item-value="id"
              label="Team 1"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-shield"
              v-model="newMatch.team1_id"
            ></v-select>
          </v-col>
          <v-col cols="12" md="6">
            <v-select
              :items="teams"
              item-title="name"
              item-value="id"
              label="Team 2"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-shield"
              v-model="newMatch.team2_id"
            ></v-select>
          </v-col>
        </v-row>      
      </v-card-text>   
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn variant="text" @click="closeMatchCreationModal">Cancel</v-btn>
        <v-btn v-if="auth.isAdmin" color="primary" @click="confirmSelection">Create Match</v-btn>
      </v-card-actions>        
    </v-card>
  </v-dialog>

  <!-- Edit Match Dialog -->
  <v-dialog
    v-if="selectedMatch"
    v-model="editMatchDialogOpen"
    max-width="600px">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-pencil</v-icon>
        Edit Match
      </v-card-title>
      <v-card-text class="pt-4">
        <v-row>
          <v-col cols="12">
            <v-select
              :items="maps"
              item-title="name"
              item-value="id"
              label="Fixed Map (Optional)"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-map"
              clearable
              v-model="selectedMatch.fixed_map_id"
            ></v-select>
          </v-col>
          <v-col cols="12" md="6">
            <v-select
              :items="teams"
              item-title="name"
              item-value="id"
              label="Team 1"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-shield"
              v-model="selectedMatch.team1_id"
            ></v-select>
          </v-col>
          <v-col cols="12" md="6">
            <v-select
              :items="teams"
              item-title="name"
              item-value="id"
              label="Team 2"
              variant="outlined"
              density="comfortable"
              prepend-inner-icon="mdi-shield"
              v-model="selectedMatch.team2_id"
            ></v-select>
          </v-col>
        </v-row>      
      </v-card-text>       
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn variant="text" @click="cancelEdit">Cancel</v-btn>
        <v-btn v-if="auth.isAdmin" color="primary" @click="updateMatch">Save Changes</v-btn>
      </v-card-actions>        
    </v-card>
  </v-dialog>
  <ConfirmDeleteDialog
    v-model="showDeleteDialog"
    message="Are you sure you want to delete this item? This action cannot be undone."
    @confirm="confirmDelete"
    @cancel="cancelDeleteDialog"
  />
  <!-- Success/Error Snackbar -->
  <v-snackbar
    v-model="showFeedback"
    :color="feedbackType"
    :timeout="5000"
    location="top"
  >
    <div class="d-flex align-center">
      <v-icon class="mr-2">{{ feedbackType === 'success' ? 'mdi-check-circle' : 'mdi-alert-circle' }}</v-icon>
      {{ feedbackMessage }}
    </div>
    <template v-slot:actions>
      <v-btn variant="text" @click="showFeedback = false">Close</v-btn>
    </template>
  </v-snackbar>
</template>
  
  <script setup>
import RowActions from '@/components/RowActions.vue';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';
import GroupedTable from '@/components/GroupedTable.vue';
import PlayerName from '@/components/PlayerName.vue';
import CastChips from '@/components/CastChips.vue';
import { useRouter, useRoute } from 'vue-router';
import { ref, onMounted, computed, watch } from 'vue';
import { useAuthStore, useSeasonStore, useMatchStore, useTeamStore, useMapStore, useSeriesStore } from '@/stores';
import { storeToRefs } from 'pinia';
import bannerImg from '@/assets/media/GNL_Banner.png';
  import { teamImageUrl, showDefaultTeamImage } from '@/helpers/team-image';
import { useDeleteDialog } from '@/helpers/delete-dialog';
import { isUnscored } from '@/helpers/season-phase.mjs';
import { roundLabel } from '@/helpers/rounds.mjs';
import { formatDateTime } from '@/helpers/datetime';


// Store initialization
const router = useRouter();
const route = useRoute();
const seasonStore = useSeasonStore();
const matchStore = useMatchStore();
const teamStore = useTeamStore();
const mapStore = useMapStore();
const auth = useAuthStore();

// Store refs
const { current_season: season } = storeToRefs(seasonStore);
const { matches } = storeToRefs(matchStore);
const { teams } = storeToRefs(teamStore);
const { maps } = storeToRefs(mapStore);

// Route params
const seasonId = seasonStore.seasonIdOf(route.params.id);
// The round of a week gives the match card its dates
const roundOf = (playday) => season.value?.rounds?.find(r => r.playday === playday) || { playday };

// Series with no result: on from ?unscored=1, held here because the week hash push drops the query
const seriesStore = useSeriesStore();
const unscoredOnly = ref(route.query.unscored === '1');
const unscoredSeries = ref([]);
const unscoredColumns = [
  { key: 'match', title: 'Match' },
  { key: 'player1', title: 'Player 1' },
  { key: 'player2', title: 'Player 2' },
  { key: 'date_time', title: 'Scheduled' },
  { key: 'cast', title: 'Cast' },
];
const unscoredGroups = computed(() => {
  const weeks = new Map();
  for (const series of unscoredSeries.value) {
    const week = series.match?.playday ?? 0;
    if (!weeks.has(week)) weeks.set(week, { key: week, rows: [] });
    weeks.get(week).rows.push(series);
  }
  return [...weeks.values()].sort((a, b) => a.key - b.key);
});

const fetchUnscoredSeries = async () => {
  try {
    const all = await seriesStore.searchSeriesBySeason(seasonId, null);
    unscoredSeries.value = (all || []).filter(isUnscored);
  } catch (error) {
    console.error('Failed to fetch the series of the season:', error);
  }
};

// Table configuration
const addTeamsTableHeader = [
  { title: 'ID', value: 'id', sortable: true },
  { title: 'Name', value: 'name', sortable: true },
  { title: 'Long Name', value: 'long_name', sortable: true },
];
    // Component state
const isLoading = ref(true);
const isInitLoading = ref(false);

// Week selection state
const selectedWeek = ref(null);

// Modal state
const isModalOpen = ref(false);
const isTeamDialogOpen = ref(false);
const editMatchDialogOpen = ref(false);

// Match state
const selectedMatch = ref(null);
const newMatch = ref(null);

// Team state
const allTeams = ref(null);
const selectedTeams = ref(null);
const selectedTeam1 = ref(null);
const selectedTeam2 = ref(null);

// Delete dialog state
const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

// Feedback snackbar state
const showFeedback = ref(false);
const feedbackMessage = ref('');
const feedbackType = ref('success'); // 'success' or 'error'

// UI state
const teamsPanel = ref(null);

// Compute teams that are not part of the season
const availableTeams = computed(() => {
  if (!allTeams.value || allTeams.value.length == 0) {
    return [];
  }
  return allTeams.value.filter(team => !teamStore.teams.some(seasonTeam => seasonTeam.id === team.id));
});

// Helper to get score color
const getScoreColor = (score, opponentScore) => {
  if (score > opponentScore) return 'success';
  if (score < opponentScore) return 'error';
  return 'grey';
};

// Helper to get map name
const getMapName = (mapId) => {
  const map = maps.value.find(m => m.id === mapId);
  return map?.name || 'Random';
};

// Team selection methods
const openTeamSelectionModal = async () => {
  // Load basic team info only when the modal is opened
  if (!allTeams.value) {
    allTeams.value = await teamStore.getTeamsBasic();
  }
  isTeamDialogOpen.value = true;
  selectedTeams.value = [];
};

const closeTeamSelectionModal = () => {
  isTeamDialogOpen.value = false;
  selectedTeams.value = null;
};

    const openMatchCreationModal = () => {
      newMatch.value = {
        fixed_map_id:null,
        team1_id:null,
        team2_id:null,
        season_id:seasonId,
        playday: selectedWeek.value
      }
      isModalOpen.value = true;
    };

    const closeMatchCreationModal = () => {
      isModalOpen.value = false;
      selectedTeam1.value = null;
      selectedTeam2.value = null;
    };

    const addTeamsToSeason = async () => {
      isLoading.value = true;
      try{
        await seasonStore.addTeamsToSeason(seasonId, selectedTeams.value);
        await fetchTeams();
      } catch (error) {
        console.error("Failed to add teams to season:", error);
      } finally {
        isLoading.value = false;
        closeTeamSelectionModal();
      }
    };

    const editMatch = (match) => {
      selectedMatch.value = { ...match }; // Clone the user object to avoid modifying the original object directly
      editMatchDialogOpen.value = true;
    };

    const updateMatch = async () => {
      try {
        await matchStore.updateMatch(selectedMatch.value);
        // Update the local state after a successful PUT request
        await fetchMatches(selectedWeek.value);
        cancelEdit(); // Reset the form
      } catch (error) {
        console.error('Error updating match:', error);
      }
    };

    const removeMatch = async (matchId) => {
      try {
        await matchStore.deleteMatch(matchId);
        await fetchMatches(selectedWeek.value); // Refresh the list after deletion
      } catch (error) {
        console.error('Error deleting match:', error);
      }
    };

    const cancelEdit = () => {
      editMatchDialogOpen.value = false;
      selectedMatch.value = null; // Clear the selected user
    };

    
    const confirmSelection = async () => {
      isLoading.value = true;
      try {
        await matchStore.createMatch(newMatch.value); // Assuming a createMatch method exists
        await fetchMatches(selectedWeek.value); // Refresh matches for the week
        closeMatchCreationModal();
      } catch (error) {
        console.error("Failed to add match:", error);
      } finally {
        isLoading.value = false;
      }
    };

    const fetchMatches = async (week) => {
  selectedWeek.value = week;
  isLoading.value = true;
  router.push({ hash: `#round-${week}` });
  try {
    await matchStore.searchMatchesBySeasonAndPlayday(seasonId, week);
  } catch (error) {
    console.error(`Failed to fetch matches for week ${week}:`, error);
  } finally {
    if (!isInitLoading.value) {
      isLoading.value = false;
    }
  }
};

    const fetchMaps = async () => {
      try {
        await mapStore.fetchMaps();
      } catch (error) {
        console.error('Failed to fetch maps:', error);
      }
    };

    // Fetch teams for the season
    const fetchTeams = async () => {
  isLoading.value = true;
  try {
    await teamStore.fetchTeamsBySeasonBasic(seasonId);
  } catch (error) {
    console.error('Failed to fetch teams for the season:', error);
  } finally {
    if (!isInitLoading.value) {
      isLoading.value = false;
    }
  }
};

    const fetchSeasonDetails = async () => {
  isLoading.value = true;
  try {
    await seasonStore.fetchSeason(seasonId);
  } catch (error) {
    console.error('Failed to fetch season details:', error);
  } finally {
    if (!isInitLoading.value) {
      isLoading.value = false;
    }
  }
};

    watch(() => route.hash, (newHash) => {
      if (newHash) {
        const roundFromHash = route.hash && route.hash.includes('#round-') 
            ? parseInt(route.hash.replace('#round-', ''), 10) 
            : 1;
          if(selectedWeek.value && roundFromHash!=selectedWeek.value){
            selectedWeek.value = roundFromHash;
            fetchMatches(roundFromHash);
          }
      }
    });

  
    // Lifecycle hooks
onMounted(async () => {
  isInitLoading.value = true;
  isLoading.value = true;
  try {
    const roundFromHash = route.hash && route.hash.includes('#round-') 
      ? parseInt(route.hash.replace('#round-', ''), 10) 
      : 1;

    // Set the selected week before fetching
    selectedWeek.value = roundFromHash;

    await Promise.all([
      fetchSeasonDetails(),
      fetchTeams(),
      fetchMatches(roundFromHash),
      fetchMaps(),
      unscoredOnly.value && fetchUnscoredSeries()
    ]);
  } finally {
    isLoading.value = false;
    isInitLoading.value = false;
  }
});

  </script>

  <style scoped>

  .unscored-row {
    cursor: pointer;
  }

  .team-icon {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  /* Header Styles */
  #seasonHeader {
    position: relative;
    color: white;
  }
  
  .banner-image {
    position: relative;
  }
  
  .banner-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: linear-gradient(to bottom, rgba(0,0,0,0.3), rgba(0,0,0,0.6));
    z-index: 1;
  }

  .season-title {
    text-shadow: 2px 2px 8px rgba(0, 0, 0, 0.8);
    letter-spacing: 1px;
  }

  /* Stat Cards */
  .stat-card {
    background: rgba(var(--v-theme-surface), 0.95) !important;
    backdrop-filter: blur(10px);
    transition: transform 0.2s, box-shadow 0.2s;
  }

  .stat-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15) !important;
  }

  /* Match Cards */
  .match-card-enhanced {
    transition: all 0.3s ease;
    cursor: pointer;
    border: 2px solid transparent;
  }

  .match-card-enhanced:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15) !important;
    border-color: rgb(var(--v-theme-primary));
  }

  .match-row {
    min-height: 200px;
  }

  .team-section {
    transition: transform 0.2s;
  }

  .match-card-enhanced:hover .team-section {
    transform: scale(1.05);
  }

  .team-avatar {
    border: 3px solid rgba(var(--v-theme-primary), 0.2);
    transition: border-color 0.2s;
  }

  .match-card-enhanced:hover .team-avatar {
    border-color: rgb(var(--v-theme-primary));
  }

  .team-name-enhanced {
    font-size: 1.1rem;
    font-weight: 600;
    color: rgb(var(--v-theme-on-surface));
  }

  .score-chip {
    font-size: 1.5rem !important;
    font-weight: bold;
    min-width: 60px;
  }

  .vs-section {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  /* Team Cards in Expansion Panel */
  .team-card-enhanced {
    transition: all 0.3s ease;
    cursor: pointer;
    border: 2px solid transparent;
  }

  .team-card-enhanced:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15) !important;
    border-color: rgb(var(--v-theme-primary));
  }

  /* Loading Overlay */
  .loading-overlay {
    z-index: 9999;
  }

  /* Responsive adjustments */
  /* On a phone the hero is a title alone, so it does not need 250px */
  @media (max-width: 599px) {
    .banner-image {
      height: 120px !important;
    }
  }

  @media (max-width: 960px) {
    .season-title {
      font-size: 2rem !important;
    }

    .stat-card .text-h4 {
      font-size: 1.5rem !important;
    }

    .match-row {
      min-height: auto;
    }

    .team-avatar {
      width: 60px !important;
      height: 60px !important;
    }

    .score-chip {
      font-size: 1.2rem !important;
    }
  }
  </style>

// next/src/app/(app)/seasons/[id]/SeasonDetailsView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { DataTable } from "@/components/ui/DataTable";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Icon } from "@/components/ui/Icon";
import { Pick } from "@/components/ui/Pick";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toneClass } from "@/components/ui/tone";
import { CastChips, type CastSeries } from "@/components/CastChips";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { EventHeader } from "@/components/EventHeader";
import { GroupedTable } from "@/components/GroupedTable";
import { PlayerName } from "@/components/PlayerName";
import { RowActions } from "@/components/RowActions";
import { StatusAlert } from "@/components/StatusAlert";
import { useDeleteDialog } from "@/hooks/delete-dialog";
import { formatDateTime } from "@/helpers/datetime";
import { fixedMapOf, rulesOf } from "@/helpers/map-order.mjs";
import { matchProblem } from "@/helpers/match.mjs";
import { currentRound, roundLabel } from "@/helpers/rounds.mjs";
import { isUnscored } from "@/helpers/season-phase.mjs";
import { showDefaultTeamImage, teamImageUrl } from "@/helpers/team-image";
import { useAuth, useMapStore, useMatchStore, useSeason, useSeriesStore, useTeamStore } from "@/stores";

type Row = Record<string, any>;

const UNSCORED_COLUMNS = [
  { key: "match", title: "Match" },
  { key: "player1", title: "Player 1" },
  { key: "player2", title: "Player 2" },
  { key: "date_time", title: "Scheduled" },
  { key: "cast", title: "Cast" },
];

// The round of a week gives the match card its dates
const roundOf = (season: Row, playday: number) => season?.rounds?.find((r: Row) => r.playday === playday) || { playday };

const scoreClass = (score: number, opponentScore: number) =>
  score > opponentScore ? "bg-win text-on-win" : score < opponentScore ? "bg-loss text-on-loss" : "bg-draw text-on-draw";

// A match with a score is done, so a missing round map is no longer worth warning about
const matchPlayed = (match: Row) => !!(match?.team1_score || match?.team2_score);

// The hash names the open round, so a reload and the back button land on the same one
const roundFromHash = () => {
  const hash = typeof window === "undefined" ? "" : window.location.hash;
  return hash.includes("#round-") ? parseInt(hash.replace("#round-", ""), 10) : null;
};

export function SeasonDetailsView({ id }: { id: string }) {
  const auth = useAuth();
  const { current_season: season, seasonIdOf, fetchSeason, addTeamsToSeason } = useSeason();
  const matchStore = useMatchStore();
  const teamStore = useTeamStore();
  const mapStore = useMapStore();
  const seriesStore = useSeriesStore();

  const seasonId = seasonIdOf(id);

  const [isLoading, setIsLoading] = useState(true);
  const [matches, setMatches] = useState<Row[]>([]);
  const [teams, setTeams] = useState<Row[]>([]);
  const [maps, setMaps] = useState<Row[]>([]);
  const [selectedWeek, setSelectedWeek] = useState<number | null>(null);

  // Series with no result: on from ?unscored=1, held here because the week hash push drops the query
  const [unscoredOnly, setUnscoredOnly] = useState(useSearchParams().get("unscored") === "1");
  const [unscoredSeries, setUnscoredSeries] = useState<Row[]>([]);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isTeamDialogOpen, setIsTeamDialogOpen] = useState(false);
  const [editMatchDialogOpen, setEditMatchDialogOpen] = useState(false);

  const [selectedMatch, setSelectedMatch] = useState<Row | null>(null);
  const [newMatch, setNewMatch] = useState<Row | null>(null);
  const [matchError, setMatchError] = useState<string | null>(null);

  const [allTeams, setAllTeams] = useState<Row[] | null>(null);
  const [selectedTeams, setSelectedTeams] = useState<number[]>([]);

  const { showDeleteDialog, openDeleteDialog, confirmDelete, cancelDeleteDialog } = useDeleteDialog();

  // Compute teams that are not part of the season
  const availableTeams = (allTeams ?? []).filter((team) => !teams.some((seasonTeam) => seasonTeam.id === team.id));

  // The fixed map of a round: season_rounds.map_id, the column the veto and the game offers read
  const usesFixedMap = rulesOf(season?.map_rules).includes("fixed");
  const roundMapId = (playday: number) => fixedMapOf(season?.map_rules, roundOf(season, playday));
  const getMapName = (mapId: number | null) => maps.find((m) => m.id === mapId)?.name || "Random";

  const unscoredGroups = (() => {
    const weeks = new Map<number, { key: number; label: string; rows: Row[] }>();
    for (const series of unscoredSeries) {
      const week = series.match?.playday ?? 0;
      if (!weeks.has(week)) weeks.set(week, { key: week, label: `Round ${week}`, rows: [] });
      weeks.get(week)!.rows.push(series);
    }
    return [...weeks.values()].sort((a, b) => a.key - b.key);
  })();

  const fetchMatches = async (week: number) => {
    setSelectedWeek(week);
    setIsLoading(true);
    window.location.hash = `#round-${week}`;
    try {
      setMatches((await matchStore.searchMatchesBySeasonAndPlayday(seasonId as number, week)) || []);
    } catch (error) {
      console.error(`Failed to fetch matches for week ${week}:`, error);
    } finally {
      setIsLoading(false);
    }
  };

  const fetchTeams = async () => {
    try {
      setTeams((await teamStore.fetchTeamsBySeasonBasic(seasonId as number)) || []);
    } catch (error) {
      console.error("Failed to fetch teams for the season:", error);
    }
  };

  useEffect(() => {
    if (!seasonId) return;
    // the loaders set state, so they run just outside the effect body (react-hooks/set-state-in-effect)
    queueMicrotask(async () => {
      setIsLoading(true);
      try {
        const hashRound = roundFromHash();
        // The rounds decide which tab opens, so the season is read before the matches
        const current = await fetchSeason(seasonId).catch((error) => {
          console.error("Failed to fetch season details:", error);
          return null;
        });
        const round = hashRound ?? currentRound(current?.rounds)?.playday ?? 1;
        await Promise.all([
          fetchTeams(),
          fetchMatches(round),
          mapStore
            .fetchMaps()
            .then((rows: Row[]) => setMaps(rows || []))
            .catch((error: Error) => console.error("Failed to fetch maps:", error)),
        ]);
      } finally {
        setIsLoading(false);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId]);

  useEffect(() => {
    if (!seasonId || !unscoredOnly) return;
    queueMicrotask(async () => {
      try {
        const all = await seriesStore.searchSeriesBySeason(seasonId);
        setUnscoredSeries((all || []).filter(isUnscored));
      } catch (error) {
        console.error("Failed to fetch the series of the season:", error);
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId, unscoredOnly]);

  // The back button moves the open round, as the tab click does
  useEffect(() => {
    const onHashChange = () => {
      const round = roundFromHash() ?? 1;
      if (selectedWeek && round !== selectedWeek) fetchMatches(round);
    };
    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedWeek]);

  const openTeamSelectionModal = async () => {
    // Load basic team info only when the modal is opened
    if (!allTeams) setAllTeams((await teamStore.getTeamsBasic()) || []);
    setSelectedTeams([]);
    setIsTeamDialogOpen(true);
  };

  const closeTeamSelectionModal = () => {
    setIsTeamDialogOpen(false);
    setSelectedTeams([]);
  };

  const addTeams = async () => {
    setIsLoading(true);
    try {
      await addTeamsToSeason(seasonId as number, selectedTeams);
      await fetchTeams();
    } catch (error) {
      console.error("Failed to add teams to season:", error);
    } finally {
      setIsLoading(false);
      closeTeamSelectionModal();
    }
  };

  const openMatchCreationModal = () => {
    setNewMatch({ team1_id: null, team2_id: null, season_id: seasonId, playday: selectedWeek });
    setMatchError(null);
    setIsModalOpen(true);
  };

  const closeMatchCreationModal = () => {
    setIsModalOpen(false);
    setMatchError(null);
  };

  const confirmSelection = async () => {
    const problem = matchProblem(newMatch);
    setMatchError(problem);
    if (problem) return;
    setIsLoading(true);
    try {
      await matchStore.createMatch(newMatch);
      await fetchMatches(selectedWeek as number);
      closeMatchCreationModal();
    } catch (error) {
      console.error("Failed to add match:", error);
      setMatchError((error as Error).message || "Failed to add the match.");
    } finally {
      setIsLoading(false);
    }
  };

  const editMatch = (match: Row) => {
    setSelectedMatch({ ...match });
    setMatchError(null);
    setEditMatchDialogOpen(true);
  };

  const cancelEdit = () => {
    setEditMatchDialogOpen(false);
    setMatchError(null);
    setSelectedMatch(null);
  };

  const updateMatch = async () => {
    const problem = matchProblem(selectedMatch);
    setMatchError(problem);
    if (problem) return;
    try {
      await matchStore.updateMatch(selectedMatch);
      await fetchMatches(selectedWeek as number);
      cancelEdit();
    } catch (error) {
      console.error("Error updating match:", error);
      setMatchError((error as Error).message || "Failed to save the match.");
    }
  };

  const removeMatch = async (matchId?: number | string) => {
    try {
      await matchStore.deleteMatch(Number(matchId));
      await fetchMatches(selectedWeek as number);
    } catch (error) {
      console.error("Error deleting match:", error);
    }
  };

  const teamItems = teams.map((team) => ({ value: team.id as number, title: team.name as string }));
  const mapLine = (playday: number | null) =>
    playday == null ? null : (
      <div className="flex flex-wrap items-center gap-2">
        <Icon name="mdi-map" size={18} className={roundMapId(playday) ? undefined : "text-warning"} />
        <span className="text-sm">Fixed map: {roundMapId(playday) ? getMapName(roundMapId(playday)) : "not set for this round"}</span>
        <Button variant="ghost" size="sm" nativeButton={false} render={<Link href={`/seasons/${id}/maps`} />}>
          Set on Series maps
        </Button>
      </div>
    );

  return (
    <div className="p-4">
      {isLoading ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60">
          <Icon name="mdi-loading" size={64} className="animate-spin text-primary" />
        </div>
      ) : null}

      {/* The season is one event of the GNL league, so it wears the shared event header */}
      <EventHeader event={season} />
      <div className="mt-3 mb-4 flex flex-wrap gap-2">
        <Badge className={toneClass()}>
          <Icon name="mdi-calendar-range" />
          {season.round_count} rounds
        </Badge>
        <Badge className={toneClass()}>
          <Icon name="mdi-account-group" />
          {teams.length} teams
        </Badge>
      </div>

      {/* Series with no result, reached from the unscored count on the Seasons page */}
      {unscoredOnly ? (
        <Card className="card mb-4 gap-0 py-0">
          <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-clipboard-alert" />
            Series
            <Badge variant="outline" className="ml-1 border-on-primary text-on-primary">
              No result
              <button type="button" aria-label="Clear the no result filter" onClick={() => setUnscoredOnly(false)}>
                <Icon name="mdi-close" />
              </button>
            </Badge>
          </CardTitle>
          <GroupedTable
            columns={UNSCORED_COLUMNS}
            groups={unscoredGroups}
            defaultOpen
            empty="Every series of this season has a result"
            group={({ group }) => (
              <td colSpan={UNSCORED_COLUMNS.length}>
                <strong>Round {group.key}</strong>
                <span className="ml-2 text-muted-foreground">{group.rows.length} with no result</span>
              </td>
            )}
            rows={({ group }) =>
              group.rows.map((row: Row) => (
                <tr key={row.id} className="detail-row border-b">
                  <td />
                  <td className="whitespace-nowrap">
                    <Link href={`/match/${row.match_id}`} className="text-inherit no-underline hover:underline">
                      {row.match?.team1?.name} vs {row.match?.team2?.name}
                    </Link>
                  </td>
                  <td>
                    <PlayerName player={row.player1} race={row.player1_race} />
                  </td>
                  <td>
                    <PlayerName player={row.player2} race={row.player2_race} />
                  </td>
                  <td className="whitespace-nowrap">{row.date_time ? formatDateTime(row.date_time) : "Not scheduled"}</td>
                  <td>
                    <CastChips series={row as CastSeries} />
                  </td>
                </tr>
              ))
            }
          />
        </Card>
      ) : null}

      {/* Round navigation tabs */}
      <Card className="card mb-4 gap-0 bg-primary py-0 text-on-primary">
        <Tabs value={selectedWeek} onValueChange={(value) => fetchMatches(Number(value))}>
          <TabsList variant="line" className="max-w-full justify-start overflow-x-auto">
            {Array.from({ length: season.round_count || 0 }, (_, i) => i + 1).map((week) => (
              <TabsTrigger key={week} value={week} className="flex-none px-3 text-on-primary">
                <Icon name="mdi-calendar-week" />
                Round {week}
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
      </Card>

      {/* Action Bar */}
      <Card className="card mb-4 gap-0 py-0">
        <CardTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
          <Icon name="mdi-trophy" />
          Round {selectedWeek} matches
        </CardTitle>
        {auth.isAdmin ? (
          <CardContent className="flex flex-wrap justify-end gap-2 p-2">
            <Button variant="outline" nativeButton={false} render={<Link href={`/seasons/${id}/maps`} />}>
              <Icon name="mdi-map-outline" />
              Series maps
            </Button>
            <Button variant="outline" nativeButton={false} render={<Link href={`/seasons/${id}/achievements`} />}>
              <Icon name="mdi-trophy-variant-outline" />
              Achievements
            </Button>
            <Button onClick={openMatchCreationModal}>
              <Icon name="mdi-plus" />
              Add match
            </Button>
          </CardContent>
        ) : null}
      </Card>

      {/* Matches for the selected round */}
      {matches.length ? (
        <div className="grid gap-4 min-[1280px]:grid-cols-2">
          {matches.map((match) => (
            <Card key={match.id} className="card gap-0 py-0 transition-colors hover:border-primary">
              <CardContent className="p-4">
                <div className="flex items-center gap-2">
                  {[
                    { team: match.team1, score: match.team1_score, other: match.team2_score },
                    null,
                    { team: match.team2, score: match.team2_score, other: match.team1_score },
                  ].map((side, i) =>
                    side ? (
                      <div key={i} className="flex-1 text-center">
                        <span className="mx-auto block size-20 overflow-hidden rounded-full border-[3px] border-primary/20 max-[959.98px]:size-15">
                          <img className="size-full object-cover" src={teamImageUrl(side.team)} alt="" onError={showDefaultTeamImage} />
                        </span>
                        <Link href={`/match/${match.id}`} className="mt-3 block font-semibold text-inherit no-underline hover:underline">
                          {side.team.name}
                        </Link>
                        <Badge className={`tnum mt-2 min-w-15 justify-center text-2xl ${scoreClass(side.score, side.other)}`}>{side.score}</Badge>
                      </div>
                    ) : (
                      <div key={i} className="flex flex-col items-center justify-center">
                        <Icon name="mdi-sword-cross" size={40} className="text-primary" />
                        <div className="mt-2 text-xs whitespace-nowrap text-muted-foreground">{roundLabel(roundOf(season, match.playday))}</div>
                      </div>
                    ),
                  )}
                </div>

                <Separator className="my-3" />
                <div className="flex items-center gap-2">
                  <div className="flex-1">
                    {roundMapId(match.playday) ? (
                      <Badge variant="ghost">
                        <Icon name="mdi-map" />
                        {getMapName(roundMapId(match.playday))}
                      </Badge>
                    ) : usesFixedMap && !matchPlayed(match) ? (
                      <Badge variant="ghost" className="text-warning">
                        <Icon name="mdi-map-marker-alert" />
                        Round {match.playday} has no fixed map
                      </Badge>
                    ) : null}
                  </div>
                  <RowActions
                    actions={[
                      { icon: "mdi-pencil", label: "Edit match", onClick: () => editMatch(match) },
                      { icon: "mdi-delete", label: "Delete match", color: "error", onClick: () => openDeleteDialog(match.id, removeMatch) },
                    ]}
                  />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <div className="p-8 text-center">
          <Icon name="mdi-calendar-blank" size={64} className="text-muted-foreground" />
          <div className="mt-4 text-xl text-muted-foreground">No matches scheduled for Round {selectedWeek}</div>
          {auth.isAdmin ? (
            <Button variant="secondary" className="mt-4" onClick={openMatchCreationModal}>
              <Icon name="mdi-plus" />
              Schedule the first match
            </Button>
          ) : null}
        </div>
      )}

      {/* Teams panel */}
      <Accordion className="card mt-6 rounded-lg px-4">
        <AccordionItem value="teams">
          <AccordionTrigger className="text-lg">
            <span className="flex items-center gap-2">
              <Icon name="mdi-shield-account" />
              Season teams ({teams.length})
            </span>
          </AccordionTrigger>
          <AccordionContent>
            {auth.isCaptain ? (
              <div className="flex flex-wrap gap-2 pb-3">
                {auth.isAdmin ? (
                  <Button variant="secondary" onClick={openTeamSelectionModal}>
                    <Icon name="mdi-plus" />
                    Add teams
                  </Button>
                ) : null}
                <Button variant="secondary" nativeButton={false} render={<Link href={`/seasons/${id}/assign`} />}>
                  <Icon name="mdi-account-multiple-plus" />
                  Assign signups
                </Button>
              </div>
            ) : null}

            {teams.length ? (
              <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 min-[1280px]:grid-cols-4">
                {teams.map((team) => (
                  <Card key={team.id} className="card gap-0 py-0 transition-colors hover:border-primary">
                    <Link href={`/team/${team.id}/season/${id}`} className="block p-4 text-center text-inherit no-underline">
                      <span className="mx-auto block size-16 overflow-hidden rounded-full">
                        <img className="size-full object-cover" src={teamImageUrl(team)} alt="" onError={showDefaultTeamImage} />
                      </span>
                      <div className="mt-3 mb-2 text-lg">{team.name}</div>
                      <Separator className="my-2" />
                      <Badge className="mb-1 bg-success text-on-success">
                        <Icon name="mdi-trophy" />
                        {team.seasons_info[0].final_score} pts
                      </Badge>
                      <div className="flex justify-between text-xs">
                        <div className="text-left">
                          <div className="text-muted-foreground">Against:</div>
                          <div className="tnum font-bold">{team.seasons_info[0].points_against}</div>
                        </div>
                        <div className="text-right">
                          <div className="text-muted-foreground">Available:</div>
                          <div className="tnum font-bold">{team.seasons_info[0].points_available}</div>
                        </div>
                      </div>
                    </Link>
                  </Card>
                ))}
              </div>
            ) : (
              <StatusAlert modelValue="No teams have been added to this season yet." type="info" />
            )}
          </AccordionContent>
        </AccordionItem>
      </Accordion>

      {/* Team Selection Dialog */}
      <Dialog open={isTeamDialogOpen} onOpenChange={(open) => (open ? setIsTeamDialogOpen(true) : closeTeamSelectionModal())}>
        <DialogContent showCloseButton={false} className="max-w-[700px] gap-0 p-0 sm:max-w-[700px]">
          <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
            <Icon name="mdi-shield-plus" />
            Add teams to the season
          </DialogTitle>
          <DataTable
            data={availableTeams}
            empty="Every team is already in this season"
            columns={[
              {
                id: "select",
                header: "",
                enableSorting: false,
                cell: ({ row }) => (
                  <Checkbox
                    checked={selectedTeams.includes(row.original.id)}
                    onCheckedChange={(checked) =>
                      setSelectedTeams((was) => (checked ? [...was, row.original.id] : was.filter((teamId) => teamId !== row.original.id)))
                    }
                    aria-label={row.original.name}
                  />
                ),
              },
              { id: "name", accessorKey: "name", header: "Name" },
              { id: "long_name", accessorKey: "long_name", header: "Long Name" },
            ]}
          />
          <div className="flex justify-end gap-2 p-4">
            <Button variant="ghost" onClick={closeTeamSelectionModal}>
              Cancel
            </Button>
            {auth.isAdmin ? (
              <Button onClick={addTeams} disabled={!selectedTeams.length}>
                Add {selectedTeams.length} Team(s)
              </Button>
            ) : null}
          </div>
        </DialogContent>
      </Dialog>

      {/* Create Match Dialog */}
      {newMatch ? (
        <Dialog open={isModalOpen} onOpenChange={(open) => (open ? setIsModalOpen(true) : closeMatchCreationModal())}>
          <DialogContent showCloseButton={false} className="max-w-[600px] gap-0 p-0 sm:max-w-[600px]">
            <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
              <Icon name="mdi-calendar-plus" />
              Create a match in round {selectedWeek}
            </DialogTitle>
            <StatusAlert modelValue={matchError} className="mx-4 mt-4" onClose={() => setMatchError(null)} />
            <div className="flex flex-col gap-4 p-4">
              {usesFixedMap ? mapLine(selectedWeek) : null}
              <div className="grid gap-4 md:grid-cols-2">
                <Pick label="Team 1" items={teamItems} value={newMatch.team1_id} onChange={(value) => setNewMatch({ ...newMatch, team1_id: value })} />
                <Pick label="Team 2" items={teamItems} value={newMatch.team2_id} onChange={(value) => setNewMatch({ ...newMatch, team2_id: value })} />
              </div>
            </div>
            <div className="flex justify-end gap-2 p-4 pt-0">
              <Button variant="ghost" onClick={closeMatchCreationModal}>
                Cancel
              </Button>
              {auth.isAdmin ? <Button onClick={confirmSelection}>Create match</Button> : null}
            </div>
          </DialogContent>
        </Dialog>
      ) : null}

      {/* Edit Match Dialog */}
      {selectedMatch ? (
        <Dialog open={editMatchDialogOpen} onOpenChange={(open) => (open ? setEditMatchDialogOpen(true) : cancelEdit())}>
          <DialogContent showCloseButton={false} className="max-w-[600px] gap-0 p-0 sm:max-w-[600px]">
            <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
              <Icon name="mdi-pencil" />
              Edit match
            </DialogTitle>
            <StatusAlert modelValue={matchError} className="mx-4 mt-4" onClose={() => setMatchError(null)} />
            <div className="flex flex-col gap-4 p-4">
              {usesFixedMap ? mapLine(selectedMatch.playday) : null}
              <div className="grid gap-4 md:grid-cols-2">
                <Pick
                  label="Team 1"
                  items={teamItems}
                  value={selectedMatch.team1_id}
                  onChange={(value) => setSelectedMatch({ ...selectedMatch, team1_id: value })}
                />
                <Pick
                  label="Team 2"
                  items={teamItems}
                  value={selectedMatch.team2_id}
                  onChange={(value) => setSelectedMatch({ ...selectedMatch, team2_id: value })}
                />
              </div>
            </div>
            <div className="flex justify-end gap-2 p-4 pt-0">
              <Button variant="ghost" onClick={cancelEdit}>
                Cancel
              </Button>
              {auth.isAdmin ? <Button onClick={updateMatch}>Save changes</Button> : null}
            </div>
          </DialogContent>
        </Dialog>
      ) : null}

      <ConfirmDeleteDialog
        modelValue={showDeleteDialog}
        message="Are you sure you want to delete this item? This action cannot be undone."
        onUpdateModelValue={(open) => (open ? undefined : cancelDeleteDialog())}
        onConfirm={confirmDelete}
        onCancel={cancelDeleteDialog}
      />
    </div>
  );
}

export default SeasonDetailsView;
