// src/views/TeamView.vue
<!-- One page per team, across every event it played. The tabs name the event and
     its league from the team route, which also carries the scores; the roster, the
     rank and the round results come from that event's team and series routes. -->
<template>
  <v-overlay v-model="isLoading" persistent contained class="align-center justify-center">
    <v-progress-circular indeterminate size="64" width="8" color="primary" />
  </v-overlay>

  <v-container fluid class="pa-4">
    <StatusAlert v-model="errorMessage" />

    <v-card v-if="team" elevation="2" class="mb-4">
      <v-card-title class="bg-primary d-flex align-center ga-3">
        <v-avatar size="40">
          <img class="team-icon" alt="" :src="teamImageUrl(team)" @error="showDefaultTeamImage">
        </v-avatar>
        <div>
          <div>{{ team.long_name || team.name }}</div>
          <div v-if="team.long_name" class="text-caption">{{ team.name }}</div>
        </div>
      </v-card-title>

      <v-tabs v-model="seasonId" bg-color="surface" show-arrows>
        <v-tab v-for="tab in seasonTabs" :key="tab.id" :value="tab.id">
          {{ tab.label }}
          <v-icon v-if="tab.id === currentSeasonId" size="small" class="ml-1" title="Current season">mdi-star</v-icon>
        </v-tab>
      </v-tabs>

      <!-- The event page holds the stages; the season team page holds the roster and
           the captain's Team rounds button -->
      <v-card-text v-if="seasonId" class="pb-0 d-flex flex-wrap ga-2">
        <v-btn size="small" variant="outlined" prepend-icon="mdi-trophy-variant" :to="`/events/${seasonId}`">
          {{ seasonLabel }}
        </v-btn>
        <v-btn v-if="seasonSlug" size="small" variant="outlined" prepend-icon="mdi-shield-account" :to="`/team/${teamId}/season/${seasonSlug}`">
          Season team page
        </v-btn>
      </v-card-text>

      <v-card-text v-if="seasonInfo" class="season-stats">
        <div v-for="stat in stats" :key="stat.label" class="text-right">
          <div class="text-caption text-medium-emphasis">
            <ColumnNote v-if="POINTS_NOTES[stat.label]" :title="stat.label" :note="POINTS_NOTES[stat.label]" />
            <template v-else>{{ stat.label }}</template>
          </div>
          <div class="text-h6 stat-value">{{ stat.value }}</div>
        </div>
      </v-card-text>
    </v-card>

    <v-card v-if="team && rounds.length" elevation="2" class="mb-4">
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-sword-cross</v-icon>
        Rounds
      </v-card-title>
      <v-table density="compact">
        <thead>
          <tr>
            <th class="text-right round-col">Round</th>
            <th>Opponent</th>
            <th class="text-right">Series</th>
            <th class="text-right">Points</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in rounds" :key="row.matchId">
            <td class="text-right stat-value">{{ row.playday }}</td>
            <td>
              <div class="d-flex align-center ga-2">
                <v-avatar size="24" rounded="sm">
                  <img class="team-icon" alt="" :src="teamImageUrl(row.opponent)" @error="showDefaultTeamImage">
                </v-avatar>
                {{ row.opponent?.long_name || row.opponent?.name }}
              </div>
            </td>
            <td class="text-right text-no-wrap stat-value">{{ row.wins }}–{{ row.losses }}<span v-if="row.toPlay" class="text-medium-emphasis"> of {{ row.wins + row.losses + row.toPlay }}</span></td>
            <td class="text-right text-no-wrap stat-value" :class="{ 'font-weight-bold': row.pointsFor > row.pointsAgainst }">{{ row.pointsFor }}–{{ row.pointsAgainst }}</td>
          </tr>
        </tbody>
      </v-table>
    </v-card>

    <TeamRoster v-if="team" :captains="captains" :members="members" />
  </v-container>
</template>

<script setup>
import { computed, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { useSeasonStore, useSeriesStore, useTeamStore } from '@/stores';
import { resolveCurrentSeasonId, loadSeasons } from '@/helpers/current-season';
import { teamImageUrl, showDefaultTeamImage } from '@/helpers/team-image';
import { seasonRank, roundResults, seriesRecord, seasonTabs as tabsOf } from '@/helpers/team-record.mjs';
import { POINTS_NOTES } from '@/helpers/achievements';
import { rosterOf } from '@/helpers/team-roster.mjs';
import ColumnNote from '@/components/ColumnNote.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import TeamRoster from '@/components/TeamRoster.vue';

const route = useRoute();
const teamStore = useTeamStore();
const seasonStore = useSeasonStore();
const seriesStore = useSeriesStore();

const teamId = Number(route.params.id);
const team = ref(null);
const seasonTeam = ref(null);
const standings = ref([]);
const seasonSeries = ref([]);
const seasonId = ref(null);
const currentSeasonId = ref(null);
const isLoading = ref(true);
const errorMessage = ref(null);

// One tab per event the team played, named by the team route or by the season list
const seasonTabs = computed(() => tabsOf(team.value?.seasons_info || [], seasonStore.seasons || []));

const seasonInfo = computed(() =>
  (team.value?.seasons_info || []).find((info) => info.season_id === seasonId.value) || null
);
const seasonLabel = computed(() => seasonTabs.value.find((tab) => tab.id === seasonId.value)?.label || '');
// The roster of the tab comes from the per-event read, captains and members alike
const captains = computed(() => rosterOf(seasonTeam.value, seasonId.value).captains);
const members = computed(() => rosterOf(seasonTeam.value, seasonId.value).members);

const rank = computed(() => seasonRank(standings.value, teamId, seasonId.value));
const rounds = computed(() => roundResults(seasonSeries.value, teamId));
const seasonSlug = computed(() => (seasonId.value ? seasonStore.slugOf(seasonId.value) : null));
const stats = computed(() => {
  const { wins, losses } = seriesRecord(rounds.value);
  return [
    { label: 'Rank', value: rank.value ? `${rank.value.rank} of ${rank.value.of}` : '—' },
    { label: 'Series', value: `${wins}–${losses}` },
    { label: 'Points', value: seasonInfo.value?.final_score ?? '—' },
    { label: 'Points against', value: seasonInfo.value?.points_against ?? '—' },
    { label: 'Points available', value: seasonInfo.value?.points_available ?? '—' },
  ];
});

// Each tab reads the roster, the season's standings and its series
watch(seasonId, async (id) => {
  if (!id) return;
  standings.value = [];
  seasonSeries.value = [];
  const [roster, teams, series] = await Promise.all([
    teamStore.getTeamDetailsSeason(teamId, id).catch(() => null),
    teamStore.getTeamsSeasonBasic(id).catch(() => []),
    seriesStore.searchSeriesBySeason(id).catch(() => []),
  ]);
  if (seasonId.value !== id) return; // a later tab won
  seasonTeam.value = roster;
  standings.value = teams;
  seasonSeries.value = series;
});

const load = async () => {
  try {
    const [loaded] = await Promise.all([teamStore.getTeam(teamId), loadSeasons()]);
    team.value = loaded;
    currentSeasonId.value = await resolveCurrentSeasonId();
    const ids = seasonTabs.value.map((tab) => tab.id);
    seasonId.value = ids.includes(currentSeasonId.value) ? currentSeasonId.value : ids[0] ?? null;
  } catch (error) {
    errorMessage.value = error.message || 'Failed to load the team.';
  } finally {
    isLoading.value = false;
  }
};

load();
</script>

<style scoped>
.team-icon {
  width: 100%;
  height: 100%;
  object-fit: contain;
}
.season-stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(104px, 1fr));
  gap: 12px 16px;
}
.stat-value {
  font-variant-numeric: tabular-nums;
}
.round-col {
  width: 72px;
}
</style>

// next/src/app/(app)/team/[id]/TeamView.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { Icon } from "@/components/ui/Icon";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ColumnNote } from "@/components/ColumnNote";
import { StatusAlert } from "@/components/StatusAlert";
import { TeamName } from "@/components/TeamName";
import { TeamRoster } from "@/components/TeamRoster";
import { POINTS_NOTES } from "@/helpers/achievements.js";
import { loadSeasons, resolveCurrentSeasonId } from "@/helpers/current-season.js";
import { seasonRank, roundResults, seasonTabs as tabsOf, seriesRecord } from "@/helpers/team-record.mjs";
import { showDefaultTeamImage, teamImageUrl } from "@/helpers/team-image.js";
import { rosterOf } from "@/helpers/team-roster.mjs";
import { useSeason, useSeriesStore, useTeamStore } from "@/stores";

type Row = Record<string, any>;
const pointsNotes = POINTS_NOTES as Record<string, string>;

export function TeamView({ id }: { id: string }) {
  const teamId = Number(id);
  const teamStore = useTeamStore();
  const seriesStore = useSeriesStore();
  const seasonStore = useSeason();
  const [team, setTeam] = useState<Row | null>(null);
  const [seasonTeam, setSeasonTeam] = useState<Row | null>(null);
  const [standings, setStandings] = useState<Row[]>([]);
  const [series, setSeries] = useState<Row[]>([]);
  const [seasonId, setSeasonId] = useState<number | null>(null);
  const [currentSeasonId, setCurrentSeasonId] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const tabs: Row[] = tabsOf(team?.seasons_info || [], seasonStore.seasons || []);
  const info = (team?.seasons_info || []).find((row: Row) => row.season_id === seasonId) || null;
  const label = tabs.find((tab) => tab.id === seasonId)?.label || "";
  const roster = rosterOf(seasonTeam, seasonId);
  const rank = seasonRank(standings, teamId, seasonId);
  const rounds: Row[] = roundResults(series, teamId);
  const record = seriesRecord(rounds);
  const slug = seasonId ? seasonStore.slugOf(seasonId) : null;
  const stats = [{ label: "Rank", value: rank ? `${rank.rank} of ${rank.of}` : "—" }, { label: "Series", value: `${record.wins}–${record.losses}` }, { label: "Points", value: info?.final_score ?? "—" }, { label: "Points against", value: info?.points_against ?? "—" }, { label: "Points available", value: info?.points_available ?? "—" }];

  useEffect(() => {
    const start = async () => {
      try {
        const [loaded] = await Promise.all([teamStore.getTeam(teamId), loadSeasons()]);
        setTeam(loaded);
        const current = await resolveCurrentSeasonId(); setCurrentSeasonId(current);
        const tabRows: Row[] = tabsOf(loaded?.seasons_info || [], seasonStore.seasons || []);
        const ids = tabRows.map((tab) => tab.id); setSeasonId(ids.includes(current) ? current : ids[0] ?? null);
      } catch (e) { setError((e as Error).message || "Failed to load the team."); }
      finally { setLoading(false); }
    };
    start();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [teamId]);

  useEffect(() => {
    if (!seasonId) return;
    let active = true;
    // the tab shows one season only, so the rows of the season before go before the reads
    queueMicrotask(() => { setStandings([]); setSeries([]); });
    Promise.all([teamStore.getTeamDetailsSeason(teamId, seasonId).catch(() => null), teamStore.getTeamsSeasonBasic(seasonId).catch(() => []), seriesStore.searchSeriesBySeason(seasonId).catch(() => [])]).then(([one, teams, rows]) => { if (active) { setSeasonTeam(one); setStandings(teams); setSeries(rows); } });
    return () => { active = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [seasonId, teamId]);

  return <div className="p-4">
    {loading ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/60"><Icon name="mdi-loading" size={64} className="animate-spin text-primary" /></div> : null}
    <StatusAlert modelValue={error} onClose={() => setError(null)} />
    {team ? <Card className="card mb-4 gap-0 py-0"><CardTitle className="flex items-center gap-3 bg-primary p-4 text-on-primary"><span className="block size-10 overflow-hidden rounded-full"><img className="size-full object-contain" src={teamImageUrl(team)} alt="" onError={showDefaultTeamImage} /></span><span><span className="block">{team.long_name || team.name}</span>{team.long_name ? <span className="block text-xs font-normal">{team.name}</span> : null}</span></CardTitle>
      {tabs.length ? <Tabs value={seasonId} onValueChange={(value) => setSeasonId(Number(value))} className="border-b px-4"><TabsList variant="line" className="max-w-full justify-start overflow-x-auto">{tabs.map((tab) => <TabsTrigger key={tab.id} value={tab.id} className="flex-none px-3">{tab.label}{tab.id === currentSeasonId ? <Icon name="mdi-star" title="Current season" /> : null}</TabsTrigger>)}</TabsList></Tabs> : null}
      {seasonId ? <CardContent className="flex flex-wrap gap-2 pt-4"><Button variant="outline" size="sm" nativeButton={false} render={<Link href={`/events/${seasonId}`} />}><Icon name="mdi-trophy-variant" />{label}</Button>{slug ? <Button variant="outline" size="sm" nativeButton={false} render={<Link href={`/team/${teamId}/season/${slug}`} />}><Icon name="mdi-shield-account" />Season team page</Button> : null}</CardContent> : null}
      {info ? <CardContent className="grid grid-cols-[repeat(auto-fit,minmax(104px,1fr))] gap-x-4 gap-y-3 pb-4">{stats.map((stat) => <div key={stat.label} className="text-right"><div className="text-xs text-muted-foreground">{pointsNotes[stat.label] ? <ColumnNote title={stat.label} note={pointsNotes[stat.label]} /> : stat.label}</div><div className="tnum text-lg">{stat.value}</div></div>)}</CardContent> : null}
    </Card> : null}
    {team && rounds.length ? <Card className="card mb-4 gap-0 py-0"><CardTitle className="flex items-center gap-2 bg-primary p-4 text-on-primary"><Icon name="mdi-sword-cross" />Rounds</CardTitle><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="w-[72px] text-right">Round</TableHead><TableHead>Opponent</TableHead><TableHead className="text-right">Series</TableHead><TableHead className="text-right">Points</TableHead></TableRow></TableHeader><TableBody>{rounds.map((row) => <TableRow key={row.matchId}><TableCell className="tnum text-right">{row.playday}</TableCell><TableCell><TeamName team={row.opponent} seasonKey={slug} /></TableCell><TableCell className="tnum whitespace-nowrap text-right">{row.wins}–{row.losses}{row.toPlay ? <span className="text-muted-foreground"> of {row.wins + row.losses + row.toPlay}</span> : null}</TableCell><TableCell className={`tnum whitespace-nowrap text-right ${row.pointsFor > row.pointsAgainst ? "font-bold" : ""}`}>{row.pointsFor}–{row.pointsAgainst}</TableCell></TableRow>)}</TableBody></Table></div></Card> : null}
    {team ? <TeamRoster captains={roster.captains} members={roster.members} /> : null}
  </div>;
}

export default TeamView;
