// src/components/CareerStatsDialog.vue
<template>
  <v-dialog v-model="show" max-width="800px">
    <v-card v-if="stat">
      <v-card-title class="text-h5">Career stats: {{ stat.player_name }}</v-card-title>
      <v-card-text>
        <v-alert v-if="error" type="error" variant="tonal" class="mb-4" closable @click:close="error = null">
          {{ error }}
        </v-alert>
        <v-row>
          <v-col cols="12" md="6">
            <v-text-field :model-value="stat.player_name" label="Name in the history" variant="outlined" disabled />
          </v-col>
          <v-col cols="12" md="6">
            <v-autocomplete
              v-model="stat.user_id"
              :items="players"
              item-title="name"
              item-value="id"
              label="Linked player"
              variant="outlined"
              clearable
              hint="The player this history belongs to"
              persistent-hint
            >
              <template #item="{ props, item }">
                <v-list-item v-bind="props" :subtitle="item.raw.battleTag" />
              </template>
            </v-autocomplete>
          </v-col>
        </v-row>

        <div class="text-subtitle-1 mt-4 mb-2">Historical baseline</div>
        <v-row dense>
          <v-col v-for="[key, label] in BASELINE" :key="key" cols="6" md="4">
            <v-text-field v-model.number="stat[`historical_${key}`]" :label="label" type="number" variant="outlined" density="comfortable" />
          </v-col>
        </v-row>

        <div class="text-subtitle-1 mt-2 mb-1">Totals with the app's results</div>
        <p class="text-body-2 text-medium-emphasis">
          Rating {{ stat.rating }}. Series {{ stat.series_won }}-{{ stat.series_lost }} ({{ stat.series_winrate }}%).
          Games {{ stat.games_won }}-{{ stat.games_lost }} ({{ stat.games_winrate }}%). {{ stat.seasons_played }} seasons.
        </p>
      </v-card-text>
      <v-card-actions>
        <v-btn color="error" variant="text" prepend-icon="mdi-delete" @click="confirmDelete = true">Delete</v-btn>
        <v-spacer />
        <v-btn variant="text" @click="show = false">Cancel</v-btn>
        <v-btn color="primary" variant="flat" :loading="saving" @click="save">Save</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <ConfirmDeleteDialog
    v-model="confirmDelete"
    :message="`Delete the career stats of ${stat?.player_name}? This cannot be undone.`"
    delete-icon="mdi-delete"
    @confirm="remove"
    @cancel="confirmDelete = false"
  />
</template>

<script setup>
import { ref } from 'vue';
import { usePlayerCareerStatsStore } from '@/stores/player_career_stats.store';
import ConfirmDeleteDialog from '@/components/ConfirmDeleteDialog.vue';

defineProps({
  players: { type: Array, default: () => [] }, // the "Linked player" choices
});
const emit = defineEmits(['changed']);

const BASELINE = [
  ['rating', 'Rating'],
  ['seasons_played', 'Seasons'],
  ['series_won', 'Series won'],
  ['series_lost', 'Series lost'],
  ['games_won', 'Games won'],
  ['games_lost', 'Games lost'],
];

const store = usePlayerCareerStatsStore();
const show = ref(false);
const stat = ref(null);
const error = ref(null);
const saving = ref(false);
const confirmDelete = ref(false);

const open = (career) => {
  stat.value = {
    ...career,
    user_id: career.user?.id ?? career.user_id ?? null,
    ...Object.fromEntries(BASELINE.map(([key]) => [`historical_${key}`, career[`historical_${key}`] ?? 0])),
  };
  error.value = null;
  show.value = true;
};

const save = async () => {
  saving.value = true;
  error.value = null;
  try {
    await store.update(stat.value.id, stat.value);
    show.value = false;
    emit('changed');
  } catch (e) {
    error.value = e.message || 'Failed to save the career stats';
  } finally {
    saving.value = false;
  }
};

const remove = async () => {
  confirmDelete.value = false;
  try {
    await store.delete(stat.value.id);
    show.value = false;
    emit('changed');
  } catch (e) {
    error.value = e.message || 'Failed to delete the career stats';
  }
};

defineExpose({ open });
</script>

// next/src/components/CareerStatsDialog.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useImperativeHandle, useState } from "react";
import { Button } from "@/components/ui/button";
import { Combobox } from "@/components/ui/Combobox";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { ConfirmDeleteDialog } from "@/components/ConfirmDeleteDialog";
import { StatusAlert } from "@/components/StatusAlert";
import { usePlayerCareerStatsStore } from "@/stores";

const BASELINE = [
  ["rating", "Rating"], ["seasons_played", "Seasons"], ["series_won", "Series won"],
  ["series_lost", "Series lost"], ["games_won", "Games won"], ["games_lost", "Games lost"],
] as const;

export type CareerStatsDialogHandle = { open: (career: Record<string, any>) => void };

export function CareerStatsDialog({ players, onChanged, ref }: { players: Record<string, any>[]; onChanged?: () => void; ref?: React.Ref<CareerStatsDialogHandle> }) {
  const store = usePlayerCareerStatsStore();
  const [show, setShow] = useState(false);
  const [stat, setStat] = useState<Record<string, any> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);

  useImperativeHandle(ref, () => ({
    open: (career) => {
      setStat({
        ...career,
        user_id: career.user?.id ?? career.user_id ?? null,
        ...Object.fromEntries(BASELINE.map(([key]) => [`historical_${key}`, career[`historical_${key}`] ?? 0])),
      });
      setError(null);
      setShow(true);
    },
  }));

  const edit = (key: string, value: unknown) => setStat((row) => row ? { ...row, [key]: value } : row);
  const save = async () => {
    if (!stat) return;
    setSaving(true); setError(null);
    try { await store.update(stat.id, stat); setShow(false); onChanged?.(); }
    catch (e) { setError((e as Error).message || "Failed to save the career stats"); }
    finally { setSaving(false); }
  };
  const remove = async () => {
    if (!stat) return;
    setConfirmDelete(false);
    try { await store.delete(stat.id); setShow(false); onChanged?.(); }
    catch (e) { setError((e as Error).message || "Failed to delete the career stats"); }
  };

  return (
    <>
      <Dialog open={show} onOpenChange={setShow}>
        <DialogContent showCloseButton={false} className="max-w-[800px] gap-0 p-0 sm:max-w-[800px]">
          {stat ? <>
            <DialogTitle className="px-4 py-3 text-xl">Career stats: {stat.player_name}</DialogTitle>
            <div className="px-4"><StatusAlert modelValue={error} onClose={() => setError(null)} /></div>
            <div className="grid gap-4 p-4 md:grid-cols-2">
              <Field label="Name in the history" htmlFor="career-name"><Input id="career-name" value={stat.player_name ?? ""} disabled /></Field>
              <Field label="Linked player" htmlFor="career-player" hint="The player this history belongs to">
                <Combobox
                  id="career-player"
                  label="Linked player"
                  items={players.map((player) => ({ value: String(player.id), title: player.name, battleTag: player.battleTag }))}
                  value={stat.user_id == null ? null : String(stat.user_id)}
                  onChange={(value) => edit("user_id", value == null ? null : Number(value))}
                  row={(item) => <span><span className="block">{item.title}</span><span className="block text-xs text-muted-foreground">{item.battleTag}</span></span>}
                />
              </Field>
              <h3 className="md:col-span-2">Historical baseline</h3>
              {BASELINE.map(([key, label]) => (
                <Field key={key} label={label} htmlFor={`career-${key}`} className="md:[&:nth-of-type(n)]:col-span-1">
                  <Input id={`career-${key}`} type="number" value={stat[`historical_${key}`] ?? 0} onChange={(event) => edit(`historical_${key}`, Number(event.target.value))} />
                </Field>
              ))}
              <div className="md:col-span-2">
                <h3 className="mb-1">Totals with the app&apos;s results</h3>
                <p className="text-sm text-muted-foreground">Rating {stat.rating}. Series {stat.series_won}-{stat.series_lost} ({stat.series_winrate}%). Games {stat.games_won}-{stat.games_lost} ({stat.games_winrate}%). {stat.seasons_played} seasons.</p>
              </div>
            </div>
            <div className="flex items-center gap-2 p-4 pt-0">
              <Button variant="ghost" className="text-error" onClick={() => setConfirmDelete(true)}><Icon name="mdi-delete" />Delete</Button>
              <span className="flex-1" />
              <Button variant="ghost" onClick={() => setShow(false)}>Cancel</Button>
              <Button disabled={saving} onClick={save}><Icon name={saving ? "mdi-loading mdi-spin" : "mdi-content-save"} />Save</Button>
            </div>
          </> : null}
        </DialogContent>
      </Dialog>
      <ConfirmDeleteDialog modelValue={confirmDelete} message={`Delete the career stats of ${stat?.player_name}? This cannot be undone.`} deleteIcon="mdi-delete" onConfirm={remove} onCancel={() => setConfirmDelete(false)} onUpdateModelValue={setConfirmDelete} />
    </>
  );
}

export default CareerStatsDialog;
