// src/components/DiscordJoinCard.vue
<script setup>
import { ref, onMounted } from 'vue';

import { useAuthStore, useConfigStore } from '@/stores';

const NO_MEMBERSHIP = 'You are signed in, but not a member of the WC3 Gym Discord server yet.';

const authStore = useAuthStore();
const inviteUrl = ref(null);
const message = ref(NO_MEMBERSHIP);
const checking = ref(false);

onMounted(async () => {
    const settings = await useConfigStore().fetchSettings().catch(() => []);
    inviteUrl.value = settings.find(s => s.key === 'discord_invite_url')?.value || null;
});

// the backend reads the Discord role on every request, so /me alone re-checks the membership
const checkAgain = async () => {
    checking.value = true;
    message.value = null;
    try {
        await authStore.fetchMe();  // a member answer unmounts this card
        message.value = NO_MEMBERSHIP;
    } catch (e) {
        message.value = e.message;
    } finally {
        checking.value = false;
    }
};
</script>

<template>
    <v-card elevation="2" max-width="500" width="100%">
        <v-card-title class="bg-primary">Join the WC3 Gym Discord</v-card-title>
        <v-card-text class="pt-6">
            <v-alert v-if="message" :type="message === NO_MEMBERSHIP ? 'info' : 'error'" variant="tonal" border="start">{{ message }}</v-alert>
            <v-btn v-if="inviteUrl" :href="inviteUrl" target="_blank" color="#5865F2" class="text-white mt-4 mr-2">Join the Discord</v-btn>
            <v-btn color="primary" variant="text" class="mt-4" :loading="checking" @click="checkAgain">Check again</v-btn>
        </v-card-text>
    </v-card>
</template>

// next/src/components/DiscordJoinCard.tsx
"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Icon } from "@/components/ui/Icon";
import { Note } from "@/components/ui/Note";
import { useAuth, useConfigStore } from "@/stores";
import { cn } from "@/lib/utils";

const NO_MEMBERSHIP = "You are signed in, but not a member of the WC3 Gym Discord server yet.";

/** What a guest reads: why the app is closed to him, the invite, and a way to check again. */
export function DiscordJoinCard({ className }: { className?: string }) {
  const { fetchMe } = useAuth();
  const { fetchSettings } = useConfigStore();
  const [inviteUrl, setInviteUrl] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(NO_MEMBERSHIP);
  const [checking, setChecking] = useState(false);

  useEffect(() => {
    let alive = true;
    fetchSettings()
      .catch(() => [])
      .then((settings: { key: string; value?: string }[]) => {
        if (alive) setInviteUrl(settings.find((s) => s.key === "discord_invite_url")?.value || null);
      });
    return () => { alive = false; };
  }, [fetchSettings]);

  // the backend reads the Discord role on every request, so /me alone re-checks the membership
  const checkAgain = async () => {
    setChecking(true);
    setMessage(null);
    try {
      await fetchMe(); // a member answer unmounts this card
      setMessage(NO_MEMBERSHIP);
    } catch (e) {
      setMessage((e as Error).message);
    } finally {
      setChecking(false);
    }
  };

  return (
    <Card className={cn("w-full max-w-[500px] gap-0 p-0", className)}>
      <CardHeader className="bg-primary p-4">
        <CardTitle className="text-on-primary">Join the WC3 Gym Discord</CardTitle>
      </CardHeader>
      <CardContent className="p-6">
        {message ? <Note type={message === NO_MEMBERSHIP ? "info" : "error"}>{message}</Note> : null}
        {inviteUrl ? (
          // Discord brand: blurple
          <Button
            nativeButton={false}
            render={<a href={inviteUrl} target="_blank" rel="noopener noreferrer" />}
            className="mt-4 mr-2 bg-[#5865F2] text-white hover:bg-[#4752C4]"
          >
            Join the Discord
          </Button>
        ) : null}
        <Button variant="ghost" className="mt-4 text-primary-text" disabled={checking} onClick={checkAgain}>
          {checking ? <Icon name="mdi-loading" className="animate-spin" /> : null}
          Check again
        </Button>
      </CardContent>
    </Card>
  );
}

export default DiscordJoinCard;
