// src/components/LadderImportDialog.vue
<template>
  <v-dialog :model-value="modelValue" max-width="760" @update:modelValue="$emit('update:modelValue', $event)">
    <v-card>
      <v-card-title class="bg-primary d-flex align-center">
        <v-icon class="mr-2">mdi-download</v-icon>
        <span>Import W3C map pool</span>
        <v-spacer />
        <v-chip size="small" variant="outlined">{{ poolRows.length }} maps in the W3C 1v1 pool</v-chip>
      </v-card-title>
      <v-card-text class="pa-0">
        <v-progress-linear v-if="loading" indeterminate color="primary" />
        <v-list max-height="500" class="overflow-y-auto">
          <template v-for="row in rows" :key="row.w3c_name">
          <v-list-subheader v-if="row === offLadderRows[0]">Not in the W3C pool, picture found</v-list-subheader>
          <v-list-item
            :class="{ 'row-skipped': isSkipped(row) }"
            @click="toggleSkip(row)"
          >
            <template #prepend>
              <span class="import-name text-body-2 font-weight-medium mr-3">{{ row.w3c_name }}</span>
              <span class="map-thumb mr-3"><img v-if="row.image_url" :src="row.image_url" :alt="row.matched_name" @error="hideMissingImage"></span>
            </template>
            <v-list-item-title class="text-body-2">{{ row.matched_name || '—' }}</v-list-item-title>
            <template #append>
              <v-chip v-if="row.shortname" size="x-small" label class="mr-3">{{ row.shortname }}</v-chip>
              <v-chip size="x-small" :color="isSkipped(row) ? 'secondary' : 'primary'" variant="tonal">{{ statusLabel(row) }}</v-chip>
            </template>
          </v-list-item>
          </template>
        </v-list>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn @click="$emit('update:modelValue', false)">Cancel</v-btn>
        <v-btn color="primary" variant="elevated" prepend-icon="mdi-plus" :disabled="!names.length" @click="$emit('confirm', names)">
          Import {{ names.length }} maps
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { computed, ref, watch } from 'vue';

import { hideMissingImage } from '@/helpers/team-image';

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  rows: { type: Array, default: () => [] },
  loading: { type: Boolean, default: false },
});
defineEmits(['update:modelValue', 'confirm']);

const STATUS = { in_pool: 'In pool', known: 'Known', no_match: 'No match', new: 'New', off_ladder: 'Not in pool' };

// a known map is imported too: that is what renames a drifted map to the ladder name and fills a
// picture it never had. Click a row to leave it out.
const offLadderRows = computed(() => props.rows.filter((row) => row.status === 'off_ladder'));
const poolRows = computed(() => props.rows.filter((row) => row.status !== 'off_ladder'));
const skipped = ref([]);
watch(() => props.rows, () => { skipped.value = []; });
const isSkipped = (row) => skipped.value.includes(row.w3c_name);
const statusLabel = (row) => (isSkipped(row) ? 'Skipped' : STATUS[row.status] || row.status);
const names = computed(() => props.rows.filter((row) => !isSkipped(row)).map((row) => row.w3c_name));
const toggleSkip = (row) => {
  const at = skipped.value.indexOf(row.w3c_name);
  if (at === -1) skipped.value.push(row.w3c_name);
  else skipped.value.splice(at, 1);
};
</script>

<style scoped>
.map-thumb {
  display: block;
  width: 40px;
  height: 27px;
  background: rgb(var(--v-theme-band));
  border-radius: 3px;
  overflow: hidden;
  flex-shrink: 0;
}

.map-thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.import-name {
  width: 170px;
  flex-shrink: 0;
}

.row-skipped {
  opacity: 0.55;
}
</style>

// next/src/components/LadderImportDialog.tsx
"use client";
import { useState } from "react";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Icon } from "@/components/ui/Icon";
import { Progress } from "@/components/ui/progress";
import { hideMissingImage } from "@/helpers/team-image";

export type ImportRow = {
  w3c_name: string;
  matched_name?: string | null;
  shortname?: string | null;
  image_url?: string | null;
  status: string;
};

const STATUS: Record<string, string> = {
  in_pool: "In pool",
  known: "Known",
  no_match: "No match",
  new: "New",
  off_ladder: "Not in pool",
};

/** The W3C 1v1 map pool, one row per map, before it is imported.
 *  A known map is imported too: that is what renames a drifted map to the ladder name and fills a
 *  picture it never had. Click a row to leave it out. */
export function LadderImportDialog({
  modelValue = false,
  rows = [],
  loading = false,
  onUpdateModelValue,
  onConfirm,
}: {
  modelValue?: boolean;
  rows?: ImportRow[];
  loading?: boolean;
  onUpdateModelValue?: (open: boolean) => void;
  onConfirm?: (names: string[]) => void;
}) {
  const [skipped, setSkipped] = useState<string[]>([]);
  // A fresh read of the pool starts with nothing skipped
  const [seenRows, setSeenRows] = useState(rows);
  if (seenRows !== rows) {
    setSeenRows(rows);
    setSkipped([]);
  }

  const offLadderRows = rows.filter((row) => row.status === "off_ladder");
  const poolRows = rows.filter((row) => row.status !== "off_ladder");
  const isSkipped = (row: ImportRow) => skipped.includes(row.w3c_name);
  const statusLabel = (row: ImportRow) => (isSkipped(row) ? "Skipped" : STATUS[row.status] || row.status);
  const names = rows.filter((row) => !isSkipped(row)).map((row) => row.w3c_name);
  const toggleSkip = (row: ImportRow) =>
    setSkipped((list) => (list.includes(row.w3c_name) ? list.filter((name) => name !== row.w3c_name) : [...list, row.w3c_name]));

  return (
    <Dialog open={modelValue} onOpenChange={(open) => onUpdateModelValue?.(open)}>
      <DialogContent showCloseButton={false} className="max-w-[760px] gap-0 p-0 sm:max-w-[760px]">
        <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
          <Icon name="mdi-download" />
          <span>Import W3C map pool</span>
          <Badge variant="outline" className="ml-auto border-current text-on-primary">
            {poolRows.length} maps in the W3C 1v1 pool
          </Badge>
        </DialogTitle>
        {/* null is the indeterminate bar, which is what the read of the ladder pool shows */}
        {loading ? <Progress value={null} /> : null}
        <ul className="max-h-[500px] overflow-y-auto">
          {rows.map((row) => (
            <li key={row.w3c_name}>
              {row === offLadderRows[0] ? (
                <div className="px-4 pt-3 text-xs text-muted-foreground">Not in the W3C pool, picture found</div>
              ) : null}
              <button
                type="button"
                className={`flex w-full items-center gap-3 px-4 py-2 text-left hover:bg-muted ${isSkipped(row) ? "opacity-55" : ""}`}
                onClick={() => toggleSkip(row)}
              >
                <span className="w-[170px] shrink-0 text-sm font-medium">{row.w3c_name}</span>
                <span className="block h-[27px] w-10 shrink-0 overflow-hidden rounded-[3px] bg-band">
                  {row.image_url ? (
                    <img src={row.image_url} alt={row.matched_name || ""} onError={hideMissingImage} className="block h-full w-full object-cover" />
                  ) : null}
                </span>
                <span className="flex-1 text-sm">{row.matched_name || "—"}</span>
                {row.shortname ? (
                  <Badge variant="outline" className="rounded-[4px]">
                    {row.shortname}
                  </Badge>
                ) : null}
                <Badge variant={isSkipped(row) ? "secondary" : "default"}>{statusLabel(row)}</Badge>
              </button>
            </li>
          ))}
        </ul>
        <div className="flex justify-end gap-2 p-4">
          <Button variant="ghost" onClick={() => onUpdateModelValue?.(false)}>
            Cancel
          </Button>
          <Button disabled={!names.length} onClick={() => onConfirm?.(names)}>
            <Icon name="mdi-plus" />
            Import {names.length} maps
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default LadderImportDialog;
