// src/components/ReportResultDialog.vue
<!-- The player reports one series: the map veto, the winner and map of each game, and
     the replay file per game. A roster member reports for a team side, which names no
     race of its own. The veto warns when it is not complete; it never blocks. -->
<template>
  <v-dialog v-model="show" :max-width="vetoMissing ? 960 : 600">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-trophy</v-icon>
        Report result
      </v-card-title>
      <v-card-text class="pt-4">
        <StatusAlert v-model="errorMessage" />
        <v-alert
          v-if="scoreVeto"
          :type="scoreVeto.complete ? 'success' : 'warning'"
          variant="tonal"
          density="compact"
          class="mb-2"
        >
          {{ scoreVeto.complete ? 'Map veto complete' : 'Enter the map veto below, or report without it.' }}
        </v-alert>
        <VetoBoard v-if="series.id" :key="series.id" :series-id="series.id" report class="mb-4" @change="board => scoreVeto = board" />
        <v-form ref="scoreForm" v-model="scoreFormValid">
          <v-container>
            <v-row v-if="series.solo && !series.raceOpen">
              <v-col cols="12" class="pt-0">
                <v-btn variant="text" size="small" density="comfortable" prepend-icon="mdi-account-switch" @click="series.raceOpen = true">
                  Played a different race
                </v-btn>
              </v-col>
            </v-row>
            <v-row v-else-if="series.solo">
              <v-col cols="6">
                <RaceSelect v-model="series.races.player1" :label="name(1)" density="comfortable" />
              </v-col>
              <v-col cols="6">
                <RaceSelect v-model="series.races.player2" :label="name(2)" density="comfortable" />
              </v-col>
            </v-row>
            <v-row v-for="game in gameRows" :key="game">
              <v-col cols="12">
                <v-card variant="outlined">
                  <v-card-text class="py-3">
                    <div class="text-subtitle-2 mb-2">Game {{ game }}</div>
                    <v-btn-toggle
                      :model-value="series.winners[game - 1]"
                      color="primary"
                      divided
                      variant="outlined"
                      density="comfortable"
                      class="d-flex mb-3"
                      @update:model-value="setWinner(game, $event)"
                    >
                      <v-btn value="A" class="flex-grow-1">{{ name(1) }} won</v-btn>
                      <v-btn value="B" class="flex-grow-1">{{ name(2) }} won</v-btn>
                    </v-btn-toggle>
                    <v-select
                      :model-value="mapOf(game)"
                      :items="mapStore.maps"
                      item-title="name"
                      item-value="id"
                      label="Map played"
                      variant="outlined"
                      density="comfortable"
                      :hint="mapHint(game)"
                      :hide-details="!mapHint(game)"
                      persistent-hint
                      clearable
                      class="mb-3"
                      @update:model-value="setMap(game, $event)"
                    />
                    <v-file-input
                      v-model="series.replays[game]"
                      :label="`Game ${game} replay`"
                      variant="outlined"
                      density="comfortable"
                      accept=".w3g"
                      prepend-icon="mdi-file-upload"
                      :rules="needsFile(game) ? [rules.required, rules.w3gFile] : [rules.w3gFile]"
                      :required="needsFile(game)"
                      :hint="fileHint(game)"
                      @update:model-value="readGameReplay(game, $event)"
                    />
                    <v-alert
                      v-if="replayNote(game)"
                      type="warning"
                      variant="tonal"
                      density="compact"
                      class="mt-2"
                    >
                      {{ replayNote(game) }}
                    </v-alert>
                  </v-card-text>
                </v-card>
              </v-col>
            </v-row>
            <v-row>
              <v-col cols="12" class="pt-0 text-center">
                <span v-if="scoreProblem" class="text-caption text-medium-emphasis">{{ scoreProblem }}</span>
                <span v-else class="text-subtitle-1 font-weight-medium">{{ resultLine }}</span>
              </v-col>
            </v-row>
          </v-container>
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" :disabled="saving" @click="close">Close</v-btn>
        <v-btn :color="vetoMissing ? 'warning' : 'primary'" variant="elevated" prepend-icon="mdi-content-save" :disabled="!isValid || saving" :loading="saving" @click="save">{{ vetoMissing ? 'Report without a veto' : 'Save Result' }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { computed, ref } from 'vue';
import { backendUrl, fetchWrapper } from '@/helpers';
import { authHeader } from '@/helpers/fetch-wrapper';
import { useMapStore } from '@/stores';
import { gamesOf, winsFor, isValidResult, replaysNeeded } from '@/helpers/best-of';
import { mapsByGame, picksOf, scoreOf, gameSlots, gamesReported } from '@/helpers/map-order.mjs';
import { readReplay, matchMap, isOtherSeries } from '@/helpers/w3g.mjs';
import { sideName } from '@/helpers/stage-view.mjs';
import RaceSelect from '@/components/RaceSelect.vue';
import StatusAlert from '@/components/StatusAlert.vue';
import VetoBoard from '@/components/VetoBoard.vue';

const emit = defineEmits(['saved']);

const mapStore = useMapStore();

const show = ref(false);
const saving = ref(false);
const errorMessage = ref(null);
const scoreFormValid = ref(true);
const scoreForm = ref(null);
const series = ref({ replays: {}, races: {}, winners: [], maps: {}, reads: {} });
// a result carries its veto, so the dialog holds the board above the scores
const scoreVeto = ref(null);
// What a side is called: the team or the player of the series, else the name the veto
// board answers, because GET /series/{id} names no team behind a team entrant yet
const name = (side) => series.value[`player${side}_name`]
  || scoreVeto.value?.[`player${side}`]?.name || `Side ${side}`;
const vetoMissing = computed(() => scoreVeto.value !== null && !scoreVeto.value.complete);

// Validation rules
const rules = {
  required: (value) => !!value || 'This field is required',
  w3gFile: (value) => {
    if (!value || !(value instanceof File)) return true;
    return value.name.toLowerCase().endsWith('.w3g') || 'Only .w3g replay files are allowed';
  },
};

const open = (item) => {
  errorMessage.value = null;
  series.value = {
    id: item.id,
    player1_name: sideName(item, 1),
    player2_name: sideName(item, 2),
    // a team side plays no one race, so only a solo series offers the off-race panel
    solo: !!(item.player1_id || item.player2_id),
    // the tags name the sides in a replay, which carries no player id of ours
    tags: [item.player1?.battleTag, item.player2?.battleTag],
    // the rules of this series, which the backend resolves with or without a fixture
    map_rules: item.rules?.map_rules,
    // the race each side played; the panel opens by itself when one is an exception
    races: { player1: item.player1_race, player2: item.player2_race },
    raceOpen: !!(item.player1_off_race || item.player2_off_race),
    // games already reported: their stored replays stay unless a new file is picked
    reported: item.player1_score != null && item.player2_score != null ? item.player1_score + item.player2_score : 0,
    replays: {},
    // the side that won each game, in play order, and the map named for a game
    winners: [],
    maps: {},
    // what each game's replay says, by game number
    reads: {},
    storedGames: '[]',
  };
  scoreVeto.value = null;
  show.value = true;
  if (!mapStore.maps.length) mapStore.fetchMaps().catch(() => {});  // names the maps each game offers
  loadGames(item.id);
};

// A series reported before opens on the games it recorded, so a fix starts from them
const loadGames = async (id) => {
  let games = [];
  try {
    games = await fetchWrapper.get(`${backendUrl}/series/${id}/games`);
  } catch {
    return;  // a series with no games recorded answers nothing to start from
  }
  if (series.value.id !== id) return;  // the dialog moved on while the read was out
  for (const game of games) {
    series.value.winners[game.game_no - 1] = game.winner_side;
    if (game.map_id) series.value.maps[game.game_no] = game.map_id;
  }
  series.value.storedGames = JSON.stringify(gamesReported(series.value.winners, mapOf));
};

const close = () => {
  show.value = false;
  series.value = { replays: {}, races: {}, winners: [], maps: {}, reads: {}, tags: [] };
};

// A picked replay says which map was played. It never blocks a report: the file is the
// evidence, but a player who names something else may be right and the parse may be wrong.
const readGameReplay = async (game, file) => {
  delete series.value.reads[game];
  if (!(file instanceof File)) return;
  const id = series.value.id;
  const read = await readReplay(file).catch(() => null);
  if (!read || series.value.id !== id) return;  // the dialog moved on, or not a replay
  series.value.reads[game] = read;
  // the replay beats the season's rule, but never a map the reporter named himself
  const map = matchMap(read.mapPath, mapStore.maps);
  if (map && !series.value.maps[game]) series.value.maps[game] = map.id;
};

// Says where the map came from when the replay named it, so a changed field is not a surprise
const mapHint = (game) => {
  const read = series.value.reads?.[game];
  const played = read && matchMap(read.mapPath, mapStore.maps);
  return played && played.id === series.value.maps[game] ? 'Read from the replay' : undefined;
};

// What the replay disagrees with, or null
const replayNote = (game) => {
  const read = series.value.reads?.[game];
  if (!read) return null;
  if (isOtherSeries(read.tags, series.value.tags)) {
    return `This replay is ${read.tags.join(' against ')}. It is not this series.`;
  }
  const played = matchMap(read.mapPath, mapStore.maps);
  if (played && series.value.maps[game] && series.value.maps[game] !== played.id) {
    return `The replay was played on ${played.name}.`;
  }
  return null;
};

const REPLAY_MAGIC = 'Warcraft III recorded game';

// The file goes from the browser straight to the bucket, at a link the backend signs per game
const uploadReplay = async (seriesId, game, file) => {
  const head = new TextDecoder().decode(await file.slice(0, REPLAY_MAGIC.length).arrayBuffer());
  if (head !== REPLAY_MAGIC) throw new Error(`Game ${game} is not a Warcraft III replay`);
  const { url } = await fetchWrapper.post(`${backendUrl}/player-series/${seriesId}/replays/${game}/upload-url`);
  const put = await fetch(url, {
    method: 'PUT',
    body: file,
    headers: { 'Content-Type': 'application/octet-stream', 'Content-Disposition': `attachment; filename="game${game}.w3g"` },
  });
  if (!put.ok) throw new Error(`Game ${game} replay upload failed`);
};

const save = async () => {
  saving.value = true;
  errorMessage.value = null;
  try {
    const [p1, p2] = reportedScore.value;
    const games = gamesReported(series.value.winners, mapOf);

    const played = replaysNeeded(p1, p2);
    for (let game = 1; game <= played; game++) {
      if (needsFile(game) && !hasReplay(game)) {
        errorMessage.value = `Game ${game} replay file is required for a ${p1}:${p2} result.`;
        return;
      }
    }

    const id = series.value.id;
    const uploaded = [];
    for (let game = 1; game <= played; game++) {
      if (!hasReplay(game)) continue;
      await uploadReplay(id, game, series.value.replays[game]);
      uploaded.push(game);
    }

    if (played === series.value.reported && uploaded.length && JSON.stringify(games) === series.value.storedGames) {
      // the result stands; each new file replaces one stored replay
      for (const game of uploaded) await fetchWrapper.put(`${backendUrl}/player-series/${id}/replays/${game}`);
    } else {
      // the report confirms every game's file in the bucket before it writes the score
      const formData = new FormData();
      formData.append('player1_score', p1);
      formData.append('player2_score', p2);
      formData.append('action', 'score_updated');
      // one entry per game played, which the backend checks against the score
      formData.append('games', JSON.stringify(games));
      if (series.value.raceOpen) {
        // the backend stores nothing when the race is the one he signed up on
        formData.append('player1_off_race', series.value.races.player1 || '');
        formData.append('player2_off_race', series.value.races.player2 || '');
      }
      const url = `${backendUrl}/player-series/${id}`;
      const response = await fetch(url, { method: 'PUT', headers: await authHeader('PUT', url), body: formData });
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Update failed');
      }
    }

    close();
    emit('saved', 'Result reported successfully!');
  } catch (error) {
    errorMessage.value = error.message || 'Error reporting result.';
  } finally {
    saving.value = false;
  }
};

// The score the tapped winners add up to, the season's maps to win, and the file picked for a game
const reportedScore = computed(() => scoreOf(series.value.winners || []));
const seriesGames = computed(() => gamesOf(series.value.map_rules));
const seriesWins = computed(() => winsFor(seriesGames.value));
const hasReplay = (game) => series.value.replays?.[game] instanceof File;
// A first report needs every game's file; a fix keeps the stored ones unless a new file is picked
const needsFile = (game) => game > (series.value.reported || 0);
const fileHint = (game) => (needsFile(game) ? undefined : 'Leave empty to keep the stored replay');

// One row per game played, plus the next while neither side has won the series
const gameRows = computed(() => gameSlots(seriesGames.value, series.value.winners || []));

// The map the season's rules offer for each game, given the veto and who won the games before
const offeredMaps = computed(() => mapsByGame(
  series.value.map_rules,
  scoreVeto.value?.week_map_id,
  picksOf(scoreVeto.value?.steps),
  series.value.winners || [],
));
const mapOf = (game) => series.value.maps?.[game] ?? offeredMaps.value[game - 1] ?? null;
const setMap = (game, mapId) => { series.value.maps[game] = mapId; };

// A changed winner reopens the games after it: they were played under a different map order
const setWinner = (game, side) => {
  const winners = series.value.winners;
  if (winners[game - 1] === side) return;
  winners[game - 1] = side || null;
  winners.length = game;
  for (const named of Object.keys(series.value.maps)) {
    if (Number(named) > game) delete series.value.maps[named];
  }
};

const scoreProblem = computed(() => {
  const [p1, p2] = reportedScore.value;
  return isValidResult(p1, p2, seriesWins.value) ? null : 'Tap the winner of each game played';
});
const resultLine = computed(() => {
  const [p1, p2] = reportedScore.value;
  return `${name(1)} ${p1} – ${p2} ${name(2)}`;
});

// Allowed score combinations and every required file present
const isValid = computed(() => {
  if (!scoreFormValid.value) return false;
  const [p1, p2] = reportedScore.value;
  if (!isValidResult(p1, p2, seriesWins.value)) return false;
  const played = replaysNeeded(p1, p2);
  for (let game = 1; game <= played; game++) if (needsFile(game) && !hasReplay(game)) return false;
  return true;
});

defineExpose({ open });
</script>

<style scoped>
/* Truncate long filenames in file input */
:deep(.v-file-input .v-field__input) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

:deep(.v-file-input .v-field__input > input) {
  text-overflow: ellipsis;
}
</style>

// next/src/components/ReportResultDialog.tsx
"use client";
import { useImperativeHandle, useRef, useState } from "react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Field } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { RaceSelect } from "@/components/RaceSelect";
import { StatusAlert } from "@/components/StatusAlert";
import { VetoBoard } from "@/components/VetoBoard";
import { authHeader, backendUrl, fetchWrapper } from "@/helpers";
import { gamesOf, winsFor, isValidResult, replaysNeeded } from "@/helpers/best-of.mjs";
import { mapsByGame, picksOf, scoreOf, gameSlots, gamesReported } from "@/helpers/map-order.mjs";
import { readReplay, matchMap, isOtherSeries } from "@/helpers/w3g.mjs";
import { sideName } from "@/helpers/stage-view.mjs";
import { useMapStore } from "@/stores";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

// The chosen side wears the primary wash, as a tonal chip does
export const SIDE_BUTTON = "h-auto min-h-8 flex-1 whitespace-normal py-1 aria-pressed:bg-primary/12 aria-pressed:text-primary-text";
type Form = {
  id?: number;
  player1_name?: string;
  player2_name?: string;
  solo?: boolean;
  tags: (string | undefined)[];
  map_rules?: string;
  races: { player1?: string | null; player2?: string | null };
  raceOpen?: boolean;
  reported?: number;
  replays: Record<number, File | null>;
  winners: (string | null)[];
  maps: Record<number, number | null>;
  reads: Record<number, { mapPath: string | null; tags: string[] }>;
  storedGames?: string;
};

export type ReportResultDialogHandle = { open: (item: Row) => void };

const EMPTY: Form = { replays: {}, races: {}, winners: [], maps: {}, reads: {}, tags: [] };
const REPLAY_MAGIC = "Warcraft III recorded game";
const isW3g = (file?: File | null) => !file || file.name.toLowerCase().endsWith(".w3g");

/** A note the reader cannot close: what the veto or a replay says about the report. */
function Note({ type, children }: { type: "success" | "warning"; children: React.ReactNode }) {
  const tone = type === "success" ? "text-success" : "text-warning";
  return (
    <Alert className={cn("alert", tone)}>
      <AlertDescription className="flex items-start gap-2 text-foreground">
        <Icon name={type === "success" ? "mdi-check-circle-outline" : "mdi-alert-outline"} className={tone} />
        {children}
      </AlertDescription>
    </Alert>
  );
}

// A file input that mounts again shows the file the form still holds for its game
const showHeld = (file?: File | null) => (input: HTMLInputElement | null) => {
  if (!input || !file || input.files?.length) return;
  const held = new DataTransfer();
  held.items.add(file);
  input.files = held.files;
};

// The map the season's rules offer for each game, given the veto and who won the games before
const offeredMaps = (form: Form, veto: Row | null): (number | null)[] => mapsByGame(form.map_rules, veto?.week_map_id, picksOf(veto?.steps), form.winners || []);
const mapOfIn = (form: Form, veto: Row | null, game: number) => form.maps?.[game] ?? offeredMaps(form, veto)[game - 1] ?? null;

/** The player reports one series: the map veto, the winner and map of each game, and
 *  the replay file per game. A roster member reports for a team side, which names no
 *  race of its own. The veto warns when it is not complete; it never blocks. The caller
 *  opens it through its ref and hands in the series row. */
export function ReportResultDialog({ onSaved, ref }: { onSaved?: (message: string) => void; ref?: React.Ref<ReportResultDialogHandle> }) {
  const mapStore = useMapStore();

  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [maps, setMaps] = useState<Row[]>([]);
  const [series, setSeries] = useState<Form>(EMPTY);
  // a read that answers late checks the series the dialog holds by then
  const openId = useRef<number | undefined>(undefined);
  // a result carries its veto, so the dialog holds the board above the scores
  const [scoreVeto, drawScoreVeto] = useState<Row | null>(null);
  const vetoRef = useRef<Row | null>(null);
  const setScoreVeto = (board: Row | null) => {
    vetoRef.current = board;
    drawScoreVeto(board);
  };
  // What a side is called: the team or the player of the series, else the name the veto
  // board answers, because GET /series/{id} names no team behind a team entrant yet
  const name = (side: 1 | 2) => series[`player${side}_name`] || scoreVeto?.[`player${side}`]?.name || `Side ${side}`;
  const vetoMissing = scoreVeto !== null && !scoreVeto.complete;

  const mapOf = (game: number) => mapOfIn(series, scoreVeto, game);

  // A series reported before opens on the games it recorded, so a fix starts from them
  const loadGames = async (id: number) => {
    let games: Row[] = [];
    try {
      games = await fetchWrapper.get(`${backendUrl}/series/${id}/games`);
    } catch {
      return; // a series with no games recorded answers nothing to start from
    }
    if (openId.current !== id) return; // the dialog moved on while the read was out
    setSeries((form) => {
      const next = { ...form, winners: [...form.winners], maps: { ...form.maps } };
      for (const game of games) {
        next.winners[game.game_no - 1] = game.winner_side;
        if (game.map_id) next.maps[game.game_no] = game.map_id;
      }
      next.storedGames = JSON.stringify(gamesReported(next.winners, (game: number) => mapOfIn(next, vetoRef.current, game)));
      return next;
    });
  };

  useImperativeHandle(ref, () => ({
    open: (item: Row) => {
      setErrorMessage(null);
      openId.current = item.id;
      setSeries({
        id: item.id,
        player1_name: sideName(item, 1),
        player2_name: sideName(item, 2),
        // a team side plays no one race, so only a solo series offers the off-race panel
        solo: !!(item.player1_id || item.player2_id),
        // the tags name the sides in a replay, which carries no player id of ours
        tags: [item.player1?.battleTag, item.player2?.battleTag],
        // the rules of this series, which the backend resolves with or without a fixture
        map_rules: item.rules?.map_rules,
        // the race each side played; the panel opens by itself when one is an exception
        races: { player1: item.player1_race, player2: item.player2_race },
        raceOpen: !!(item.player1_off_race || item.player2_off_race),
        // games already reported: their stored replays stay unless a new file is picked
        reported: item.player1_score != null && item.player2_score != null ? item.player1_score + item.player2_score : 0,
        replays: {},
        // the side that won each game, in play order, and the map named for a game
        winners: [],
        maps: {},
        // what each game's replay says, by game number
        reads: {},
        storedGames: "[]",
      });
      setScoreVeto(null);
      setShow(true);
      if (!maps.length) mapStore.fetchMaps().then((rows: Row[]) => setMaps(rows || [])).catch(() => {}); // names the maps each game offers
      loadGames(item.id);
    },
  }));

  const close = () => {
    setShow(false);
    openId.current = undefined;
    setSeries(EMPTY);
  };

  // A picked replay says which map was played. It never blocks a report: the file is the
  // evidence, but a player who names something else may be right and the parse may be wrong.
  const readGameReplay = async (game: number, file: File | null) => {
    setSeries((form) => {
      const reads = { ...form.reads };
      delete reads[game];
      return { ...form, reads, replays: { ...form.replays, [game]: file } };
    });
    if (!file) return;
    const id = series.id;
    const read = await readReplay(file).catch(() => null);
    if (!read || openId.current !== id) return; // the dialog moved on, or not a replay
    // the replay beats the season's rule, but never a map the reporter named himself
    const map = matchMap(read.mapPath, maps);
    setSeries((form) => ({
      ...form,
      reads: { ...form.reads, [game]: read },
      maps: map && !form.maps[game] ? { ...form.maps, [game]: map.id } : form.maps,
    }));
  };

  // Says where the map came from when the replay named it, so a changed field is not a surprise
  const mapHint = (game: number) => {
    const read = series.reads?.[game];
    const played = read && matchMap(read.mapPath, maps);
    return played && played.id === series.maps[game] ? "Read from the replay" : undefined;
  };

  // What the replay disagrees with, or null
  const replayNote = (game: number) => {
    const read = series.reads?.[game];
    if (!read) return null;
    if (isOtherSeries(read.tags, series.tags)) {
      return `This replay is ${read.tags.join(" against ")}. It is not this series.`;
    }
    const played = matchMap(read.mapPath, maps);
    if (played && series.maps[game] && series.maps[game] !== played.id) {
      return `The replay was played on ${played.name}.`;
    }
    return null;
  };

  // The file goes from the browser straight to the bucket, at a link the backend signs per game
  const uploadReplay = async (seriesId: number, game: number, file: File) => {
    const head = new TextDecoder().decode(await file.slice(0, REPLAY_MAGIC.length).arrayBuffer());
    if (head !== REPLAY_MAGIC) throw new Error(`Game ${game} is not a Warcraft III replay`);
    const { url } = await fetchWrapper.post(`${backendUrl}/player-series/${seriesId}/replays/${game}/upload-url`);
    const put = await fetch(url, {
      method: "PUT",
      body: file,
      headers: { "Content-Type": "application/octet-stream", "Content-Disposition": `attachment; filename="game${game}.w3g"` },
    });
    if (!put.ok) throw new Error(`Game ${game} replay upload failed`);
  };

  // The score the tapped winners add up to, the season's maps to win, and the file picked for a game
  const reportedScore: number[] = scoreOf(series.winners || []);
  const seriesGames = gamesOf(series.map_rules);
  const seriesWins = winsFor(seriesGames);
  const hasReplay = (game: number) => series.replays?.[game] instanceof File;
  // A first report needs every game's file; a fix keeps the stored ones unless a new file is picked
  const needsFile = (game: number) => game > (series.reported || 0);
  const fileHint = (game: number) => (needsFile(game) ? undefined : "Leave empty to keep the stored replay");

  // One row per game played, plus the next while neither side has won the series
  const gameRows = Array.from({ length: gameSlots(seriesGames, series.winners || []) }, (_, index) => index + 1);

  const setMap = (game: number, mapId: number | null) => setSeries((form) => ({ ...form, maps: { ...form.maps, [game]: mapId } }));

  // A changed winner reopens the games after it: they were played under a different map order
  const setWinner = (game: number, side: string | null) =>
    setSeries((form) => {
      if (form.winners[game - 1] === side) return form;
      const winners = form.winners.slice(0, game);
      winners[game - 1] = side || null;
      const kept = Object.fromEntries(Object.entries(form.maps).filter(([named]) => Number(named) <= game));
      return { ...form, winners, maps: kept };
    });

  const [p1, p2] = reportedScore;
  const scoreProblem = isValidResult(p1, p2, seriesWins) ? null : "Tap the winner of each game played";
  const resultLine = `${name(1)} ${p1} – ${p2} ${name(2)}`;

  // Allowed score combinations, every required file present, and every file a .w3g
  const isValid = (() => {
    if (!isValidResult(p1, p2, seriesWins)) return false;
    if (gameRows.some((game) => !isW3g(series.replays[game]))) return false;
    const played = replaysNeeded(p1, p2);
    for (let game = 1; game <= played; game++) if (needsFile(game) && !hasReplay(game)) return false;
    return true;
  })();

  const save = async () => {
    setSaving(true);
    setErrorMessage(null);
    try {
      const games = gamesReported(series.winners, mapOf);

      const played = replaysNeeded(p1, p2);
      for (let game = 1; game <= played; game++) {
        if (needsFile(game) && !hasReplay(game)) {
          setErrorMessage(`Game ${game} replay file is required for a ${p1}:${p2} result.`);
          return;
        }
      }

      const id = series.id!;
      const uploaded: number[] = [];
      for (let game = 1; game <= played; game++) {
        if (!hasReplay(game)) continue;
        await uploadReplay(id, game, series.replays[game] as File);
        uploaded.push(game);
      }

      if (played === series.reported && uploaded.length && JSON.stringify(games) === series.storedGames) {
        // the result stands; each new file replaces one stored replay
        for (const game of uploaded) await fetchWrapper.put(`${backendUrl}/player-series/${id}/replays/${game}`);
      } else {
        // the report confirms every game's file in the bucket before it writes the score
        const formData = new FormData();
        formData.append("player1_score", String(p1));
        formData.append("player2_score", String(p2));
        formData.append("action", "score_updated");
        // one entry per game played, which the backend checks against the score
        formData.append("games", JSON.stringify(games));
        if (series.raceOpen) {
          // the backend stores nothing when the race is the one he signed up on
          formData.append("player1_off_race", series.races.player1 || "");
          formData.append("player2_off_race", series.races.player2 || "");
        }
        const url = `${backendUrl}/player-series/${id}`;
        const response = await fetch(url, { method: "PUT", headers: await authHeader("PUT", url), body: formData });
        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.error || "Update failed");
        }
      }

      close();
      onSaved?.("Result reported successfully!");
    } catch (error) {
      setErrorMessage((error as Error).message || "Error reporting result.");
    } finally {
      setSaving(false);
    }
  };

  const width = vetoMissing ? "max-w-[960px] sm:max-w-[960px]" : "max-w-[600px] sm:max-w-[600px]";

  return (
    <Dialog open={show} onOpenChange={(open) => (open ? setShow(true) : saving ? null : close())}>
      <DialogContent showCloseButton={false} className={cn("max-h-[90vh] gap-0 overflow-y-auto p-0", width)}>
        <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
          <Icon name="mdi-trophy" />
          Report result
        </DialogTitle>
        <div className="flex flex-col gap-3 p-4">
          <StatusAlert modelValue={errorMessage} onClose={() => setErrorMessage(null)} className="mb-0" />
          {scoreVeto ? (
            <Note type={scoreVeto.complete ? "success" : "warning"}>{scoreVeto.complete ? "Map veto complete" : "Enter the map veto below, or report without it."}</Note>
          ) : null}
          {series.id ? <VetoBoard key={series.id} seriesId={series.id} report onChange={(board) => openId.current === series.id && setScoreVeto(board)} /> : null}

          {series.solo && !series.raceOpen ? (
            <div>
              <Button variant="ghost" size="sm" onClick={() => setSeries((form) => ({ ...form, raceOpen: true }))}>
                <Icon name="mdi-account-switch" />
                Played a different race
              </Button>
            </div>
          ) : series.solo ? (
            <div className="grid grid-cols-2 gap-3">
              {([1, 2] as const).map((side) => (
                <RaceSelect
                  key={side}
                  label={name(side)}
                  value={series.races[`player${side}`] ?? null}
                  onChange={(race) => setSeries((form) => ({ ...form, races: { ...form.races, [`player${side}`]: race } }))}
                />
              ))}
            </div>
          ) : null}

          {gameRows.map((game) => (
            <div key={game} className="flex flex-col gap-3 rounded border p-3">
              <div className="text-sm font-medium">Game {game}</div>
              <ToggleGroup
                variant="outline"
                spacing={0}
                className="w-full"
                aria-label={`Winner of game ${game}`}
                value={series.winners[game - 1] ? [series.winners[game - 1] as string] : []}
                onValueChange={(value) => setWinner(game, (value[0] as string) ?? null)}
              >
                <ToggleGroupItem value="A" className={SIDE_BUTTON}>
                  {name(1)} won
                </ToggleGroupItem>
                <ToggleGroupItem value="B" className={SIDE_BUTTON}>
                  {name(2)} won
                </ToggleGroupItem>
              </ToggleGroup>
              <Field label="Map played" htmlFor={`report-map-${game}`} hint={mapHint(game)}>
                <div className="flex gap-2">
                  <Select value={mapOf(game)} onValueChange={(value) => setMap(game, value as number | null)}>
                    <SelectTrigger id={`report-map-${game}`} className="w-full">
                      <SelectValue>{(id: number | null) => maps.find((map) => map.id === id)?.name ?? ""}</SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      {maps.map((map) => (
                        <SelectItem key={map.id} value={map.id}>
                          {map.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {mapOf(game) ? (
                    <Button variant="ghost" size="icon" aria-label="Clear the map" onClick={() => setMap(game, null)}>
                      <Icon name="mdi-close" />
                    </Button>
                  ) : null}
                </div>
              </Field>
              <Field
                label={`Game ${game} replay`}
                htmlFor={`report-replay-${game}`}
                hint={fileHint(game)}
                error={isW3g(series.replays[game]) ? null : "Only .w3g replay files are allowed"}
              >
                <Input
                  id={`report-replay-${game}`}
                  ref={showHeld(series.replays[game])}
                  type="file"
                  accept=".w3g"
                  required={needsFile(game)}
                  onChange={(event) => readGameReplay(game, event.target.files?.[0] ?? null)}
                />
              </Field>
              {replayNote(game) ? <Note type="warning">{replayNote(game)}</Note> : null}
            </div>
          ))}

          <div className="text-center">
            {scoreProblem ? <span className="text-xs text-muted-foreground">{scoreProblem}</span> : <span className="text-base font-medium">{resultLine}</span>}
          </div>
        </div>
        <div className="flex justify-end gap-2 p-4 pt-0">
          <Button variant="ghost" disabled={saving} onClick={close}>
            Close
          </Button>
          <Button variant={vetoMissing ? "outline" : "default"} className={vetoMissing ? "text-warning" : undefined} disabled={!isValid || saving} onClick={save}>
            <Icon name={saving ? "mdi-loading mdi-spin" : "mdi-content-save"} />
            {vetoMissing ? "Report without a veto" : "Save Result"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default ReportResultDialog;
