// src/components/SeasonSignupDialog.vue
<template>
  <v-dialog v-model="show" max-width="600">
    <v-card>
      <v-card-title class="bg-primary">
        <v-icon class="mr-2">mdi-account-check</v-icon>
        Add Signup
      </v-card-title>

      <v-alert
        v-if="addError"
        type="error"
        variant="tonal"
        border="start"
        border-color="error"
        class="mx-4 my-2"
        closable
        @click:close="addError = null"
      >
        {{ addError }}
      </v-alert>

      <v-card-text class="pt-4">
        <v-select
          v-model="seasonId"
          :items="seasonStore.seasons"
          item-title="name"
          item-value="id"
          label="Season"
          variant="outlined"
          density="comfortable"
          :readonly="!!presetSeason"
        ></v-select>

        <v-autocomplete
          v-model="playerId"
          :items="playerStore.players"
          item-title="name"
          item-value="id"
          label="Player"
          variant="outlined"
          density="comfortable"
          :readonly="!!presetPlayer"
        >
          <template #selection="{ item }">
            <PlayerName :player="item.raw" @click.stop.prevent />
          </template>
          <template #item="{ props: itemProps, item }">
            <v-list-item v-bind="itemProps" :title="null">
              <PlayerName :player="item.raw" @click.prevent />
            </v-list-item>
          </template>
        </v-autocomplete>

        <RaceSelect v-model="race" variant="outlined" density="comfortable" />

        <div class="d-flex align-center ga-2">
          <W3CMmr />
          <span>{{ mmr ?? '—' }}</span>
        </div>
      </v-card-text>

      <v-card-actions>
        <v-spacer />
        <v-btn @click="close">Cancel</v-btn>
        <v-btn
          color="primary"
          variant="elevated"
          prepend-icon="mdi-plus"
          :loading="isAdding"
          :disabled="!seasonId || !playerId || !race"
          @click="addSignup"
        >
          Add signup
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { computed, ref, watch } from 'vue';
import { usePlayerStore, useSeasonStore } from '@/stores';
import W3CMmr from '@/components/W3CMmr.vue';
import { resolveCurrentSeasonId, resolveCurrentW3CSeason } from '@/helpers/current-season';
import { getW3CGames, getW3CMMR } from '@/helpers/w3c-stats';
import { defaultSignupRace } from '@/helpers/players.mjs';

const emit = defineEmits(['added']);

const playerStore = usePlayerStore();
const seasonStore = useSeasonStore();

const show = ref(false);
const isAdding = ref(false);
const addError = ref(null);
const seasonId = ref(null);
const playerId = ref(null);
const race = ref(null);
const presetSeason = ref(null);
const presetPlayer = ref(null);
const currentW3CSeason = ref(null);

const selectedPlayer = computed(() => (playerStore.players || []).find(p => p.id === playerId.value));
const mmr = computed(() =>
  selectedPlayer.value && race.value ? getW3CMMR(selectedPlayer.value, currentW3CSeason.value, race.value) : null
);

// The signup opens on the race the player last registered on, or the race he
// plays most on the ladder. Picking another player moves it.
watch([selectedPlayer, currentW3CSeason], ([player], [previousPlayer]) => {
  if (player !== previousPlayer || race.value === null) {
    race.value = defaultSignupRace(player, r => getW3CGames(player, currentW3CSeason.value, r));
  }
});

const open = async ({ season = null, player = null } = {}) => {
  presetSeason.value = season;
  presetPlayer.value = player;
  seasonId.value = season?.id ?? null;
  playerId.value = player?.id ?? null;
  race.value = null;
  addError.value = null;
  show.value = true;
  try {
    if (!seasonStore.seasons.length) await seasonStore.fetchSeasons();
    if (!playerStore.players.length) await playerStore.fetchPlayers();
    if (!seasonId.value) seasonId.value = await resolveCurrentSeasonId();
    currentW3CSeason.value = await resolveCurrentW3CSeason();
  } catch (err) {
    console.error('Failed to load the signup dialog lists:', err);
  }
};

const addSignup = async () => {
  addError.value = null;
  isAdding.value = true;
  try {
    await seasonStore.addUserSignup(seasonId.value, [playerId.value], race.value);
    emit('added');
    close();
  } catch (error) {
    console.error('Error adding signup:', error);
    addError.value = 'Error adding signup: ' + error.message;
  } finally {
    isAdding.value = false;
  }
};

const close = () => {
  show.value = false;
};

defineExpose({ open });
</script>

// next/src/components/SeasonSignupDialog.tsx
"use client";
import { useImperativeHandle, useState } from "react";
import { Button } from "@/components/ui/button";
import { Combobox } from "@/components/ui/Combobox";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Icon } from "@/components/ui/Icon";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PlayerName } from "@/components/PlayerName";
import type { Player } from "@/components/PlayerName";
import { RaceSelect } from "@/components/RaceSelect";
import { StatusAlert } from "@/components/StatusAlert";
import { W3CMmr } from "@/components/W3CMmr";
import { usePlayerStore, useSeason } from "@/stores";
import { resolveCurrentSeasonId, resolveCurrentW3CSeason } from "@/helpers/current-season.js";
import { getW3CGames, getW3CMMR } from "@/helpers/w3c-stats.js";
import { defaultSignupRace } from "@/helpers/players.mjs";

type Season = { id: number; name: string };

export type SeasonSignupDialogHandle = { open: (preset?: { season?: Season | null; player?: Player | null }) => void };

/** Signs one player up for one season by hand. The caller opens it through its ref, and may
 *  preset the season or the player, which the form then shows but does not take. */
export function SeasonSignupDialog({ onAdded, ref }: { onAdded?: () => void; ref?: React.Ref<SeasonSignupDialogHandle> }) {
  const playerStore = usePlayerStore();
  const seasonStore = useSeason();

  const [show, setShow] = useState(false);
  const [isAdding, setIsAdding] = useState(false);
  const [addError, setAddError] = useState<string | null>(null);
  const [seasonId, setSeasonId] = useState<number | null>(null);
  const [playerId, setPlayerId] = useState<number | null>(null);
  const [race, setRace] = useState<string | null>(null);
  const [presetSeason, setPresetSeason] = useState<Season | null>(null);
  const [presetPlayer, setPresetPlayer] = useState<Player | null>(null);
  const [currentW3CSeason, setCurrentW3CSeason] = useState<number | null>(null);
  // The ported player store keeps no rows, so the list the picker offers lives here
  const [players, setPlayers] = useState<Player[]>([]);

  const selectedPlayer = players.find((player) => player.id === playerId) ?? null;
  const mmr = selectedPlayer && race ? getW3CMMR(selectedPlayer, currentW3CSeason ?? undefined, race) : null;

  // The signup opens on the race the player last registered on, or the race he
  // plays most on the ladder. Picking another player moves it.
  const [raceKey, setRaceKey] = useState<string | null>(null);
  const key = `${selectedPlayer?.id ?? ""}:${currentW3CSeason ?? ""}`;
  if (raceKey !== key) {
    setRaceKey(key);
    setRace(selectedPlayer ? defaultSignupRace(selectedPlayer, (r: string) => getW3CGames(selectedPlayer, currentW3CSeason ?? undefined, r)) : null);
  }

  useImperativeHandle(ref, () => ({
    open: async ({ season = null, player = null } = {}) => {
      setPresetSeason(season);
      setPresetPlayer(player);
      setSeasonId(season?.id ?? null);
      setPlayerId((player?.id as number) ?? null);
      setRace(null);
      setRaceKey(null);
      setAddError(null);
      setShow(true);
      try {
        if (!seasonStore.seasons.length) await seasonStore.fetchSeasons();
        if (!players.length) setPlayers(await playerStore.fetchPlayers());
        if (!season?.id) setSeasonId(await resolveCurrentSeasonId());
        setCurrentW3CSeason(await resolveCurrentW3CSeason());
      } catch (err) {
        console.error("Failed to load the signup dialog lists:", err);
      }
    },
  }));

  const close = () => setShow(false);

  const addSignup = async () => {
    setAddError(null);
    setIsAdding(true);
    try {
      await seasonStore.addUserSignup(seasonId as number, [playerId as number], race as string);
      onAdded?.();
      close();
    } catch (error) {
      console.error("Error adding signup:", error);
      setAddError("Error adding signup: " + (error as Error).message);
    } finally {
      setIsAdding(false);
    }
  };

  return (
    <Dialog open={show} onOpenChange={(open) => (open ? setShow(true) : close())}>
      <DialogContent showCloseButton={false} className="max-w-[600px] gap-0 p-0 sm:max-w-[600px]">
        <DialogTitle className="flex items-center gap-2 bg-primary px-4 py-3 text-on-primary">
          <Icon name="mdi-account-check" />
          Add signup
        </DialogTitle>

        <div className="px-4 pt-4">
          <StatusAlert modelValue={addError} onClose={() => setAddError(null)} />
        </div>

        <div className="flex flex-col gap-4 p-4">
          <Select
            items={seasonStore.seasons.map((season) => ({ value: season.id, label: season.name }))}
            value={seasonId}
            onValueChange={(value) => setSeasonId(value as number | null)}
            disabled={!!presetSeason}
          >
            <SelectTrigger aria-label="Season" className="w-full">
              <SelectValue placeholder="Season" />
            </SelectTrigger>
            <SelectContent>
              {seasonStore.seasons.map((season) => (
                <SelectItem key={season.id} value={season.id}>
                  {season.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Combobox
            label="Player"
            items={players.map((player) => ({ value: String(player.id), title: player.name ?? "" }))}
            value={playerId == null ? null : String(playerId)}
            onChange={(value) => (presetPlayer ? undefined : setPlayerId(value == null ? null : Number(value)))}
            row={(item) => {
              const player = players.find((row) => String(row.id) === item.value);
              return player ? <PlayerName player={player} plain /> : item.title;
            }}
          />

          <RaceSelect value={race} onChange={setRace} />

          <div className="flex items-center gap-2">
            <W3CMmr />
            <span className="tnum">{mmr ?? "—"}</span>
          </div>
        </div>

        <div className="flex justify-end gap-2 p-4 pt-0">
          <Button variant="ghost" onClick={close}>
            Cancel
          </Button>
          <Button onClick={addSignup} disabled={isAdding || !seasonId || !playerId || !race}>
            <Icon name={isAdding ? "mdi-loading mdi-spin" : "mdi-plus"} />
            Add signup
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default SeasonSignupDialog;
