// src/components/SeriesCard.vue
<!-- One series on a phone: a title line, then one line per player with a value at the right -->
<template>
  <div class="series-card">
    <div class="title-row d-flex align-center justify-space-between text-caption text-medium-emphasis">
      <span><slot name="title" /></span>
      <slot name="actions" />
    </div>
    <div v-for="(player, n) in [series.player1, series.player2]" :key="n" class="d-flex align-center ga-2" :class="{ 'font-weight-bold': winner === n }">
      <PlayerName :player="player" :race="races[n]" :host="series.host_player_id === player.id" class="flex-grow-1" />
      <slot name="side" :player="player" :race="races[n]" :n="n" :won="winner === n" />
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import PlayerName from '@/components/PlayerName.vue';

const props = defineProps({
  series: { type: Object, required: true }, // player1, player2, host_player_id, scores
});

// the race each side played, which is his signup race unless he reported another
const races = computed(() => [props.series.player1_race, props.series.player2_race]);

const winner = computed(() => {
  const { player1_score: a = 0, player2_score: b = 0 } = props.series;
  return a === b ? null : (a > b ? 0 : 1);
});
</script>

<style scoped>
.series-card {
  padding: 8px 12px;
  border-bottom: thin solid rgba(var(--v-border-color), var(--v-border-opacity));
}
.series-card :deep(.player-name) {
  white-space: normal;
}
/* the caption-sized title link is the only way into the match on a phone */
.title-row :deep(a) {
  display: inline-block;
  padding-block: 6px;
}
</style>

// next/src/components/SeriesCard.tsx
"use client";
import { PlayerName, type Player } from "@/components/PlayerName";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

/** One series on a phone: a title line, then one line per player with a value at the right.
 *  `title`, `actions` and `side` fill the title line, its right end and each player line. */
export function SeriesCard({
  series, // player1, player2, host_player_id, scores
  title,
  actions,
  side,
}: {
  series: Row;
  title?: React.ReactNode;
  actions?: React.ReactNode;
  side?: (args: { player: Player; race?: string; n: number; won: boolean }) => React.ReactNode;
}) {
  // the race each side played, which is his signup race unless he reported another
  const races: (string | undefined)[] = [series.player1_race, series.player2_race];

  const { player1_score: a = 0, player2_score: b = 0 } = series;
  const winner = a === b ? null : a > b ? 0 : 1;

  return (
    <div className="border-b px-3 py-2 [&_.player-name]:whitespace-normal">
      {/* the caption-sized title link is the only way into the match on a phone */}
      <div className="flex items-center justify-between text-xs text-muted-foreground [&_a]:inline-block [&_a]:py-1.5">
        <span>{title}</span>
        {actions}
      </div>
      {[series.player1, series.player2].map((player: Player, n) => (
        <div key={n} className={cn("flex items-center gap-2", winner === n && "font-bold")}>
          <span className="flex-1">
            <PlayerName player={player} race={races[n]} host={series.host_player_id === player.id} />
          </span>
          {side?.({ player, race: races[n], n, won: winner === n })}
        </div>
      ))}
    </div>
  );
}

export default SeriesCard;
