// src/components/SeriesBox.vue
<!-- One series of a stage: a side per row with its race, the score, and the state as a
     word. A team side reads as the team name over the roster it fields. A free for all
     lobby reads one row a seat with its place. The winning side wears the win token;
     a click opens the series. -->
<template>
  <component :is="readonly ? 'div' : 'button'" :type="readonly ? undefined : 'button'"
    class="series-box" :class="{ flat, readonly }" @click="readonly || $emit('open', series)">
    <!-- a free for all lobby: one row a seat, the winner first, the place as the number -->
    <div v-for="seat in seats" :key="seat.key" class="side" :class="seat.result">
      <span class="mark" />
      <PlayerName v-if="seat.user" :player="seat.user" :plain="!readonly" />
      <span v-else class="text-medium-emphasis empty">{{ fed ? 'To be decided' : 'Empty seat' }}</span>
      <span class="score">{{ seat.place ?? '' }}</span>
    </div>
    <div v-for="side in seats.length ? [] : [1, 2]" :key="side" class="side" :class="sideClass(side)">
      <span class="mark" />
      <v-icon v-if="crown && side === 1" size="14" icon="mdi-crown" class="crown" aria-hidden="true" />
      <div v-if="team(side)" class="who">
        <span class="team-name">{{ team(side).name }}</span>
        <span v-if="roster(side).length" class="roster">
          <PlayerName v-for="seat in roster(side)" :key="seat.player.id" :player="seat.player"
            :race="seat.race || undefined" :plain="!readonly" />
        </span>
      </div>
      <PlayerName v-else-if="player(side)" :player="player(side)" :race="race(side)" :plain="!readonly" />
      <span v-else class="text-medium-emphasis empty">{{ empty(side) }}</span>
      <span class="score">{{ score(side) }}</span>
    </div>
    <div class="foot text-caption text-medium-emphasis">
      <span>{{ stateWord }}</span>
      <span v-if="label">{{ label }}</span>
    </div>
  </component>
</template>

<script setup>
import { computed, inject, ref } from 'vue';

import { HIDE_RESULTS } from '@/helpers/events.mjs';
import PlayerName from '@/components/PlayerName.vue';
import { isByeSide, lobbySeats, seriesState, shownPlayer, shownTeam, winnerSide } from '@/helpers/stage-view.mjs';

const props = defineProps({
  series: { type: Object, required: true },
  label: { type: String, default: '' },  // the grand final and the third place name themselves
  crown: Boolean,                        // the standing king of a KOTH chain
  flat: Boolean,                         // inside a list, the card around it draws the border
  readonly: Boolean,                     // the series page opens nothing, so its names link
  rosters: { type: Object, default: () => ({}) },  // the players of each team entrant, by entrant id
  fed: Boolean,                          // a lobby seated by the round before it, not by the seeds
});
defineEmits(['open']);

const STATE_WORD = {
  pending: 'Waiting for both sides',
  open: 'To play',
  played: 'Played',
  walkover: 'Walkover',
  forfeit: 'Forfeit',
};

// The spoiler switch of the page around this box; a page with no switch shows every result
const hidden = inject(HIDE_RESULTS, ref(false));

const state = computed(() => seriesState(props.series));
// A lobby seats more than two, so its seats replace the two side rows
const seats = computed(() => lobbySeats(props.series, hidden.value, props.fed));
// A lobby fills from the round before it, so it never waits for "both sides"
const stateWord = computed(() => (seats.value.length && state.value === 'pending'
  ? 'Waiting for the round before' : STATE_WORD[state.value]));
const winner = computed(() => (hidden.value ? null : winnerSide(props.series)));

const player = (side) => shownPlayer(props.series, side, hidden.value);
const team = (side) => shownTeam(props.series, side, hidden.value);
// The roster reads only beside the team it belongs to, so a hidden side names nobody
const roster = (side) => (team(side) && props.rosters[props.series[`entrant${side}_id`]]) || [];
const race = (side) => props.series[`player${side}_race`] || undefined;
const score = (side) => (hidden.value ? '' : props.series[`player${side}_score`] ?? '');
// A side with no feeder and no entrant can never fill: the other side passes through
const empty = (side) => (isByeSide(props.series, side) ? 'Bye' : 'To be decided');
const sideClass = (side) => ({
  won: winner.value === side,
  lost: winner.value !== null && winner.value !== side,
});
</script>

<style scoped>
.series-box {
  display: block;
  width: 100%;
  text-align: left;
  background: rgb(var(--v-theme-surface));
  border: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
  border-radius: 4px;
  overflow: hidden;
}
.series-box.flat { border: none; border-radius: 0; background: none; }
.series-box:hover:not(.readonly) { border-color: rgb(var(--v-theme-primary)); }
.series-box:focus-visible { outline: 2px solid rgb(var(--v-theme-primary)); outline-offset: 1px; }

.side {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 3px 8px;
  min-height: 26px;
}
.side + .side { border-top: 1px solid rgba(var(--v-border-color), var(--v-border-opacity)); }
/* The result is a mark beside the name, never coloured text */
.mark {
  flex: 0 0 auto;
  width: 3px;
  align-self: stretch;
  border-radius: 2px;
  background: rgb(var(--v-theme-draw));
}
.side.won .mark { background: rgb(var(--v-theme-win)); }
.side.lost .mark { background: rgb(var(--v-theme-loss)); }
.side.won { font-weight: 700; }
/* A team side stacks its name over its roster and keeps the score on the right */
.who { display: flex; flex-direction: column; gap: 1px; min-width: 0; }
.roster { display: flex; flex-wrap: wrap; gap: 2px 10px; font-size: 0.8125rem; font-weight: 400; }
.crown { color: rgb(var(--v-theme-primary-text)); }
.empty { font-size: 0.8125rem; }
.score { margin-left: auto; font-variant-numeric: tabular-nums; font-weight: 700; }

.foot {
  display: flex;
  gap: 8px;
  justify-content: space-between;
  padding: 2px 8px 4px;
  line-height: 1.2;
}
</style>

// next/src/components/SeriesBox.tsx
"use client";
import { PlayerName } from "@/components/PlayerName";
import { Icon } from "@/components/ui/Icon";
import { useHideResults } from "@/components/hide-results";
import { sideRoster } from "@/helpers/fixture.mjs";
import { isByeSide, isLobby, lobbySeats, seriesState, shownPlayer, shownTeam, winnerSide } from "@/helpers/stage-view.mjs";
import { cn } from "@/lib/utils";

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const STATE_WORD: Record<string, string> = {
  pending: "Waiting for both sides",
  open: "To play",
  played: "Played",
  walkover: "Walkover",
  forfeit: "Forfeit",
};

// The result is a mark beside the name, never coloured text
const MARK = "shrink-0 w-[3px] self-stretch rounded-[2px]";
const SIDE = "flex items-center gap-1.5 px-2 py-[3px] min-h-[26px]";

/** One series of a stage: a side per row with its race, the score, and the state as a word.
 *  A team side reads as the team name over the roster it fields. A free for all lobby reads
 *  one row a seat with its place. The winning side wears the win token; a click opens the series. */
export function SeriesBox({
  series,
  label = "", // the grand final and the third place name themselves
  round = "", // the column the box sits in, so a screen reader hears it per box
  crown, // the standing king of a KOTH chain
  flat, // inside a list, the card around it draws the border
  readonly, // the series page opens nothing, so its names link
  rosters = {}, // the players of each team entrant, by entrant id
  fed, // a lobby seated by the round before it, not by the seeds
  onOpen,
  className,
}: {
  series: Row;
  label?: string;
  round?: string;
  crown?: boolean;
  flat?: boolean;
  readonly?: boolean;
  rosters?: Record<string, Row[]>;
  fed?: boolean;
  onOpen?: (series: Row) => void;
  className?: string;
}) {
  // The spoiler switch of the page around this box; a page with no switch shows every result
  const hidden = useHideResults();

  const state = seriesState(series);
  // A lobby seats more than two, so its seats replace the two side rows. A fixture series
  // writes the same rows for its side rosters, and those read under the team name instead.
  const seats: Row[] = isLobby(series) ? lobbySeats(series, hidden, fed) : [];
  // A lobby fills from the round before it, so it never waits for "both sides"
  const stateWord = seats.length && state === "pending" ? "Waiting for the round before" : STATE_WORD[state];
  const winner = hidden ? null : winnerSide(series);

  const player = (side: number) => shownPlayer(series, side, hidden);
  const team = (side: number) => shownTeam(series, side, hidden);
  const race = (side: number) => series[`player${side}_race`] || undefined;
  const score = (side: number) => (hidden ? "" : series[`player${side}_score`] ?? "");
  // A side with no feeder and no entrant can never fill: the other side passes through
  const empty = (side: number) => (isByeSide(series, side) ? "Bye" : "To be decided");
  // Who a team side fields: the players the series names, else the one player it drafted,
  // else every member the team is rostered with. A series that names its own pick rule
  // fields the players it names alone, so a side nobody has named yet reads empty.
  const roster = (side: number): Row[] => {
    if (!team(side)) return [];
    const named = sideRoster(series, side);
    if (named.length) return named.map((one: Row) => ({ player: one, race: one.signup_race }));
    const drafted = player(side);
    if (drafted) return [{ player: drafted, race: race(side) }];
    if (series.pick_rule) return [];
    return rosters[series[`entrant${side}_id`]] || [];
  };

  // What a screen reader hears for the box: where it sits, who plays, and the state
  const sideName = (side: number) => team(side)?.name || player(side)?.name || empty(side);
  const where = [round, label].filter(Boolean).join(", ");
  const who = seats.length ? `${seats.length} seats` : `${sideName(1)} vs ${sideName(2)}`;
  const name = `${where ? `${where}: ` : ""}${who}, ${stateWord}`;

  const sideClass = (side: number) => (winner === side ? "won" : winner !== null ? "lost" : "");
  const markClass = (result: string) => (result === "won" ? "bg-win" : result === "lost" ? "bg-loss" : "bg-draw");

  const rows = seats.length
    ? seats.map((seat, index) => (
        <div key={seat.key} className={cn(SIDE, index && "border-t", seat.result === "won" && "font-bold")}>
          <span className={cn(MARK, markClass(seat.result))} />
          {seat.user ? (
            <PlayerName player={seat.user} plain={!readonly} />
          ) : (
            <span className="text-[0.8125rem] text-muted-foreground">{fed ? "To be decided" : "Empty seat"}</span>
          )}
          <span className="tnum ml-auto font-bold">{seat.place ?? ""}</span>
        </div>
      ))
    : [1, 2].map((side, index) => (
        <div key={side} className={cn(SIDE, index && "border-t", sideClass(side) === "won" && "font-bold")}>
          <span className={cn(MARK, markClass(sideClass(side)))} />
          {crown && side === 1 ? <Icon name="mdi-crown" size={14} className="text-primary-text" /> : null}
          {team(side) ? (
            <div className="flex min-w-0 flex-col gap-px">
              <span>{team(side).name}</span>
              {roster(side).length ? (
                <span className="flex flex-wrap gap-x-2.5 gap-y-0.5 text-[0.8125rem] font-normal">
                  {roster(side).map((seat) => (
                    <PlayerName key={seat.player.id} player={seat.player} race={seat.race || undefined} plain={!readonly} />
                  ))}
                </span>
              ) : series.pick_rule ? (
                <span className="flex text-[0.8125rem] font-normal text-muted-foreground">Roster not named</span>
              ) : null}
            </div>
          ) : player(side) ? (
            <PlayerName player={player(side)} race={race(side)} plain={!readonly} />
          ) : (
            <span className="text-[0.8125rem] text-muted-foreground">{empty(side)}</span>
          )}
          <span className="tnum ml-auto font-bold">{score(side)}</span>
        </div>
      ));

  const body = (
    <>
      {rows}
      <div className="flex justify-between gap-2 px-2 pt-0.5 pb-1 text-xs leading-tight text-muted-foreground">
        <span>{stateWord}</span>
        {label ? <span>{label}</span> : null}
      </div>
    </>
  );

  const shell = cn(
    "block w-full overflow-hidden rounded text-left",
    flat ? "rounded-none border-0 bg-transparent" : "border bg-surface",
    !readonly && "hover:border-primary focus-visible:outline-2 focus-visible:outline-primary focus-visible:outline-offset-1",
    className,
  );

  if (readonly)
    return (
      <div role="group" aria-label={name} className={shell}>
        {body}
      </div>
    );
  return (
    <button type="button" aria-label={name} className={shell} onClick={() => onOpen?.(series)}>
      {body}
    </button>
  );
}

export default SeriesBox;
