// src/components/W3CMmr.vue
<!-- The "W3C MMR" column label: the W3Champions W3C mark ahead of the word MMR.
     Source of the mark in src/assets/media/README.md. -->
<template>
  <span class="d-inline-flex align-baseline text-no-wrap">
    <img :src="logo" alt="W3C" class="w3c-mmr-logo mr-1">
    <span>MMR{{ suffix }}</span>
    <v-icon v-if="sortIcon" size="x-small" class="ml-1">{{ sortIcon }}</v-icon>
  </span>
</template>

<script setup>
import { computed } from 'vue';
import { useTheme } from 'vuetify';
import w3cLogo from '@/assets/media/w3c-logo.png';
import w3cLogoWhite from '@/assets/media/w3c-logo-white.png';

// The dark-ink mark is made for the light theme; the dark theme takes the white original.
const theme = useTheme();
const logo = computed(() => (theme.global.current.value.dark ? w3cLogoWhite : w3cLogo));

defineProps({
  suffix: { type: String, default: '' },
  sortIcon: { type: String, default: null },
});
</script>

<style scoped>
.w3c-mmr-logo {
  height: 1.4em;
  transform: translateY(3%);
  object-fit: contain;
  vertical-align: baseline;
  flex-shrink: 0;
}
</style>

// next/src/components/W3CMmr.tsx
"use client";
import { Icon } from "@/components/ui/Icon";
import { useTheme } from "@/hooks/theme";
import w3cLogo from "@/assets/media/w3c-logo.png";
import w3cLogoWhite from "@/assets/media/w3c-logo-white.png";

/** The "W3C MMR" column label: the W3Champions W3C mark ahead of the word MMR.
 *  Source of the mark in src/assets/media/README.md. */
export function W3CMmr({ suffix = "", sortIcon = null }: { suffix?: string; sortIcon?: string | null }) {
  // The dark-ink mark is made for the light theme; the dark theme takes the white original.
  const { activeTheme } = useTheme();
  const logo = activeTheme === "dark" ? w3cLogoWhite : w3cLogo;
  return (
    <span className="inline-flex items-baseline whitespace-nowrap">
      <img src={logo.src} alt="W3C" className="mr-1 h-[1.4em] shrink-0 translate-y-[3%] object-contain align-baseline" />
      <span>MMR{suffix}</span>
      {sortIcon ? <Icon name={sortIcon} size={12} className="ml-1" /> : null}
    </span>
  );
}

export default W3CMmr;
